src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Registration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U.S. Business</fullName>
                    <default>true</default>
                    <label>U.S. Business</label>
                </value>
                <value>
                    <fullName>Foreign Business</fullName>
                </value>
                <value>
                    <fullName>Trade/Industry Association</fullName>
                </value>
                <value>
                    <fullName>Business Service Provider/Consultant/Lawyer</fullName>
                </value>
                <value>
                    <fullName>Economic Development Organization</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Researcher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <description>This object allows us to track Contracts through their related Applications.</description>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The successful payment for this order.</description>
        <inlineHelpText>The successful payment for this order.</inlineHelpText>
        <label>Payment 2</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>The name of the product family to which this payment applies.</description>
        <inlineHelpText>The name of the product family to which this payment applies.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Services</fullName>
                    <default>true</default>
                    <label>Services</label>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Privacy Shield</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>The name of the bank on a check.</description>
        <inlineHelpText>The name of the bank on a check.</inlineHelpText>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_Date__c</fullName>
        <description>The date on a check.</description>
        <inlineHelpText>The date on a check.</inlineHelpText>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <description>The number of a check.</description>
        <inlineHelpText>The number of a check.</inlineHelpText>
        <label>Check Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Post_Acronym__c</fullName>
        <description>Populated from Opportunity.Collection_Post__r.Acronym__c</description>
        <label>Collection Post Acronym</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Post_Name__c</fullName>
        <description>Populated from Opportunity.Collection_Post__r.Name</description>
        <label>Collection Post Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Post_Org_Code__c</fullName>
        <description>Populated from Opportunity.Collection_Post__r.Org_Code__c</description>
        <label>Collection Post Org Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract to which this payment applies.</description>
        <inlineHelpText>The contract to which this payment applies.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Post_Acronym__c</fullName>
        <description>Populated from Opportunity.Fulfillment_Post__r.Acronym__c</description>
        <label>Fulfillment Post Acronym</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Post_Name__c</fullName>
        <description>Populated from Opportunity.Fulfillment_Post__r.Name</description>
        <label>Fulfillment Post Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Post_Org_Code__c</fullName>
        <description>Populated from Opportunity.Fulfillment_Post__r.Org_Code__c</description>
        <label>Fulfillment Post Org Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Created_Date__c</fullName>
        <description>Populated from Opportunity.CreatedDate</description>
        <label>Opportunity Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <description>Populated from Opportunity.Owner.Name</description>
        <label>Opportunity Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <description>Populated from Opportunity.Account.Name</description>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <defaultValue>&apos;PayGov&apos;</defaultValue>
        <description>The name of the entity that processed this payment.</description>
        <inlineHelpText>The name of the entity that processed this payment.</inlineHelpText>
        <label>Payment Processor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Card Refund</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled</fullName>
                    <isActive>false</isActive>
                    <label>NIST-Handled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Code__c</fullName>
        <description>Populated when payment record is created. First four characters come from the order line item. Last 3 characters are static.</description>
        <label>Project Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The DateTime of the payment transaction, as returned from pay.gov for credit card and ACH payments or the date the transaction was recorded for other types of payments.</description>
        <inlineHelpText>The DateTime of the payment transaction, as returned from pay.gov for credit card and ACH payments or the date the transaction was recorded for other types of payments.</inlineHelpText>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Bank_Transfer_Payment</fullName>
        <active>true</active>
        <description>Record type for bank transfer payments.</description>
        <label>Bank Transfer Payment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cash_Payment</fullName>
        <active>true</active>
        <description>Record type for cash payments.</description>
        <label>Cash Payment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Check_Payment</fullName>
        <active>true</active>
        <description>Record type for check payments.</description>
        <label>Check Payment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Flow_CreatePaymentRecord.cls
global without sharing class Flow_CreatePaymentRecord {

	private static String contractId;
	private static String paymentType;
	private static Decimal amount;
	private static List<Order> orders;
	private static String bankName;
	private static String checkNumber;
	private static Date checkDate;
	private static Datetime bankTransferDatetime;
	private static String accountType;

	@InvocableMethod(label='Create Payment Record' description='Inserts a Payment record and updates the order(s)' category='Payments')
	global static List<String> createPaymentRecord(List<RequestVariables> inputs){

		if (inputs.isEmpty()) {
			return null;
		}

		RequestVariables requestVariables = inputs[0];

		try {
			populateVariables(requestVariables);

			//Create the payment record
			Payment2__c payment = new Payment2__c();

			//Determine the record type id
			String recordTypeName = getRecordTypeNameForPaymentType(payment);

			//Populate Payment Details
			populatePaymentDetails(payment, recordTypeName);

			//Create Payment DML
			savePaymentRecord(payment);

			return new List<String>{(String) payment.Id};

		} catch(Exception e) {
			throw new CreatePaymentRecordActionException(e.getMessage());
		}
	}

	private static void populateVariables(RequestVariables requestVariables) {
		contractId = requestVariables.contractId;
		paymentType = requestVariables.paymentType;
		amount = requestVariables.amount;
		orders = requestVariables.orders;
		bankName = requestVariables.bankName;
		checkNumber = requestVariables.checkNumber;
		checkDate = requestVariables.checkDate;
		bankTransferDatetime = requestVariables.bankTransferDatetime;
		accountType = requestVariables.accountType;
	}

	private static String getRecordTypeNameForPaymentType(Payment2__c payment) {
		String recordTypeName;
		switch on paymentType {
			when 'Check' {

				payment.Bank_Name__c = bankName;
				payment.Check_Number__c = checkNumber;
				payment.Check_Date__c = checkDate;
				payment.Payment_Type__c = 'Check';
				recordTypeName = 'Check_Payment';
			}
			when 'Cash' {
				recordTypeName = 'Cash_Payment';
				payment.Payment_Type__c = 'Cash';
			}
			when 'Bank Transfer' {
				recordTypeName = 'Bank_Transfer_Payment';
				payment.Payment_Type__c = 'Bank Transfer';
				payment.Transaction_Date__c = bankTransferDatetime;
			}
			when else {
				throw new CreatePaymentRecordActionException('Invalid Payment Type');
			}
		}
		return recordTypeName;
	}

	private static void populatePaymentDetails(Payment2__c payment, String recordTypeName) {
		Id ordersId = orders[0].Id;
		payment.Account_Type__c = accountType;
		payment.RecordTypeId = Utils.getRecordTypeIdMap('Payment2__c').get(recordTypeName);
		payment.Contract__c = contractId;
		payment.Payment_Processor__c = '';
		payment.Transaction_Status__c = 'Success';
		payment.Transaction_Amount__c = amount;

		//Look at the first Order to get data from the associated Opportunity
		Set<Id> orderIds = new Set<Id>();
		orderIds.add(ordersId);
		//The OrdersSelector will only return order items that are marked as primary
		List<Order> orders = OrdersSelector.newInstance().selectWithOrderItemDetails(orderIds, true);
		Order order = orders[0];

		payment.Organization_Name__c 			= order.Opportunity.Account.Name;
		payment.Opportunity_Owner__c 			= order.Opportunity.Owner.Name;
		payment.Opportunity_Created_Date__c 	= order.Opportunity.CreatedDate;
		payment.Collection_Post_Name__c 		= order.Opportunity.Collection_Post__r.Name;
		payment.Collection_Post_Org_Code__c 	= order.Opportunity.Collection_Post__r.Org_Code__c;
		payment.Collection_Post_Acronym__c		= order.Opportunity.Collection_Post__r.Acronym__c;
		payment.Fulfillment_Post_Name__c 		= order.Opportunity.Fulfillment_Post__r.Name;
		payment.Fulfillment_Post_Org_Code__c 	= order.Opportunity.Fulfillment_Post__r.Org_Code__c;
		payment.Fulfillment_Post_Acronym__c		= order.Opportunity.Fulfillment_Post__r.Acronym__c;
		if (order.OrderItems.size() != 0) {
			if (String.isNotBlank(order.OrderItems[0].Accounting_code__c)) {
				payment.Project_Code__c = order.OrderItems[0].Accounting_code__c.Left(4) + '231';
			}
		}
	}

	private static void savePaymentRecord(Payment2__c payment) {
		try {
			fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<SObjectType> {Payment2__c.SObjectType, Order.SObjectType});
			uow.registerNew(payment);
			for (Order eachOrder: orders) {
				eachOrder.Payment2__c = payment.Id;
				eachOrder.Order_Paid__c = true;
				payment.Receipt_Ready__c = true;
				uow.registerDirty(eachOrder, Order.Payment2__c, payment);
			}
			uow.commitWork();
		} catch (Exception e) {
			String errorMessage = 'Unable to insert payment or update order records.';
			throw new CreatePaymentRecordActionException(errorMessage + '  ' + e.getMessage());
		}
	}

	//Inputs from Flow to Apex
	global class RequestVariables {
		@InvocableVariable(label='Contract Id' required=true)
		global String contractId;

		@InvocableVariable(label='Payment Type' required=true)
		global String paymentType;  //Bank Transfer, Cash, Check

		@InvocableVariable(label='Payment Amount' required=true)
		global Decimal amount;

		@InvocableVariable(label='Orders' required=true)
		global List<Order> orders;

		@InvocableVariable(label='Bank Name' required=false)
		global String bankName;

		@InvocableVariable(label='Check Number' required=false)
		global String checkNumber;

		@InvocableVariable(label='Check Date' required=false)
		global Date checkDate;

		@InvocableVariable(label='Bank Transfer Datetime' required=false)
		global Datetime bankTransferDatetime;

		@InvocableVariable(label='Account Type' required=true)
		global String accountType;
	}

	class CreatePaymentRecordActionException extends Exception {}


}