src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Registration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U.S. Business</fullName>
                    <default>true</default>
                    <label>U.S. Business</label>
                </value>
                <value>
                    <fullName>Foreign Business</fullName>
                </value>
                <value>
                    <fullName>Trade/Industry Association</fullName>
                </value>
                <value>
                    <fullName>Business Service Provider/Consultant/Lawyer</fullName>
                </value>
                <value>
                    <fullName>Economic Development Organization</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Researcher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <description>This object allows us to track Contracts through their related Applications.</description>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The successful payment for this order.</description>
        <inlineHelpText>The successful payment for this order.</inlineHelpText>
        <label>Payment 2</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refunded_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>The amount of an order that has been refunded.</description>
        <inlineHelpText>The amount of an order that has been refunded.</inlineHelpText>
        <label>Refunded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>The name of the product family to which this payment applies.</description>
        <inlineHelpText>The name of the product family to which this payment applies.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Services</fullName>
                    <default>true</default>
                    <label>Services</label>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Privacy Shield</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collection_Post_Name__c</fullName>
        <description>Populated from Opportunity.Collection_Post__r.Name</description>
        <label>Collection Post Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Post_Org_Code__c</fullName>
        <description>Populated from Opportunity.Collection_Post__r.Org_Code__c</description>
        <label>Collection Post Org Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract to which this payment applies.</description>
        <inlineHelpText>The contract to which this payment applies.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Post_Name__c</fullName>
        <description>Populated from Opportunity.Fulfillment_Post__r.Name</description>
        <label>Fulfillment Post Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Post_Org_Code__c</fullName>
        <description>Populated from Opportunity.Fulfillment_Post__r.Org_Code__c</description>
        <label>Fulfillment Post Org Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Created_Date__c</fullName>
        <description>Populated from Opportunity.CreatedDate</description>
        <label>Opportunity Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <description>Populated from Opportunity.Owner.Name</description>
        <label>Opportunity Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <description>Populated from Opportunity.Account.Name</description>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field for refunds related to current payment</description>
        <label>Parent Payment</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <defaultValue>&apos;PayGov&apos;</defaultValue>
        <description>The name of the entity that processed this payment.</description>
        <inlineHelpText>The name of the entity that processed this payment.</inlineHelpText>
        <label>Payment Processor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Card Refund</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled</fullName>
                    <isActive>false</isActive>
                    <label>NIST-Handled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Code__c</fullName>
        <description>Populated when payment record is created. First four characters come from the order line item. Last 3 characters are static.</description>
        <label>Project Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund_Explanation__c</fullName>
        <description>If the Refund Reason is &quot;other&quot;, the explanation about why the refund is being given.</description>
        <inlineHelpText>If the Refund Reason is &quot;other&quot;, the explanation about why the refund is being given.</inlineHelpText>
        <label>Refund Explanation</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund_Reason__c</fullName>
        <description>The reason for the refund.</description>
        <inlineHelpText>The reason for the refund.</inlineHelpText>
        <label>Refund Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting adjustment</fullName>
                </value>
                <value>
                    <fullName>Client cancelled participation (before fees incurred)</fullName>
                </value>
                <value>
                    <fullName>Political/economic conditions of market changed</fullName>
                </value>
                <value>
                    <fullName>Post unable to process due to competing demands</fullName>
                </value>
                <value>
                    <fullName>Product not provided when promised</fullName>
                </value>
                <value>
                    <fullName>Product provided was of poor quality</fullName>
                </value>
                <value>
                    <fullName>Service did not meet all requirements</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>NIST_Issued_Refund</fullName>
        <active>true</active>
        <description>Record type for manually recorded refunds of all types.</description>
        <label>NIST-Issued Refund</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Flow_CreateRefundRecord.cls
global without sharing class Flow_CreateRefundRecord {

	@InvocableMethod(label='Create Refund Record' description='Inserts a Refund record and updates the order(s)' category='Payments')
	global static List<ResponseVariables> createRefundRecord(List<RequestVariables> inputs){

		ResponseVariables responseVariables = new ResponseVariables();
		List<ResponseVariables> responseVariablesList = new List<ResponseVariables>();

		if (inputs.isEmpty()) {
			return errorMessageResponse('<li>Nothing to validate.</li>', responseVariables, responseVariablesList);
		}

		List<String> errorList = new List<String>();
		RequestVariables requestVariables = inputs[0];

		try {
			String contractId = requestVariables.contractId;
			String accountType = requestVariables.accountType;
			List<String> refundAmounts = requestVariables.refundAmounts;
			List<String> refundReasons = requestVariables.refundReasons;
			List<String> refundExplanations = requestVariables.refundExplanations;
			List<Order> orders = requestVariables.orders;

			Order myOrder;
			String refundAmountString;

			Map<Id, List<Order>> paymentOrderMap = new Map<Id, List<Order>>();  //Id = Payment Id
			Map<Id, Decimal> paymentRefundMap = new Map<Id, Decimal>();   //Id = Payment Id, Decimal is total refund for that payment
			Map<Id, Decimal> orderRefundMap = new Map<Id, Decimal>();	  // Id = order.id, Decimal is the refund for that order

			for (Integer x=0; x<orders.size(); x++) {
				myOrder = orders[x];
				//Check to make sure that each order is paid
				if (myOrder.Order_Paid__c != true) {
					return errorMessageResponse('<li>All orders must be paid before issuing refunds.</li>', responseVariables, responseVariablesList);
				}
				refundAmountString = refundAmounts[x];
				populatePaymentOrderMap(myOrder, orderRefundMap, refundAmountString, paymentOrderMap);
				populateRefundOrderMap(paymentRefundMap, myOrder, refundAmountString);
			}

			List<Payment2__c> payments = PaymentsSelector2.newInstance().selectById(paymentOrderMap.keySet());
			Map<Id, Payment2__c> paymentIdMap =new Map<Id, Payment2__c>(payments);

			for(Payment2__c payment :payments) {
				//For each Payment, issue the refund

				//Look at the first Order to get data from the associated Opportunity
				List<Order> orderList = paymentOrderMap.get(payment.Id);
				Set<Id> orderIds = new Set<Id>();
				orderIds.add(orderList[0].Id);
				List<Order> orderListWithDetails = OrdersSelector.newInstance().selectWithOrderItemDetails(orderIds, true);
				Order order = orderListWithDetails[0];

				//Create the refund record
				Payment2__c refund = createPayment2(accountType, contractId, paymentRefundMap, refundReasons, refundExplanations, order, payment);

				if (order.OrderItems.size() != 0) {
					if (String.isNotBlank(order.OrderItems[0].Accounting_code__c)) {
						refund.Project_Code__c = order.OrderItems[0].Accounting_code__c.Left(4) + '231';
					}
				}

				attemptRefundDML(refund, paymentOrderMap, orderRefundMap, payment);
			}//End loop

			if (! errorList.isEmpty()) {
				responseVariables.hasError = true;
				responseVariables.errorReasons = String.join(errorList, '  ');  //Convert the list to a single string
			}
			responseVariablesList.add(responseVariables);
			return responseVariablesList;

		} catch(Exception e) {
			throw new CreateRefundRecordActionException(e.getMessage());
		}
	}

	private static Payment2__c createPayment2(String accountType, String contractId, Map<Id,Decimal> paymentRefundMap,
												List<String> refundReasons, List<String> refundExplanations, Order order, Payment2__c payment) {
		//Create the refund record
		Payment2__c refund = new Payment2__c();

		String recordTypeName = 'NIST_Issued_Refund';
		refund.Payment_Type__c = 'NIST-Handled Refund';
		refund.Payment_2__c = payment.Id;  //A reference to the parent payment record
		refund.Account_Type__c = accountType;
		refund.RecordTypeId = Utils.getRecordTypeIdMap('Payment2__c').get(recordTypeName);
		refund.Contract__c = contractId;
		refund.Payment_Processor__c = '';
		refund.Transaction_Status__c = 'Success';
		refund.Transaction_Amount__c = paymentRefundMap.get(payment.Id);
		refund.Refund_Reason__c = refundReasons[0];  //Only the first refund reason is used
		refund.Refund_Explanation__c = refundExplanations[0];  //Only the first refund explanation is used
		refund.Organization_Name__c 			= order.Opportunity.Account.Name;
		refund.Opportunity_Owner__c 			= order.Opportunity.Owner.Name;
		refund.Opportunity_Created_Date__c 		= order.Opportunity.CreatedDate;
		refund.Collection_Post_Name__c 			= order.Opportunity.Collection_Post__r.Name;
		refund.Collection_Post_Org_Code__c 		= order.Opportunity.Collection_Post__r.Org_Code__c;
		refund.Fulfillment_Post_Name__c 		= order.Opportunity.Fulfillment_Post__r.Name;
		refund.Fulfillment_Post_Org_Code__c 	= order.Opportunity.Fulfillment_Post__r.Org_Code__c;
		refund.Receipt_Ready__c = true;
		return refund;
	}

	private static void populatePaymentOrderMap(Order myOrder, Map<Id,Decimal> orderRefundMap, String refundAmountString, Map<Id,List<Order>> paymentOrderMap) {
		List<order> o = new List<order>();
		orderRefundMap.put(myOrder.Id, Decimal.valueOf(refundAmountString));
		if (paymentOrderMap.containsKey(myOrder.Payment2__c)) {
			o = paymentOrderMap.get(myOrder.Payment2__c);
			o.add(myOrder);
			paymentOrderMap.put(myOrder.Payment2__c, o);
		} else {
			o.add(myOrder);
			paymentOrderMap.put(myOrder.Payment2__c, o);
		}
	}

	private static void populateRefundOrderMap(Map<Id,Decimal> paymentRefundMap, Order myOrder, String refundAmountsString) {
		if (paymentRefundMap.containsKey(myOrder.Payment2__c)) {
			Decimal d = paymentRefundMap.get(myOrder.Payment2__c);
			d += Decimal.ValueOf(refundAmountsString);
			paymentRefundMap.put(myOrder.Payment2__c, d);
		} else {
			paymentRefundMap.put(myOrder.Payment2__c, Decimal.ValueOf(refundAmountsString));
		}
	}

	private static void attemptRefundDML(Payment2__c refund, Map<Id,List<Order>> paymentOrderMap, Map<Id,Decimal> orderRefundMap, Payment2__c payment) {
		try {
			fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<SObjectType> {Payment2__c.SObjectType, Order.SObjectType});
			uow.registerNew(refund);

			List<Order> ordersByPayment = paymentOrderMap.get(payment.Id);
			for (Integer x = 0; x < ordersByPayment.size(); x++) {
				Order eachOrder = ordersByPayment.get(x);
				eachOrder.Payment2__c = payment.Id;
				eachOrder.Refunded_Amount__c += orderRefundMap.get(eachOrder.Id);
				system.debug('Order.Payment2__c ==> ' + Order.Payment2__c);
				uow.registerDirty(eachOrder, Order.Payment2__c, payment);
			}
			uow.commitWork();
		} catch (Exception e) {
			String errorMessage = 'Unable to insert refund or update order records.' + e.getMessage();
			throw new CreateRefundRecordActionException(errorMessage);
		}
	}

	private static List<ResponseVariables> errorMessageResponse(String errorMessage, ResponseVariables responseVariables, List<ResponseVariables> responseVariablesList) {
		responseVariables.hasError = true;
		responseVariables.errorReasons = errorMessage;
		responseVariablesList.add(responseVariables);
		return responseVariablesList;
	}

	//Inputs from Flow to Apex
	global class RequestVariables {
		@InvocableVariable(label='Orders' required=true)
		global List<Order> orders;

		@InvocableVariable(label='Refund Reasons' required=true)
		global List<String> refundReasons;

		@InvocableVariable(label='Refund Amounts' required=true)
		global List<String> refundAmounts;

		@InvocableVariable(label='Refund Explanations' required=true)
		global List<String> refundExplanations;
		// the following three variables are not in the credit card refund flow

		@InvocableVariable(label='Contract Id' required=true)
		global String contractId;

		@InvocableVariable(label='Account Type' required=true)
		global String accountType;

		//The total refund
		@InvocableVariable(label='Refund Total' required=true)
		global Decimal refundTotal;

	}

	//Outputs from Apex to Flow
	global class ResponseVariables {
		@InvocableVariable(label='Has Error' required=true)
		global Boolean hasError = false;

		@InvocableVariable(label='Error Reasons' required=true)
		global String errorReasons;
	}

	class CreateRefundRecordActionException extends Exception {}

}