src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Congressional_District__c</fullName>
        <label>Congressional District</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County_Name__c</fullName>
        <inlineHelpText>This field is auto populated for US Organizations based on zip code</inlineHelpText>
        <label>County (US Only)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Master_CongressionalDistrict__c.object
<CustomObject>
    <fields>
        <fullName>Congressional_Dist__c</fullName>
        <label>Congressional Dist</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County_Name__c</fullName>
        <label>County Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max4__c</fullName>
        <description>In Zip+4 the Maximum 4 digit value will be stored in this field.</description>
        <externalId>true</externalId>
        <label>Max4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max9Zip__c</fullName>
        <formula>zip_Plus4__c + Max4__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max9Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min4__c</fullName>
        <description>In Zip+4 the last 4 Minimum value will be stored in this field.</description>
        <externalId>true</externalId>
        <label>Min4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min9Zip__c</fullName>
        <formula>zip_Plus4__c  +  Min4__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Min9Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zip_Plus4__c</fullName>
        <description>Will have 5 digit zip code.</description>
        <externalId>true</externalId>
        <label>zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Master CongressionalDistrict</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Master CongressionalDistrict Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master CongressionalDistricts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountsServiceImpl.cls
/*
	Author: Mark Keckeis
	Date: 9-2-2020
	Name: Accounts.cls
	Purpose: Implementation of IAccounts interface that will be used as an FFLIB domain object.
 */
public class AccountsServiceImpl implements IAccountsService{

	public void UpdateCCDLookupId(List<SObject> records){
		List<Account> accounts = new List<Account>();
		accounts = (List<Account>)records;
		if(Trigger.isBefore && !System.isBatch()){
			Set<String> zipPlus4 = new Set<String>();
			Set<String> zip4 = new Set<String>();
			Set<String> zip5 = new Set<String>();

			for(Account acc: accounts) {
				if(acc.BillingPostalCode != NULL && acc.BillingCountry == 'United States'){
					System.debug(' **** Inside the for loop ****** ');
					Pattern zipCodSpecChar = Pattern.compile('[0-9]{5}-[0-9]{4}');
					Matcher zipMatch = zipCodSpecChar.matcher(acc.BillingPostalCode);
					//Condition to check if the Country is US and it has proper formate of zip [XXXXX-XXXX]
					//This conditon will be used only for US address only.
					if(zipMatch.matches()) {
						System.debug(' **** Inside the IF True loop ****** ');
						zipPlus4.add(acc.BillingPostalCode.replace('-',''));
						zip4.add(acc.BillingPostalCode.replace('-','').substring(5,9));
						zip5.add(acc.BillingPostalCode.substring(0,5));
					} else {
						acc.Congressional_District__c = '';
						acc.County_Name__c = '';
						acc.State_Code__c = '';
					}
				} else {
					acc.Congressional_District__c = '';
					acc.County_Name__c = '';
					acc.State_Code__c = '';
				}
			}
			if(zip4.size() > 0 && zip5.size()>0){
				List<Master_CongressionalDistrict__c> cDistricts = new List<Master_CongressionalDistrict__c>();
				if(Test.isRunningTest()){
					cDistricts = [SELECT id, Congressional_Dist__c,
					State_Code__c,
					County_Name__c,
					Zip_Plus4__c,
					Max9Zip__c,
					Min9Zip__c
					FROM Master_CongressionalDistrict__c
					WHERE Max9Zip__c >= :zipPlus4
					AND Min9Zip__c <= :zipPlus4 LIMIT 1];
					}
				else {
					cDistricts = [SELECT id, Congressional_Dist__c,
					State_Code__c,
					County_Name__c,
					Zip_Plus4__c,
					Max9Zip__c,
					Min9Zip__c
					FROM Master_CongressionalDistrict__c
					WHERE Max4__c >= :zip4
					AND Min4__c <= :zip4
					AND Zip_Plus4__c = :zip5 LIMIT 1];
				}
				System.debug('*** cDistricts ***** '+cDistricts);
				for(Account accFor : accounts){
					//This condition is used to set the existing value to Null
					//if the cDistricts value is not populated and there is an existing value in
					//for Master congressional district.
					if(cDistricts.size()>0){
						for(Master_CongressionalDistrict__c mccd : cDistricts){
							Pattern zipCodSpecChar = Pattern.compile('[0-9]{5}-[0-9]{4}');
							Matcher zipMatch = zipCodSpecChar.matcher(accFor.BillingPostalCode);
							if(mccd.Min9Zip__c <= accFor.billingPostalCode.replace('-','')
								&& mccd.Max9Zip__c >= accFor.billingPostalCode.replace('-','')
								&& zipMatch.matches()){
									accFor.Congressional_District__c = mccd.Congressional_Dist__c;
									accFor.County_Name__c = mccd.County_Name__c;
									accFor.State_Code__c = mccd.State_Code__c;
							}
						}
					}
				}
			}
		}
	}
}