src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Registration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U.S. Business</fullName>
                    <default>true</default>
                    <label>U.S. Business</label>
                </value>
                <value>
                    <fullName>Foreign Business</fullName>
                </value>
                <value>
                    <fullName>Trade/Industry Association</fullName>
                </value>
                <value>
                    <fullName>Business Service Provider/Consultant/Lawyer</fullName>
                </value>
                <value>
                    <fullName>Economic Development Organization</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Researcher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The successful payment for this order.</description>
        <inlineHelpText>The successful payment for this order.</inlineHelpText>
        <label>Payment 2</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <description>Services order record type</description>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>The name of the product family to which this payment applies.</description>
        <inlineHelpText>The name of the product family to which this payment applies.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Services</fullName>
                    <default>true</default>
                    <label>Services</label>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Privacy Shield</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <defaultValue>&apos;PayGov&apos;</defaultValue>
        <description>The name of the entity that processed this payment.</description>
        <inlineHelpText>The name of the entity that processed this payment.</inlineHelpText>
        <label>Payment Processor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Card Refund</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled</fullName>
                    <isActive>false</isActive>
                    <label>NIST-Handled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Credit_Card_or_ACH_Payment</fullName>
        <active>true</active>
        <description>Record type for credit card and ACH payments.</description>
        <label>Credit Card or ACH Payment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentDetailsLightningController2Test.cls
@isTest
public class PaymentDetailsLightningController2Test {

	@testSetup static void createTestData() {
		Account account = TestUtils.createAccount(true);
		Program__c program = TestUtils.createProgram('Test Program', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product2 = TestUtils.createProduct(true);
		ID standardPbId = Test.getStandardPricebookId();
		PricebookEntry standardPbe = TestUtils.createPricebookEntry(standardPbId, product2.Id, true);
		PricebookEntry pbe = TestUtils.createPricebookEntry(pricebook.Id, product2.Id, true);
		Id servicesRecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Services').getRecordTypeId();
		Contract contract = new Contract();
		contract.Name = 'Contract Test X';
		contract.AccountId = account.Id;
		insert contract;
		contract.Status = 'Activated';
		update contract;
		List<Order> orders = new List<Order>();
		Order order1 = TestUtils.createOrder(account.Id, null, program.Id, pricebook.Id);
		order1.Type = 'Services';
		order1.Name = 'Credit Card Order X';
		order1.ContractId = contract.Id;
		order1.RecordTypeId = servicesRecordTypeId;
		orders.add(order1);
		Order order2 = TestUtils.createOrder(account.Id, null, program.Id, pricebook.Id);
		order2.Type = 'Services';
		order2.Name = 'ACH Order X';
		order2.ContractId = contract.Id;
		order2.RecordTypeId = servicesRecordTypeId;
		orders.add(order2);
		update orders;

		OrderItem orderItem1 = TestUtils.createStandardOrderItem(false, order1.Id, pbe.Id);
		orderItem1.Quantity = 2;
		orderItem1.UnitPrice = 2400;
		orderItem1.Product2id = product2.id;
		insert orderItem1;

		OrderItem orderItem2 = TestUtils.createStandardOrderItem(false, order2.Id, pbe.Id);
		orderItem2.Quantity = 2;
		orderItem2.UnitPrice = 2400;
		orderItem2.Product2id = product2.id;
		insert orderItem2;

		//Insert a Payment record
		Payment2__c payment1 = TestUtils.createPayment2(false, 'Credit_Card_or_ACH_Payment');
		payment1.Account_Type__c = 'Services';
		payment1.Payment_Processor__c = 'Paygov';
		payment1.Transaction_Status__c = 'Success';
		payment1.Transaction_Amount__c = 4800.00;
		payment1.Payment_Type__c = 'PLASTIC_CARD';
		insert payment1;

		order1.Status = 'Paid';
		order1.Order_Paid__c = true;
		order1.Payment2__c = payment1.Id;
		update order1;

		Payment2__c payment2 = TestUtils.createPayment2(false, 'Credit_Card_or_ACH_Payment');
		payment2.Account_Type__c = 'Services';
		payment2.Payment_Processor__c = 'Paygov';
		payment2.Transaction_Status__c = 'Success';
		payment2.Transaction_Amount__c = 4800.00;
		payment2.Payment_Type__c = 'ACH';
		insert payment2;

		order2.Status = 'Paid';
		order2.Order_Paid__c = true;
		order2.Payment2__c = payment2.Id;
		update order2;
	}

	@isTest static void getPaymentDetails_ACH_Positive(){
		List<Order> orders = [SELECT Id, Type, Payment2__c, Order_Paid__c, ContractId FROM Order WHERE Name = 'ACH Order X'];
		Id paymentId = orders[0].Payment2__c;
		Test.startTest();
		Test.setMock(WebServiceMock.class, new TEST_PayGovSingleQueryAchMockImpl());
		String returnValue = PaymentDetailsLightningController2.getPaymentDetails(paymentId);
		PaymentDetailsForPayGov.ReturnValue paymentDetails = (PaymentDetailsForPayGov.ReturnValue)JSON.deserialize(returnValue, PaymentDetailsForPayGov.ReturnValue.class);
		System.assertEquals(true, paymentDetails.isAch);
		System.assertEquals('transactionAmount', paymentDetails.transactionAmount);
		Test.stopTest();
	}

	@isTest static void getPaymentDetails_CreditCard_Positive(){
		List<Order> orders = [SELECT Id, Type, Payment2__c, Order_Paid__c, ContractId FROM Order WHERE Name = 'Credit Card Order X'];
		Id paymentId = orders[0].Payment2__c;
		Test.startTest();
		Test.setMock(WebServiceMock.class, new TEST_PayGovSingleQueryCCMockImpl());
		String returnValue = PaymentDetailsLightningController2.getPaymentDetails(paymentId);
		PaymentDetailsForPayGov.ReturnValue paymentDetails = (PaymentDetailsForPayGov.ReturnValue)JSON.deserialize(returnValue, PaymentDetailsForPayGov.ReturnValue.class);
		System.assertEquals(true, paymentDetails.isCreditCard);
		System.assertEquals('transactionAmount', paymentDetails.transactionAmount);
		Test.stopTest();
	}

}