src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Service Providers</fullName>
                </value>
                <value>
                    <fullName>Codes</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Country Pages</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Form</fullName>
                </value>
                <value>
                    <fullName>Links</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Market Research</fullName>
                </value>
                <value>
                    <fullName>Procurment Opportunity</fullName>
                </value>
                <value>
                    <fullName>Promotion Opportunity</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Statistics</fullName>
                </value>
                <value>
                    <fullName>Tariff Schedules</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Web Content</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <description>The Atom Body (Formatting should be done here)</description>
        <inlineHelpText>The Atom Body (Formatting should be done here)</inlineHelpText>
        <label>Atom</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Display_Title__c</fullName>
        <inlineHelpText>Public display title on the web. If this field is blank, the Atom Name can used as the display title.</inlineHelpText>
        <label>Atom Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Atom</label>
    <nameField>
        <label>Atom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <description>Services order record type</description>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Class__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abatement Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Fuels</fullName>
                </value>
                <value>
                    <fullName>Advanced Reactors</fullName>
                </value>
                <value>
                    <fullName>Advanced Technology</fullName>
                </value>
                <value>
                    <fullName>Ancillary Equipment</fullName>
                </value>
                <value>
                    <fullName>Apprenticeship Programs</fullName>
                </value>
                <value>
                    <fullName>Assessment &amp; Consulting</fullName>
                </value>
                <value>
                    <fullName>Asset Management/Plant Life Extension</fullName>
                </value>
                <value>
                    <fullName>BOP Controls</fullName>
                </value>
                <value>
                    <fullName>Casing</fullName>
                </value>
                <value>
                    <fullName>Cells</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Compressors</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Construction, Design, and Installation</fullName>
                </value>
                <value>
                    <fullName>Construction/Installation</fullName>
                </value>
                <value>
                    <fullName>Construction Materials/Equipment</fullName>
                </value>
                <value>
                    <fullName>Construction Services</fullName>
                </value>
                <value>
                    <fullName>Contractors</fullName>
                </value>
                <value>
                    <fullName>Control Systems</fullName>
                </value>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Corrosion Prevention and Services</fullName>
                </value>
                <value>
                    <fullName>Couplings</fullName>
                </value>
                <value>
                    <fullName>CSP Components</fullName>
                </value>
                <value>
                    <fullName>CSP Construction</fullName>
                </value>
                <value>
                    <fullName>CSP Design &amp; Engineering</fullName>
                </value>
                <value>
                    <fullName>CSP Legal &amp; Financial</fullName>
                </value>
                <value>
                    <fullName>CSP Operations</fullName>
                </value>
                <value>
                    <fullName>CSP Project Development</fullName>
                </value>
                <value>
                    <fullName>CSP Systems</fullName>
                </value>
                <value>
                    <fullName>Public Acceptance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advanced Meteorological Information</fullName>
                </value>
                <value>
                    <fullName>Advanced Metering Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Advisory and Legal Support Services</fullName>
                </value>
                <value>
                    <fullName>Airborne Collision Avoidance Systems</fullName>
                </value>
                <value>
                    <fullName>Airport Accessibility</fullName>
                </value>
                <value>
                    <fullName>Airport Collaborative Decision Making (CDM)</fullName>
                </value>
                <value>
                    <fullName>Arrival/ Departure Management</fullName>
                </value>
                <value>
                    <fullName>Artificial Lift Systems</fullName>
                </value>
                <value>
                    <fullName>Automated Control Systems</fullName>
                </value>
                <value>
                    <fullName>Automation and Control</fullName>
                </value>
                <value>
                    <fullName>Automation Systems</fullName>
                </value>
                <value>
                    <fullName>Back-End Services</fullName>
                </value>
                <value>
                    <fullName>Batteries</fullName>
                </value>
                <value>
                    <fullName>Cargo Handling Equipment and Services</fullName>
                </value>
                <value>
                    <fullName>Cementing Products and Services</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Cleaners</fullName>
                </value>
                <value>
                    <fullName>Coatings</fullName>
                </value>
                <value>
                    <fullName>Communications Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Components</fullName>
                </value>
                <value>
                    <fullName>Compressors</fullName>
                </value>
                <value>
                    <fullName>Compressors, Parts and Services</fullName>
                </value>
                <value>
                    <fullName>Computer Systems and Software</fullName>
                </value>
                <value>
                    <fullName>Connectors and Fittings</fullName>
                </value>
                <value>
                    <fullName>Construction, Manufacturing, and Temp. Housing</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Interface Technologies</fullName>
                </value>
                <value>
                    <fullName>Consumer Smart Grid Interface Technologies</fullName>
                </value>
                <value>
                    <fullName>Continuous Climb Operations</fullName>
                </value>
                <value>
                    <fullName>Design, Construction, Operation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Web_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Web Resource</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Related Resources</relationshipLabel>
        <relationshipName>Related_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Related Web Resources</relationshipLabel>
        <relationshipName>Related_Web_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Resource</label>
    <nameField>
        <displayFormat>RR {0}</displayFormat>
        <label>Related Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ShoppingCart.cls
@IsTest
public class Test_ShoppingCart{

	public static testMethod void No_Products_Selected1(){
		//SETUP DATA
		Account account = TestUtils.createAccount(true);
		Contact contact = TestUtils.createContact('Smith', account.Id , true);
		User u = TestUtils.createCommunityUser('smith@sm.ith', contact.Id);
		TestUtils.createPaymentSettings();
		Program__c program = TestUtils.createProgram('Cool-Aid', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product1 = TestUtils.createProduct('Product 1', true);
		//this product has a Class and a Category
		product1.Class__c = 'Advisory and Legal Support Services';
		product1.Category__c = 'Public Acceptance';
		Product2 product2 = TestUtils.createProduct('Product 2', true);
		product2.Class__c = 'Design, Construction, Operation';
		Product2 product3 = TestUtils.createProduct('Product 3', true);  //no class or category
		List<Product2> products = new Product2[]{product1, product2, product3};
		update products;

		TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});
		Id recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Web_Resource' LIMIT 1].Id;
		Content__c Issue1 = new Content__c(Name = 'Issue 1', Display_Title__c = 'Issue 1', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue2 = new Content__c(Name = 'Issue 2', Display_Title__c = 'Issue 2', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue3 = new Content__c(Name = 'Issue 3', Display_Title__c = 'Issue 3', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		insert( new Content__c[]{Issue1, Issue2, Issue3});

		Related_Resource__c RR1 = new Related_Resource__c(Primary_Web_Resource__c = Issue1.Id, Product__c = product1.Id);
		Related_Resource__c RR2 = new Related_Resource__c(Primary_Web_Resource__c = Issue2.Id, Product__c = product2.Id);
		Related_Resource__c RR3 = new Related_Resource__c(Primary_Web_Resource__c = Issue3.Id, Product__c = product3.Id);
		insert(new Related_Resource__c[]{RR1, RR2, RR3});

		Application app = new Application();
		System.runAs(u){
			Participation__c application = app.createApplication(program.Id);
			Order order = app.createOrder(application.Id, program.Id);
			ProductSelectorComponent controller = new ProductSelectorComponent();
			controller.OrderId = order.Id;
			controller.PriceBookId = pricebook.Id;
			controller.WebResourceType = 'Environmental Issue';
			System.assertEquals(controller.getInit(), '');
			System.assertEquals(controller.PriceBookEntries.size(), 3);
			System.assertEquals(controller.RelatedWebResources.size(), 3);
			System.assertEquals(controller.Tier1VisibleSelectOptions.size(), 3);
		}
	}

	public static testMethod void No_Products_Selected2(){
		//SETUP DATA
		Account account = TestUtils.createAccount(true);
		Contact contact = TestUtils.createContact('Smith', account.Id , true);
		User u = TestUtils.createCommunityUser('smith@sm.ith', contact.Id);
		TestUtils.createPaymentSettings();
		Program__c program = TestUtils.createProgram('Cool-Aid', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product1 = TestUtils.createProduct('Product 1', true);
		//this product has a Class and a Category
		product1.Class__c = 'Advisory and Legal Support Services';
		product1.Category__c = 'Public Acceptance';
		Product2 product2 = TestUtils.createProduct('Product 2', true);
		product2.Class__c = 'Design, Construction, Operation';
		Product2 product3 = TestUtils.createProduct('Product 3', true);  //no class or category
		List<Product2> products = new Product2[]{product1, product2, product3};
		update products;

		TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});
		Id recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Web_Resource' LIMIT 1].Id;
		Content__c Issue1 = new Content__c(Name = 'Issue 1', Display_Title__c = 'Issue 1', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue2 = new Content__c(Name = 'Issue 2', Display_Title__c = 'Issue 2', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue3 = new Content__c(Name = 'Issue 3', Display_Title__c = 'Issue 3', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		insert( new Content__c[]{Issue1, Issue2, Issue3});

		Related_Resource__c RR1 = new Related_Resource__c(Primary_Web_Resource__c = Issue1.Id, Product__c = product1.Id);
		Related_Resource__c RR2 = new Related_Resource__c(Primary_Web_Resource__c = Issue2.Id, Product__c = product2.Id);
		Related_Resource__c RR3 = new Related_Resource__c(Primary_Web_Resource__c = Issue3.Id, Product__c = product3.Id);
		insert(new Related_Resource__c[]{RR1, RR2, RR3});

		Application app = new Application();
		System.runAs(u){
			Participation__c application = app.createApplication(program.Id);
			Order order = app.createOrder(application.Id, program.Id);
			ProductSelectorComponent controller = new ProductSelectorComponent();
			controller.OrderId = order.Id;
			controller.PriceBookId = pricebook.Id;
			controller.WebResourceType = 'Environmental Issue';
			System.assertEquals(controller.getInit(), '');
			System.assertEquals(controller.PriceBookEntries.size(), 3);
			System.assertEquals(controller.RelatedWebResources.size(), 3);
			System.assertEquals(controller.Tier1VisibleSelectOptions.size(), 3);
			controller.Tier1Selected.add(Issue1.Id);
			controller.refreshPage(); //the action done when an option is selected.
			System.assertEquals(controller.Tier2VisibleSelectOptions.size(), 1);
		}
	}

	public static testMethod void No_Products_Selected3(){
		//SETUP DATA
		Account account = TestUtils.createAccount(true);
		Contact contact = TestUtils.createContact('Smith', account.Id , true);
		User u = TestUtils.createCommunityUser('smith@sm.ith', contact.Id);
		TestUtils.createPaymentSettings();
		Program__c program = TestUtils.createProgram('Cool-Aid', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product1 = TestUtils.createProduct('Product 1', true);
		//this product has a Class and a Category
		product1.Class__c = 'Advisory and Legal Support Services';
		product1.Category__c = 'Public Acceptance';
		Product2 product2 = TestUtils.createProduct('Product 2', true);
		product2.Class__c = 'Design, Construction, Operation';
		Product2 product3 = TestUtils.createProduct('Product 3', true);  //no class or category
		List<Product2> products = new Product2[]{product1, product2, product3};
		update products;

		TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});
		Id recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Web_Resource' LIMIT 1].Id;
		Content__c Issue1 = new Content__c(Name = 'Issue 1', Display_Title__c = 'Issue 1', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue2 = new Content__c(Name = 'Issue 2', Display_Title__c = 'Issue 2', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue3 = new Content__c(Name = 'Issue 3', Display_Title__c = 'Issue 3', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		insert( new Content__c[]{Issue1, Issue2, Issue3});

		Related_Resource__c RR1 = new Related_Resource__c(Primary_Web_Resource__c = Issue1.Id, Product__c = product1.Id);
		Related_Resource__c RR2 = new Related_Resource__c(Primary_Web_Resource__c = Issue2.Id, Product__c = product2.Id);
		Related_Resource__c RR3 = new Related_Resource__c(Primary_Web_Resource__c = Issue3.Id, Product__c = product3.Id);
		insert(new Related_Resource__c[]{RR1, RR2, RR3});

		Application app = new Application();
		System.runAs(u){
			Participation__c application = app.createApplication(program.Id);
			Order order = app.createOrder(application.Id, program.Id);
			ProductSelectorComponent controller = new ProductSelectorComponent();
			controller.OrderId = order.Id;
			controller.PriceBookId = pricebook.Id;
			controller.WebResourceType = 'Environmental Issue';
			System.assertEquals(controller.getInit(), '');
			System.assertEquals(controller.PriceBookEntries.size(), 3);
			System.assertEquals(controller.RelatedWebResources.size(), 3);
			System.assertEquals(controller.Tier1VisibleSelectOptions.size(), 3);
			controller.Tier1Selected.add(Issue1.Id);
			controller.refreshPage();
			System.assertEquals(controller.Tier2VisibleSelectOptions.size(), 1);
			controller.Tier2Selected.add('Advisory and Legal Support Services');
			controller.refreshPage();
			System.assertEquals(controller.Tier3VisibleSelectOptions.keySet().contains('Advisory and Legal Support Services'), true);
		}
	}

	public static testMethod void No_Products_Selected4(){
		//SETUP DATA
		Account account = TestUtils.createAccount(true);
		Contact contact = TestUtils.createContact('Smith', account.Id , true);
		User u = TestUtils.createCommunityUser('smith@sm.ith', contact.Id);
		TestUtils.createPaymentSettings();
		Program__c program = TestUtils.createProgram('Cool-Aid', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product1 = TestUtils.createProduct('Product 1', true);
		//this product has a Class and a Category
		product1.Class__c = 'Advisory and Legal Support Services';
		product1.Category__c = 'Public Acceptance';
		Product2 product2 = TestUtils.createProduct('Product 2', true);
		product2.Class__c = 'Design, Construction, Operation';
		Product2 product3 = TestUtils.createProduct('Product 3', true);  //no class or category
		List<Product2> products = new Product2[]{product1, product2, product3};
		update products;

		TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});
		Id recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Web_Resource' LIMIT 1].Id;
		Content__c Issue1 = new Content__c(Name = 'Issue 1', Display_Title__c = 'Issue 1', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue2 = new Content__c(Name = 'Issue 2', Display_Title__c = 'Issue 2', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue3 = new Content__c(Name = 'Issue 3', Display_Title__c = 'Issue 3', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		insert( new Content__c[]{Issue1, Issue2, Issue3});

		Related_Resource__c RR1 = new Related_Resource__c(Primary_Web_Resource__c = Issue1.Id, Product__c = product1.Id);
		Related_Resource__c RR2 = new Related_Resource__c(Primary_Web_Resource__c = Issue2.Id, Product__c = product2.Id);
		Related_Resource__c RR3 = new Related_Resource__c(Primary_Web_Resource__c = Issue3.Id, Product__c = product3.Id);
		insert(new Related_Resource__c[]{RR1, RR2, RR3});

		Application app = new Application();
		System.runAs(u){
			Participation__c application = app.createApplication(program.Id);
			Order order = app.createOrder(application.Id, program.Id);
			ProductSelectorComponent controller = new ProductSelectorComponent();
			controller.OrderId = order.Id;
			controller.PriceBookId = pricebook.Id;
			controller.WebResourceType = 'Environmental Issue';
			System.assertEquals(controller.getInit(), '');
			System.assertEquals(controller.PriceBookEntries.size(), 3);
			System.assertEquals(controller.RelatedWebResources.size(), 3);
			System.assertEquals(controller.Tier1VisibleSelectOptions.size(), 3);
			controller.Tier1Selected.add(Issue1.Id);
			controller.refreshPage();
			System.assertEquals(controller.Tier2VisibleSelectOptions.size(), 1);
			controller.Tier2Selected.add('Advisory and Legal Support Services');
			controller.refreshPage();
			System.assertEquals(controller.Tier3VisibleSelectOptions.keySet().contains('Advisory and Legal Support Services'), true);
			controller.Tier3Selected.get('Advisory and Legal Support Services').add('Public Acceptance');
			controller.refreshPage();
			System.assertEquals(new set<String>(controller.Tier3Selected.get('Advisory and Legal Support Services')).contains('Public Acceptance'), true);
		}
	}

	public static testMethod void No_Products_Selected5(){
		//SETUP DATA
		Account account = TestUtils.createAccount(true);
		Contact contact = TestUtils.createContact('Smith', account.Id , true);
		User u = TestUtils.createCommunityUser('smith@sm.ith', contact.Id);
		TestUtils.createPaymentSettings();
		Program__c program = TestUtils.createProgram('Cool-Aid', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product1 = TestUtils.createProduct('Product 1', true);
		//this product has a Class and a Category
		product1.Class__c = 'Advisory and Legal Support Services';
		product1.Category__c = 'Public Acceptance';
		Product2 product2 = TestUtils.createProduct('Product 2', true);
		product2.Class__c = 'Design, Construction, Operation';
		Product2 product3 = TestUtils.createProduct('Product 3', true);  //no class or category
		List<Product2> products = new Product2[]{product1, product2, product3};
		update products;

		List<PricebookEntry> priceBookEntryLists = TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});
		upsert priceBookEntryLists;
		System.debug('****************************************************** \nMethod: No_Products_Selected5; \nVariableName: priceBookEntryLists, \nVariableValue: ' + JSON.serializePretty(priceBookEntryLists));

		Id recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Web_Resource' LIMIT 1].Id;
		Content__c Issue1 = new Content__c(Name = 'Issue 1', Display_Title__c = 'Issue 1', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue2 = new Content__c(Name = 'Issue 2', Display_Title__c = 'Issue 2', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue3 = new Content__c(Name = 'Issue 3', Display_Title__c = 'Issue 3', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		insert( new Content__c[]{Issue1, Issue2, Issue3});

		Related_Resource__c RR1 = new Related_Resource__c(Primary_Web_Resource__c = Issue1.Id, Product__c = product1.Id);
		Related_Resource__c RR2 = new Related_Resource__c(Primary_Web_Resource__c = Issue2.Id, Product__c = product2.Id);
		Related_Resource__c RR3 = new Related_Resource__c(Primary_Web_Resource__c = Issue3.Id, Product__c = product3.Id);
		insert(new Related_Resource__c[]{RR1, RR2, RR3});

		Application app = new Application();
		System.runAs(u){
			Participation__c application = app.createApplication(program.Id);
			Order order = app.createOrder(application.Id, program.Id);
			ProductSelectorComponent controller = new ProductSelectorComponent();
			controller.OrderId = order.Id;
			controller.PriceBookId = pricebook.Id;
			order.Pricebook2Id = controller.PriceBookId;
			update order;
			controller.WebResourceType = 'Environmental Issue';
			System.assertEquals(controller.getInit(), '');
			System.assertEquals(controller.PriceBookEntries.size(), 3);
			System.assertEquals(controller.RelatedWebResources.size(), 3);
			System.assertEquals(controller.Tier1VisibleSelectOptions.size(), 3);
			controller.Tier1Selected.add(Issue1.Id);
			controller.refreshPage();
			System.assertEquals(controller.Tier2VisibleSelectOptions.size(), 1);
			controller.Tier2Selected.add('Advisory and Legal Support Services');
			controller.refreshPage();
			System.assertEquals(controller.Tier3VisibleSelectOptions.keySet().contains('Advisory and Legal Support Services'), true);
			controller.Tier3Selected.get('Advisory and Legal Support Services').add('Public Acceptance');
			controller.Tier4Selected.put('Advisory and Legal Support Services - Public Acceptance', new String[]{});
			controller.Tier4Selected.get('Advisory and Legal Support Services - Public Acceptance').add(product1.Id);
			System.assertEquals(controller.ProductSelector.getAllOrderProducts(controller.OrderId).size(), 0); //there should not be any products yet;
			controller.refreshPage();
			controller.addRemoveProducts();
			System.assertEquals(controller.ProductSelector.getAllOrderProducts(controller.OrderId).size(), 1); // should be 1 product now
		}
	}

	public static testMethod void PricebookVersion(){
		//SETUP DATA
		Account account = TestUtils.createAccount(true);
		Contact contact = TestUtils.createContact('Smith', account.Id , true);
		User u = TestUtils.createCommunityUser('smith@sm.ith', contact.Id);
		TestUtils.createPaymentSettings();
		Program__c program = TestUtils.createProgram('Cool-Aid', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Product2 product1 = TestUtils.createProduct('Product 1', true);
		//this product has a Class and a Category
		product1.Class__c = 'Advisory and Legal Support Services';
		product1.Category__c = 'Public Acceptance';
		Product2 product2 = TestUtils.createProduct('Product 2', true);
		product2.Class__c = 'Design, Construction, Operation';
		Product2 product3 = TestUtils.createProduct('Product 3', true);
		product3.Class__c = 'Advisory and Legal Support Services';
		List<Product2> products = new Product2[]{product1, product2, product3};
		update products;

		List<PricebookEntry> priceBookEntryLists = TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});
		upsert priceBookEntryLists;
		System.debug('****************************************************** \nMethod: No_Products_Selected5; \nVariableName: priceBookEntryLists, \nVariableValue: ' + JSON.serializePretty(priceBookEntryLists));

		Id recordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Web_Resource' LIMIT 1].Id;
		Content__c Issue1 = new Content__c(Name = 'Issue 1', Display_Title__c = 'Issue 1', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue2 = new Content__c(Name = 'Issue 2', Display_Title__c = 'Issue 2', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		Content__c Issue3 = new Content__c(Name = 'Issue 3', Display_Title__c = 'Issue 3', RecordTypeId = recordType, Type__c = 'Environmental Issue');
		insert( new Content__c[]{Issue1, Issue2, Issue3});

		/*Related_Resource__c RR1 = new Related_Resource__c(Primary_Web_Resource__c = Issue1.Id, Product__c = product1.Id);
		Related_Resource__c RR2 = new Related_Resource__c(Primary_Web_Resource__c = Issue2.Id, Product__c = product2.Id);
		Related_Resource__c RR3 = new Related_Resource__c(Primary_Web_Resource__c = Issue3.Id, Product__c = product3.Id);
		insert(new Related_Resource__c[]{RR1, RR2, RR3});*/

		Application app = new Application();
		System.runAs(u){
			Participation__c application = app.createApplication(program.Id);
			Order order = app.createOrder(application.Id, program.Id);
			ProductSelectorComponent controller = new ProductSelectorComponent();
			controller.OrderId = order.Id;
			controller.PriceBookId = pricebook.Id;
			order.Pricebook2Id = controller.PriceBookId;
			update order;
			controller.WebResourceType = 'Environmental Issue';
			System.assertEquals(controller.getInit(), '');
			System.assertEquals(controller.PriceBookEntries.size(), 3);
			//System.assertEquals(controller.RelatedWebResources.size(), 3);
			//System.assertEquals(controller.Tier1VisibleSelectOptions.size(), 3);
			controller.Tier1Selected.add(Issue1.Id);
			controller.refreshPage();
			//System.assertEquals(controller.Tier2VisibleSelectOptions.size(), 1);
			controller.Tier2Selected.add('Advisory and Legal Support Services');
			controller.refreshPage();
			System.assertEquals(controller.Tier3VisibleSelectOptions.keySet().contains('Advisory and Legal Support Services'), true);
			controller.Tier3Selected.get('Advisory and Legal Support Services').add('Public Acceptance');
			controller.Tier4Selected.put('Advisory and Legal Support Services - Public Acceptance', new String[]{});
			controller.Tier4Selected.get('Advisory and Legal Support Services - Public Acceptance').add(product1.Id);
			System.assertEquals(controller.ProductSelector.getAllOrderProducts(controller.OrderId).size(), 0); //there should not be any products yet;
			controller.refreshPage();
			controller.addRemoveProducts();
			System.assertEquals(controller.ProductSelector.getAllOrderProducts(controller.OrderId).size(), 1); // should be 1 product now
		}
	}
}