src/objects/ADCVD_Objects__mdt.object
<CustomObject>
    <description>This holds the object types, record types, and a type field (if present) delineating a difference in records for the ADCVD app</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Petition__c</fullName>
                    <default>true</default>
                    <label>Petition__c</label>
                </value>
                <value>
                    <fullName>Investigation__c</fullName>
                </value>
                <value>
                    <fullName>ADCVD_Order__c</fullName>
                </value>
                <value>
                    <fullName>Segment__c</fullName>
                </value>
                <value>
                    <fullName>Litigation__c</fullName>
                </value>
                <value>
                    <fullName>Related_Organization__c</fullName>
                </value>
                <value>
                    <fullName>Federal_Register__c</fullName>
                </value>
                <value>
                    <fullName>Recusal__c</fullName>
                </value>
                <value>
                    <fullName>Staffing_Assignment__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
                <value>
                    <fullName>Administrative_Review</fullName>
                </value>
                <value>
                    <fullName>Anti_Circumvention_Review</fullName>
                </value>
                <value>
                    <fullName>Changed_Circumstances_Review</fullName>
                </value>
                <value>
                    <fullName>Expedited_Review</fullName>
                </value>
                <value>
                    <fullName>New_Shipper_Review</fullName>
                </value>
                <value>
                    <fullName>Scope_Inquiry</fullName>
                </value>
                <value>
                    <fullName>Sunset_Review</fullName>
                </value>
                <value>
                    <fullName>International_Litigation</fullName>
                </value>
                <value>
                    <fullName>Remand</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Related</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Objects</label>
    <pluralLabel>ADCVD Objects</pluralLabel>
</CustomObject>

src/objects/Constant__mdt.object
<CustomObject>
    <description>This holds constant values used in classes</description>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Constants</relationshipLabel>
        <relationshipName>Constants</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Used_with_Field_Named__c</fullName>
        <label>Used with Field Named</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constant</label>
    <pluralLabel>Constants</pluralLabel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Sunset_Initiation_Date__c</fullName>
        <label>Next Sunset Initiation Date</label>
        <type>Date</type>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/classes/SuspensionAgreementTriggerHandler.cls
public without sharing class SuspensionAgreementTriggerHandler {

	private static Map<String,Constant__mdt> saCalcOffsets = saCalcOffsets();

	//FINAL ADCVD Order Offsets
	private static FINAL Integer SUNSET_INIT_YEARS				    = ((Integer)saCalcOffsets.get('Susp_Agr_Sunset_Initiation_Years').Number_Value__c);//Next_Sunset_Initiation_Date__c
	private static FINAL Integer SUNSET_INIT_MONTHS				    = ((Integer)saCalcOffsets.get('Susp_Agr_Sunset_Initiation_Months').Number_Value__c);//Next_Sunset_Initiation_Date__c


    public static boolean preventRecursion = false;
    public static void mainEntry(List<Suspension_Agreement__c> newList, List<Suspension_Agreement__c> oldList, Map<Id, Suspension_Agreement__c> newMap, 
        Map<Id, Suspension_Agreement__c> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete, 
        Boolean isBefore, Boolean isAfter) {
        if (preventRecursion) {return;}

        if (isBefore && isInsert) {
            initialize(newList,newMap);
            calculateDates(newList);
        }
        if (isBefore && isUpdate) {
            initialize(newList,newMap);
            calculateDates(newList);
        }
        if (isAfter && isUpdate) {

        }
        if(isAfter && isInsert) {

        }
    }

    /*****************************
     * Class Level Variables
    *****************************/

    @TestVisible private static Map<Id,ADCVD_FederalRegisterUtility> frUtilMap = new Map<Id,ADCVD_FederalRegisterUtility>();


    /******************************************
    * Methods called directly by mainEntry()
    ******************************************/

    @TestVisible private static void initialize(List<Suspension_Agreement__c> newList, Map<Id,Suspension_Agreement__c> newMap) {
        if(newMap != null) {
            ADCVD_FederalRegisterUtility listInstance = ADCVD_FederalRegisterUtility.getInstance(newMap.values());//pass newMap to only get Segments with an Id
            frUtilMap = listInstance.utilMap;
        }
    }

    @TestVisible private static void calculateDates(List<Suspension_Agreement__c> newList) {
		for (Suspension_Agreement__c sa : newList) {
            setAnniversaryMonth(sa);
			setNextSunsetInitiationDate(sa);
		}
	}


    /***********************************
    * Helper Methods
    ***********************************/

    //used to set Offset Variables
	@TestVisible private static Map<String,Constant__mdt> saCalcOffsets() {
		if(saCalcOffsets == null || saCalcOffsets.size() < 1) {
			Map<String,Constant__mdt> returnMap = new Map<String,Constant__mdt>();
			List<Constant__mdt> tempList = [SELECT QualifiedAPIName, Used_with_Field_Named__c, Number_Value__c, 
													ADCVD_Objects__r.Object_API_Name__c, ADCVD_Objects__r.Record_Type_Name__c 
											FROM Constant__mdt 
											WHERE Suspension_Agreement_Calculation_Offset__c =: true];
			for(Constant__mdt sc : tempList) {
				returnMap.put(sc.QualifiedAPIName, sc);
			}
			return returnMap;
		} else {
			return saCalcOffsets;
		}
	}


    /*********************************
    * Date Calculations
    *********************************/

    //Set Anniversary_Month__c
    @TestVisible private static void setAnniversaryMonth(Suspension_Agreement__c sa) {
        Date suspensionAgreementPublishedDate = null;
        if (sa.Id != null && frUtilMap != null) {
            suspensionAgreementPublishedDate = frUtilMap.get(sa.Id) != null ? frUtilMap.get(sa.Id).suspensionAgreementPublishedDate : null;
        }
        if (suspensionAgreementPublishedDate != null) {
            sa.Anniversary_Month__c = utils.getMonthFromDate(suspensionAgreementPublishedDate);
        } else {
            sa.Anniversary_Month__c = null;
        }
    }

    //Next_Sunset_Initiation_Date__c
    @TestVisible private static void setNextSunsetInitiationDate(Suspension_Agreement__c sa) {
    	Date nextSSR = null;
    	if (sa.Id != null && frUtilMap != null) {
    		nextSSR = frUtilMap.get(sa.Id) != null ? frUtilMap.get(sa.Id).suspensionAgreementPublishedDate : null;//set to suspensionAgreementPublishedDate if populated
    		nextSSR = (frUtilMap.get(sa.Id) != null && frUtilMap.get(sa.Id).continuationPublishedDate != null) ? frUtilMap.get(sa.Id).continuationPublishedDate : nextSSR;//overwrite to continuationPublishedDate if populated
    		nextSSR = (frUtilMap.get(sa.Id) != null && frUtilMap.get(sa.Id).terminationPublishedDate != null) ? null : nextSSR;//overwrite to null if revocationPublishedDate is populated
    	}
    	if (nextSSR != null) {
    		sa.Next_Sunset_Initiation_Date__c = nextSSR.toStartOfMonth().addYears(SUNSET_INIT_YEARS).addMonths(SUNSET_INIT_MONTHS);
    	} else {
            sa.Next_Sunset_Initiation_Date__c = null;
        }
    }
}