src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVD_ParentObjectFetchingServiceImpl.cls
public class ADCVD_ParentObjectFetchingServiceImpl
    implements ADCVD_IParentObjectFetchingService
{
    public List<SObject> selectById(Set<Id> idSet)
    {
        if (idSet == null || idSet.isEmpty()) return new List<SObject>();

        SObjectType sobjType = validateSetIsHomogenous(idSet);

        if (sobjType == Petition__c.SObjectType)
        {
            return ADCVD_PetitionSelector.newInstance().selectById(idSet);
        }
        else if(sobjType == Investigation__c.SObjectType)
        {
            return ADCVD_InvestigationSelector.newInstance().selectById(idSet);
        }
        else if(sobjType == ADCVD_Order__c.SObjectType)
        {
            return ADCVD_AdcvdOrderSelector.newInstance().selectById(idSet);
        }
        else if(sobjType == Segment__c.SObjectType)
        {
            return ADCVD_SegmentSelector.newInstance().selectById(idSet);
        }
        else if(sobjType == Related_Organization__c.SObjectType)
        {
            return ADCVD_RelatedOrganizationSelector.newInstance().selectById(idSet);
        }

        return new List<SObject>();
    }

    private Set<SObjectType> validSObjectTypes =
            new Set<SObjectType>
            {
                    Petition__c.SObjectType,
                    Investigation__c.SObjectType,
                    ADCVD_Order__c.SObjectType,
                    Segment__c.SObjectType,
                    Related_Organization__c.SObjectType
            };

    private SObjectType validateSetIsHomogenous(Set<Id> idSet)
    {
        List<Id> idList = new List<Id>(idSet);

        SObjectType t = idList.get(0).getSobjectType();

        if (!validSObjectTypes.contains(t))
        {
            throw new ADCVD_ParentObjectFetchingServiceException('The supplied Id set references SObjects that are not supported.');
        }

        for (Id i : idList)
        {
            if (t != i.getSobjectType())
            {
                throw new ADCVD_ParentObjectFetchingServiceException('The supplied Id set must reference only one SObject.');
            }
        }

        return t;
    }

    public class ADCVD_ParentObjectFetchingServiceException
        extends Exception
    {

    }
}