src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Domestic_Party_File_Substan_Response__c</fullName>
        <label>Domestic Party File Substan. Response?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notice_of_intent_to_participate_Ips__c</fullName>
        <description>Was notice of intent to participate by domestic IPs filed?</description>
        <label>Notice of intent to participate Ips?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Respondent_File_Substantive_Response__c</fullName>
        <label>Respondent File Substantive Response?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_to_address_zeroing_in_Segments__c</fullName>
        <description>Conduct 240-day review to address zeroing in underlying segments?</description>
        <inlineHelpText>Conduct 240-day review to address zeroing in underlying segments?</inlineHelpText>
        <label>Review to address zeroing in Segments?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Sunset_Review</fullName>
        <active>true</active>
        <label>Sunset Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/SunsetReviewControllerTest.cls
@isTest
public class SunsetReviewControllerTest {
    static Petition__c p {
        get {
            if (p == null) {
                p = [SELECT Id FROM Petition__c LIMIT 1];
            }
            return p;
        } set;
    }
    static Investigation__c i {
        get {
            if (i == null) {
                i = [SELECT Id FROM Investigation__c LIMIT 1];
            }
            return i;
        } set;
    }
    static ADCVD_Order__c o {
        get {
            if (o == null) {
                o = [SELECT Id FROM ADCVD_Order__c LIMIT 1];
            }
            return o;
        } set;
    }
    static Segment__c s {
        get {
            if (s == null) {
                s = [SELECT Id, Notice_of_intent_to_participate_Ips__c, Domestic_Party_File_Substan_Response__c, Respondent_File_Substantive_Response__c, Review_to_address_zeroing_in_Segments__c 
                        FROM Segment__c LIMIT 1];
            }
            return s;
        } set;
    }
    static User u{
        get{
            if(u == null){
                u = [SELECT Id, ProfileId, isActive, Alias, LanguageLocaleKey, LastName, FirstName, 
                                Email, EmailEncodingKey, TimeZoneSidKey, CommunityNickname, Username 
                            FROM User WHERE LastName =: 'LastName1' LIMIT 1];
            }
            return u;
        }
    }
    static SunsetReviewController ext;
    static PageReference pageRef;
    static ApexPages.StandardController con;

    @isTest static void sunsetTypeTest() {
        Test.startTest();
        sunsetSetup();
        ext.toggleEdit();
        System.assertNotEquals(null, ext.reviewInfoFieldsList);
        System.assertNotEquals(null, ext.fieldsList90);
        System.assertNotEquals(null, ext.fieldsList120);
        System.assertNotEquals(null, ext.fieldsList240);

        ext.ssReview.Notice_of_intent_to_participate_Ips__c = 'No';
        System.assertEquals(true, ext.is90day);
        System.assertEquals(false, ext.is120day);
        System.assertEquals(false, ext.is240day);

        ext.ssReview.Notice_of_intent_to_participate_Ips__c = 'Yes';
        ext.ssReview.Domestic_Party_File_Substan_Response__c = 'Yes';
        ext.ssReview.Respondent_File_Substantive_Response__c = 'No';
        System.assertEquals(false, ext.is90day);
        System.assertEquals(true, ext.is120day);
        System.assertEquals(false, ext.is240day);

        ext.ssReview.Review_to_address_zeroing_in_Segments__c = 'Yes';

        Test.stopTest();
        System.assertEquals(false, ext.is90day);
        System.assertEquals(false, ext.is120day);
        System.assertEquals(true, ext.is240day);
    }
    @isTest static void saveTest() {
        Test.startTest();
        sunsetSetup();
        ext.toggleEdit();
        ext.ssReview.Notice_of_intent_to_participate_Ips__c = 'No';
        ext.save();

        Test.stopTest();

    }
//    @isTest static void cancelTest() {
//        Test.startTest();
//        sunsetSetup();
//        ext.toggleEdit();
//        ext.cancel();
//
//        Test.stopTest();
//        System.assertEquals(false, ext.edit);
//    }
    @isTest static void uxContext() {
        Test.startTest();
        sunsetSetup();
        
        Test.stopTest();
        System.assertNotEquals(null, ext.isSalesforce1);
        System.assertNotEquals(null, ext.isLightningExperience);
        System.assertNotEquals(null, ext.isSalesforceClassic);
    }
    
    @testSetup static void dataSetup() {
        Test.startTest();
        p = TestUtils.createPetition(System.today().addDays(-280), 'AD ME', true);
        i = TestUtils.createInvestigation('AD', p, true);
        o = TestUtils.createOrder(i, true);
        s = TestUtils.createSegment(o, 'Sunset_Review', true);
        u = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
    } 
    private static void sunsetSetup(){
        pageRef = Page.SunsetReview;
        pageRef.getParameters().put('id', s.Id);
        pageRef.getParameters().put('retURL', 'apex/'+ s.Id);
        test.setCurrentPage(pageRef);
        con = new ApexPages.StandardController(s);
        ext = new SunsetReviewController(con);
    }
}