src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staffing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Organization</label>
        <referenceTo>Related_Organization__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staffing Assignment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Staffing Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StaffingAssignmentTriggerHandler.cls
/**
*
*    Created by Joshua Moody
*    on Jan 4 2019
*    MIL Corporation
*
**/
public without sharing class StaffingAssignmentTriggerHandler {
    /***********************************************************
    * This class handles all trigger contexts for the Staffing_Assignment__c
    * object.  It provides methods that:
    * 1. Organize the flow of logic for each trigger context
    * 2. Initialize class variables
    * 3. Help in the mapping of related objects
    * 4. Call services classes
    * 5. Retrieve constant values saved in custom metadata
    ***********************************************************/
    
    public static void mainEntry (List<Staffing_Assignment__c> newList, List<Staffing_Assignment__c> oldList, Map<Id, Staffing_Assignment__c> newMap,
        Map<Id, Staffing_Assignment__c> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete,
        Boolean isBefore, Boolean isAfter) {

        if (!AppConfigService.triggerEnabled) {return;}

        if (isBefore && isInsert) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList, newMap);
            setCaseValues(newList);
        }
        if (isBefore && isUpdate) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList, newMap);
        }
        if (isAfter && isInsert) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList, newMap);
        }
        if (isAfter && isUpdate) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList, newMap);
        }

    }
    //Mapper declared that will be initialized later based on the parent
    @TestVisible private static ADCVD_IMapper adcvdMapper;
    //Mapper declared that will be initialized after caseMapper is initialized
    @TestVisible private static StaffingAssignmentMapper staffMapper;
    //Mapper declared that will be initialized in the initialize method
    @TestVisible private static ADCVD_CaseMapper caseMapper;

    //method to initialize the caseMapper and if newMap is passed (after insert/update) it will add the new staff to the Mappers
    @TestVisible private static void initialize(List<Staffing_Assignment__c> newList, Map<Id,Staffing_Assignment__c> newMap) {
        Set<Id> caseIdSet = getCaseIdSet(newList);
        caseMapper = (ADCVD_CaseMapper) ADCVD_CaseMapper.mapperMap.get('ADCVD_Case__c');
        caseMapper = caseMapper.getInstance(caseIdSet);
        if (newMap != null) {
            addNewStaffToMappers(newMap);
        }
    }
    //method to get the case Ids from the parents.  If a list of Staff is added that have parents from all 5 potential
    //parents, all 5 queries will run.  This should only be called in the initialize method.
    @TestVisible private static Set<Id> getCaseIdSet (List<Staffing_Assignment__c> newList) {
        Set<Id> caseIdSet = new Set<Id>();
        String parentName = '';
        for (Staffing_Assignment__c sa : newList) {
            if (sa.ADCVD_Case__c != null) {
                caseIdSet.add(sa.ADCVD_Case__c);
            }
            if(sa.Petition__c != null) {
                parentName = 'Petition__c';
            } else if(sa.Investigation__c != null) {
                parentName = 'Investigation__c';
            } else if(sa.Segment__c != null) {
                parentName = 'Segment__c';
            } else if(sa.ADCVD_Order__c != null) {
                parentName = 'ADCVD_Order__c';
            } else if(sa.Related_Organization__c != null) {
                parentName = 'Related_Organization__c';
            }
            setSaParent(sa, parentName);
        }
        return caseIdSet;
    }
    //used to set the ADCVD_Case__c field on the Staffing Assignments based on the value in the parents
    @TestVisible private static void setCaseValues(List<Staffing_Assignment__c> newList) {
        ParentValuesService pvs = new ParentValuesService();
        for (Staffing_Assignment__c sa : newList) {
            Id parentId = (Id) sa.get(sa.Staff_Parent__c);
            adcvdMapper = (ADCVD_IMapper) caseMapper.getMapper(sa.Staff_Parent__c).getInstance();
            sa = (Staffing_Assignment__c) pvs.setCaseValuesFromParent(adcvdMapper.getMap(true).get(parentId), sa);
        }
    }
    //Sets Staff_Parent__c to the DeveloperName of the field of the parent (allows .get(Staff_Parent__c) to retrieve the Id of the parent)
    @TestVisible private static void setSaParent (Staffing_Assignment__c sa, String parentName) {
        if (String.isBlank(sa.Staff_Parent__c)) {
            sa.Staff_Parent__c = parentName;
        }
    }
    //method to add the Staff from the recent insert/update to the staffMapper, the caseMapper,
    //and update the StaffingAssignmentMapper instance in the map of selectors with the new Staff
    @TestVisible private static void addNewStaffToMappers(Map<Id,Staffing_Assignment__c> newMap) {
        Map<Id,List<Staffing_Assignment__c>> caseToStaffMap = new Map<Id,List<Staffing_Assignment__c>>();
        //get the StaffingAssignmentMapper instance from the caseMapper
        staffMapper = (StaffingAssignmentMapper) caseMapper.getMapper('Staffing_Assignment__c').getInstance();
        for (Staffing_Assignment__c sa : newMap.values()) {
            //update StaffingAssignmentMapper instance
            staffMapper.addStaffToMap(sa);
            List<Staffing_Assignment__c> tempList = caseToStaffMap.get(sa.ADCVD_Case__c) != null ?
                caseToStaffMap.get(sa.ADCVD_Case__c) : new List<Staffing_Assignment__c>();
            tempList.add(sa);
            caseToStaffMap.put(sa.ADCVD_Case__c, tempList);
        }
        //add the Staff to the case Maps
        for (Id caseId : caseToStaffMap.keySet()) {
            caseMapper.setCaseIdToStaffingMap(caseId, caseToStaffMap.get(caseId));
        }
        //replace the StaffingAssignmentMapper in the caseMapper map with the new updated one
        caseMapper.putMapper('Staffing_Assignment__c', staffMapper);
    }
}