src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <label>ADCVD Case Number Text Value</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Batch_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for triggering a mass batch update via ADCVDStandardCaseFieldsBatch class, which then runs an update an all related child records. To update changes in logic on to the records.</description>
        <label>Batch Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Concat_Text_Values__c</fullName>
        <label>Case Concat Text Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>Commodity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cement and Ceramics</fullName>
                </value>
                <value>
                    <fullName>Chemicals and Allied Industries</fullName>
                </value>
                <value>
                    <fullName>Foodstuffs</fullName>
                </value>
                <value>
                    <fullName>Machinery and Automotive</fullName>
                </value>
                <value>
                    <fullName>Minerals</fullName>
                </value>
                <value>
                    <fullName>Other Metals and Articles of Metal</fullName>
                </value>
                <value>
                    <fullName>Other Mfg.</fullName>
                </value>
                <value>
                    <fullName>Paper and Paperboard</fullName>
                </value>
                <value>
                    <fullName>Plastics and Rubber</fullName>
                </value>
                <value>
                    <fullName>Steel-Related</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Short_Name__c</fullName>
        <label>Product Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Configuration data for applications that utilize triggers in the org. There should be a &quot;default&quot; config and a &quot;testConfig&quot; AppConfig list in an org. EnableTriggers to be checked for both.</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AppConfig</label>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/classes/ADCVDCaseTriggerHandler.cls
public without sharing class ADCVDCaseTriggerHandler {
    /******************
    This class handles all trigger contexts for the ADCVD_Case__c object.
    1. For after update it check for changes in the 5 standardized case fields,
    and if there are changes, it schedules the ADCVDStandardCaseFieldsBatch class
    to update all related child records.
     ******************/
    

    public static void mainEntry(List<ADCVD_Case__c> newList, List<ADCVD_Case__c> oldList, Map<Id, ADCVD_Case__c> newMap,
            Map<Id, ADCVD_Case__c> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete,
            Boolean isBefore, Boolean isAfter) {

        if (!AppConfigService.triggerEnabled) {return;}

        if (isBefore && isInsert) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            updateCaseSearchTextFields(newList);
        }
        if (isBefore && isUpdate) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            updateCaseSearchTextFields(newList);
        }
        if (isAfter && isInsert) {

        }
        if (isAfter && isUpdate) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            updateCaseChildren(newList, oldMap);
        }
    }

    /*****************************************
    * Methods called directly by mainEntry()
    *****************************************/

    @TestVisible private static void updateCaseSearchTextFields(List<ADCVD_Case__c> newList){
        //Method update 3 standardized fields on adcvd case, upon creation of case.
        //Case Country Text field, concatenated case field, adcvd case number
        for(ADCVD_Case__c adcvdCase: newList){
            adcvdCase.ADCVD_Case_Number__c = adcvdCase.Name;
            adcvdCase.Case_Concat_Text_Values__c = adcvdCase.Commodity__c+'; '+adcvdCase.Country__c+'; '+adcvdCase.ADCVD_Case_Type__c;
        }
    }

    @TestVisible private static void updateCaseChildren(List<ADCVD_Case__c> newList, Map<Id, ADCVD_Case__c> oldMap){
        List<ADCVD_Case__c> changedCasesList = getChangedCases(newList, oldMap);
        if(!changedCasesList.isEmpty()){
            //If there is a queued batch job, use getRecentlyModifiedCases method to combine the records from that job
            //into the current context, and run one batch for all modified case records
            Boolean queuedBatchJob = checkCron();
            if(queuedBatchJob) changedCasesList = getRecentlyModifiedCases(changedCasesList);
            scheduleBatchJob(changedCasesList);

        }
    }

    @TestVisible private static List<ADCVD_Case__c> getChangedCases(List<ADCVD_Case__c> newList, Map<Id, ADCVD_Case__c> oldMap){
        List<ADCVD_Case__c> changedCasesList = new List<ADCVD_Case__c>();
        for(ADCVD_Case__c adcvdCase: newList){
            if(adcvdCase.ADCVD_Case_Type__c != oldMap.get(adcvdCase.Id).ADCVD_Case_Type__c || adcvdCase.Commodity__c != oldMap.get(adcvdCase.Id).Commodity__c ||
                    adcvdCase.Country__c != oldMap.get(adcvdCase.Id).Country__c || adcvdCase.Product__c != oldMap.get(adcvdCase.Id).Product__c ||
                    adcvdCase.Product_Short_Name__c != oldMap.get(adcvdCase.Id).Product_Short_Name__c || adcvdCase.Batch_Update__c != oldMap.get(adcvdCase.Id).Batch_Update__c){
                changedCasesList.add(adcvdCase);
            }
        }
        return changedCasesList;
    }

    @TestVisible private static List<ADCVD_Case__c> getRecentlyModifiedCases(List<ADCVD_Case__c> changedCasesList){
        //Construct set of ids to check against, to avoid returning duplicate case records
        Set<Id> alreadyIncludedCasesIds = new Set<Id>();
        for(ADCVD_Case__c adcvdCase: changedCasesList){
            alreadyIncludedCasesIds.add(adcvdCase.Id);
        }
        Datetime dt  = System.now().addHours(-24);
        //Check for most recent completed batch job.
        List<AsyncApexJob> recentAdcvdCaseBatchJob = [select id,JobType,CompletedDate,MethodName,Status, ApexClassId from AsyncApexJob Where JobType = 'BatchApex' and ApexClassId IN (SELECT Id FROM ApexClass WHERE Name = 'ADCVDStandardCaseFieldsBatch') Order by CompletedDate DESC Limit 1];
        //If a batch job was completed recently, use that completed date as most recently updated changes to case
        //and set a batch for all cases that have been edited since then
        if(!recentAdcvdCaseBatchJob.isEmpty()) dt = recentAdcvdCaseBatchJob[0].CompletedDate;
        //Query cases with last modified > dt. From when the last batch job was complete to now.
        List<ADCVD_Case__c> recentlyModifiedCases = [SELECT Id FROM ADCVD_Case__c Where (LastModifiedDate >: dt OR LastModifiedDate >= YESTERDAY) AND Id NOT IN: alreadyIncludedCasesIds];
        recentlyModifiedCases.addAll(changedCasesList);
        return recentlyModifiedCases;

    }

    @TestVisible private static void scheduleBatchJob(List<ADCVD_Case__c> changedCasesList){
        //Get batch size from custom settings
        Decimal batchSize = (Decimal) AppConfig__c.getValues('ADCVDStandardCaseFieldsBatch').get('Batch_Size__c');
        String currentHour = System.now().format('HH');
        Integer minutesTillMidnight = (24 - Integer.valueOf(currentHour)) * 60;
        //Schedule to run today at sometime between 12am and 1am
        //Added a random number at the end of the scheduled batch name, to avoid failures due to duplicate names
        If(!Test.isRunningTest()) System.scheduleBatch(new ADCVDStandardCaseFieldsBatch(changedCasesList), 'Standardized ADCVD Case Fields Update', minutesTillMidnight, (Integer)batchSize);
    }

    @TestVisible private static Boolean checkCron(){
        //Check for batches in queue and if one is there, abort it in order to be able to schedule another
        List<CronTrigger> queuedJob = [SELECT Id, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType, OwnerId, CronExpression, StartTime FROM CronTrigger Where CronJobDetail.Name = 'Standardized ADCVD Case Fields Update'];
        if(!queuedJob.isEmpty()){
            System.abortJob(queuedJob[0].Id);
            return true;
        }
        return false;
    }

}