src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <recordTypes>
        <fullName>Anti_Circumvention_Review</fullName>
        <active>true</active>
        <label>Anti-Circumvention Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harmonized_Tariff_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Harmonized Tariff Schedules</relationshipLabel>
        <relationshipName>Harmonized_Tariff_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Harmonized Tariff Schedule</label>
    <nameField>
        <label>Harmonized Tariff Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harmonized Tariff Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adequacy_of_Respondents_Submission__c</fullName>
        <label>Adequacy of Respondents Submission</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inadequate or Non-Substantive</fullName>
                </value>
                <value>
                    <fullName>Adequate or Substantive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Accepted__c</fullName>
        <label>Application Accepted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Domestic_Party_File_Substan_Response__c</fullName>
        <label>Domestic Party File Substan. Response?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Date_of_Anniversary_Month__c</fullName>
        <description>Final Date of Anniversary Month</description>
        <inlineHelpText>Final Date of Anniversary Month</inlineHelpText>
        <label>Final Date of Anniversary Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notice_of_intent_to_participate_Ips__c</fullName>
        <description>Was notice of intent to participate by domestic IPs filed?</description>
        <label>Notice of intent to participate Ips?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Filed__c</fullName>
        <label>Request Filed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Respondent_File_Substantive_Response__c</fullName>
        <label>Respondent File Substantive Response?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_to_address_zeroing_in_Segments__c</fullName>
        <description>Conduct 240-day review to address zeroing in underlying segments?</description>
        <inlineHelpText>Conduct 240-day review to address zeroing in underlying segments?</inlineHelpText>
        <label>Review to address zeroing in Segments?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Anti_Circumvention_Review</fullName>
        <active>true</active>
        <label>Anti-Circumvention Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Changed_Circumstances_Review</fullName>
        <active>true</active>
        <label>Changed Circumstances Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expedited_Review</fullName>
        <active>true</active>
        <label>Expedited Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>New_Shipper_Review</fullName>
        <active>true</active>
        <label>New Shipper Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scope_Inquiry</fullName>
        <active>true</active>
        <label>Scope Inquiry</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sunset_Review</fullName>
        <active>true</active>
        <label>Sunset Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/ADCVD_OrderSearchTest.cls
@isTest
public class ADCVD_OrderSearchTest {

	private static Date orderDate = System.today();

	@isTest static void mainTest(){
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new ADCVD_OrderSearchTestImpl());
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ADCVD_OrderSearch/';
        req.httpMethod = 'POST'; 
        RestContext.request = req;
        RestContext.response = res;
        ADCVD_OrderSearch.doPost();
        Test.stopTest();
        
        ADCVD_OrderSearch.JsonOutput jsonResponse = (ADCVD_OrderSearch.JsonOutput)JSON.deserialize(res.responseBody.toString(), ADCVD_OrderSearch.JsonOutput.class);
        System.assertEquals(4, jsonResponse.adcvdOrders[0].segments.size());
        System.assertEquals('tacos', jsonResponse.adcvdOrders[0].productShortName);
        System.assertEquals(5, jsonResponse.adcvdOrders[0].htsNums.size());
    }


	@testSetup static void dataSetup() {
		Test.startTest();
		User testUser = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
		Petition__c testADPetition = TestUtils.createPetition(orderDate.addDays(-280), 'AD ME', true);
		Investigation__c testADinvestigation = TestUtils.createInvestigation('AD', testADPetition, true);
		ADCVD_Order__c testOrder = TestUtils.createOrder(testADinvestigation, true);
		List<Harmonized_Tariff_Schedule__c> testHTS = TestUtils.createHtsNumbers(testOrder.Id, Decimal.valueOf('1000000000'), Decimal.valueOf('5'), true);
		Map<String,Segment__c> segsToInsert = new Map<String,Segment__c>();
		System.runAs(testUser) {
			for(String segRecordTypeName : Utils.getRecordTypeDeveloperNameMap('Segment__c').values()) {
				Segment__c testSeg = TestUtils.createSegment(testOrder, segRecordTypeName, false);
				if (segRecordTypeName != 'Sunset_Review') {
					testSeg = setStartDates(testSeg);
				} else {//90 day Sunset
					testSeg.Notice_of_intent_to_participate_Ips__c = 'No';
			        testSeg.Domestic_Party_File_Substan_Response__c = 'No';
			        testSeg.Review_to_address_zeroing_in_Segments__c = '';
			        testSeg.Respondent_File_Substantive_Response__c = '';
			        testSeg.Adequacy_of_Respondents_Submission__c = '';
				}
				segsToInsert.put(segRecordTypeName, testSeg);
			}
			insert segsToInsert.values();
			if (segsToInsert.get('Sunset_Review') != null) {
				Segment__c ssr = segsToInsert.get('Sunset_Review');
				Federal_Register__c testFR = TestUtils.createFR(ssr.Id, 'Segment__c', orderDate.addDays(120), 'Initiation', true);
			}
		}
	}

	private static Segment__c setStartDates(Segment__c s) {
		Map<String,String> recordTypeNameToStartDateMap = new Map<String,String>{
			'Administrative_Review'=>'Final_Date_of_Anniversary_Month__c',
			'Anti_Circumvention_Review'=>'Application_Accepted__c',
			'Changed_Circumstances_Review'=>'Request_Filed__c',
			'Expedited_Review'=>'Calculated_Initiation_Signature__c',
			'New_Shipper_Review'=>'Calculated_Initiation_Signature__c',
			'Scope_Inquiry'=>'Request_Filed__c'
		};
        s.put(recordTypeNameToStartDateMap.get(Utils.recordTypeIdToRecordTypeMap.get(s.RecordTypeId).DeveloperName), orderDate);
        return s;
    }
}