src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Configuration data for applications that utilize triggers in the org. There should be a &quot;default&quot; config and a &quot;testConfig&quot; AppConfig list in an org. EnableTriggers to be checked for both.</description>
    <label>AppConfig</label>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <formula>TEXT(ADCVD_Case__r.ADCVD_Case_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ADCVD Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CVD</fullName>
        <active>true</active>
        <description>A countervailing duties investigation</description>
        <label>CVD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Master Automation</label>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <description>Referenced from parent Petition case</description>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <formula>TEXT(ADCVD_Case__r.ADCVD_Case_Type__c)</formula>
        <label>ADCVD Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomMetadataSelectorTest.cls
@isTest
public class CustomMetadataSelectorTest {

	private static FINAL Integer COUNT = 1;

	@isTest static void allConstants() {
		System.assertNotEquals(0, CustomMetadataSelector.allConstants.size());
	}

	@isTest static void allAdcvdObjects() {
		System.assertNotEquals(0, CustomMetadataSelector.allAdcvdObjects.size());
	}

	@isTest static void allDateCalculations() {
		System.assertNotEquals(0, CustomMetadataSelector.allDateCalculations.size());
	}

	@testSetup static void dataSetup() {
		Test.startTest();
		//create custom setting configuration to activate triggers, workflow rules, and validation rules
        Master_Automation__c ma = TestUtils.createMasterAutomation(true, true, true);
        AppConfig__c ac = TestUtils.createAppConfig('default', true, true);
        //create test data
		Date petitionDate = System.today();
		List<User> uList = new List<User>();
		List<ADCVD_Case__c> cList = new List<ADCVD_Case__c>();
		List<Petition__c> pList = new List<Petition__c>();
		List<Investigation__c> iList = new List<Investigation__c>();
		List<Federal_Register__c> frList = new List<Federal_Register__c>();
		for (Integer i = 0; i < COUNT; i++) {
			User testUser = TestUtils.createAdminUser(false, 'myemail@email.com.testita', i);
			uList.add(testUser);
			ADCVD_Case__c testADCase = TestUtils.createADCVDCase('A-123-12' + i, 'AD ME', false);
			cList.add(testADCase);
			ADCVD_Case__c testCVDCase = TestUtils.createADCVDCase('C-123-12' + i, 'CVD', false);
			cList.add(testCVDCase);
		}
		insert uList;
		insert cList;
		Integer counter = 0;
		for (ADCVD_Case__c c : cList) {
			if (c.ADCVD_Case_Type__c.indexOf('A') > -1) {
				Petition__c testADPetition = TestUtils.createPetition(c, petitionDate.addDays(counter),false);
			pList.add(testADPetition);
			} else if (c.ADCVD_Case_Type__c.indexOf('C') > -1) {
				Petition__c testCVDPetition = TestUtils.createPetition(c, petitionDate.addDays(7 + counter),false);
			pList.add(testCVDPetition);
		}
			counter++;
		}
		insert pList;
		for (Petition__c p : pList) {
			Investigation__c testInvestigation = TestUtils.createInvestigation(p, false);
			iList.add(testInvestigation);
			Federal_Register__c initFR = TestUtils.createFR(p.Id, 'Petition__c', petitionDate.addDays(120), 'Initiation', false);
			frList.add(initFR);
		}
		insert iList;
		for (Investigation__c i : iList) {
			Federal_Register__c prelimFR = TestUtils.createFR(i.Id, 'Investigation__c', petitionDate.addDays(120), 'Preliminary', false);
			frList.add(prelimFR);
			Federal_Register__c finalFR = TestUtils.createFR(i.Id, 'Investigation__c', petitionDate.addDays(120), 'Final', false);
			frList.add(finalFR);
		}
		insert frList;
		//Select newly inserted data
		List<ADCVD_Case__c> adcvdCaseList = [SELECT Id FROM ADCVD_Case__c];
		List<Petition__c> petitionList = [SELECT Id FROM Petition__c];
		List<Investigation__c> investigationList = [SELECT Id FROM Investigation__c];
		List<Federal_Register__c> federalRegisterList = [SELECT Id FROM Federal_Register__c];
		Test.stopTest();
		//Assert that records were inserted
		System.assert(adcvdCaseList.size() > 0);
		System.assert(petitionList.size() > 0);
		System.assert(investigationList.size() > 0);
		System.assert(federalRegisterList.size() > 0);
	}

	@isTest static void childToParentsSObjectMap_Positive() {
		System.assertNotEquals(0, CustomMetadataSelector.childToParentsSObjectMap.size());
	}

	@isTest static void getConstantNameToConstantMap_Positive() {
		System.assertNotEquals(0, CustomMetadataSelector.getConstantNameToConstantMap('adcvd_order_calculation_offset__c').size());
	}

	@isTest static void getParentsForChildSObject_Positive() {
		Test.startTest();
		CustomMetadataSelector cms = new CustomMetadataSelector();
		Test.stopTest();
		System.assertNotEquals(0, cms.getParentsForChildSObject('Segment__c').size());
	}


	@isTest static void getPaymentSettings_Positive() {
		System.assertNotEquals(0, CustomMetadataSelector.getPaymentSettings('Paygov').size());
	}

	@isTest static void childToParentsSObjectMap_Positive() {
		System.assertNotEquals(0, CustomMetadataSelector.childToParentsSObjectMap.size());
	}

	@isTest static void getConstantNameToConstantMap_Positive() {
		System.assertNotEquals(0, CustomMetadataSelector.getConstantNameToConstantMap('adcvd_order_calculation_offset__c').size());
	}

	@isTest static void getParentsForChildSObject_Positive() {
		CustomMetadataSelector cms = new CustomMetadataSelector();
		System.assertNotEquals(0, cms.getParentsForChildSObject('Segment__c').size());
	}


	@isTest static void getPaymentSettings_Positive() {
		System.assertNotEquals(0, CustomMetadataSelector.getPaymentSettings('Paygov').size());
	}
}