src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVD_ParentObjectFetchingService_Test.cls
@IsTest
private class ADCVD_ParentObjectFetchingService_Test
{
    @IsTest
    static void fetchPetition()
    {
        ID id = fflib_IDGenerator.generate(Petition__c.SObjectType);
        new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id> {id});
    }

    @IsTest
    static void fetchInvestigation()
    {
        ID id = fflib_IDGenerator.generate(Investigation__c.SObjectType);
        new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id> {id});
    }

    @IsTest
    static void fetchAdcvdOrder()
    {
        ID id = fflib_IDGenerator.generate(ADCVD_Order__c.SObjectType);
        new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id> {id});
    }

    @IsTest
    static void fetchSegment()
    {
        ID id = fflib_IDGenerator.generate(Segment__c.SObjectType);
        new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id> {id});
    }

    @IsTest
    static void fetchRelatedOrganization()
    {
        ID id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType);
        new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id> {id});
    }

    @IsTest
    static void fetchWithNonhomogenousIdSet()
    {
        ID id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType);
        ID anotherId = fflib_IDGenerator.generate(Petition__c.SObjectType);

        try
        {
            new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id> {id, anotherId});
            System.assert(false);
        }
        catch (Exception exc)
        {
            // as expected
        }
    }

    @IsTest
    static void fetchInvalidSObjectType()
    {
        ID id = fflib_IDGenerator.generate(Account.SObjectType);
        try
        {
            new ADCVD_ParentObjectFetchingServiceImpl().selectById(new Set<Id>{
                    id
            });
            System.assert(false);
        }
        catch (Exception exc)
        {
            // as expected
        }
    }
}