src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>AD_Investigation_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AD investigation that this CVD investigation is aligned to</description>
        <label>AD Investigation Aligned To</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Investigation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AD</value>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Commodity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Commodity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Initiation_Signature__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Initiation_Signature__c</valueField>
            </filterItems>
            <infoMessage>The Product on both investigations must match as well</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Aligned CVD Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Extension_of_days__c</fullName>
        <description>Final Extension (# of days)</description>
        <inlineHelpText>Final Extension (# of days)</inlineHelpText>
        <label>Final Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prelim_Extension_of_days__c</fullName>
        <description>Prelim Extension (# of days)</description>
        <inlineHelpText>Prelim Extension (# of days)</inlineHelpText>
        <label>Prelim Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <description>Initiation Extension (# of days)</description>
        <inlineHelpText>Initiation Extension (# of days)</inlineHelpText>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Litigation_Resolved__c</fullName>
        <label>Litigation Resolved</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Litigation_YesNo__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>Litigation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/InvestigationChatterPostWriterTest.cls
/**
 * 
 *    Created by Skip Kleckner
 *    on Feb 28 2019
 *    MIL Corporation
 *    
 **/

@IsTest
private class InvestigationChatterPostWriterTest {

    private static Date petitionDate = Date.newInstance(2019, 3, 5);
    private static Date investigationDate = Date.newInstance(2019, 3, 5);

    private static ADCVD_Case__c testADCase;
    private static Petition__c petition;
    private static Petition__c petition2;
    private static Investigation__c newI;

    @IsTest
    static void testCheckConditions() {
        dataSetup();

        Investigation__c oldI = newI.clone(true, true, true, true);
        newI.Prelim_Extension_of_days__c = 1;
        newI.Calculated_Preliminary_Signature__c = null;
        oldI.Prelim_Extension_of_days__c = 2;

        Test.startTest();
        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        icpw = new InvestigationChatterPostWriter();
        icpw.checkConditions(newI, oldI);
        //Calculated_Preliminary_Signature__c is null
        System.assert(icpw.getMap(false).get(newI.Id) == null);

        Test.stopTest();
    }

    @IsTest
    static void testPrelimExtensionChanged() {
        dataSetup();

        Investigation__c oldI = newI.clone(true, true, true, true);
        newI.Prelim_Extension_of_days__c = 1;
        newI.Calculated_Preliminary_Signature__c = investigationDate;
        oldI.Prelim_Extension_of_days__c = 2;

        Test.startTest();
        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        icpw = new InvestigationChatterPostWriter();
        icpw.checkConditions(newI, oldI);
        //Calculated_Initiation_Signature__c and Initiation_Extension_of_days__c has changed so we have a chatter post
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('<p>The Calculated Preliminary Signature date is: <b>3/5/2019</b></p>'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('<p>Preliminary Extension Number of Days changed from 2 to 1</p>'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('<p>Link to record:'));

        Test.stopTest();
    }

    @IsTest
    static void testFinalExtensionChanged() {
        dataSetup();

        Investigation__c oldI = newI.clone(true, true, true, true);
        newI.Final_Extension_of_days__c = 1;
        newI.Calculated_Final_Signature__c = null;
        oldI.Final_Extension_of_days__c = 2;

        Test.startTest();
        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        icpw = new InvestigationChatterPostWriter();
        icpw.finalExtensionChanged(newI, oldI);
        //Calculated_Final_Signature__c is null
        System.assert(icpw.getMap(false).get(newI.Id) == null);

        newI.Final_Extension_of_days__c = 1;
        newI.Calculated_Final_Signature__c = investigationDate;
        oldI.Final_Extension_of_days__c = 2;

        icpw = new InvestigationChatterPostWriter();
        icpw.finalExtensionChanged(newI, oldI);
        //Calculated_Initiation_Signature__c and Initiation_Extension_of_days__c has changed so we have a chatter post
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('<p>The Calculated Final Signature date is: <b>3/5/2019</b></p>'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('<p>Final Extension Number of Days changed from 2 to 1</p>'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('<p>Link to record:'));

        Test.stopTest();
    }

    @IsTest
    static void testLitigationNoChange() {
        dataSetup();

        Investigation__c oldI = newI.clone(true, true, true, true);

        newI.Litigation_YesNo__c = 'Yes';
        newI.Litigation_Resolved__c = 'Yes';

        Test.startTest();

        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        //old - yes/yes -- new - yes/yes
        icpw.litigationChanged(newI, oldI);
        System.assert(icpw.getMap(false).get(newI.Id) == null);

        Test.stopTest();


    }
    @IsTest
    static void testLitigationNoChange2() {
        dataSetup();

        newI.Litigation_YesNo__c = 'Yes';
        newI.Litigation_Resolved__c = 'Yes';
        Investigation__c oldI = newI.clone(true, true, true, true);

        Test.startTest();

        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        //old - yes/yes -- new - no/blank
        newI.Litigation_YesNo__c = 'No';
        newI.Litigation_Resolved__c = '';
        icpw = new InvestigationChatterPostWriter();
        icpw.litigationChanged(newI, oldI);
        System.assert(icpw.getMap(false).get(newI.Id) == null);

        Test.stopTest();


    }
    @IsTest
    static void testLitigationLitigated() {
        dataSetup();

        Investigation__c oldI = newI.clone(true, true, true, true);

        Test.startTest();

        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        //old - no/blank -- new - yes/no
        oldI.Litigation_YesNo__c = 'No';
        oldI.Litigation_Resolved__c = '';
        newI.Litigation_YesNo__c = 'Yes';
        newI.Litigation_Resolved__c = 'No';
        icpw = new InvestigationChatterPostWriter();
        icpw.litigationChanged(newI, oldI);
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('Litigation Status has changed'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('is being litigated.'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('Link to record:'));

        Test.stopTest();

    }
    @IsTest
    static void testLitigationLitigatedNotLitigated() {
        dataSetup();

        Investigation__c oldI = newI.clone(true, true, true, true);

        Test.startTest();

        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        //old - yes/no -- new - yes/yes
        oldI.Litigation_YesNo__c = 'Yes';
        oldI.Litigation_Resolved__c = 'No';
        newI.Litigation_YesNo__c = 'Yes';
        newI.Litigation_Resolved__c = 'Yes';
        icpw = new InvestigationChatterPostWriter();
        icpw.litigationChanged(newI, oldI);
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('Litigation Status has changed'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('is not being litigated.'));
        System.assert(icpw.getMap(false).get(newI.Id).get(0).contains('Link to record:'));

        Test.stopTest();
    }
    @IsTest
    static void testAlignmentChanged() {

        dataSetup();

        //create aligned to investigations
        Investigation__c alignedToInv1 = TestUtils.createInvestigation(petition, false);
        alignedToInv1.Id = fflib_IDGenerator.generate(Investigation__c.SObjectType);
        Investigation__c alignedToInv2 = TestUtils.createInvestigation(petition2, false);
        alignedToInv2.Id = fflib_IDGenerator.generate(Investigation__c.SObjectType);


        Investigation__c oldI = newI.clone(true, true, true, true);

        Test.startTest();

        InvestigationChatterPostWriter icpw = new InvestigationChatterPostWriter();
        //old - yes/no -- new - yes/yes
        oldI.AD_Investigation_Aligned_To__c = null;
        newI.AD_Investigation_Aligned_To__c = alignedToInv2.Id;
        icpw = new InvestigationChatterPostWriter();
        icpw.alignmentChanged(newI, oldI);

        System.assert(icpw.getMap(false).get(newI.Id ).get(0).contains('Alignment to another record has changed on '));
        System.assert(icpw.getMap(false).get(newI.Id ).get(0).contains('Alignment has been added'));
        System.assert(icpw.getMap(false).get(newI.Id ).get(0).contains('Link to record:'));

        Test.stopTest();
    }
    @testSetup static void dataSetup() {
        // Create ADCVD_Case record
        testADCase = TestUtils.createADCVDCase('A-123-123', 'AD ME', false);
        testADCase.Id = fflib_IDGenerator.generate(ADCVD_Case__c.SObjectType);

        petition = TestUtils.createPetition(testADCase, petitionDate, false);
        petition.Calculated_Initiation_Signature__c = petitionDate;
        petition.Id = fflib_IDGenerator.generate(Petition__c.SObjectType);

        petition2 = TestUtils.createPetition(testADCase, petitionDate, false);
        petition2.Calculated_Initiation_Signature__c = petitionDate;
        petition2.Id = fflib_IDGenerator.generate(Petition__c.SObjectType);

        newI = TestUtils.createInvestigation(petition, false);
        newI.Id = fflib_IDGenerator.generate(Investigation__c.SObjectType);
    }

}