src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suspension_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suspension Agreement</label>
        <referenceTo>Suspension_Agreement__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>AD_Investigation_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AD investigation that this CVD investigation is aligned to</description>
        <label>AD Investigation Aligned To</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Investigation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AD</value>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Commodity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Commodity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Initiation_Signature__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Initiation_Signature__c</valueField>
            </filterItems>
            <infoMessage>The Product on both investigations must match as well</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Aligned CVD Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suspension_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suspension Agreement</label>
        <referenceTo>Suspension_Agreement__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field displays the Type of Suspension Agreement</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD - 734(b) - Cessation of Exports</fullName>
                </value>
                <value>
                    <fullName>AD - 734(b) - Normal Value</fullName>
                </value>
                <value>
                    <fullName>AD - 734(c) - Reference Price</fullName>
                </value>
                <value>
                    <fullName>AD - 734(l) - NME</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(b) - Elimination of Subsidy</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(b) - Cessation of Exports</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(c) - Other than Quantitative Restriction</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(c) - Quantitative Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Federal_RegisterCS.cls
public without sharing class Federal_RegisterCS implements ADCVD_CascadeService {

	/**
	 * Implements the ADCVD_CascadeService for Federal_Register__c objects
	 * @param  parentObjectName Not needed currently, but is in place in case special logic applies to different parent SObject types
	 * @param  parentIdSet      List of parentIds. Can be Federal_Register__c Ids if a Federal_Register__c is inserted or updated
	 * @return                  Map of parentId to Federal_Register__c that has been type cast to an SObject
	 */

	public Map<Id,SObject> getParentIdToObjectMap(String parentObjectName, Set<Id> parentIdSet){
		return new Map<Id,SObject>();
	}

	/**
	 * Implements the ADCVD_CascadeService for Federal_Register__c objects
	 * @param  parentObjectName Not needed currently, but is in place in case special logic applies to different parent SObject types
	 * @param  parentIdSet      List of parentIds. Can be Federal_Register__c Ids if a Federal_Register__c is inserted or updated
	 * @return                  Map of parentId to List of Federal_Register__c objects that has been type cast to SObjects
	 */
	public Map<Id,List<SObject>> getParentIdToObjectsMap(String parentObjectName, Set<Id> parentIdSet) {
		Map<Id,List<Federal_Register__c>> returnMap = new Map<Id,List<Federal_Register__c>>();
		if (parentObjectName == 'Segment__c') {
			for (Segment__c s : [SELECT ADCVD_Order__c FROM Segment__c WHERE Id IN: parentIdSet]) {
				parentIdSet.add(s.ADCVD_Order__c);
			}
		}
		//query all potential parents for the FRs whose parent is in the parentIdSet
		for(Federal_Register__c fr : [SELECT Id, Type__c, Published_Date__c, Do_Delete__c, Segment__c, Investigation__c, CreatedDate, 
										Investigation__r.AD_Investigation_Aligned_To__c, Investigation__r.Petition__c,
										Investigation__r.AD_Investigation_Aligned_To__r.Petition__c,
										ADCVD_Order__c, ADCVD_Order__r.Investigation__c, ADCVD_Order__r.Investigation__r.Petition__c,
										Suspension_Agreement__c, Suspension_Agreement__r.Investigation__c, Suspension_Agreement__r.Investigation__r.Petition__c,
										Segment__r.ADCVD_Order__c, Segment__r.ADCVD_Order__r.Investigation__c,
										Segment__r.ADCVD_Order__r.Investigation__r.AD_Investigation_Aligned_To__c, 
										Segment__r.ADCVD_Order__r.Investigation__r.AD_Investigation_Aligned_To__r.Petition__c,
										Segment__r.ADCVD_Order__r.Investigation__r.Petition__c,
										Segment__r.Suspension_Agreement__c, Segment__r.Suspension_Agreement__r.Investigation__c,
										Segment__r.Suspension_Agreement__r.Investigation__r.AD_Investigation_Aligned_To__c, 
										Segment__r.Suspension_Agreement__r.Investigation__r.AD_Investigation_Aligned_To__r.Petition__c,
										Segment__r.Suspension_Agreement__r.Investigation__r.Petition__c 
										FROM Federal_Register__c 
										WHERE Id IN: parentIdSet
										OR Segment__c IN: parentIdSet
										OR Investigation__c IN: parentIdSet
										OR Investigation__r.AD_Investigation_Aligned_To__c IN: parentIdSet
										OR Investigation__r.Petition__c IN: parentIdSet
										OR Investigation__r.AD_Investigation_Aligned_To__r.Petition__c IN: parentIdSet
										OR ADCVD_Order__c IN: parentIdSet
										OR ADCVD_Order__r.Investigation__c IN: parentIdSet
										OR ADCVD_Order__r.Investigation__r.Petition__c IN: parentIdSet
										OR Suspension_Agreement__c IN: parentIdSet
										OR Suspension_Agreement__r.Investigation__c IN: parentIdSet
										OR Suspension_Agreement__r.Investigation__r.Petition__c IN: parentIdSet
										OR Segment__r.ADCVD_Order__c IN: parentIdSet
										OR Segment__r.ADCVD_Order__r.Investigation__c IN: parentIdSet
										OR Segment__r.ADCVD_Order__r.Investigation__r.AD_Investigation_Aligned_To__c IN: parentIdSet
										OR Segment__r.ADCVD_Order__r.Investigation__r.AD_Investigation_Aligned_To__r.Petition__c IN: parentIdSet
										OR Segment__r.ADCVD_Order__r.Investigation__r.Petition__c IN: parentIdSet
										OR Segment__r.Suspension_Agreement__c IN: parentIdSet
										OR Segment__r.Suspension_Agreement__r.Investigation__c IN: parentIdSet
										OR Segment__r.Suspension_Agreement__r.Investigation__r.AD_Investigation_Aligned_To__c IN: parentIdSet
										OR Segment__r.Suspension_Agreement__r.Investigation__r.AD_Investigation_Aligned_To__r.Petition__c IN: parentIdSet
										OR Segment__r.Suspension_Agreement__r.Investigation__r.Petition__c IN: parentIdSet]) {
			//create a temporary set for this FR that contains all it's potential parents
			Set<Id> tempSet = new Set<Id>{fr.Id, fr.Segment__c, fr.Investigation__c, fr.ADCVD_Order__c, fr.Suspension_Agreement__c, fr.Investigation__r.AD_Investigation_Aligned_To__c,
										fr.ADCVD_Order__r.Investigation__c, fr.Suspension_Agreement__r.Investigation__c, fr.Segment__r.ADCVD_Order__r.Investigation__c,
										fr.Segment__r.ADCVD_Order__r.Investigation__r.AD_Investigation_Aligned_To__c, fr.Segment__r.Suspension_Agreement__r.Investigation__c,
										fr.Segment__r.Suspension_Agreement__r.Investigation__r.AD_Investigation_Aligned_To__c};
			for(Id tempId : tempSet) {
				if(tempId != null) {//only map this FR to parents that are not null
					List<Federal_Register__c> tempList = new List<Federal_Register__c>();
					if(returnMap.get(tempId) != null) {
						tempList.addAll(returnMap.get(tempId));
						tempList.add(fr);
					} else {
						tempList.add(fr);
					}
					returnMap.put(tempId, tempList);
				}
			}
		}
		return (Map<Id,List<SObject>>)returnMap;
	}
}