src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Objects__mdt.object
<CustomObject>
    <description>This holds the object types, record types, and a type field (if present) delineating a difference in records for the ADCVD app</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Petition__c</fullName>
                    <default>true</default>
                    <label>Petition__c</label>
                </value>
                <value>
                    <fullName>Investigation__c</fullName>
                </value>
                <value>
                    <fullName>ADCVD_Order__c</fullName>
                </value>
                <value>
                    <fullName>Segment__c</fullName>
                </value>
                <value>
                    <fullName>Litigation__c</fullName>
                </value>
                <value>
                    <fullName>Related_Organization__c</fullName>
                </value>
                <value>
                    <fullName>Federal_Register__c</fullName>
                </value>
                <value>
                    <fullName>Recusal__c</fullName>
                </value>
                <value>
                    <fullName>Staffing_Assignment__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
                <value>
                    <fullName>Administrative_Review</fullName>
                </value>
                <value>
                    <fullName>Anti_Circumvention_Review</fullName>
                </value>
                <value>
                    <fullName>Changed_Circumstances_Review</fullName>
                </value>
                <value>
                    <fullName>Expedited_Review</fullName>
                </value>
                <value>
                    <fullName>New_Shipper_Review</fullName>
                </value>
                <value>
                    <fullName>Scope_Inquiry</fullName>
                </value>
                <value>
                    <fullName>Sunset_Review</fullName>
                </value>
                <value>
                    <fullName>International_Litigation</fullName>
                </value>
                <value>
                    <fullName>Remand</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Related</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Objects</label>
    <pluralLabel>ADCVD Objects</pluralLabel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Sunset_Initiation_Date__c</fullName>
        <label>Next Sunset Initiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment_Status__c</fullName>
        <label>Segment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Litigation Hold</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Constant__mdt.object
<CustomObject>
    <description>This holds constant values used in classes</description>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Constants</relationshipLabel>
        <relationshipName>Constants</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used_with_Field_Named__c</fullName>
        <label>Used with Field Named</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constant</label>
    <pluralLabel>Constants</pluralLabel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Segment_Status__c</fullName>
        <description>Segment Status</description>
        <inlineHelpText>Segment Status</inlineHelpText>
        <label>Segment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Litigation Hold</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <description>Services order record type</description>
        <label>Services</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>How To Proceed</fullName>
                </value>
                <value>
                    <fullName>Prelim</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amend Final</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Customs</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Litigation Hold</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected/Deficient/Negative Finding</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Remand/International Litigation</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>With the Court</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Withdrawn/Rescinded</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/classes/ADCVDOrderTriggerHandler.cls
/**
 * 
 *    Created by Joshua Moody
 *    on Apr 17 2017
 *    MIL Corporation
 * 
 **/
 public without sharing class ADCVDOrderTriggerHandler {
     /***********************************************************
    * This class handles all trigger contexts for the ADCVD_Order__c
    * object.  It provides methods that:
    * 1. Organize the flow of logic for each trigger context
    * 2. Initialize class variables
    * 3. Help in the mapping of related objects
    * 4. Call services classes to do date calculations
    * 5. Retrieve constant values saved in custom metadata
    * 6. Performs status calculations
    * 7. Performs custom validations not possible with validation rules
    ***********************************************************/

    @TestVisible private static Set<String> activeSegmentStatuses = new Set<String>();
    private static Map<String,Constant__mdt> orderCalcOffsets = orderCalcOffsets();

    //FINAL ADCVD Order Offsets
    private static FINAL Integer SUNSET_INIT_YEARS                  = ((Integer)orderCalcOffsets.get('Order_Sunset_Initiation_Years').Number_Value__c);//Next_Sunset_Initiation_Date__c
    private static FINAL Integer SUNSET_INIT_MONTHS                 = ((Integer)orderCalcOffsets.get('Order_Sunset_Initiation_Months').Number_Value__c);//Next_Sunset_Initiation_Date__c
    private static FINAL Integer EFFECTIVE_DATE_REVO_MONTHS         = ((Integer)orderCalcOffsets.get('Order_Effective_Revocation_Months').Number_Value__c);//Effective_Date_of_Revocation__c
    private static FINAL Integer EFFECTIVE_DATE_REVO_YEARS          = ((Integer)orderCalcOffsets.get('Order_Effective_Revocation_Years').Number_Value__c);//Effective_Date_of_Revocation__c


    public static boolean preventRecursion = false;
    public static void mainEntry(List<ADCVD_Order__c> newList, List<ADCVD_Order__c> oldList, Map<Id, ADCVD_Order__c> newMap, 
        Map<Id, ADCVD_Order__c> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete, 
        Boolean isBefore, Boolean isAfter) {
        
        if (!AppConfigService.triggerEnabled) {
            return;
        }

        if (isBefore && isInsert) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList,newMap);
            setCaseValues(newList);
            calculateOrderDates(newList);
            calculateOrderStatuses(newList);
            runCustomValidations(newList);
        }
        if (isBefore && isUpdate) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList,newMap);
            calculateOrderDates(newList);
            calculateOrderStatuses(newList);
            runCustomValidations(newList);
        }
        if (isAfter && isInsert) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList, newMap);
            new StaffingAssignmentService().createStaffFromSObjectParent(newList, 'ADCVD_Order__c');
        }
        if (isAfter && isUpdate) {
            newList = new LockedRecordHandler().removeLockedRecords(newList);
            initialize(newList, newMap);
        }
    }

    /*****************************
    * Class Level Variables
    *****************************/
    @TestVisible private static Map<Id,Investigation__c> investigationsInScopeMap = new Map<Id,Investigation__c>();
    @TestVisible private static Map<Id,List<Segment__c>> orderIdToSegmentMap = new Map<Id,List<Segment__c>>();
    @TestVisible private static Map<Id,String> orderIdToSegmentStatusMap = new Map<Id,String>();
    @TestVisible private static Map<Id, FederalRegisterMapper.MappedFRs> frUtilMap = new Map<Id, FederalRegisterMapper.MappedFRs>();
    @TestVisible private static ADCVD_CaseMapper caseMapper = (ADCVD_CaseMapper) ADCVD_CaseMapper.mapperMap.get('ADCVD_Case__c');
    @TestVisible private static ADCVD_OrderMapper orderMapper;
    @TestVisible private static FederalRegisterMapper frMapper;

    /*****************************************
    * Methods called directly by mainEntry()
    *****************************************/

    /**
     * Sets class level variables
     * @param  newList new Orders in scope, available before insert
     * @param  newMap  new Orders in scope, null before insert
     * @return         [description]
     */
    @TestVisible private static void initialize(List<ADCVD_Order__c> newList, Map<Id,ADCVD_Order__c> newMap) {
        Set<Id> caseIdSet = getCaseIdSet(newList);
        for (ADCVD_Order__c ao : newList) {
            caseIdSet.add(ao.ADCVD_Case__c);
        }
        caseMapper = caseMapper.getInstance(caseIdSet);
        InvestigationMapper is = (InvestigationMapper) caseMapper.getMapper('Investigation__c').getInstance();
        investigationsInScopeMap = (Map<Id,Investigation__c>) caseMapper.getMapper('Investigation__c').getInstance().getMap(true);
        if(newMap != null) {
            addNewOrderToMappers(newMap);
            frMapper = (FederalRegisterMapper) caseMapper.getMapper('Federal_Register__c').getInstance();
            frUtilMap = frMapper.getMappedFRs(newMap.keySet(), caseMapper);
            
            if(!system.isFuture() && !system.isBatch() && !system.isQueueable() && Limits.getLimitFutureCalls() > Limits.getFutureCalls()){
                
                setOrderIdToSegmentMap(newMap.keySet());
            }
            
            setOrderIdToSegmentStatusMap(newMap.keySet());
        }
    }
    @TestVisible private static Set<Id> getCaseIdSet (List<ADCVD_Order__c> newList) {
        Set<Id> caseIdSet = new Set<Id>();
        Set<Id> invIdSet = new Set<Id>();
        for (ADCVD_Order__c ao : newList) {
            invIdSet.add(ao.Investigation__c);
        }
        for (Investigation__c i : [SELECT ADCVD_Case__c FROM Investigation__c WHERE Id IN: invIdSet]) {
            caseIdSet.add(i.ADCVD_Case__c);
        }
        return caseIdSet;
    }

    @TestVisible private static void setCaseValues(List<ADCVD_Order__c> newList) {
        ParentValuesService pvs = new ParentValuesService();
        for (ADCVD_Order__c ao : newList) {
            ao = (ADCVD_Order__c) pvs.setCaseValuesFromParent(investigationsInScopeMap.get(ao.Investigation__c), ao);
        }
    }

    @TestVisible private static void addNewOrderToMappers(Map<Id,ADCVD_Order__c> newMap) {
        Map<Id,List<ADCVD_Order__c>> caseToOrderMap = new Map<Id,List<ADCVD_Order__c>>();
        orderMapper = (ADCVD_OrderMapper) caseMapper.getMapper('ADCVD_Order__c').getInstance();
        for (ADCVD_Order__c ao : newMap.values()) {
            orderMapper.addOrderToMap(ao);
            List<ADCVD_Order__c> tempList = caseToOrderMap.get(ao.ADCVD_Case__c) != null ?
                                                   caseToOrderMap.get(ao.ADCVD_Case__c) : new List<ADCVD_Order__c>();
            tempList.add(ao);
            caseToOrderMap.put(ao.ADCVD_Case__c, tempList);
        }
        for (Id caseId : caseToOrderMap.keySet()) {
            caseMapper.setCaseIdToOrderMap(caseId, caseToOrderMap.get(caseId));
        }
    }

    /**
     * Primary method to order and call all date calculations.  Restricted to only logical order, not specific field calculations
     * @param  newList [description]
     * @return         [description]
     */
    @TestVisible private static void calculateOrderDates(List<ADCVD_Order__c> newList) {
        for (ADCVD_Order__c o : newList) {
            setAnniversaryMonth(o);
            setNextSunsetInitiationDate(o);
        }
    }

    /**
     * Primary method to order and call all status calculations. Restricted to only logical order, not specific field calculations
     * @param  newList [description]
     * @return         [description]
     */
    @TestVisible private static void calculateOrderStatuses(List<ADCVD_Order__c> newList) {
        setSegmentStatus(newList);
        setStatus(newList);
    }

    @TestVisible private static void runCustomValidations(List<ADCVD_Order__c> newList) {
        for (ADCVD_Order__c o : newList) {
            validateEffectiveDateOfRevocation(o);
        }
    }


    /***********************************
    * Helper Methods
    ***********************************/

    //used to set Offset Variables
    @TestVisible private static Map<String,Constant__mdt> orderCalcOffsets() {
        if(orderCalcOffsets == null || orderCalcOffsets.size() < 1) {
            Map<String,Constant__mdt> returnMap = new Map<String,Constant__mdt>();
            for (Constant__mdt sc : [
                    SELECT QualifiedAPIName, Used_with_Field_Named__c, Number_Value__c, String_Value__c,
                                                    ADCVD_Objects__r.Object_API_Name__c, ADCVD_Objects__r.Record_Type_Name__c,
                                                    Segment_Calculation_Offset__c 
                                            FROM Constant__mdt 
                    WHERE ADCVD_Order_Calculation_Offset__c = :true
            ]) {
                if (sc.Used_with_Field_Named__c == 'Status__c' && sc.Segment_Calculation_Offset__c && sc.String_Value__c != null) {
                    activeSegmentStatuses.add(sc.String_Value__c);
                }
                returnMap.put(sc.QualifiedAPIName, sc);
            }
            return returnMap;
        } else {
            return orderCalcOffsets;
        }
    }

    /**
     * Sets map of order Ids in scope to all of their Segments.
     * Segment Status
     * @param  orderIdSet [description]
     * @return            [description]
     */

    @Future
    @TestVisible private static void setOrderIdToSegmentMap(Set<Id> orderIdSet) {
        for (Segment__c s : [SELECT Id, ADCVD_Order__c, Status__c, Do_Delete__c FROM Segment__c WHERE ADCVD_Order__c IN: orderIdSet]) {
            List<Segment__c> tempList = new List<Segment__c>();
            if (orderIdToSegmentMap.get(s.ADCVD_Order__c) != null) {
                tempList = orderIdToSegmentMap.get(s.ADCVD_Order__c);
            }
            tempList.add(s);
            orderIdToSegmentMap.put(s.ADCVD_Order__c, tempList);
        }
    }

    @TestVisible private static void setOrderIdToSegmentStatusMap(Set<Id> orderIdSet) {
        if (orderIdToSegmentMap != null && !orderIdToSegmentMap.isEmpty()) {
            for (Id orderId : orderIdToSegmentMap.keySet()) {
                for (Segment__c s : orderIdToSegmentMap.get(orderId)) {
                    if ((orderIdToSegmentStatusMap.get(orderId) == null || !activeSegmentStatuses.contains(orderIdToSegmentStatusMap.get(orderId))) && !s.Do_Delete__c) {
                        orderIdToSegmentStatusMap.put(orderId, s.Status__c);
                    }
                }
            }
        }
        for (Id orderId : orderIdSet) {
            if (!orderIdToSegmentMap.keySet().contains(orderId)) {
                orderIdToSegmentStatusMap.put(orderId, '');
            }
        }
    }


    /*********************************
    * Date Calculations
    *********************************/

    //Set Anniversary_Month__c
    @TestVisible private static void setAnniversaryMonth(ADCVD_Order__c o) {
        Date orderPublishedDate = null;
        if (o.Id != null && frUtilMap != null) {
            orderPublishedDate = frUtilMap.get(o.Id) != null ? frUtilMap.get(o.Id).typeToPublishedDateMap.get('Order') : null;
        }
        if (orderPublishedDate != null) {
            o.Anniversary_Month__c = utils.getMonthFromDate(orderPublishedDate);
        } else {
            o.Anniversary_Month__c = null;
        }
    }

    //Next_Sunset_Initiation_Date__c
    @TestVisible private static void setNextSunsetInitiationDate(ADCVD_Order__c o) {
        Date nextSSR = null;
        if (o.Id != null && frUtilMap != null) {
            nextSSR = frUtilMap.get(o.Id) != null ? frUtilMap.get(o.Id).typeToPublishedDateMap.get('Order') : null;//set to orderPublishedDate if populated
            nextSSR = frUtilMap.get(o.Id) != null && frUtilMap.get(o.Id).typeToPublishedDateMap.get('Continuation') != null ? frUtilMap.get(o.Id).typeToPublishedDateMap.get('Continuation') : nextSSR;//overwrite to continuationPublishedDate if populated
            nextSSR = frUtilMap.get(o.Id) != null && frUtilMap.get(o.Id).typeToPublishedDateMap.get('Revocation') != null ? null : nextSSR;//overwrite to null if revocationPublishedDate is populated
        }
        if (nextSSR != null) {
            o.Next_Sunset_Initiation_Date__c = nextSSR.toStartOfMonth().addYears(SUNSET_INIT_YEARS).addMonths(SUNSET_INIT_MONTHS);
        } else {
            o.Next_Sunset_Initiation_Date__c = null;
        }
    }

    /******************************
    * Status Calculations
    ******************************/

    @TestVisible private static void setSegmentStatus(List<ADCVD_Order__c> newList) {
        for (ADCVD_Order__c o : newList) {
            if (o.Id != null && orderIdToSegmentStatusMap.get(o.Id) != null && activeSegmentStatuses.contains(orderIdToSegmentStatusMap.get(o.Id))){
                o.Segment_Status__c = 'Active';
            } else {
                o.Segment_Status__c = 'Inactive';
            }
        }
    }

    @TestVisible private static void setStatus(List<ADCVD_Order__c> newList){        
        for (ADCVD_Order__c o : newList){
            if (o.Status__c != 'Revoked-Complete') {//skip if already Revoked-Complete
                o.Status__c = 'Order FR Needed';//set for before insert context
                Date orderPublished = null;
                Date revocationPublished = null;
                if (o.Id != null && frUtilMap != null) {
                    revocationPublished = frUtilMap.get(o.Id) != null ? frUtilMap.get(o.Id).typeToPublishedDateMap.get('Revocation') : null;
                    orderPublished = frUtilMap.get(o.Id) != null ? frUtilMap.get(o.Id).typeToPublishedDateMap.get('Order') : null;
                }
                if (orderPublished == null) {//set if updated and still does not have an Order FR
                    o.Status__c = 'Order FR Needed';
                } else if (o.Segment_Status__c == 'Active') {//set based on Segment Status
                    o.Status__c = 'Current-Active';
                } else if (o.Segment_Status__c != 'Active') {
                    o.Status__c = 'Current-Inactive';
                }
                if (revocationPublished != null) {
                    o.Status__c = 'Revoked-Incomplete';
                }
            }
        }
    }


    /**************************
    * Custom Validations
    **************************/

    //Effective_Date_of_Revocation__c
    @TestVisible private static void validateEffectiveDateOfRevocation(ADCVD_Order__c o) {
        String maxDateName = '';
        Date maxDate = null;
        if (o.Id != null && frUtilMap != null && frUtilMap.get(o.Id) != null && frUtilMap.get(o.Id).typeToPublishedDateMap.get('Revocation') != null) {
            if (frUtilMap.get(o.Id).typeToPublishedDateMap.get('Order') != null) {
                maxDate = frUtilMap.get(o.Id).typeToPublishedDateMap.get('Order');
                maxDateName = 'Order Federal Register Published Date: ' + maxDate.format();
            }
            if (frUtilMap.get(o.Id).typeToPublishedDateMap.get('Continuation') != null) {
                maxDate = frUtilMap.get(o.Id).typeToPublishedDateMap.get('Continuation');
                maxDateName = 'most recent Continuation Federal Register Published Date: ' + maxDate.format();
            }
            maxDate = maxDate != null ? maxDate.addYears(EFFECTIVE_DATE_REVO_YEARS).addMonths(EFFECTIVE_DATE_REVO_MONTHS) : null;
        }
        if (maxDate != null && o != null && o.Effective_Date_of_Revocation__c != null && maxDate < o.Effective_Date_of_Revocation__c) {
            o.Effective_Date_of_Revocation__c.addError('The Effective Date of Revocation cannot be more than 5 years from the ' + maxDateName);
        }
    }
}