src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>AD_Investigation_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AD investigation that this CVD investigation is aligned to</description>
        <label>AD Investigation Aligned To</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Investigation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AD</value>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Commodity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Commodity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Initiation_Signature__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Initiation_Signature__c</valueField>
            </filterItems>
            <infoMessage>The Product on both investigations must match as well</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Aligned CVD Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVD_FederalRegisterUtilityTest.cls
/**
 * 
 *    Created by Joshua Moody
 *    on Feb 28 2017
 *    MIL Corporation
 * 
 **/

@isTest
public class ADCVD_FederalRegisterUtilityTest {

	/************************************************
    * This class performs unit tests on the ADCVD_FederalRegisterUtility
    * under these condititions.
    * 1. Test to ensure that an instance is created from a list of SObjects
    * Further testing for functionality needed.
    *************************************************/

	private static Date petitionDate = System.today();
	private static String parentObjectName = '';
	private static List<Investigation__c> iList {
		get {
			if(iList == null) {
				iList = [SELECT Id, RecordTypeId, AD_Investigation_Aligned_To__c, Calculated_Final_Signature__c, Petition__c FROM Investigation__c];
			}
			return iList;
		}
	}
	private static List<Segment__c> sList {
		get {
			if(sList == null) {
				sList = [SELECT Id FROM Segment__c];
			}
			return sList;
		}
	}
	private static Federal_Register__c invFR {
		get {
			if(invFR == null) {
				invFR = [SELECT Id FROM Federal_Register__c WHERE Investigation__c !=: null LIMIT 1];
			}
			return invFR;
		}
		
	}
	private static Federal_Register__c segFR {
		get {
			if(segFR == null) {
				segFR = [SELECT Id FROM Federal_Register__c WHERE Segment__c !=: null LIMIT 1];
			}
			return segFR;
		}
		
	}
	private static List<SObject> setToSObjectList(List<SObject> parentObjectList) {
		List<SObject> returnList = (List<SObject>) parentObjectList;
		return returnList;
	}
	private static void parentObjectName(List<SObject> soList) {
		parentObjectName = utils.getSObjectName(soList[0]);
	}
	@isTest static void getInstance() {
		Test.startTest();
		ADCVD_FederalRegisterUtility.getInstance(iList);
		Test.stopTest();
	}
/*	@isTest static void setParentObjectIdSet() {
		Test.startTest();
		ADCVD_FederalRegisterUtility.getInstance(iList);
		Set<Id> testSet = new Set<Id>();
		Set<Id> utilitySet = new Set<Id>();
		for(Investigation__c i : iList) {
			testSet.add(i.Id);
		}
		utilitySet = ADCVD_FederalRegisterUtility.setParentObjectIdSet(iList);
		System.assertEquals(testSet, utilitySet);
		Test.stopTest();
	}
	@isTest static void setLookupFieldName() {
		Test.startTest();
		ADCVD_FederalRegisterUtility.getInstance(iList);
		parentObjectName(iList);//set object name in memory
		String testLookupFieldName = ADCVD_FederalRegisterUtility.setLookupFieldName();//lookupFieldName in utility should match parentObjectName for Investigations
		System.assertEquals(parentObjectName, testLookupFieldName);//confirm the match
		Test.stopTest();
	}
*/
	@testSetup static void dataSetup() {
		Test.startTest();
		User u = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
		petitionDate = ADCVD_TollingDayUtility.getCalculatedDate(petitionDate, petitionDate, true);
		Petition__c testPet = TestUtils.createPetition(petitionDate, 'AD ME', true);
		Investigation__c testInv = TestUtils.createInvestigation('AD', testPet, true);
		ADCVD_Order__c testOrder = TestUtils.createOrder(testInv, true);
		Segment__c testSeg = TestUtils.createSegment(testOrder, 'Administrative_Review', true);
		Integer days = 140;
		List<Federal_Register__c> frsToInsert = new List<Federal_Register__c>();
		Schema.DescribeFieldResult f = Federal_Register__c.Type__c.getDescribe();
		for(Schema.PicklistEntry frType : f.getPicklistValues()) {
			Federal_Register__c testInvFR = TestUtils.createFR(testInv.Id, 'Investigation__c', ADCVD_TollingDayUtility.getCalculatedDate(petitionDate, petitionDate.addDays(days), true), frType.getValue(), false);
			frsToInsert.add(testInvFR);
			days += 7;
			Federal_Register__c testSegFR = TestUtils.createFR(testSeg.Id, 'Segment__c', ADCVD_TollingDayUtility.getCalculatedDate(petitionDate, petitionDate.addDays(days), true), frType.getValue(), false);
			days += 7;
			frsToInsert.add(testSegFR);
		}
		insert frsToInsert;
	}
}