src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <label>ADCVD Case Number Text Value</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Preliminary_Signature__c</fullName>
        <label>Actual Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <description>Actual Final Signature</description>
        <inlineHelpText>Actual Final Signature</inlineHelpText>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Preliminary_Signature__c</fullName>
        <description>Actual Preliminary Signature</description>
        <inlineHelpText>Actual Preliminary Signature</inlineHelpText>
        <label>Actual Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>ADCVD Case Number Text Value Deprecated</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <formula>ADCVD_Case__r.Name</formula>
        <label>ADCVD Case Number Text Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <description>Actual Final Signature</description>
        <inlineHelpText>Actual Final Signature</inlineHelpText>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Preliminary_Signature__c</fullName>
        <description>Actual Preliminary Signature</description>
        <inlineHelpText>Actual Preliminary Signature</inlineHelpText>
        <label>Actual Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Announcement_Date__c</fullName>
        <label>Final Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preliminary_Announcement_Date__c</fullName>
        <label>Preliminary Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment_Outcome__c</fullName>
        <label>Segment Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Rescission</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Deficient</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Partial Rescission</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected/Deficient/Negative Finding</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVD_OrderDetailControllerTest.cls
/**
 * 
 *    Created by Eitan Alfiya
 *    on April 23 2018
 *    MIL Corporation
 * 
 **/
@isTest
public class ADCVD_OrderDetailControllerTest {
   
    @testSetup static void createData(){
        ADCVD_Case__c adcvdCase = TestUtils.createADCVDCase('A-111-222', 'AD ME', true); //Matching case name to adcvd order case name
        Petition__c petition = TestUtils.createPetition(adcvdCase, Date.today(), true);
        Investigation__c investigation = TestUtils.createInvestigation(petition, true);
        ADCVD_Order__c adcvdOrder = TestUtils.createOrder(investigation, false); 
        adcvdOrder.ADCVD_Case__c = adcvdCase.Id;
        insert adcvdOrder;
        //Attachment to the order
        Attachment anAttachment = TestUtils.createAttachment(adcvdOrder.Id, false);
        anAttachment.Name = 'Scope.txt';
        insert anAttachment;
        //Create two segments, one to be preliminary and one to be final
        Segment__c prelimSegment = TestUtils.createSegment(adcvdOrder, 'Administrative_Review', false);
        prelimSegment.Actual_Preliminary_Signature__c = Date.today().addDays(-7);
        prelimSegment.Calculated_Preliminary_Signature__c = Date.today().addDays(2);
        Segment__c finalSegment = TestUtils.createSegment(adcvdOrder, 'Administrative_Review', false);
        finalSegment.Actual_Final_Signature__c = Date.Today().addDays(1);
        finalSegment.Calculated_Final_Signature__c = Date.Today().addDays(1);
        finalSegment.Segment_Outcome__c = 'Withdrawn';
        insert new List<Segment__c>{prelimSegment, finalSegment};
            
            } 
    
    private static Segment__c finalAdminRevSegment{
        get{
            if(finalAdminRevSegment == null){
                Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Administrative_Review');
                finalAdminRevSegment = [SELECT Id, ADCVD_Order__c, Next_Announcement_Date__c ,Final_Announcement_Date__c,
                                         Preliminary_Announcement_Date__c, Actual_Final_Signature__c, Actual_Preliminary_Signature__c,
                                         Calculated_Final_Signature__c, Segment_Outcome__c FROM Segment__c WHERE RecordTypeId =: recordTypeId 
                                         AND Actual_Preliminary_Signature__c =: Date.today().addDays(-7) LIMIT 1];
            }
            return finalAdminRevSegment;
        }
        set;
    }
    
    private static Segment__c prelimAdminRevSegment{
        get{
            if(prelimAdminRevSegment == null){
                Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Administrative_Review');
                prelimAdminRevSegment = [SELECT Id, ADCVD_Order__c, Next_Announcement_Date__c ,Final_Announcement_Date__c,
                                         Preliminary_Announcement_Date__c, Actual_Final_Signature__c, Actual_Preliminary_Signature__c,
                                         Calculated_Final_Signature__c, Segment_Outcome__c FROM Segment__c WHERE RecordTypeId =: recordTypeId 
                                         AND Segment_Outcome__c = 'Withdrawn' LIMIT 1];
            }
            return prelimAdminRevSegment;
        }
        set;
        
    }
    
    static testMethod void testPreliminarySegment(){
        PageReference pageRef = Page.adcvd;
        Test.setCurrentPage(pageRef);
        ADCVD_Case__c adcvdCase = [Select Id, ADCVD_Case_Number__c From ADCVD_Case__c];
        pageRef.getParameters().put('adcvdcase', adcvdCase.ADCVD_Case_Number__c);
        ADCVD_OrderDetailController adcvdPageController = new ADCVD_OrderDetailController();
        System.assert(adcvdPageController.Segments.size() == 2);
        prelimAdminRevSegment = null;
        finalAdminRevSegment = null;
        System.debug(prelimAdminRevSegment);
        System.debug(finalAdminRevSegment);
        System.assertEquals(prelimAdminRevSegment.Next_Announcement_Date__c, prelimAdminRevSegment.Preliminary_Announcement_Date__c);
        System.assertEquals(finalAdminRevSegment.Next_Announcement_Date__c, finalAdminRevSegment.Final_Announcement_Date__c);
        
    }
    
}