src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country Text</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Custom_Instruction__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type_Text__c</fullName>
        <label>ADCVD Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Custom Instructions</relationshipLabel>
        <relationshipName>Custom_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Custom Instructions</relationshipLabel>
        <relationshipName>Custom_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AD_CVD_Module_Number__c</fullName>
        <label>AD/CVD Module Number</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicable_Rate__c</fullName>
        <label>Applicable Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Basis_for_Rate__c</fullName>
        <label>Basis for Rate</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HM</fullName>
                </value>
                <value>
                    <fullName>COP</fullName>
                </value>
                <value>
                    <fullName>CV</fullName>
                </value>
                <value>
                    <fullName>NME</fullName>
                </value>
                <value>
                    <fullName>FA</fullName>
                </value>
                <value>
                    <fullName>TM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CBP_Case_Number_Text__c</fullName>
        <label>CBP Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CBP_Instructions_Category__c</fullName>
        <label>CBP Instructions Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADL</fullName>
                </value>
                <value>
                    <fullName>ADM</fullName>
                </value>
                <value>
                    <fullName>ARF-Admin Review Final</fullName>
                </value>
                <value>
                    <fullName>ARP-Admin Review Prelim</fullName>
                </value>
                <value>
                    <fullName>CIE</fullName>
                </value>
                <value>
                    <fullName>COR</fullName>
                </value>
                <value>
                    <fullName>FIN-Final Determination</fullName>
                </value>
                <value>
                    <fullName>FNO-Final Det w/Order</fullName>
                </value>
                <value>
                    <fullName>INF-Information Notice</fullName>
                </value>
                <value>
                    <fullName>INI-Initiation of Review</fullName>
                </value>
                <value>
                    <fullName>INJ-Injunction</fullName>
                </value>
                <value>
                    <fullName>INQ-Inquiry</fullName>
                </value>
                <value>
                    <fullName>LIQ-Liquidation</fullName>
                </value>
                <value>
                    <fullName>NSR-New Shipper Review</fullName>
                </value>
                <value>
                    <fullName>ORD-Order</fullName>
                </value>
                <value>
                    <fullName>OTH-Other</fullName>
                </value>
                <value>
                    <fullName>PRE-Preliminary</fullName>
                </value>
                <value>
                    <fullName>REV-Revocation</fullName>
                </value>
                <value>
                    <fullName>SCO-Scope</fullName>
                </value>
                <value>
                    <fullName>TER-Termination Notice</fullName>
                </value>
                <value>
                    <fullName>WRIT-Writ of Mandamus</fullName>
                </value>
                <value>
                    <fullName>coming</fullName>
                    <isActive>false</isActive>
                    <label>coming</label>
                </value>
                <value>
                    <fullName>later</fullName>
                    <isActive>false</isActive>
                    <label>later</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CBP_Instructions_Sub_Category__c</fullName>
        <label>CBP Instructions Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADRV-Administrative Review</fullName>
                </value>
                <value>
                    <fullName>AFF-Affirmative</fullName>
                </value>
                <value>
                    <fullName>ALI-Auto Liquidation</fullName>
                </value>
                <value>
                    <fullName>ALIWE-Auto Liq Exception</fullName>
                </value>
                <value>
                    <fullName>AMD-Amend</fullName>
                </value>
                <value>
                    <fullName>COR-Correction</fullName>
                </value>
                <value>
                    <fullName>CTDIS-Court ORD Dissolved</fullName>
                </value>
                <value>
                    <fullName>FRM-Firm</fullName>
                </value>
                <value>
                    <fullName>GAP-Gap Period</fullName>
                </value>
                <value>
                    <fullName>INSCO-In Scope</fullName>
                </value>
                <value>
                    <fullName>NAFTA-NA Free Trd Agmt</fullName>
                </value>
                <value>
                    <fullName>NEG-Negative</fullName>
                </value>
                <value>
                    <fullName>ORD-Order</fullName>
                </value>
                <value>
                    <fullName>OUTSCO-Out of Scope</fullName>
                </value>
                <value>
                    <fullName>PARRES-Partial Rescission</fullName>
                </value>
                <value>
                    <fullName>PRELIM-Preliminary</fullName>
                </value>
                <value>
                    <fullName>REF-Refund</fullName>
                </value>
                <value>
                    <fullName>RES-Rescission</fullName>
                </value>
                <value>
                    <fullName>REV-Revocation</fullName>
                </value>
                <value>
                    <fullName>TMI-Mat Injury Threat</fullName>
                </value>
                <value>
                    <fullName>TRO-Temp Rest Order</fullName>
                </value>
                <value>
                    <fullName>coming</fullName>
                    <isActive>false</isActive>
                    <label>coming</label>
                </value>
                <value>
                    <fullName>later</fullName>
                    <isActive>false</isActive>
                    <label>later</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commodity_Text__c</fullName>
        <label>Commodity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Countervailed_Programs__c</fullName>
        <label>Countervailed Programs</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Custom Instruction</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Custom Instruction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Countervailed_Programs__c</fullName>
        <description>hide if customs_instructions_yes_no is not TRUE; if customs_instructions_yes_no is TRUE, validation (must be completed before closing case); disable if Case Type (field &quot;type&quot;) = AD ME or AD NME; repeating (one Countervailed Programs per selection made from Applicable CPB Instructions)</description>
        <label>Countervailed Programs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type_Text__c</fullName>
        <label>ADCVD Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBP_Case_Number_Text__c</fullName>
        <label>CBP Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commodity_Text__c</fullName>
        <label>Commodity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Countervailed_Programs__c</fullName>
        <description>Countervailed Programs</description>
        <inlineHelpText>Countervailed Programs</inlineHelpText>
        <label>Countervailed Programs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type_Text__c</fullName>
        <label>ADCVD Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBP_Case_Number_Text__c</fullName>
        <label>CBP Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commodity_Text__c</fullName>
        <label>Commodity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomInstructionSelector.cls
public class CustomInstructionSelector
    extends fflibext_SObjectSelector
    implements ICustomInstructionSelector
{
    public static ICustomInstructionSelector newInstance()
    {
        return (ICustomInstructionSelector) fflibext_Application.Selector.newInstance(Custom_Instruction__c.SObjectType);
    }
    @TestVisible
    private Schema.sObjectType getSObjectType()
    {
        return Custom_Instruction__c.SObjectType;
    }
    private List<Schema.SObjectField> getAdditionalSObjectFieldList()
    {
        return new List<Schema.SObjectField>
        {
            Custom_Instruction__c.ADCVD_Case_Number_Text__c,
            Custom_Instruction__c.ADCVD_Case_Type_Text__c,
            Custom_Instruction__c.ADCVD_Case__c,
            Custom_Instruction__c.ADCVD_Order__c,
            Custom_Instruction__c.AD_CVD_Module_Number__c,
            Custom_Instruction__c.Applicable_Rate__c,
            Custom_Instruction__c.Basis_for_Rate__c,
            Custom_Instruction__c.CBP_Case_Number_Text__c,
            Custom_Instruction__c.CBP_Instructions_Category__c,
            Custom_Instruction__c.CBP_Instructions_Sub_Category__c,
            Custom_Instruction__c.Commodity_Text__c,
            Custom_Instruction__c.Countervailed_Programs__c,
            Custom_Instruction__c.Country_Text__c,
            Custom_Instruction__c.Country_in_which_factors_were_valued__c,
            Custom_Instruction__c.Date_Message_Loaded_in_ACE__c,
            Custom_Instruction__c.IMN_NO__c,
            Custom_Instruction__c.Investigation__c,
            Custom_Instruction__c.Locked__c,
            Custom_Instruction__c.Message_Date__c,
            Custom_Instruction__c.Message_No__c,
            Custom_Instruction__c.Petition__c,
            Custom_Instruction__c.Product_Short_Name_Text__c,
            Custom_Instruction__c.Product_Text__c,
            Custom_Instruction__c.Segment__c,
            Custom_Instruction__c.Suspension_Agreement__c
        };
    }
    public List<Custom_Instruction__c> selectById(Set<Id> idSet)
    {
        return (List<Custom_Instruction__c>) selectSObjectsById(idSet);
    }
    public List<Custom_Instruction__c> selectAllToLimit()
    {
        return
            (List<Custom_Instruction__c>)
            Database.query(
                newQueryFactory()
                .setLimit(Limits.getLimitQueryRows())
                .toSOQL());
    }
}