src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Case_Concat_Text_Values__c</fullName>
        <label>Case Concat Text Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country Text</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Lotus_Notes_History_Data__c</fullName>
        <label>Lotus Notes History Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Roman_Numerals</valueSetName>
        </valueSet>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type_Text__c</fullName>
        <label>ADCVD Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Additional Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CBP_Case_Number_Text__c</fullName>
        <label>CBP Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Concat_Text_Values__c</fullName>
        <label>Case Concat Text Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Commodity_Text__c</fullName>
        <label>Commodity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date_of_Termination__c</fullName>
        <label>Effective Date of Termination</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enforcement_Concerns__c</fullName>
        <label>Enforcement Concerns</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lotus_Notes_History_Data__c</fullName>
        <label>Lotus Notes History Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Sunset_Initiation_Date_UI__c</fullName>
        <formula>TEXT(YEAR(Next_Sunset_Initiation_Date__c)) &amp; &apos;/&apos; &amp;
 CASE(MONTH(Next_Sunset_Initiation_Date__c),
1, &apos;January&apos;, 
2, &apos;February&apos;,
3, &apos;March&apos;,
4, &apos;April&apos;,
5, &apos;May&apos;,
6, &apos;June&apos;,
7, &apos;July&apos;,
8, &apos;August&apos;,
9, &apos;September&apos;,
10, &apos;October&apos;,
11, &apos;November&apos;,
12, &apos;December&apos;,
&apos;Date Not Set&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Sunset Initiation Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Sunset_Initiation_Date__c</fullName>
        <label>Next Sunset Initiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SA</fullName>
                    <default>true</default>
                    <label>SA</label>
                </value>
                <value>
                    <fullName>Suspension Office</fullName>
                    <isActive>false</isActive>
                    <label>Suspension Office</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Short_Name_Text_Value__c</fullName>
        <label>Product Short Name Text Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Short_Name_Text__c</fullName>
        <label>Product Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Text_Value__c</fullName>
        <label>Product Text Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Text__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suspension_Date__c</fullName>
        <label>Suspension Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date - Deprecated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>This_Investigation_has_a_Susp_Agreement__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>This Investigation has a Susp. Agreement</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/globalValueSets/Roman_Numerals.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>V</fullName>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
    </customValue>
    <customValue>
        <fullName>VII</fullName>
    </customValue>
    <masterLabel>Roman Numerals</masterLabel>
</GlobalValueSet>

src/classes/SuspensionAgreementSelector.cls
public class SuspensionAgreementSelector
	extends fflibext_SObjectSelector
	implements ISuspensionAgreementSelector
{
    public static ISuspensionAgreementSelector newInstance()
    {
        return (ISuspensionAgreementSelector) fflibext_Application.Selector.newInstance(Suspension_Agreement__c.SObjectType);
    }
    @TestVisible
    private Schema.sObjectType getSObjectType()
    {
        return Suspension_Agreement__c.SObjectType;
    }
    private List<Schema.SObjectField> getAdditionalSObjectFieldList()
    {
        return new List<Schema.SObjectField>
        {
            Suspension_Agreement__c.ADCVD_Case__c,
            Suspension_Agreement__c.ADCVD_Case_Number_Text__c,
            Suspension_Agreement__c.ADCVD_Case_Type_Text__c,
            Suspension_Agreement__c.Additional_Notes__c,
            Suspension_Agreement__c.Anniversary_Month__c,
            Suspension_Agreement__c.Case_Concat_Text_Values__c,
            Suspension_Agreement__c.CBP_Case_Number_Text__c,
            Suspension_Agreement__c.Commodity_Text__c,
            Suspension_Agreement__c.Country_Text__c,
            Suspension_Agreement__c.CreatedById,
            Suspension_Agreement__c.CreatedDate,
            Suspension_Agreement__c.Effective_Date_of_Termination__c,
            Suspension_Agreement__c.Enforcement_Concerns__c,
            Suspension_Agreement__c.Investigation__c,
            Suspension_Agreement__c.LastModifiedById,
            Suspension_Agreement__c.LastModifiedDate,
            Suspension_Agreement__c.Locked__c,
            Suspension_Agreement__c.Lotus_Notes_History_Data__c,
            Suspension_Agreement__c.Name,
            Suspension_Agreement__c.Next_Sunset_Initiation_Date_UI__c,
            Suspension_Agreement__c.Next_Sunset_Initiation_Date__c,
            Suspension_Agreement__c.Office__c,
            Suspension_Agreement__c.Product_Text__c,
            Suspension_Agreement__c.Product_Short_Name_Text__c,
            Suspension_Agreement__c.Product_Short_Name_Text_Value__c,
            Suspension_Agreement__c.Product_Text_Value__c,
            Suspension_Agreement__c.Suspension_Date__c,
            Suspension_Agreement__c.Termination_Date__c,
            Suspension_Agreement__c.This_Investigation_has_a_Susp_Agreement__c
        };
    }
    public List<Suspension_Agreement__c> selectById(Set<Id> idSet)
    {
        return (List<Suspension_Agreement__c>) selectSObjectsById(idSet);
    }
    public List<Suspension_Agreement__c> selectAllToLimit()
    {
        return
            (List<Suspension_Agreement__c>)
            Database.query(
                newQueryFactory()
                .setLimit(Limits.getLimitQueryRows())
                .toSOQL());
    }
}