src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <label>ADCVD Case Number Text Value</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Concat_Text_Values__c</fullName>
        <label>Case Concat Text Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>Commodity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cement and Ceramics</fullName>
                </value>
                <value>
                    <fullName>Chemicals and Allied Industries</fullName>
                </value>
                <value>
                    <fullName>Foodstuffs</fullName>
                </value>
                <value>
                    <fullName>Machinery and Automotive</fullName>
                </value>
                <value>
                    <fullName>Minerals</fullName>
                </value>
                <value>
                    <fullName>Other Metals and Articles of Metal</fullName>
                </value>
                <value>
                    <fullName>Other Mfg.</fullName>
                </value>
                <value>
                    <fullName>Paper and Paperboard</fullName>
                </value>
                <value>
                    <fullName>Plastics and Rubber</fullName>
                </value>
                <value>
                    <fullName>Steel-Related</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Short_Name__c</fullName>
        <label>Product Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Configuration data for applications that utilize triggers in the org. There should be a &quot;default&quot; config and a &quot;testConfig&quot; AppConfig list in an org. EnableTriggers to be checked for both.</description>
    <label>AppConfig</label>
</CustomObject>

src/objects/Master_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Master Automation</label>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/classes/ADCVDCaseTriggerHandlerTest.cls
@isTest
public with sharing class ADCVDCaseTriggerHandlerTest {

    private static Map<Id, ADCVD_Case__c> casesMap{
        get{
            if(casesMap == null){
                casesMap = new Map<Id, ADCVD_Case__c>([SELECT Id, ADCVD_Case_Type__c, Commodity__c, Country__c, Product_Short_Name__c, Product__c, LastModifiedDate FROM ADCVD_Case__c]);
            }
            return casesMap;
        }
        set;
    }

    private static ADCVD_Case__c adCase{
        get{
            if(adCase == null){
                adCase = [SELECT Id, Name, ADCVD_Case_Number__c, Case_Concat_Text_Values__c FROM ADCVD_Case__c WHERE ADCVD_Case_Type__c = 'AD ME'];
            }
            return adCase;
        }
        set;
    }

    private static ADCVD_Case__c cvdCase{
        get{
            if(cvdCase == null){
                cvdCase = [SELECT Id, Name, ADCVD_Case_Number__c, Case_Concat_Text_Values__c FROM ADCVD_Case__c WHERE ADCVD_Case_Type__c = 'CVD'];
            }
            return cvdCase;
        }
        set;
    }

    @isTest static void testStandardizedFieldChange(){
        //This test method tests the functionality of the checkStandardizedFieldChanges() method in the ADCVDCaseTriggerHandler
        casesMap = null;
        List<ADCVD_Case__c> newList = new List<ADCVD_Case__c>();
        for(ADCVD_Case__c adcvdCase: casesMap.values()){
            //Clone with preserving id equals to true
            ADCVD_Case__c newCase = adcvdCase.clone(true);
            newCase.Country__c = 'United States';
            newCase.Product__c = 'New Name';
            newList.add(newCase);
        }
        List<ADCVD_Case__c> changedCasesList = ADCVDCaseTriggerHandler.getChangedCases(newList, casesMap);
        System.assertEquals(newList.size(), changedCasesList.size());
    }

    @isTest static void testFieldUpdateOnInsert(){
        adCase = null;
        cvdCase = null;
        //Concatenated case fields have the following format: "Commodity__c; Country__c; ADCVD_Case_Type_Text__c"
        String adCaseConcatenatedField = 'Foodstuffs; Argentina; AD ME';
        String cvdCaseConcatenatedField = 'Foodstuffs; Argentina; CVD';
        //Assert that custom text field have been populated correctly
        //ADCVD Case Number is used in the parent value service class to populate child records with the case number.
        System.assertEquals(adCase.ADCVD_Case_Number__c, adCase.Name);
        System.assertEquals(adCase.Case_Concat_Text_Values__c, adCaseConcatenatedField);
        System.assertEquals(cvdCase.ADCVD_Case_Number__c, cvdCase.Name);
        System.assertEquals(cvdCase.Case_Concat_Text_Values__c, cvdCaseConcatenatedField);
    }

    @isTest static void testFieldUpdateOnUpdate(){
        Test.startTest();
        adCase = null;
        cvdCase = null;

        adCase.Country__c = 'China';
        cvdCase.Commodity__c = 'Minerals';
        List<ADCVD_Case__c> casesToUpdate = new List<ADCVD_Case__c>{adCase, cvdCase};
        System.debug(casesToUpdate);
        update casesToUpdate;
        Test.stopTest();
        adCase = null;
        cvdCase = null;

        //Concatenated case fields have the following format: "Commodity__c; Country__c; ADCVD_Case_Type_Text__c"
        String adCaseConcatenatedField = 'Foodstuffs; China; AD ME';
        String cvdCaseConcatenatedField = 'Minerals; Argentina; CVD';

        System.assertEquals(adCaseConcatenatedField, adCase.Case_Concat_Text_Values__c);
        System.assertEquals(cvdCaseConcatenatedField, cvdCase.Case_Concat_Text_Values__c);


    }

    @isTest static void testBatchJobInPipeline(){
        //This test method tests the functionality of the getRecentlyModifiedCases() method in ADCVDCaseTriggerHandler
        //Pass one case to the getRecentlyModifiedCases, and confirm it will return two cases. Since two cases were created in this test class (past 24 hrs)
        adCase = null;
        List<ADCVD_Case__c> casesList = new List<ADCVD_Case__c>{adCase};
        casesList = ADCVDCaseTriggerHandler.getRecentlyModifiedCases(casesList);
        System.assert(casesList.size() == 2);

    }

    @testSetup static void dataSetup(){
        Master_Automation__c ma = TestUtils.createMasterAutomation(true, true, true);
        AppConfig__c ac = TestUtils.createAppConfig('ADCVDStandardCaseFieldBatch', true, true);
        //create test data
        ADCVD_Case__c testADCase = TestUtils.createADCVDCase('A-534-124', 'AD ME', false);
        ADCVD_Case__c testCVDCase = TestUtils.createADCVDCase('C-352-523', 'CVD', false);
        List<ADCVD_Case__c> casesToInsert = new List<ADCVD_Case__c>{testADCase, testCVDCase};
        insert casesToInsert;
    }
}