src/objects/ADCVD_Objects__mdt.object
<CustomObject>
    <description>This holds the object types, record types, and a type field (if present) delineating a difference in records for the ADCVD app</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Petition__c</fullName>
                    <default>true</default>
                    <label>Petition__c</label>
                </value>
                <value>
                    <fullName>Investigation__c</fullName>
                </value>
                <value>
                    <fullName>ADCVD_Order__c</fullName>
                </value>
                <value>
                    <fullName>Segment__c</fullName>
                </value>
                <value>
                    <fullName>Litigation__c</fullName>
                </value>
                <value>
                    <fullName>Related_Organization__c</fullName>
                </value>
                <value>
                    <fullName>Federal_Register__c</fullName>
                </value>
                <value>
                    <fullName>Recusal__c</fullName>
                </value>
                <value>
                    <fullName>Staffing_Assignment__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
                <value>
                    <fullName>Administrative_Review</fullName>
                </value>
                <value>
                    <fullName>Anti_Circumvention_Review</fullName>
                </value>
                <value>
                    <fullName>Changed_Circumstances_Review</fullName>
                </value>
                <value>
                    <fullName>Expedited_Review</fullName>
                </value>
                <value>
                    <fullName>New_Shipper_Review</fullName>
                </value>
                <value>
                    <fullName>Scope_Inquiry</fullName>
                </value>
                <value>
                    <fullName>Sunset_Review</fullName>
                </value>
                <value>
                    <fullName>International_Litigation</fullName>
                </value>
                <value>
                    <fullName>Remand</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Related</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Initiation/Prelim</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Petitioner</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Respondent</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Objects</label>
    <pluralLabel>ADCVD Objects</pluralLabel>
</CustomObject>

src/objects/Constant__mdt.object
<CustomObject>
    <description>This holds constant values used in classes</description>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Constants</relationshipLabel>
        <relationshipName>Constants</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used_with_Field_Named__c</fullName>
        <label>Used with Field Named</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constant</label>
    <pluralLabel>Constants</pluralLabel>
</CustomObject>

src/objects/Date_Calculation__mdt.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Date Calculations</relationshipLabel>
        <relationshipName>Date_Calculations</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Calculated_Date_Field_Name__c</fullName>
        <label>Calculated Date Field Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Constant_1__c</fullName>
        <label>Constant 1</label>
        <referenceTo>Constant__mdt</referenceTo>
        <relationshipLabel>Date Calculations</relationshipLabel>
        <relationshipName>Date_Calculations</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Constant_2__c</fullName>
        <label>Constant 2</label>
        <referenceTo>Constant__mdt</referenceTo>
        <relationshipLabel>Date Calculations (Constant 2)</relationshipLabel>
        <relationshipName>Date_Calculations1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Constant_3__c</fullName>
        <label>Constant 3</label>
        <referenceTo>Constant__mdt</referenceTo>
        <relationshipLabel>Date Calculations (Constant 3)</relationshipLabel>
        <relationshipName>Date_Calculations2</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Constant_4__c</fullName>
        <label>Constant 4</label>
        <referenceTo>Constant__mdt</referenceTo>
        <relationshipLabel>Date Calculations (Constant 4)</relationshipLabel>
        <relationshipName>Date_Calculations3</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Order_of_Execution__c</fullName>
        <label>Order of Execution</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Date Calculation</label>
    <pluralLabel>Date Calculations</pluralLabel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Status__c</fullName>
        <label>Legal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ops_Status__c</fullName>
        <label>Ops Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Status__c</fullName>
        <label>Policy Status</label>
        <picklist>
            <picklistValues>
                <fullName>Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amended Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amended Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>Issue-{00000000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVDSelector.cls
public without sharing class ADCVDSelector {

	public static List<Petition__c> allPetitions {
		get {
			if (allPetitions == null) {
				String query = soqlBuilderAllFields('Petition__c', true);
				allPetitions = database.query(query);
			}
			return allPetitions;
		} set;
	}
	public static List<Investigation__c> allInvestigations {
		get {
			if (allInvestigations == null) {
				String query = soqlBuilderAllFields('Investigation__c', true);
				allInvestigations = database.query(query);
			}
			return allInvestigations;
		} set;
	}
	public static List<Segment__c> allSegments {
		get {
			if (allSegments == null) {
				String query = soqlBuilderAllFields('Segment__c', true);
				allSegments = database.query(query);
			}
			return allSegments;
		} set;
	}
	public static List<ADCVD_Objects__mdt> allAdcvdObjects {
		get {
			if (allAdcvdObjects == null) {
				String query = soqlBuilderAllFields('ADCVD_Objects__mdt', true);
				allAdcvdObjects = database.query(query);
			}
			return allAdcvdObjects;
		} set;
	}
	public static List<Constant__mdt> allConstants {
		get {
			if (allConstants == null) {
				String query = soqlBuilderAllFields('Constant__mdt', false);
				query += ', ADCVD_Objects__r.Object_API_Name__c, ADCVD_Objects__r.Record_Type_Name__c FROM Constant__mdt';
				allConstants = database.query(query);
			}
			return allConstants;
		} set;
	}
	public static List<Date_Calculation__mdt> allDateCalculations {
		get {
			if (allDateCalculations == null) {
				String query = soqlBuilderAllFields('Date_Calculation__mdt', false);
				query += ', ADCVD_Objects__r.Object_API_Name__c, ADCVD_Objects__r.Record_Type_Name__c, ' +
						'Constant_1__r.Number_Value__c, Constant_1__r.String_Value__c, ' +
						'Constant_1__r.Used_with_Field_Named__c, Constant_2__r.Number_Value__c, Constant_2__r.String_Value__c, ' +
						'Constant_2__r.Used_with_Field_Named__c, Constant_3__r.Number_Value__c, Constant_3__r.String_Value__c, ' +
						'Constant_3__r.Used_with_Field_Named__c, Constant_4__r.Number_Value__c, Constant_4__r.String_Value__c, ' +
						'Constant_4__r.Used_with_Field_Named__c FROM Date_Calculation__mdt';
				allDateCalculations = database.query(query);
			}
			return allDateCalculations;
		} set;
	}
	public static List<Issue__c> allIssues {
		get {
			if (allIssues == null) {
				String query = soqlBuilderAllFields('Issue__c', true);
				allIssues = database.query(query);
			}
			return allIssues;
		} set;
	}

	public static Map<ID,ADCVD_FederalRegisterUtility> getFrUtilMap(List<SObject> soList) {
		ADCVD_FederalRegisterUtility listInstance = ADCVD_FederalRegisterUtility.getInstance(soList);
		Map<ID,ADCVD_FederalRegisterUtility> frUtilMap = listInstance.utilMap;
		return frUtilMap;
	}

	public static Map<String,Date> getFrDateMap(List<SObject> soList) {
		ADCVD_FederalRegisterUtility listInstance = ADCVD_FederalRegisterUtility.getInstance(soList);
		Map<String,Date> frDateMap = listInstance.varMap;
		return frDateMap;
	}

	public static Map<Id,Petition__c> getPetitionsInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Petition__c> returnMap = new Map<Id,Petition__c>();
		System.debug('*** getPetitionsInScope soList: ' + soList);
		Set<Id> tempIdSet = new Set<Id>();
		List<SObject> castRecords = castRecordsToType(soList, soType);
		for (SObject so : castRecords) {
			tempIdSet.add((Id)so.get(lookupFieldName));
		}
		for (Petition__c p : allPetitions) {
			if (tempIdSet.contains(p.Id)) {
				returnMap.put(p.Id, p);
			}
		}
		return returnMap;
	}

	public static Map<Id,Investigation__c> getInvestigationsInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Investigation__c> returnMap = new Map<Id,Investigation__c>();
		Set<Id> tempIdSet = new Set<Id>();
		List<SObject> castRecords = castRecordsToType(soList, soType);
		for (SObject so : castRecords) {
			tempIdSet.add((Id)so.get(lookupFieldName));
		}
		for (Investigation__c i : allInvestigations) {
			if (tempIdSet.contains(i.Id)) {
				returnMap.put(i.Id, i);
			}
		}
		return returnMap;
	}

	public static Map<Id,Issue__c> getIssuesInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Issue__c> returnMap = new Map<Id,Issue__c>();
		Set<Id> tempIdSet = new Set<Id>();
		List<SObject> castRecords = castRecordsToType(soList, soType);
		for (SObject so : castRecords) {
			tempIdSet.add((Id)so.get('Id'));
		}
		for (Issue__c i : allIssues) {
			if (tempIdSet.contains((Id)i.get(lookupFieldName))) {
				returnMap.put(i.Id, i);
			}
		}
		return returnMap;
	}

	public static Map<Id,Issue__c> getCompletedIssuesInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Issue__c> returnMap = getIssuesInScope(soList, soType, lookupFieldName);
		Map<Id,Map<String,Boolean>> parentIdToCompletedIssues = getCompletedIssues(soList, lookupFieldName);
		for(Id i : returnMap.keySet()) {
			if (!parentIdToCompletedIssues.containsKey(i) || !parentIdToCompletedIssues.get(i).get(returnMap.get(i).Type__c)) {
				returnMap.remove(i);
			}
		}
		return returnMap;
	}

	public static Map<Id,Map<String,Boolean>> getCompletedIssues(List<SObject> soList, String lookupFieldName) {
		Map<Id,Map<String,Boolean>> parentIdToCompletedIssues = new Map<Id,Map<String,Boolean>>();
		Set<Id> tempIdSet = new Set<Id>();
		for (SObject so : soList) {
			if (so.get('Id') != null) {
				tempIdSet.add((Id)so.get('Id'));
			}
		}
		for (Issue__c i : allIssues) {
			Map<String,Boolean> tempMap = new Map<String,Boolean>();
			if (tempIdSet.contains((Id)i.get(lookupFieldName))) {
				if (tempMap.get(i.Type__c) == null || tempMap.get(i.Type__c) == true) {
					Boolean tempBoolean = i.Ops_Status__c == 'Completed' ? true : false;
					tempBoolean = (tempBoolean == true && i.Policy_Status__c == 'Completed') ? true : false;
					tempBoolean = (tempBoolean == true && i.Legal_Status__c == 'Completed') ? true : false;
					tempMap.put(i.Type__c, tempBoolean);
					parentIdToCompletedIssues.put((Id)i.get(lookupFieldName), tempMap);
				}
			}
		}
		return parentIdToCompletedIssues;
	}

	public static Map<String,Constant__mdt> getConstantNameToConstantMap(String offsetFieldName) {
		Map<String,Constant__mdt> returnMap = new Map<String,Constant__mdt>();
		for (Constant__mdt c : allConstants) {
			if ((Boolean)c.get(offsetFieldName)) {
				returnMap.put(c.QualifiedApiName, c);
			}
		}
		return returnMap;
	}

	public static Constant__mdt getConstant(String idOrQualifiedApiName) {
		Constant__mdt returnConstant = null;
		if (idOrQualifiedApiName instanceOf Id) {
			Id i = (Id) idOrQualifiedApiName;
			for (Constant__mdt c : allConstants) {
				if (c.Id == i) {
					returnConstant = c;
					break;
				}
			}
		} else {
			for (Constant__mdt c : allConstants) {
				if (c.QualifiedApiName == idOrQualifiedApiName) {
					returnConstant = c;
					break;
				}
			}
		}
		return returnConstant;
	}

	public static Map<String,Date_Calculation__mdt> getDateCalculationsMap(String soType, String recordType) {
		Map<Integer, Date_Calculation__mdt> tempMap = new Map<Integer, Date_Calculation__mdt>();
		Map<String,Date_Calculation__mdt> returnMap = new Map<String,Date_Calculation__mdt>();
		for (Date_Calculation__mdt dc : allDateCalculations) {
			if (dc.ADCVD_Objects__r.Object_API_Name__c == soType && 
				(String.isBlank(recordType) || dc.ADCVD_Objects__r.Record_Type_Name__c == recordType)) {
				tempMap.put((Integer)dc.Order_of_Execution__c, dc);
			}
		}
		for (Integer i = 0; i < 100; i++) {
			if (tempMap.get(i) != null) {
				returnMap.put(tempMap.get(i).Calculated_Date_Field_Name__c, tempMap.get(i));
			}
		}
		return returnMap;
	}

	public static List<SObject> castRecordsToType(List<SObject> records, String soType) {
	    String listType = 'List<' + soType + '>';
	    List<SObject> returnList = (List<SObject>)Type.forName(listType).newInstance();
	    returnList.addAll(records);
	    return returnList;
	}

	public static String soqlBuilderAllFields(String soType, Boolean finishSOQL) {
        Map<String, Schema.SObjectType> schemaMap = utils.cachedGD;
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get(soType).getDescribe().fields.getMap();
        Set<String> searchFields = new Set<String>();
        String commaSeparatedFields = '';
        for (String fieldName : fieldMap.keyset()){
            searchFields.add(fieldName.toLowerCase());
        }
        for (String s: searchFields) {
            if (commaSeparatedFields != '') {
                commaSeparatedFields = commaSeparatedFields + ', ' + s;
            } else {
                commaSeparatedFields = s;
            }
        }
        String query = 'SELECT ' + commaSeparatedFields;
        if (finishSOQL) {
        	query += ' FROM ' + soType;
        }
        return query;
    }
}