src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Configuration data for applications that utilize triggers in the org. There should be a &quot;default&quot; config and a &quot;testConfig&quot; AppConfig list in an org. EnableTriggers to be checked for both.</description>
    <label>AppConfig</label>
</CustomObject>

src/objects/Master_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Master Automation</label>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Petitioner</fullName>
                </value>
                <value>
                    <fullName>Respondent</fullName>
                </value>
                <value>
                    <fullName>Customs Instructions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelatedOrganizationSelectorTest.cls
/*
 * Create by Eitan Alfiya
 * on 5/9/2018
 * Mil Corporation
 */
@isTest
public class RelatedOrganizationSelectorTest {

    private static Related_Organization__c relatedOrg{
        get{
            if(relatedOrg == null){
                relatedOrg = [Select Id, Name, Type__c From Related_Organization__c Limit 1];
            }
            return relatedOrg;
        }
        set;
    }
    
    @testSetup static void dataSetup(){
        Master_Automation__c ma = TestUtils.createMasterAutomation(true, true, true);
        AppConfig__c ac = TestUtils.createAppConfig('default', true, true);
        //Create parent for Related Organization
        ADCVD_Case__c adcvdCase = TestUtils.createADCVDCase('A-111-222', 'AD ME', true);
        Petition__c petition = TestUtils.createPetition(adcvdCase, Date.today(), true);
        //Get picklist values for type__c field, using schema class in case picklist values changes
        List<Schema.PicklistEntry> typeFieldPicklistValues = Related_Organization__c.Type__c.getDescribe().getPicklistValues(); 
        Related_Organization__c relatedOrg = TestUtils.createRelatedOrg(petition, false);
        relatedOrg.Type__c = typeFieldPicklistValues[0].getValue();
        insert relatedOrg;
    }
    
    @isTest static void testRelatedOrganizations(){
        List<Related_Organization__c> relatedOrgsList = RelatedOrganizationSelector.allRelatedOrganizations;
        System.assertEquals(relatedOrg.Id, relatedOrgsList[0].Id);
        System.assertEquals(relatedOrg.Name, relatedOrgsList[0].Name);
        for(Related_Organization__c org:relatedOrgsList){
            System.debug(org.Id +' --- '+org.Name+' --- '+org.Petition__c);

        }
    }
    
    @isTest static void testRelatedOrganizationsInContext(){
        Set<String> fields = new Set<String>{'Name', 'Type__c'};
        List<Related_Organization__c> relatedOrgsInContext = RelatedOrganizationSelector.getRelatedOrganizationsInContext(new Set<Id>{relatedOrg.Id}, fields, true);
        System.assertEquals(relatedOrg.Name, relatedOrgsInContext[0].Name);
        System.assertEquals(relatedOrg.Type__c, relatedOrgsInContext[0].Type__c);
    }
    
    
}