src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>ADCVD_Case__r.Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>Case Number</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Referenced from parent Petition case</description>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Referenced from parent Petition</description>
        <label>Country Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Iran</fullName>
                </value>
                <value>
                    <fullName>Iraq</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Referenced from parent Petition</description>
        <label>Product Deprecated</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>(ADCVD_Case__r.Product__c)</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staffing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staffing Assignment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Staffing Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/classes/TestUtils.cls
@isTest
public with sharing class TestUtils {
	
	private static Id adminProfileId = [SELECT Id FROM Profile WHERE Name=: 'System Administrator' LIMIT 1].Id;
	
	/*public static Staffing_Assignment__c createStaffingAssignment(Boolean doInsert, Segment__c seg, ADCVD_Order__c ord) {
		Staffing_Assignment__c sa = new Staffing_Assignment__c(Segment__c = seg.Id, ADCVD_Order__c = ord.Id);
		if(doInsert) {
			insert sa;
		}
		return sa;
	}*/

/*	/public static List<User> createStaffUsers(Boolean doInsert) {
		Integer i = 0;
		List<User> userList = new List<User>();
		for(String s: StaffingAssignmentController.userTitlesSet) {
			i++;
			User u = createAdminUser(false, 'test@test.tst', i);
            u.AD_CVD_Title__c = s;
            userList.add(u);
		}
		if(doInsert) {
			insert userList;	
		}
		return userList;
	}
*/	
	public static User createAdminUser(Boolean doInsert, String email, Integer i) {
		User u = new User();
		u.ProfileId = adminProfileId;
     	u.isActive = true;
    	u.Alias = 'Alias' + i;
        u.LocaleSidKey = 'en_US';
        u.LanguageLocaleKey='en_US';
        u.LastName = 'LastName' + i;
        u.FirstName = 'FirstName' + i;
        u.EmailEncodingKey = 'ISO-8859-1';
        u.Email = email + i;
        u.TimeZoneSidKey = 'America/New_York';
        u.CommunityNickname = 'Ltest' + i;
        u.UserName = email + '.test' + i;
        if(doInsert) {
        	insert u;
        }
        return u;
	}
	public static Account createAccount(Boolean doInsert) {
        Account newRecord = new Account(
            Name='Acme', 
            BillingStreet = '101 binary way', 
            BillingCity = 'New York', 
            BillingState='NY',
            BillingPostalCode='10101'
            );
        if(doInsert) {insert newRecord;}
        return newRecord; 
    }
    
    public static Product2 createProduct(Boolean doInsert) {
        Product2 newRecord = new product2(
            Name='MyTestProduct', 
            IsActive = true
            );
        if(doInsert) {insert newRecord;}
        return newRecord; 
    }

        
    public static Asset createAsset(Account account, Product2 product, Boolean doInsert){
        Asset newRecord = new Asset(
            Name = Product.Name, 
            AccountId = account.Id, 
            Product2id = Product.Id, 
            Status='Installed'
            );
        if(doInsert) {insert newRecord;}
        return newRecord;
    }

    public static Attachment createAttachment(Id parentId, Boolean doInsert) {
        Attachment newRecord = new Attachment(
            ParentId = parentId,
            Name = 'mytestname',
            Body = Blob.valueOf('mystring')
            );
        if(doInsert) {insert newRecord;}
        return newRecord;
    }
    //create test Contact
    public static Contact createContact(String name, String accId , Boolean isInsert){
        Contact con = new Contact(LastName = name, accountId = accId, ownerId = UserInfo.getUserId());
        if(isInsert){
            insert con;
        }
        return con;
    }
    
    // create Case
    public static Case createCase(String sub, boolean isInsert){
        Case cs = new Case();
        cs.Subject = sub;
        if(isInsert) {
            insert cs;
        }  
        return cs;
    }

    //create Federal Register
    public static Federal_Register__c createFR(Id parentId, String parentLookupField, Date publishedDate, String frType, Boolean doInsert) {
        Federal_Register__c fr = new Federal_Register__c();
        fr.put(parentLookupField, parentId);
        fr.Type__c = frType;
        fr.Published_Date__c = publishedDate;
        if(doInsert) {
            insert fr;
        }
        return fr;
    }
    
    //create Investigation
    public static Investigation__c createInvestigation(String recordTypeName, Petition__c p, Boolean doInsert) {
        Investigation__c i = new Investigation__c();
        i.Petition__c = p.Id;
        i.RecordTypeId = utils.getRecordTypeIdMap(i).get(recordTypeName);
        if (doInsert) {
            insert i;
        }
        return i;
    }
    
    // create Case
    public static Lead createLead(String firstName, String LastName,boolean isInsert){
        Lead lead = new Lead ();
        lead.firstName = firstName;
        lead.LastName = LastName;
        lead.Company = 'Test';
        if(isInsert) {
            insert lead;
        }
        return lead;
    }
            
    // create test Opportunity
    public static Opportunity createOpportunity(String accId, String conId, boolean isInsert){
        Opportunity opp = new Opportunity();
        opp.Name = 'opportunity';
        opp.AccountId = accId;
        opp.CloseDate = Date.Today();
        opp.stageName = 'Open';
        if(isInsert) {
            insert opp;
        }
        return opp;
    }

    // create test order
    public static ADCVD_Order__c createOrder(Boolean doInsert) {
        ADCVD_Order__c o = new ADCVD_Order__c();
        Datetime tempDatetime = System.now();
        o.Anniversary_Month__c = tempDatetime.format('MMMMM');
        if(doInsert) {
            insert o;
        }
        return o;
    }

    // create test Petition
    public static Petition__c createPetition(Date petitionDate, String caseType, Boolean doInsert){
        Petition__c petition = new Petition__c();
        petition.Product__c = 'tacos';
        petition.Case_Type__c = caseType;
        if(caseType.substring(0, 1) == 'A'){
            petition.Case_Number__c = 'A-111-222';
        } else {
            petition.Case_Number__c = 'C-111-222';
        }
        petition.Country__c = 'United States';
        petition.Commodity__c = 'Foodstuffs'; 
        petition.Petition_Filed__c = petitionDate;
        //added for testing purposes
        petition.Petition_Outcome__c = 'Initiated';
        petition.Initiation_Extension_of_days__c = 3;
        if(doInsert){
            insert petition;
        }
        return petition;
    }

    //create test segment
    public static Segment__c createSegment(ADCVD_Order__c ord, String recordTypeName, Boolean doInsert) {
        Segment__c seg = new Segment__c();
        seg.RecordTypeId = utils.getRecordTypeIdMap('Segment__c').get(recordTypeName);
        if(ord != null && ord.Id != null) {
            seg.ADCVD_Order__c = ord.Id;
        }
        //added for testing purposes
        Date tempDate = System.today();
        seg.Final_Date_of_Anniversary_Month__c = tempDate.toStartOfMonth().addDays(Date.daysInMonth(tempDate.year(), tempDate.month()) - 1);
        if(doInsert) {
            insert seg;
        }
        return seg;
    }

    //create test Tolling Day
    public static Tolling_Day__c createTollingDay(Date startDate, Date endDate, User u, Boolean doInsert){
        Tolling_Day__c td = new Tolling_Day__c();
        td.Start_Date__c = startDate;
        td.End_Date__c = endDate;
        td.Reason__c = 'Snow Day';
        if(doInsert){
            System.runAs(u){
                insert td;
            }
        }
        return td;
    }
    
     public static User createGenericUser(string username, string email, String profileId) {
        User user = new User();
        user.ProfileId = profileId;
        user.isActive = true;
        user.Alias = 'Alias1';
        user.LocaleSidKey = 'en_US';
        user.LanguageLocaleKey='en_US';
        user.LastName = 'LastName1';
        user.FirstName = 'FirstName1';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.Email = email;
        user.TimeZoneSidKey = 'America/New_York';
        user.CommunityNickname = username+ 'nick87Test';
        user.UserName = username + '.test';
        //user.CallCenterId  = [select Id from CallCenter limit 1].Id;       
        //user.ContactId = conId;
        return user;
    }
}