src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Recusal__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recusal</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Recusal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recusals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecusalMapperTest.cls
/**
 *
 *    Created by Joshua Moody
 *    on 6/29/2019
 *    MIL Corporation
 *
 **/
@isTest
public class RecusalMapperTest {

    private static List<ADCVD_Case__c> adcvdCaseList { get; set;}
    private static List<Petition__c> petitionsList {get; set;}
    private static List<Recusal__c> recList {get; set;}

    @isTest static void testRecusalMapper(){

        dataSetup();
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ADCVD_ICaseSelector mockADCVD_CaseSelector = (ADCVD_ICaseSelector) mocks.mock(ADCVD_ICaseSelector.class);

        mocks.startStubbing();
        mocks.when(mockADCVD_CaseSelector.sObjectType()).thenReturn(ADCVD_Case__c.SObjectType);
        mocks.when(mockADCVD_CaseSelector.selectByIdWithRelations(new Set<Id> {adcvdCaseList.get(0).Id})).thenReturn(adcvdCaseList);
        mocks.stopStubbing();

        fflibext_Application.Selector.setMock(mockADCVD_CaseSelector);

        RecusalSelector mockRecusalSelector = (RecusalSelector) mocks.mock(RecusalSelector.class);

        mocks.startStubbing();
        mocks.when(mockRecusalSelector.sObjectType()).thenReturn(Recusal__c.SObjectType);
        mocks.when(mockRecusalSelector.selectById(new Set<Id> {recList.get(0).Id, recList.get(1).Id})).thenReturn(recList);
        mocks.stopStubbing();

        fflibext_Application.Selector.setMock(mockRecusalSelector);

        Test.startTest();
        RecusalMapper recMapper = new RecusalMapper(new Set<Id>{recList[0].Id, recList[1].Id});
        Map<Id, SObject> idToUnlockedRecusalMap = recMapper.getMap(false);
        Map<Id, SObject> idToAllRecusalMap = recMapper.getMap(true);
        Map<Id, List<Recusal__c>> userIdToUnlockedRecusalMap = recMapper.getMapByUserIds();

        Test.stopTest();

        //Assert adcvd case records
        System.assertEquals(recList[0].Id, idToUnlockedRecusalMap.get(recList[0].Id).Id);
        System.assertEquals(null, idToUnlockedRecusalMap.get(recList[1].Id));
        System.assertEquals(recList[0].Id, idToAllRecusalMap.get(recList[0].Id).Id);
        System.assertEquals(recList[1].Id, idToAllRecusalMap.get(recList[1].Id).Id);

    }

    @IsTest static void testBehavior()
    {
        RecusalMapper rm = new RecusalMapper();
        rm.getInstance();
        rm.getInstance(new Set<Id>());
        rm.getNewInstance(new Set<Id>());
    }


    private static void dataSetup(){
        // Create ADCVD_Case record
        adcvdCaseList = new List<ADCVD_Case__c>();
        adcvdCaseList.add(
            new ADCVD_Case__c(
                Id = fflib_IdGenerator.generate(ADCVD_Case__c.SObjectType),
                Locked__c = false
            )
        );

        //Create Petition records
        petitionsList = new List<Petition__c>();
        petitionsList.add(
            new Petition__c(
                Id = fflib_IDGenerator.generate(Petition__c.SObjectType),
                Locked__c = false,
                ADCVD_Case__c = adcvdCaseList[0].Id
            )
        );
        //Create relationship between ADCVD_Cases and Petitions
        adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
            List<ADCVD_Case__c>.class,
            adcvdCaseList,
            Petition__c.ADCVD_Case__c,
            new List<List<Petition__c>>{
                new List<Petition__c> {petitionsList.get(0)}
            }
        );
        //Create Recusal records, one locked and one unlocked with ADCVD Case and one unlocked without ADCVD Case
        recList = new List<Recusal__c>();
        recList.add(
            new Recusal__c(
                Id = fflib_IDGenerator.generate(Recusal__c.SObjectType),
                Locked__c = false,
                ADCVD_Case__c = adcvdCaseList[0].Id
            )
        );
        recList.add(
            new Recusal__c(
                Id = fflib_IDGenerator.generate(Recusal__c.SObjectType),
                Locked__c = false
            )
        );
        recList.add(
            new Recusal__c(
                Id = fflib_IDGenerator.generate(Recusal__c.SObjectType),
                Locked__c = true
            )
        );
        //Create relationship between ADCVD Case and Recusals
        adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
            List<ADCVD_Case__c>.class,
            adcvdCaseList,
            Recusal__c.ADCVD_Case__c,
            new List<List<Recusal__c>>{
                new List<Recusal__c> {recList.get(0)}
            }
        );
    }
}