src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HTS_Number__c</fullName>
        <label>HTS Number</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harmonized_Tariff_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Harmonized Tariff Schedules</relationshipLabel>
        <relationshipName>Harmonized_Tariff_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTS_Number_Formatted__c</fullName>
        <formula>CASE( LEN( HTS_Number__c ) ,
 4, HTS_Number__c ,
 6, LEFT(HTS_Number__c, 4) + &apos;.&apos; + RIGHT(HTS_Number__c, 2) ,
 8, LEFT(HTS_Number__c, 4) + &apos;.&apos; + MID(HTS_Number__c, 5, 2) + &apos;.&apos; + RIGHT(HTS_Number__c, 2) ,
 10, LEFT(HTS_Number__c, 4) + &apos;.&apos; + MID(HTS_Number__c, 5, 2) + &apos;.&apos; + MID(HTS_Number__c, 7, 2) + &apos;.&apos; + RIGHT(HTS_Number__c, 2) ,
 HTS_Number__c )</formula>
        <label>HTS Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTS_Number__c</fullName>
        <description>Harmonized Tariff Schedule</description>
        <externalId>true</externalId>
        <label>HTS Number</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Short_Name__c</fullName>
        <formula>ADCVD_Case__r.Product_Short_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Short Name Deprecated</label>
        <type>Text</type>
    </fields>
    <label>Harmonized Tariff Schedule</label>
    <nameField>
        <label>Harmonized Tariff Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harmonized Tariff Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <formula>ADCVD_Case__r.Name</formula>
        <label>ADCVD Case Number Text Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <description>Actual Final Signature</description>
        <inlineHelpText>Actual Final Signature</inlineHelpText>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Announcement_Date__c</fullName>
        <label>Final Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Extension_Remaining__c</fullName>
        <formula>CASE( RecordType.DeveloperName , 
&apos;Administrative_Review&apos;, 
 IF( Prelim_Extension__c = 0 &amp;&amp;  ISNULL(Actual_Preliminary_Signature__c) , 
     60 - Final_Extension_of_days__c, 
     IF( Prelim_Extension__c = 0 &amp;&amp;  NOT(ISNULL(Actual_Preliminary_Signature__c)) , 
         180 - Final_Extension_of_days__c, 
         60 - Final_Extension_of_days__c)) ,
&apos;Anti_Circumvention_Review&apos;, 180 - Final_Extension_of_days__c , 
&apos;Expedited_Review&apos;, 60 - Final_Extension_of_days__c , 
&apos;New_Shipper_Review&apos;, 60 - Final_Extension_of_days__c , 
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Extension Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initiation_Announcement_Date__c</fullName>
        <label>Initiation Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_Remaining__c</fullName>
        <formula>CASE( RecordType.DeveloperName , 
&apos;Anti_Circumvention_Review&apos;, 45 - Initiation_Extension_of_days__c ,
&apos;Changed_Circumstances_Review&apos;, 45 - Initiation_Extension_of_days__c ,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initiation Extension Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preliminary_Announcement_Date__c</fullName>
        <label>Preliminary Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preliminary_Extension_Remaining__c</fullName>
        <formula>CASE( RecordType.DeveloperName ,
 &apos;Administrative_Review&apos;, 120 - Prelim_Extension__c,
 &apos;Expedited_Review&apos;, 120 - Prelim_Extension__c ,
 &apos;New_Shipper_Review&apos;, 120 - Prelim_Extension__c ,
 &apos;Sunset_Review&apos;, 90 - Prelim_Extension__c ,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preliminary Extension Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Short_Name__c</fullName>
        <formula>(ADCVD_Case__r.Product_Short_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Short Name</label>
        <type>Text</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVD_OrderSearch.cls
@RestResource(urlMapping='/ADCVD_OrderSearch/*')
global without sharing class ADCVD_OrderSearch {
    
    //JSON output classes.  These are marked as Public so the ADCVD_OrderSearchTest can see them.
       
    public class ADCVD_Order {
        public String id;
        public String caseNumber;
        public String productShortName;
        public String country;
        public List<Segment> segments = new List<Segment>();
        public List<HTS> htsNums = new List<HTS>();
    }
    
    public class Segment {
        public String id;
        public String recordType;
        public String decisionSigned;
        public String daysRemaining;
        public String announcementType;
        public String announcementDate;
    }

    public class Hts {
        public String id;
        public String htsNumber;
        public String htsNumberFormatted;
    }
    
    //The class that is used to create the JSON return value
    public class JsonOutput {
        public List<ADCVD_Order> adcvdOrders = new List<ADCVD_Order>();
    }

    private static Map<Id,String> recordTypeIdToNameMap {
    	get {
    		if (recordTypeIdToNameMap == null) {
    			recordTypeIdToNameMap = utils.getRecordTypeLabelMap('Segment__c');
    		}
    		return recordTypeIdToNameMap;
    	} set;
    }

    //The only callable method
    @HttpPost   
    global static void doPost() {
        
        //Initialize the return value
        JsonOutput output = new JsonOutput();
                
        List<ADCVD_Order__c> orders = [SELECT Id, ADCVD_Case_Number__c, Product_Short_Name__c, Country__c, 
			                               (SELECT Id, RecordTypeId, Actual_Final_Signature__c, Initiation_Extension_Remaining__c, 
			                               			Preliminary_Extension_Remaining__c, Final_Extension_Remaining__c, Initiation_Announcement_Date__c, 
			                               			Preliminary_Announcement_Date__c, Final_Announcement_Date__c, Next_Announcement_Date__c 
			                               			FROM Segments__r WHERE Next_Announcement_Date__c != null ORDER BY Next_Announcement_Date__c ASC),
			                               (SELECT Id, HTS_Number__c, HTS_Number_Formatted__c FROM Harmonized_Tariff_Schedules__r ORDER BY HTS_Number_Formatted__c ASC)
			                               FROM ADCVD_Order__c
			                             ];
        
        for (ADCVD_Order__c o: orders) {
            ADCVD_Order ao = new ADCVD_Order();
            ao.id = o.id;
            ao.caseNumber = o.ADCVD_Case_Number__c;
            ao.productShortName = o.Product_Short_Name__c;
            ao.country = o.Country__c;
            
            for (Segment__c seg: o.Segments__r) {
                Segment s = new Segment();
                s.id = seg.id;
                s.recordType = recordTypeIdToNameMap.get(seg.RecordTypeId);
                s.announcementDate = seg.Next_Announcement_Date__c.format();
                getAnnouncementTypeInfo(seg, s);
                ao.segments.add(s);
            }
            for (Harmonized_Tariff_Schedule__c hts: o.Harmonized_Tariff_Schedules__r) {
                Hts h = new Hts();
                h.id = hts.id;
                h.htsNumber = hts.HTS_Number__c;
                h.htsNumberFormatted = hts.HTS_Number_Formatted__c;
                ao.htsNums.add(h);
            }
            
            output.adcvdOrders.add(ao);
            
        }
        
        //Create the JSON output
        RestContext.response.addHeader('Content-Type', 'application/json');
        String returnValue = JSON.serialize(output, true);
        System.debug(loggingLevel.Error, '*** returnValue: ' + returnValue);
        RestContext.response.responseBody = Blob.valueOf(returnValue);
        return;

    }

    private static void getAnnouncementTypeInfo(Segment__c seg, Segment s) {
    	if (seg.Next_Announcement_Date__c == seg.Initiation_Announcement_Date__c) {
    		s.announcementType = 'Initiation';
    		s.daysRemaining = seg.Initiation_Extension_Remaining__c.toPlainString();
    	} else if (seg.Next_Announcement_Date__c == seg.Preliminary_Announcement_Date__c) {
    		s.announcementType = 'Preliminary';
    		s.daysRemaining = seg.Preliminary_Extension_Remaining__c.toPlainString();
    	} else if (seg.Next_Announcement_Date__c == seg.Final_Announcement_Date__c) {
    		s.announcementType = 'Final';
    		s.daysRemaining = seg.Final_Extension_Remaining__c.toPlainString();
    	}
    	if (seg.Actual_Final_Signature__c != null) {
    		s.daysRemaining = 'Decision Signed';
    		s.decisionSigned = 'true';
    	} else {
    		s.decisionSigned = 'false';
    	}
    }

}