src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <label>ADCVD Case Number Text Value</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Configuration data for applications that utilize triggers in the org. There should be a &quot;default&quot; config and a &quot;testConfig&quot; AppConfig list in an org. EnableTriggers to be checked for both.</description>
    <label>AppConfig</label>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cite_Number__c</fullName>
        <label>Cite Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suspension_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suspension Agreement</label>
        <referenceTo>Suspension_Agreement__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Roman_Numerals</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Automation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Master Automation</label>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>ADCVD Case Number Text Value Deprecated</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ADCVD_Offices</valueSetName>
        </valueSet>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <formula>ADCVD_Case__r.Name</formula>
        <label>ADCVD Case Number Text Value Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Sunset_Initiation_Date__c</fullName>
        <label>Next Sunset Initiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SA</fullName>
                    <default>true</default>
                    <label>SA</label>
                </value>
                <value>
                    <fullName>Suspension Office</fullName>
                    <isActive>false</isActive>
                    <label>Suspension Office</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suspension_Date__c</fullName>
        <label>Suspension Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date - Deprecated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field displays the Type of Suspension Agreement</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD - 734(b) - Cessation of Exports</fullName>
                </value>
                <value>
                    <fullName>AD - 734(b) - Normal Value</fullName>
                </value>
                <value>
                    <fullName>AD - 734(c) - Reference Price</fullName>
                </value>
                <value>
                    <fullName>AD - 734(l) - NME</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(b) - Elimination of Subsidy</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(b) - Cessation of Exports</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(c) - Other than Quantitative Restriction</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(c) - Quantitative Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/ADCVD_Offices.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>V</fullName>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
    </customValue>
    <customValue>
        <fullName>VII</fullName>
    </customValue>
    <customValue>
        <fullName>VIII</fullName>
    </customValue>
    <masterLabel>ADCVD Offices</masterLabel>
</GlobalValueSet>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/globalValueSets/Roman_Numerals.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>V</fullName>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
    </customValue>
    <customValue>
        <fullName>VII</fullName>
    </customValue>
    <masterLabel>Roman Numerals</masterLabel>
</GlobalValueSet>

src/classes/SuspensionAgreementTriggerHandlerTest.cls
/**
 * 
 *    Created by Joshua Moody
 *    on May 16 2017
 *    MIL Corporation
 * 
 **/
 @isTest
public class SuspensionAgreementTriggerHandlerTest {
    /************************************************
    * This class performs unit tests on the SuspensionAgreementTriggerHandler
    * under these condititions.
    * 1. Test to ensure that class variables initialize
    * 2. Test to ensure that date calculations are logically correct
    *************************************************/
    
    private static Date suspDate = System.today();
    private static Date testActual = System.today();//reusable date variable for each test to add roll forward logic allowing data normalization
    private static Date testCalculated = System.today();//reusable date variable for each test to add roll forward logic allowing data normalization
    private static User u{
        get{
            if(u == null){
                u = [SELECT Id, ProfileId, isActive, Alias, LanguageLocaleKey, LastName, FirstName, 
                                Email, EmailEncodingKey, TimeZoneSidKey, CommunityNickname, Username 
                            FROM User WHERE LastName =: 'LastName1' LIMIT 1];
            }
            return u;
        }
    }
    private static Suspension_Agreement__c sa{
        get{
            if (sa == null) {
                sa = [SELECT Id, ADCVD_Case__c, Anniversary_Month__c, Suspension_Date__c, Investigation__c, Office__c, Next_Sunset_Initiation_Date__c, Termination_Date__c FROM Suspension_Agreement__c LIMIT 1];
            }
            return sa;
        }
    }
    private static Federal_Register__c suspensionAgreementFR{
        get{
            if (suspensionAgreementFR == null) {
                suspensionAgreementFR = [SELECT Id, Suspension_Agreement__c, Type__c, Published_Date__c FROM Federal_Register__c WHERE Type__c =: 'Suspension Agreement' LIMIT 1];
            }
            return suspensionAgreementFR;
        }
    }
    private static Federal_Register__c continuationFR{
        get{
            if (continuationFR == null) {
                continuationFR = [SELECT Id, Suspension_Agreement__c, Type__c, Published_Date__c FROM Federal_Register__c WHERE Type__c =: 'Continuation' LIMIT 1];
            }
            return continuationFR;
        }
    }
    private static Federal_Register__c termFR{
        get{
            if (termFR == null) {
                termFR = [SELECT Id, Suspension_Agreement__c, Type__c, Published_Date__c FROM Federal_Register__c WHERE Type__c =: 'Termination' LIMIT 1];
            }
            return termFR;
        }
    }

    @isTest static void initialize(){
        Test.startTest();
        List<Suspension_Agreement__c> aList = new List<Suspension_Agreement__c>();
        aList.add(sa);
        SuspensionAgreementTriggerHandler.initialize(aList, null);

        Test.stopTest();
        System.assert(SuspensionAgreementTriggerHandler.frUtilMap.isEmpty());
    }

    //Test to check if Suspension Agreement is auto-populated with ADCVD Case number
    @isTest static void setCaseValuesFromParent() {
        Test.startTest();
        ADCVD_Case__c testCase = TestUtils.createADCVDCase('A-111-123', 'AD ME', true);
        Petition__c testPetition = TestUtils.createPetition(testCase,suspDate.addDays(-14), true);
        //insert testPetition;
        Investigation__c testInvestigation = TestUtils.createInvestigation(testPetition, true);
        Suspension_Agreement__c testSuspAgr = TestUtils.createSuspensionAgreement(testInvestigation, suspDate, true); 
        Test.stopTest();
        Suspension_Agreement__c savedSuspAgrmnt = [SELECT Id, ADCVD_Case__c, ADCVD_Case_Number__c
                                                  FROM Suspension_Agreement__c WHERE ADCVD_Case__c =: testCase.Id];
        System.assertEquals(testCase.Id, savedSuspAgrmnt.ADCVD_Case__c);
        System.assertEquals(testCase.ADCVD_Case_Number__c, savedSuspAgrmnt.ADCVD_Case_Number__c);
        System.assertEquals(testPetition.ADCVD_Case__c, savedSuspAgrmnt.ADCVD_Case__c);
    }
       

    @isTest static void setNextSunsetInitiationDate() {
        Test.startTest();
        System.assertEquals(null, sa.Next_Sunset_Initiation_Date__c);
        //Create a JSON string from the Federal Register object to be able to modify the CreatedDate
        String frJSON = JSON.serialize(new Federal_Register__c());
        Map<String, Object> frJSONMap = (Map<String, Object>)JSON.deserializeUntyped(frJSON);
        frJSONMap.put('CreatedDate',Date.Today().addDays(-1));
        frJSONMap.put('Type__c','Suspension Agreement');
        frJSONMap.put('Cite_Number__c','3rfef');
        frJSONMap.put('Published_Date__c',Date.today().addDays(5));
        frJSONMap.put('Suspension_Agreement__c', sa.Id);
        String frJSON2 = JSON.serialize(frJSONMap);
        //Deserialize string back to FR object and commit to database
        Federal_Register__c suspensionAgreementFR = (Federal_Register__c)JSON.deserializeStrict(frJSON2, Federal_Register__c.class);
        insert suspensionAgreementFR;
        sa = null;
        testCalculated = suspDate.toStartOfMonth().addYears(4).addMonths(11);
        System.assertEquals(testCalculated, sa.Next_Sunset_Initiation_Date__c);
        suspDate = suspDate.addMonths(1);
        setFR(sa.Id, 'Continuation', true);
        sa = null;
        testCalculated = suspDate.toStartOfMonth().addYears(4).addMonths(11);
        System.assertEquals(testCalculated, sa.Next_Sunset_Initiation_Date__c);
        suspDate = suspDate.addMonths(1);
        setFR(sa.Id, 'Termination', true);
        sa = null;
        Test.stopTest();
        System.assertEquals(null, sa.Next_Sunset_Initiation_Date__c);

    }

    @isTest static void setAnniversaryMonth() {
        Test.startTest();
        setFR(sa.Id, 'Suspension Agreement', true);
        String month = utils.getMonthFromDate(suspDate);
        sa = null;
        
        Test.stopTest();
        System.assertEquals(month, sa.Anniversary_Month__c);
    }

    @testSetup static void dataSetup() {
        Test.startTest();
        //create custom setting configuration to activate triggers, workflow rules, and validation rules
        Master_Automation__c ma = TestUtils.createMasterAutomation(true, true, true);
        AppConfig__c ac = TestUtils.createAppConfig('default', true, true);
        //create test data
        User testUser = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
        ADCVD_Case__c testADCase = TestUtils.createADCVDCase('A-123-123', 'AD ME', true);
        Petition__c testADPetition = TestUtils.createPetition(testADCase, suspDate.addDays(-14), true);
        Investigation__c testADinvestigation = TestUtils.createInvestigation(testADPetition, true);
        Suspension_Agreement__c testADSuspAgreement = TestUtils.createSuspensionAgreement(testADinvestigation, suspDate, true);

    }

    private static Federal_Register__c setFR(Id parentId, String frType, Boolean doInsert) {
        Federal_Register__c testFR = TestUtils.createFR(parentId, 'Suspension_Agreement__c', suspDate, frType, doInsert);
        return testFR;
    }

    private static String attemptUpsert(SObject o){
        String error = '';
        try{
            upsert o;
            error = 'Success';
        } catch (DmlException e) {
            error = e.getMessage();
        }
        return error;
    }
}