src/objects/ADCVD_Objects__mdt.object
<CustomObject>
    <description>This holds the object types, record types, and a type field (if present) delineating a difference in records for the ADCVD app</description>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
                <value>
                    <fullName>Administrative_Review</fullName>
                </value>
                <value>
                    <fullName>Anti_Circumvention_Review</fullName>
                </value>
                <value>
                    <fullName>Changed_Circumstances_Review</fullName>
                </value>
                <value>
                    <fullName>Expedited_Review</fullName>
                </value>
                <value>
                    <fullName>New_Shipper_Review</fullName>
                </value>
                <value>
                    <fullName>Scope_Inquiry</fullName>
                </value>
                <value>
                    <fullName>Sunset_Review</fullName>
                </value>
                <value>
                    <fullName>International_Litigation</fullName>
                </value>
                <value>
                    <fullName>Remand</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Related</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Initiation/Prelim</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Petitioner</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Respondent</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Objects</label>
    <pluralLabel>ADCVD Objects</pluralLabel>
</CustomObject>

src/objects/Constant__mdt.object
<CustomObject>
    <description>This holds constant values used in classes</description>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Constants</relationshipLabel>
        <relationshipName>Constants</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Used_with_Field_Named__c</fullName>
        <label>Used with Field Named</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constant</label>
    <pluralLabel>Constants</pluralLabel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Calc_Amended_Prelim_Determination_Sig__c</fullName>
        <description>Calculated Amended Preliminary Determination Signature</description>
        <inlineHelpText>Calculated Amended Preliminary Determination Signature</inlineHelpText>
        <label>Calc Amended Prelim Determination Sig</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Amended_Final_Signature__c</fullName>
        <description>Calculated Amended Final Signature</description>
        <inlineHelpText>Calculated Amended Final Signature</inlineHelpText>
        <label>Calculated Amended Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amended Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amended Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>Issue-{00000000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Amended_Final_Signature__c</fullName>
        <label>Calculated Amended Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Draft_Remand_release_to_party__c</fullName>
        <label>Calculated Draft Remand release to party</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litigation</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Litigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation</pluralLabel>
    <recordTypes>
        <fullName>Remand</fullName>
        <active>true</active>
        <label>Remand</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Amended_Final_Signature__c</fullName>
        <description>Calculated Amended Final Signature</description>
        <inlineHelpText>Calculated Amended Final Signature</inlineHelpText>
        <label>Calculated Amended Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deadline_for_Decision_on_How_to_Proceed__c</fullName>
        <description>Deadline for Decision on How to Proceed</description>
        <inlineHelpText>Deadline for Decision on How to Proceed</inlineHelpText>
        <label>Deadline for Decision on How to Proceed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Anti_Circumvention_Review</fullName>
        <active>true</active>
        <label>Anti-Circumvention Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Changed_Circumstances_Review</fullName>
        <active>true</active>
        <label>Changed Circumstances Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expedited_Review</fullName>
        <active>true</active>
        <label>Expedited Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>New_Shipper_Review</fullName>
        <active>true</active>
        <label>New Shipper Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scope_Inquiry</fullName>
        <active>true</active>
        <label>Scope Inquiry</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sunset_Review</fullName>
        <active>true</active>
        <label>Sunset Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IssueTriggerHandler.cls
public without sharing class IssueTriggerHandler {

	private static Map<String,Constant__mdt> issueCalcOffsets = issueCalcOffsets();
	//FINAL Issue Parent Object Types
	private static FINAL String PETITION = 'Petition__c';
	private static FINAL String INVESTIGATION = 'Investigation__c';
	private static FINAL String SEGMENT = 'Segment__c';
	private static FINAL String LITIGATION = 'Litigation__c';

	//FINAL Issue Parent Object Record Types
	private static FINAL String ADMIN_REVIEW						= issueCalcOffsets.get('Admin_Review_Calc_Prelim_Sig').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String ANTI_CIRCUMVENTION_REVIEW			= issueCalcOffsets.get('Anti_Circ_Calc_Prelim_Sig').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String CHANGED_CIRCUMSTANCES_REVIEW		= issueCalcOffsets.get('Changed_Circ_Calc_Prelim_Sig').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String EXPEDITED_REVIEW					= issueCalcOffsets.get('Exped_Review_Calc_Prelim_Sig').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String NEW_SHIPPER_REVIEW					= issueCalcOffsets.get('New_Shipper_Calc_Prelim_Sig').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String SCOPE_INQUIRY						= issueCalcOffsets.get('Scope_Inq_Calc_Prelim_Sig').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String SUNSET_REVIEW						= issueCalcOffsets.get('SS_Rev_Notice_Intent_Participate').ADCVD_Objects__r.Record_Type_Name__c;
	private static FINAL String INT_LITIGATION 						= issueCalcOffsets.get('Int_Lit_Calc_Initiation_Sig').ADCVD_Objects__r.Record_Type_Name__c;
    private static FINAL String REMAND 								= issueCalcOffsets.get('Remand_Calc_Draft_Remand_Release').ADCVD_Objects__r.Record_Type_Name__c;

    //FINAL Issue Types
    private static FINAL String TYPE_INITIATION 					= issueCalcOffsets.get('Issues_to_DAS_Initiation').ADCVD_Objects__r.Type__c;
    private static FINAL String TYPE_PRELIMINARY 					= issueCalcOffsets.get('Issues_to_DAS_Preliminary').ADCVD_Objects__r.Type__c;
    private static FINAL String TYPE_AMENDED_PRELIMINARY 			= issueCalcOffsets.get('Issues_to_DAS_Amended_Prelim').ADCVD_Objects__r.Type__c;
    private static FINAL String TYPE_FINAL 							= issueCalcOffsets.get('Issues_to_DAS_Final').ADCVD_Objects__r.Type__c;
    private static FINAL String TYPE_AMENDED_FINAL 					= issueCalcOffsets.get('Issues_to_DAS_Amended_Final').ADCVD_Objects__r.Type__c;
    private static FINAL String TYPE_DEADLINE_FOR_HOP 				= issueCalcOffsets.get('Issues_to_DAS_Deadline_for_Dec_on_HOP').ADCVD_Objects__r.Type__c;
    private static FINAL String TYPE_CONT_OR_REVO 					= issueCalcOffsets.get('Concur_to_DAS_Cont_or_Revo').ADCVD_Objects__r.Type__c;

	//FINAL Issues To DAS Offsets
	private static FINAL Integer ISSUES_PETITION_INITIATION 		= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Petition_Initiation').Number_Value__c);//Calculated_Initiation_Signature__c
	private static FINAL Integer ISSUES_INITIATION 					= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Initiation').Number_Value__c);//Calculated_Initiation_Signature__c
	private static FINAL Integer ISSUES_PRELIMINARY 				= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Preliminary').Number_Value__c);//Calculated_Preliminary_Signature__c or Calculated_Draft_Remand_release_to_party__c
	private static FINAL Integer ISSUES_AMENDED_PRELIMINARY 		= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Amended_Prelim').Number_Value__c);//Calc_Amended_Prelim_Determination_Sig__c
	private static FINAL Integer ISSUES_FINAL 						= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Final').Number_Value__c);//Calculated_Final_Signature__c
	private static FINAL Integer ISSUES_AMENDED_FINAL				= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Amended_Final').Number_Value__c);//Calculated_Amended_Final_Signature__c
	private static FINAL Integer ISSUES_DEADLINE_FOR_HOP 			= ((Integer)issueCalcOffsets.get('Issues_to_DAS_Deadline_for_Dec_on_HOP').Number_Value__c);//Deadline_for_Decision_on_how_to_proceed__c
	//FINAL Concurrence to DAS Offsets
	private static FINAL Integer CONCURRENCE_PETITION_INITIATION 	= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Petition_Initiation').Number_Value__c);//Calculated_Initiation_Signature__c
	private static FINAL Integer CONCURRENCE_INITIATION 			= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Initiation').Number_Value__c);//Calculated_Initiation_Signature__c
	private static FINAL Integer CONCURRENCE_PRELIMINARY 			= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Preliminary').Number_Value__c);//Calculated_Preliminary_Signature__c or Calculated_Draft_Remand_release_to_party__c
	private static FINAL Integer CONCURRENCE_AMENDED_PRELIMINARY 	= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Amended_Prelim').Number_Value__c);//Calc_Amended_Prelim_Determination_Sig__c
	private static FINAL Integer CONCURRENCE_FINAL 					= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Final').Number_Value__c);//Calculated_Final_Signature__c
	private static FINAL Integer CONCURRENCE_AMENDED_FINAL			= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Amended_Final').Number_Value__c);//Calculated_Amended_Final_Signature__c
	private static FINAL Integer CONCURRENCE_DEADLINE_FOR_HOP 		= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Deadline_for_Dec_on_HOP').Number_Value__c);//Deadline_for_Decision_on_how_to_proceed__c
	private static FINAL Integer CONCURRENCE_CONT_OR_REVO			= ((Integer)issueCalcOffsets.get('Concur_to_DAS_Cont_or_Revo').Number_Value__c);//Continuation_or_Revocation_FR_Notice_Pub__c


	public static boolean preventRecursion = false;
    public static void mainEntry(List<Issue__c> newList, List<Issue__c> oldList, Map<Id, Issue__c> newMap, 
        Map<Id, Issue__c> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete, 
        Boolean isBefore, Boolean isAfter){
        if(preventRecursion) {return;}

        if(isBefore && isInsert) {
            calculateIssueDates(newList);
        }
        if(isBefore && isUpdate) {
            calculateIssueDates(newList);
        }
        if(isAfter && isInsert) {

        }
        if(isAfter && isUpdate) {
            
        }
    }

    //Parent maps
    @TestVisible private static Map<Id,Petition__c> petitionParents = new Map<Id,Petition__c>();
    @TestVisible private static Map<Id,Investigation__c> investigationParents = new Map<Id,Investigation__c>();
    @TestVisible private static Map<Id,Segment__c> segmentParents = new Map<Id,Segment__c>();
    @TestVisible private static Map<Id,Litigation__c> litigationParents = new Map<Id,Litigation__c>();
    @TestVisible private static Map<Id,List<Issue__c>> parentIdToIssueMap = new Map<Id,List<Issue__c>>();
    @TestVisible private static Map<Id,String> parentIdToObjectTypeMap = new Map<Id,String>();
    @TestVisible private static Map<Id,String> parentIdToRecordTypeNameMap = new Map<Id,String>();

    @TestVisible private static void calculateIssueDates(List<Issue__c> newList) {
    	setParentMaps(newList);
    	if (parentIdToIssueMap == null) {return;}// if no parents, set nothing
		for (Id parentId : parentIdToIssueMap.keySet()) {//for each parent
			for (Issue__c i : parentIdToIssueMap.get(parentId)) {//iterate through the related issues
				if (i.Type__c != null) {//if type == null, skip issue
					//Only run each Issue through the method that matches it's type
					if (i.Type__c == TYPE_INITIATION) {
						setInitiationIssuesToDAS(parentId, i);
						setInitiationConcurrenceToDAS(parentId, i);
					} else if (i.Type__c == TYPE_PRELIMINARY) {
						setPreliminaryIssuesToDAS(parentId, i);
						setPreliminaryConcurrenceToDAS(parentId, i);
					} else if (i.Type__c == TYPE_AMENDED_PRELIMINARY) {
						setAmendedPreliminaryIssuesToDAS(parentId, i);
						setAmendedPreliminaryConcurrenceToDAS(parentId, i);
					} else if (i.Type__c == TYPE_FINAL) {
						setFinalIssuesToDAS(parentId, i);
						setFinalConcurrenceToDAS(parentId, i);
					} else if (i.Type__c == TYPE_AMENDED_FINAL) {
						setAmendedFinalIssuesToDAS(parentId, i);
						setAmendedFinalConcurrenceToDAS(parentId, i);
					} else if (i.Type__c == TYPE_DEADLINE_FOR_HOP) {
						setDeadlineForDecisionHOPIssuesToDAS(parentId, i);
						setDeadlineForDecisionHOPConcurrenceToDAS(parentId, i);
					} else if (i.Type__c == TYPE_CONT_OR_REVO) {
						setContinuationOrRevocationConcurrenceToDAS(parentId, i);
					}
				}   
			}
		}
	}

    //TODO: Load mdt into class as finals
    //TODO: Identify parent object type
    //TODO: Identify segment and litigation record types
    //TODO: Query parent for starting dates
    //TODO: Method for each type of Date, branching based on parent record
    //TODO: Set parent Next Deadline Date
  	//TODO: Set prevent recursion and update parents in after context
    

    //used to set Offset Variables
    @TestVisible private static Map<String,Constant__mdt> issueCalcOffsets() {
        if(issueCalcOffsets == null || issueCalcOffsets.size() < 1) {
            Map<String,Constant__mdt> returnMap = new Map<String,Constant__mdt>();
            List<Constant__mdt> tempList = [SELECT QualifiedAPIName, Used_with_Field_Named__c, Number_Value__c, ADCVD_Objects__r.Type__c,
                                                    ADCVD_Objects__r.Object_API_Name__c, ADCVD_Objects__r.Record_Type_Name__c,
                                                    Petition_Calculation_Offset__c, Segment_Calculation_Offset__c, 
                                                    Litigation_Calculation_Offset__c, Investigation_Calculation_Offset__c,
                                                    Issue_Calculation_Offset__c
                                            FROM Constant__mdt];
            for(Constant__mdt sc : tempList) {
                returnMap.put(sc.QualifiedAPIName, sc);
            }
            return returnMap;
        } else {
            return issueCalcOffsets;
        }
    }

    @TestVisible private static void setParentMaps(List<Issue__c> newList) {
    	Map<Id,String> tempSegmentRecordTypeMap = utils.getRecordTypeDeveloperNameMap(SEGMENT);
    	Map<Id,String> tempLitigationRecordTypeMap = utils.getRecordTypeDeveloperNameMap(LITIGATION);
    	for (Issue__c i : newList) {
    		List<Issue__c> tempList = new List<Issue__c>();
	    	if (i.Petition__c != null) {
	    		tempList = parentIdToIssueMap.get(i.Petition__c) != null ? parentIdToIssueMap.get(i.Petition__c) : tempList;
	    		tempList.add(i);
				parentIdToIssueMap.put(i.Petition__c, tempList);
				parentIdToObjectTypeMap.put(i.Petition__c, PETITION);
			} else if (i.Investigation__c != null) {
				tempList = parentIdToIssueMap.get(i.Investigation__c) != null ? parentIdToIssueMap.get(i.Investigation__c) : tempList;
	    		tempList.add(i);
				parentIdToIssueMap.put(i.Investigation__c, tempList);
				parentIdToObjectTypeMap.put(i.Investigation__c, INVESTIGATION);
			} else if (i.Segment__c != null) {
				tempList = parentIdToIssueMap.get(i.Segment__c) != null ? parentIdToIssueMap.get(i.Segment__c) : tempList;
	    		tempList.add(i);
				parentIdToIssueMap.put(i.Segment__c, tempList);
				parentIdToObjectTypeMap.put(i.Segment__c, SEGMENT);
			} else if (i.Litigation__c != null) {
				tempList = parentIdToIssueMap.get(i.Litigation__c) != null ? parentIdToIssueMap.get(i.Litigation__c) : tempList;
	    		tempList.add(i);
				parentIdToIssueMap.put(i.Litigation__c, tempList);
				parentIdToObjectTypeMap.put(i.Litigation__c, LITIGATION);
			}
    	}
    	for (Petition__c p : [SELECT Id, Calculated_Initiation_Signature__c FROM Petition__c WHERE Id IN: parentIdToIssueMap.keySet()]) {
    		petitionParents.put(p.Id, p);
    	}
    	for (Investigation__c i : [SELECT Id, Calculated_Preliminary_Signature__c, Calc_Amended_Prelim_Determination_Sig__c, Calculated_Final_Signature__c,
    										Calculated_Amended_Final_Signature__c 
    								FROM Investigation__c WHERE Id IN: parentIdToIssueMap.keySet()]) {
    		investigationParents.put(i.Id, i);
    	}
    	for (Segment__c s : [SELECT Id, Calculated_Initiation_Signature__c, Calculated_Preliminary_Signature__c,
    								Calculated_Final_Signature__c, Calculated_Amended_Final_Signature__c, Deadline_for_Decision_on_how_to_proceed__c,
    								Continuation_or_Revocation__c, RecordTypeId 
    							FROM Segment__c WHERE Id IN: parentIdToIssueMap.keySet()]) {
    		segmentParents.put(s.Id, s);
    		parentIdToRecordTypeNameMap.put(s.Id, tempSegmentRecordTypeMap.get(s.RecordTypeId));
    	}
    	for (Litigation__c l : [SELECT Id, Calculated_Initiation_Signature__c, Calculated_Draft_Remand_release_to_party__c, 
    									Calculated_Final_Signature__c, RecordTypeId 
    								FROM Litigation__c WHERE Id IN: parentIdToIssueMap.keySet()]) {
    		litigationParents.put(l.Id, l);
    		parentIdToRecordTypeNameMap.put(l.Id, tempLitigationRecordTypeMap.get(l.RecordTypeId));
    	}
    }

    /**************************************
    * All Issues To DAS Calculations
    **************************************/

    @TestVisible private static void setInitiationIssuesToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == PETITION) {
    		Petition__c p = petitionParents.get(parentId);
    		if (p.Calculated_Initiation_Signature__c != null) {
    			i.Start_Date__c = p.Calculated_Initiation_Signature__c;
    			i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_PETITION_INITIATION);
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == ANTI_CIRCUMVENTION_REVIEW
				|| parentIdToRecordTypeNameMap.get(s.Id) == CHANGED_CIRCUMSTANCES_REVIEW
				|| parentIdToRecordTypeNameMap.get(s.Id) == NEW_SHIPPER_REVIEW
				) {
    			if (s.Calculated_Initiation_Signature__c != null) {
    				i.Start_Date__c = s.Calculated_Initiation_Signature__c;
	    			i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_INITIATION);
	    		}
    		}
    	}
    }

    @TestVisible private static void setPreliminaryIssuesToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calculated_Preliminary_Signature__c != null) {
    			i.Start_Date__c = inv.Calculated_Preliminary_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (s.Calculated_Preliminary_Signature__c != null) {
    			i.Start_Date__c = s.Calculated_Preliminary_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == LITIGATION) {
    		Litigation__c l = litigationParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(l.Id) == INT_LITIGATION) {
    			if (l.Calculated_Preliminary_Signature__c != null) {
    				i.Start_Date__c = l.Calculated_Preliminary_Signature__c;
	    		}
    		} else if (parentIdToRecordTypeNameMap.get(l.Id) == REMAND) {
    			if (l.Calculated_Draft_Remand_release_to_party__c != null) {
    				i.Start_Date__c = l.Calculated_Draft_Remand_release_to_party__c;
	    		}
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_PRELIMINARY);
        }
    }

    @TestVisible private static void setAmendedPreliminaryIssuesToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calc_Amended_Prelim_Determination_Sig__c != null) {
    			i.Start_Date__c = inv.Calc_Amended_Prelim_Determination_Sig__c;
    			i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_AMENDED_PRELIMINARY);
    		}
    	}
    }

    @TestVisible private static void setFinalIssuesToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calculated_Final_Signature__c != null) {
    			i.Start_Date__c = inv.Calculated_Final_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (s.Calculated_Final_Signature__c != null) {
    			i.Start_Date__c = s.Calculated_Final_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == LITIGATION) {
    		Litigation__c l = litigationParents.get(parentId);
    		if (l.Calculated_Final_Signature__c != null) {
    			i.Start_Date__c = l.Calculated_Final_Signature__c;
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_FINAL);
        }
    }

    @TestVisible private static void setAmendedFinalIssuesToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calculated_Amended_Final_Signature__c != null) {
    			i.Start_Date__c = inv.Calculated_Amended_Final_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == ADMIN_REVIEW
    			|| parentIdToRecordTypeNameMap.get(s.Id) == EXPEDITED_REVIEW
    			|| parentIdToRecordTypeNameMap.get(s.Id) == NEW_SHIPPER_REVIEW
    			) {
    			if (s.Calculated_Amended_Final_Signature__c != null) {
    				i.Start_Date__c = s.Calculated_Amended_Final_Signature__c;
	    		}
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_AMENDED_FINAL);
        }
    }

    @TestVisible private static void setDeadlineForDecisionHOPIssuesToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == SCOPE_INQUIRY) {
    			if (s.Deadline_for_Decision_on_How_to_Proceed__c != null) {
    				i.Start_Date__c = s.Deadline_for_Decision_on_How_to_Proceed__c;
	    			i.Issues_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, ISSUES_DEADLINE_FOR_HOP);
	    		}
    		}
    	}
    }

    /**************************************
    * All Concurrence To DAS Calculations
    **************************************/

    @TestVisible private static void setInitiationConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == PETITION) {
    		Petition__c p = petitionParents.get(parentId);
    		if (p.Calculated_Initiation_Signature__c != null) {
                i.Start_Date__c = p.Calculated_Initiation_Signature__c;
    			i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_PETITION_INITIATION);
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == ANTI_CIRCUMVENTION_REVIEW
				|| parentIdToRecordTypeNameMap.get(s.Id) == CHANGED_CIRCUMSTANCES_REVIEW
				) {
    			if (s.Calculated_Initiation_Signature__c != null) {
                    i.Start_Date__c = s.Calculated_Initiation_Signature__c;
	    		}
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == LITIGATION) {
    		Litigation__c l = litigationParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(l.Id) == INT_LITIGATION) {
    			if (l.Calculated_Initiation_Signature__c != null) {
                    i.Start_Date__c = l.Calculated_Initiation_Signature__c;
	    		}
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_INITIATION);
        }
    }

    @TestVisible private static void setPreliminaryConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calculated_Preliminary_Signature__c != null) {
                i.Start_Date__c = inv.Calculated_Preliminary_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (s.Calculated_Preliminary_Signature__c != null) {
                i.Start_Date__c = s.Calculated_Preliminary_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == LITIGATION) {
    		Litigation__c l = litigationParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(l.Id) == INT_LITIGATION) {
    			if (l.Calculated_Preliminary_Signature__c != null) {
                    i.Start_Date__c = l.Calculated_Preliminary_Signature__c;
	    		}
    		} else if (parentIdToRecordTypeNameMap.get(l.Id) == REMAND) {
    			if (l.Calculated_Draft_Remand_release_to_party__c != null) {
                    i.Start_Date__c = l.Calculated_Draft_Remand_release_to_party__c;
	    		}
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_PRELIMINARY);
        }
    }

    @TestVisible private static void setAmendedPreliminaryConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calc_Amended_Prelim_Determination_Sig__c != null) {
    			i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_AMENDED_PRELIMINARY);
    		}
    	}
    }

    @TestVisible private static void setFinalConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calculated_Final_Signature__c != null) {
                i.Start_Date__c = inv.Calculated_Final_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (s.Calculated_Final_Signature__c != null) {
                i.Start_Date__c = s.Calculated_Final_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == LITIGATION) {
    		Litigation__c l = litigationParents.get(parentId);
    		if (l.Calculated_Final_Signature__c != null) {
                i.Start_Date__c = l.Calculated_Final_Signature__c;
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_FINAL);
        }
    }

    @TestVisible private static void setAmendedFinalConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == INVESTIGATION) {
    		Investigation__c inv = investigationParents.get(parentId);
    		if (inv.Calculated_Amended_Final_Signature__c != null) {
                i.Start_Date__c = inv.Calculated_Amended_Final_Signature__c;
    		}
    	} else if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == ADMIN_REVIEW
    			|| parentIdToRecordTypeNameMap.get(s.Id) == EXPEDITED_REVIEW
    			|| parentIdToRecordTypeNameMap.get(s.Id) == NEW_SHIPPER_REVIEW
    			) {
    			if (s.Calculated_Amended_Final_Signature__c != null) {
                    i.Start_Date__c = s.Calculated_Amended_Final_Signature__c;
	    		}
    		}
    	}
        if (i.Start_Date__c != null) {
            i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_AMENDED_FINAL);
        }
    }

    @TestVisible private static void setDeadlineForDecisionHOPConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == SCOPE_INQUIRY) {
    			if (s.Deadline_for_Decision_on_How_to_Proceed__c != null) {
                    i.Start_Date__c = s.Deadline_for_Decision_on_How_to_Proceed__c;
	    			i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_DEADLINE_FOR_HOP);
	    		}
    		}
    	}
    }

    @TestVisible private static void setContinuationOrRevocationConcurrenceToDAS(Id parentId, Issue__c i) {
    	if (parentIdToObjectTypeMap.get(parentId) == SEGMENT) {
    		Segment__c s = segmentParents.get(parentId);
    		if (parentIdToRecordTypeNameMap.get(s.Id) == SUNSET_REVIEW) {
    			if (s.Continuation_or_Revocation_FR_Notice_Pub__c != null) {
    				i.Start_Date__c = s.Continuation_or_Revocation_FR_Notice_Pub__c;
	    			i.Concurrence_to_DAS__c = ADCVD_TollingDayUtility.countBackBusinessDays(i.Start_Date__c, CONCURRENCE_CONT_OR_REVO);
	    		}
    		}
    	}
    }
}