src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country Text</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Recusal__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type_Text__c</fullName>
        <label>ADCVD Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actor_End_Date__c</fullName>
        <label>Acting User End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actor_Start_Date__c</fullName>
        <label>Acting User Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acting User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Recusals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBP_Case_Number_Text__c</fullName>
        <label>CBP Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commodity_Text__c</fullName>
        <label>Commodity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>DATEVALUE(&apos;2099-01-02&apos;)</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Short_Name_Text__c</fullName>
        <label>Product Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Text__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Recusal__c</fullName>
        <label>Reason for Recusal</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Organization</label>
        <referenceTo>Related_Organization__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recusal</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Recusal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recusals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecusalSelector.cls
public class RecusalSelector extends fflibext_SObjectSelector implements IRecusalSelector {

    public static IRecusalSelector newInstance() {
        return (IRecusalSelector) fflibext_Application.Selector.newInstance(Recusal__c.SObjectType);
    }

    @TestVisible private Schema.sObjectType getSObjectType() {
        return Recusal__c.SObjectType;
    }

    private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
        return new List<Schema.SObjectField>
        {
            Recusal__c.Actor__c,
            Recusal__c.Actor_End_Date__c,
            Recusal__c.Actor_Start_Date__c,
            Recusal__c.ADCVD_Case__c,
            Recusal__c.ADCVD_Case_Number_Text__c,
            Recusal__c.ADCVD_Case_Type_Text__c,
            Recusal__c.CBP_Case_Number_Text__c,
            Recusal__c.Commodity_Text__c,
            Recusal__c.Country_Text__c,
            Recusal__c.End_Date__c,
            Recusal__c.Product_Text__c,
            Recusal__c.Product_Short_Name_Text__c,
            Recusal__c.Reason_for_Recusal__c,
            Recusal__c.Locked__c,
            Recusal__c.Recusal_Parent__c,
            Recusal__c.Related_Organization__c,
            Recusal__c.Start_Date__c,
            Recusal__c.User__c
        };
    }
    public List<Recusal__c> selectById(Set<Id> idSet) {
        return (List<Recusal__c>) selectSObjectsById(idSet);
    }

    public List<Recusal__c> selectByUserAndNoCase(Set<Id> userIdSet) {
        return (List<Recusal__c>) Database.query(
            newQueryFactory()
            .selectField('ADCVD_Case__c')
            .selectField('Related_Organization__r.Account__c')
            .setCondition(Recusal__c.ADCVD_Case__c + ' = null AND ' + Recusal__c.User__c + ' in :userIdSet')
            .toSOQL()
        );
    }
}