src/objects/ADCVD_Objects__mdt.object
<CustomObject>
    <description>This holds the object types, record types, and a type field (if present) delineating a difference in records for the ADCVD app</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Petition__c</fullName>
                    <default>true</default>
                    <label>Petition__c</label>
                </value>
                <value>
                    <fullName>Investigation__c</fullName>
                </value>
                <value>
                    <fullName>ADCVD_Order__c</fullName>
                </value>
                <value>
                    <fullName>Segment__c</fullName>
                </value>
                <value>
                    <fullName>Litigation__c</fullName>
                </value>
                <value>
                    <fullName>Related_Organization__c</fullName>
                </value>
                <value>
                    <fullName>Federal_Register__c</fullName>
                </value>
                <value>
                    <fullName>Recusal__c</fullName>
                </value>
                <value>
                    <fullName>Staffing_Assignment__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                    <default>true</default>
                    <label>AD</label>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
                <value>
                    <fullName>Administrative_Review</fullName>
                </value>
                <value>
                    <fullName>Anti_Circumvention_Review</fullName>
                </value>
                <value>
                    <fullName>Changed_Circumstances_Review</fullName>
                </value>
                <value>
                    <fullName>Expedited_Review</fullName>
                </value>
                <value>
                    <fullName>New_Shipper_Review</fullName>
                </value>
                <value>
                    <fullName>Scope_Inquiry</fullName>
                </value>
                <value>
                    <fullName>Sunset_Review</fullName>
                </value>
                <value>
                    <fullName>International_Litigation</fullName>
                </value>
                <value>
                    <fullName>Remand</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Related</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Initiation/Prelim</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Petitioner</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Respondent</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Objects</label>
    <pluralLabel>ADCVD Objects</pluralLabel>
</CustomObject>

src/objects/Date_Calculation__mdt.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Date Calculations</relationshipLabel>
        <relationshipName>Date_Calculations</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Calculated_Date_Field_Name__c</fullName>
        <label>Calculated Date Field Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_of_Execution__c</fullName>
        <label>Order of Execution</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Date Calculation</label>
    <pluralLabel>Date Calculations</pluralLabel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amended Preliminary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amended Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>Issue-{00000000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DateCalculationSelector.cls
public without sharing class DateCalculationSelector {

	public static Map<String,List<SObject>> allRecordsMap {
		get {
			if (allRecordsMap == null) {
				allRecordsMap = new Map<String,List<SObject>>();
				allRecordsMap.put('Petition__c', PetitionSelector.allPetitions);
				allRecordsMap.put('Investigation__c', InvestigationSelector.allInvestigations);
				allRecordsMap.put('Issue__c', IssueSelector.allIssues);
			}
			return allRecordsMap;
		} set;
	}

	public static Map<ID,ADCVD_FederalRegisterUtility> getFrUtilMap(List<SObject> soList) {
		ADCVD_FederalRegisterUtility listInstance = ADCVD_FederalRegisterUtility.getInstance(soList);
		Map<ID,ADCVD_FederalRegisterUtility> frUtilMap = listInstance.utilMap;
		return frUtilMap;
	}

	public static Map<String,Date> getFrDateMap(List<SObject> soList) {
		ADCVD_FederalRegisterUtility listInstance = ADCVD_FederalRegisterUtility.getInstance(soList);
		Map<String,Date> frDateMap = listInstance.varMap;
		return frDateMap;
	}

	public static Map<Id,SObject> getSObjectsInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,SObject> returnMap = new Map<Id,SObject>();
		Set<Id> tempIdSet = new Set<Id>();
		if (lookupFieldName == null) {return returnMap;}
		for (SObject so : Utils.castRecordsToType(soList, soType)) {
			tempIdSet.add((Id)so.get(lookupFieldName));
		}
		for (SObject so : allRecordsMap.get(soType)) {
			if (tempIdSet.contains(so.Id)) {
				returnMap.put(so.Id, so);
			}
		}
		return returnMap;
	}
/*
	public static Map<Id,Petition__c> getPetitionsInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Petition__c> returnMap = new Map<Id,Petition__c>();
		System.debug('*** getPetitionsInScope soList: ' + soList);
		Set<Id> tempIdSet = new Set<Id>();
		List<SObject> castRecords = castRecordsToType(soList, soType);
		for (SObject so : castRecordsToType(soList, soType)) {
			tempIdSet.add((Id)so.get(lookupFieldName));
		}
		for (Petition__c p : allPetitions) {
			if (tempIdSet.contains(p.Id)) {
				returnMap.put(p.Id, p);
			}
		}
		return returnMap;
	}

	public static Map<Id,Investigation__c> getInvestigationsInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Investigation__c> returnMap = new Map<Id,Investigation__c>();
		Set<Id> tempIdSet = new Set<Id>();
		List<SObject> castRecords = castRecordsToType(soList, soType);
		for (SObject so : castRecords) {
			tempIdSet.add((Id)so.get(lookupFieldName));
		}
		for (Investigation__c i : allInvestigations) {
			if (tempIdSet.contains(i.Id)) {
				returnMap.put(i.Id, i);
			}
		}
		return returnMap;
	}
*/
	public static Map<Id,SObject> getIssuesInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,SObject> returnMap = new Map<Id,SObject>();
		Set<Id> tempIdSet = new Set<Id>();
		List<SObject> castRecords = Utils.castRecordsToType(soList, soType);
		for (SObject so : castRecords) {
			tempIdSet.add((Id)so.get('Id'));
		}
		for (SObject so : castRecords) {
			if (tempIdSet.contains((Id)so.get(lookupFieldName))) {
				returnMap.put(so.Id, so);
			}
		}
		return returnMap;
	}

	public static Map<Id,Issue__c> getCompletedIssuesInScope(List<SObject> soList, String soType, String lookupFieldName) {
		Map<Id,Issue__c> returnMap = (Map<Id,Issue__c>)getIssuesInScope(soList, soType, lookupFieldName);
		Map<Id,Map<String,Boolean>> parentIdToCompletedIssues = getCompletedIssues(soList, lookupFieldName);
		for(Id i : returnMap.keySet()) {
			if (!parentIdToCompletedIssues.containsKey(i) || !parentIdToCompletedIssues.get(i).get(returnMap.get(i).Type__c)) {
				returnMap.remove(i);
			}
		}
		return returnMap;
	}

	public static Map<Id,Map<String,Boolean>> getCompletedIssues(List<SObject> soList, String lookupFieldName) {
		Map<Id,Map<String,Boolean>> parentIdToCompletedIssues = new Map<Id,Map<String,Boolean>>();
		Set<Id> tempIdSet = new Set<Id>();
		for (SObject so : soList) {
			if (so.get('Id') != null) {
				tempIdSet.add((Id)so.get('Id'));
			}
		}
		for (Issue__c i : IssueSelector.allIssues) {
			Map<String,Boolean> tempMap = new Map<String,Boolean>();
			if (tempIdSet.contains((Id)i.get(lookupFieldName))) {
				if (tempMap.get(i.Type__c) == null || tempMap.get(i.Type__c) == true) {
					tempMap.put(i.Type__c, i.Completed_Issue__c);
					parentIdToCompletedIssues.put((Id)i.get(lookupFieldName), tempMap);
				}
			}
		}
		return parentIdToCompletedIssues;
	}

	public static Map<String,Date_Calculation__mdt> getDateCalculationsMap(String soType, String recordType) {
		Map<Integer, Date_Calculation__mdt> tempMap = new Map<Integer, Date_Calculation__mdt>();
		Map<String,Date_Calculation__mdt> returnMap = new Map<String,Date_Calculation__mdt>();
		for (Date_Calculation__mdt dc : CustomMetadataSelector.allDateCalculations) {
			if (dc.ADCVD_Objects__r.Object_API_Name__c == soType && 
				(String.isBlank(recordType) || dc.ADCVD_Objects__r.Record_Type_Name__c == recordType)) {
				tempMap.put((Integer)dc.Order_of_Execution__c, dc);
			}
		}
		for (Integer i = 0; i < 100; i++) {
			if (tempMap.get(i) != null) {
				returnMap.put(tempMap.get(i).Calculated_Date_Field_Name__c, tempMap.get(i));
			}
		}
		return returnMap;
	}
}