src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suspension_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suspension Agreement</label>
        <referenceTo>Suspension_Agreement__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suspension_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suspension Agreement</label>
        <referenceTo>Suspension_Agreement__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field displays the Type of Suspension Agreement</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD - 734(b) - Cessation of Exports</fullName>
                </value>
                <value>
                    <fullName>AD - 734(b) - Normal Value</fullName>
                </value>
                <value>
                    <fullName>AD - 734(c) - Reference Price</fullName>
                </value>
                <value>
                    <fullName>AD - 734(l) - NME</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(b) - Elimination of Subsidy</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(b) - Cessation of Exports</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(c) - Other than Quantitative Restriction</fullName>
                </value>
                <value>
                    <fullName>CVD - 704(c) - Quantitative Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FederalRegisterSelector.cls
public without sharing class FederalRegisterSelector {

  /**
   * This is a selector class to hold Federal Register information for the execution cycle.
   *
   * Example of normal execution cycle:
   * A trigger, such as InvestigationTriggerHandler will reference the FederalRegisterMapper.
   * The FederalRegisterMapper will call the FederalRegisterSelector.
   * The FederalRegisterSelector will retrieve data from the ADCVD_CaseSelector class and via SOQL, storing the data for reference during a transaction.
   * The FederalRegisterMapper then uses the retrieved data and maps it in inner classes and a map called masterMap.
   * The FederalRegisterMapper masterMap is then utilized by the InvestigationTriggerHandler.
   *
   */

  /**
   * The first Id in the caseIdToFRMap is the Id of the ADCVD Case.
   * The inner map is the Id of the Federal Register and then the Federal Register itself.
   */
  @TestVisible private static Map<Id, Map<Id, Federal_Register__c>> caseIdToFRMap = new Map<Id, Map<Id, Federal_Register__c>>();  //Id is the Case Id

  /**
   * The first Id in the parentIdToFRMap is the Id of the Petition, Investigation, ADCVD Order, Suspension Agreement, or Segment
   * The inner map is the Id of the Federal Register and then the Federal Register itself.
   */
  public static Map<Id, Map<Id, Federal_Register__c>> parentIdToFRMap = new Map<Id, Map<Id, Federal_Register__c>>();

  /**
   * Populate the maps caseIdToFRMap and parentIdToFRMap based on case Ids in scope.
   */
  static {
    //Only populate the maps if they haven't already been populated.
    if (caseIdToFRMap.isEmpty() || parentIdToFRMap.isEmpty()) {
      //Get the Case Ids in Scope
      Set<Id> caseIdsInScope = ADCVD_CaseSelector.idToCaseMap.keySet();  //idToCaseMap is Map<Id, ADCVD_Case__c> where Id is the Case Id

      //Create a temporary map
      Map<Id, Federal_Register__c> tempFRMap;

      //Retrieve Federal Registers based on the Case Ids in Scope
      for (Federal_Register__c fr : [
          SELECT Id, Type__c, Published_Date__c, Segment__c, Segment__r.ADCVD_Order__c,
              Investigation__c, Petition__c, CreatedDate, ADCVD_Order__c, ADCVD_Order__r.Investigation__c,
              Suspension_Agreement__c, Suspension_Agreement__r.Investigation__c, Do_Delete__c, ADCVD_Case__c
          FROM Federal_Register__c
          WHERE ADCVD_Case__c IN :caseIdsInScope
      ]) {
        //Populate the maps with each Federal Register returned
        if (fr.Petition__c != null) {
          //This Federal Register is for a Petition
          //Get the map in the parentIdToFRMap if this Petition is already in the map.  Otherwise, create a new map.
          Map<Id, Federal_Register__c> tempMap = parentIdToFRMap.containsKey(fr.Petition__c)
              ? parentIdToFRMap.get(fr.Petition__c) : new Map<Id, Federal_Register__c>();
          tempMap.put(fr.Id, fr);
          parentIdToFRMap.put(fr.Petition__c, tempMap);
        } else if (fr.Investigation__c != null) {
          //This Federal Register is for an Investigation
          //Get the map in the parentIdToFRMap if this Investigation is already in the map.  Otherwise, create a new map.
          Map<Id, Federal_Register__c> tempMap = parentIdToFRMap.containsKey(fr.Investigation__c)
              ? parentIdToFRMap.get(fr.Investigation__c) : new Map<Id, Federal_Register__c>();
          tempMap.put(fr.Id, fr);
          parentIdToFRMap.put(fr.Investigation__c, tempMap);
        } else if (fr.ADCVD_Order__c != null) {
          //This Federal Register is for an ADCVD Order
          //Get the map in the parentIdToFRMap if this ADCVD Order is already in the map.  Otherwise, create a new map.
          Map<Id, Federal_Register__c> tempMap = parentIdToFRMap.containsKey(fr.ADCVD_Order__c)
              ? parentIdToFRMap.get(fr.ADCVD_Order__c) : new Map<Id, Federal_Register__c>();
          tempMap.put(fr.Id, fr);
          parentIdToFRMap.put(fr.ADCVD_Order__c, tempMap);
        } else if (fr.Suspension_Agreement__c != null) {
          //This Federal Register is for a Suspension Agreement
          //Get the map in the parentIdToFRMap if this Suspension Agreement is already in the map.  Otherwise, create a new map.
          Map<Id, Federal_Register__c> tempMap = parentIdToFRMap.containsKey(fr.Suspension_Agreement__c)
              ? parentIdToFRMap.get(fr.Suspension_Agreement__c) : new Map<Id, Federal_Register__c>();
          tempMap.put(fr.Id, fr);
          parentIdToFRMap.put(fr.Suspension_Agreement__c, tempMap);
        } else if (fr.Segment__c != null) {
          //This Federal Register is for a Segment
          //Get the map in the parentIdToFRMap if this Segment is already in the map.  Otherwise, create a new map.
          Map<Id, Federal_Register__c> tempMap = parentIdToFRMap.containsKey(fr.Segment__c)
              ? parentIdToFRMap.get(fr.Segment__c) : new Map<Id, Federal_Register__c>();
          tempMap.put(fr.Id, fr);
          parentIdToFRMap.put(fr.Segment__c, tempMap);
        }
        tempFRMap = new Map<Id, Federal_Register__c>();
        tempFRMap.put(fr.Id, fr);
        caseIdToFRMap.put(fr.ADCVD_Case__c, tempFRMap);
      }
    }
  }
}