src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country Text</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Litigation__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Due_to_DAS_Deadline__c</fullName>
        <label>Next Due to DAS Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Office_Deadline__c</fullName>
        <label>Next Office Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by a Schedulable class to cause the Tolling Date Service to recalculate tolling days whenever a calculated announcement date is equal to &quot;yesterday when the associated trigger calculates the next announcement date.</description>
        <inlineHelpText>Hidden field used by system</inlineHelpText>
        <label>Schedule Refresh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litigation</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Litigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Referenced from parent Petition</description>
        <label>Country Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Iran</fullName>
                </value>
                <value>
                    <fullName>Iraq</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Due_to_DAS_Deadline__c</fullName>
        <label>Next Due to DAS Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Office_Deadline__c</fullName>
        <label>Next Office Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by a Schedulable class to cause the Tolling Date Service to recalculate tolling days whenever a calculated announcement date is equal to &quot;yesterday when the associated trigger calculates the next announcement date.</description>
        <inlineHelpText>For system use only.</inlineHelpText>
        <label>Schedule Refresh</label>
        <type>Checkbox</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Due_to_DAS_Deadline__c</fullName>
        <description>Next Due to DAS Deadline and Timeline on Segment</description>
        <inlineHelpText>Next Due to DAS Deadline and Timeline on Segment</inlineHelpText>
        <label>Next Due to DAS Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Office_Deadline__c</fullName>
        <description>Next Office/PM Deadline and Timeline on Segment</description>
        <inlineHelpText>Next Office/PM Deadline and Timeline on Segment</inlineHelpText>
        <label>Next Office Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by a Schedulable class to cause the Tolling Date Service to recalculate tolling days whenever a calculated announcement date is equal to &quot;yesterday when the associated trigger calculates the next announcement date.</description>
        <inlineHelpText>For system use only.</inlineHelpText>
        <label>Schedule Refresh</label>
        <type>Checkbox</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/classes/ScheduleRecordRefreshTest.cls
/**
 *
 *    Created by Skip Kleckner
 *    on June 13 2019
 *    MIL Corporation
 *
 **/

@IsTest
public class ScheduleRecordRefreshTest {

	private static List<ADCVD_Case__c> adcvdCaseList { get; set; }
	private static List<Petition__c> petitionList { get; set; }
	private static List<Investigation__c> investigationList { get; set; }
	private static List<ADCVD_Order__c> orderList { get; set; }
	private static List<Litigation__c> litigationList { get; set; }
	private static List<Segment__c> segmentList { get; set; }

	@IsTest
	static void testRefreshDueDates() {
		dataSetup();
		selectorSetup();
		Test.startTest();

		ADCVD_Case__c c = adcvdCaseList.get(0);
		Petition__c p = petitionList.get(0);
		ADCVD_Order__c o = orderList.get(0);
		Investigation__c i = investigationList.get(0);
		Litigation__c l = litigationList.get(0);
		Segment__c s = segmentList.get(0);

		ScheduleRecordsRefresh srr = new ScheduleRecordsRefresh();
		srr.refreshDueDates();

		System.assertEquals(1, srr.petitionsToRefresh.size());
		System.assertEquals(1, srr.segmentsToRefresh.size());
		System.assertEquals(1, srr.investigationsToRefresh.size());
		System.assertEquals(1, srr.litigationsToRefresh.size());
		System.assertEquals(1, srr.caseIdSet.size());

		System.assertEquals(true, srr.petitionsToRefresh.get(0).Schedule_Refresh__c);
		System.assertEquals(false, srr.segmentsToRefresh.get(0).Schedule_Refresh__c);
		System.assertEquals(true, srr.investigationsToRefresh.get(0).Schedule_Refresh__c);
		System.assertEquals(true, srr.litigationsToRefresh.get(0).Schedule_Refresh__c);

		Test.stopTest();
	}

	@testSetup static void dataSetup() {
		TestUtils.createAppConfig('default', true, true);
		// Create ADCVD_Case record
		adcvdCaseList = new List<ADCVD_Case__c>();
		adcvdCaseList.add(
				new ADCVD_Case__c(
						Id = fflib_IdGenerator.generate(ADCVD_Case__c.SObjectType),
						Locked__c = false,
						Country__c = 'Mexico'
				)
		);

		//Create Petition record
		petitionList = new List<Petition__c>();
		petitionList.add(
				new Petition__c(
						Id = fflib_IDGenerator.generate(Petition__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Country_Text__c = 'Mexico',
						Schedule_Refresh__c = false,
						Next_Announcement_Date__c = System.today().addDays(-1),
						Next_Due_to_DAS_Deadline__c = System.today().addDays(-1),
						Next_Office_Deadline__c = System.today().addDays(-1)
				)
		);

		//Create Investigation record
		investigationList = new List<Investigation__c>();
		investigationList.add(
				new Investigation__c(
						Id = fflib_IDGenerator.generate(Investigation__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Petition__c = petitionList[0].Id,
						Schedule_Refresh__c = false,
						Next_Announcement_Date__c = System.today().addDays(-1),
						Next_Due_to_DAS_Deadline__c = System.today().addDays(-1),
						Next_Office_Deadline__c = System.today().addDays(-1)
				)
		);

		//Create ADCVD Order record
		orderList = new List<ADCVD_Order__c>();
		orderList.add(
				new ADCVD_Order__c(
						Id = fflib_IDGenerator.generate(ADCVD_Order__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Investigation__c = investigationList[0].Id
				)
		);

		//Create Litigation record
		litigationList = new List<Litigation__c>();
		litigationList.add(
				new Litigation__c(
						Id = fflib_IDGenerator.generate(Litigation__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Schedule_Refresh__c = false,
						Next_Announcement_Date__c = System.today().addDays(-1),
						Next_Due_to_DAS_Deadline__c = System.today().addDays(-1),
						Next_Office_Deadline__c = System.today().addDays(-1)

				)
		);

		//Create Segment record
		segmentList = new List<Segment__c>();
		segmentList.add(
				new Segment__c(
						Id = fflib_IDGenerator.generate(Segment__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Schedule_Refresh__c = true,
						Next_Announcement_Date__c = System.today().addDays(-1),
						Next_Due_to_DAS_Deadline__c = System.today().addDays(-1),
						Next_Office_Deadline__c = System.today().addDays(-1)

				)
		);

		//Create relationship between ADCVD_Case and Petition
		adcvdCaseList = (List<ADCVD_Case__c>) fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Petition__c.ADCVD_Case__c,
				new List<List<Petition__c>>{
						petitionList
				}
		);

		//Create relationship between ADCVD_Case and Investigation
		adcvdCaseList = (List<ADCVD_Case__c>) fflib_ApexMocksUtils.makeRelationship(List<ADCVD_Case__c>.class, adcvdCaseList, Investigation__c.ADCVD_Case__c, new List<List<Investigation__c>>{investigationList} );

		//Create relationship between ADCVD_Case and ADCVD Order
		adcvdCaseList = (List<ADCVD_Case__c>) fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				ADCVD_Order__c.ADCVD_Case__c,
				new List<List<ADCVD_Order__c>>{
						orderList
				}
		);

		//Create relationship between ADCVD_Case and Litigation
		adcvdCaseList = (List<ADCVD_Case__c>) fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Litigation__c.ADCVD_Case__c,
				new List<List<Litigation__c>>{
						litigationList
				}
		);
		//Create relationship between ADCVD_Case and Segment
		adcvdCaseList = (List<ADCVD_Case__c>) fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Segment__c.ADCVD_Case__c,
				new List<List<Segment__c>>{
						segmentList
				}
		);

		//Create relationship between Petition and Investigation
		petitionList = (List<Petition__c>) fflib_ApexMocksUtils.makeRelationship(
				List<Petition__c>.class,
				petitionList,
				Investigation__c.Petition__c,
				new List<List<Investigation__c>>{
						investigationList
				}
		);
		//Create relationship between Investigation and ADCVD Order
		investigationList = (List<Investigation__c>) fflib_ApexMocksUtils.makeRelationship(
				List<Investigation__c>.class,
				investigationList,
				ADCVD_Order__c.Investigation__c,
				new List<List<ADCVD_Order__c>>{
						orderList
				}
		);
	}

	private static void selectorSetup() {
		fflib_ApexMocks mocks = new fflib_ApexMocks();
		//Mock ADCVD Case Selector
		ADCVD_ICaseSelector mockADCVD_CaseSelector = (ADCVD_ICaseSelector) mocks.mock(ADCVD_ICaseSelector.class);
		mocks.startStubbing();
		mocks.when(mockADCVD_CaseSelector.sObjectType()).thenReturn(ADCVD_Case__c.SObjectType);
		mocks.when(mockADCVD_CaseSelector.selectByIdWithRelations(new Set<Id>{adcvdCaseList[0].Id})).thenReturn(adcvdCaseList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockADCVD_CaseSelector);

		//Mock Petition Selector
		IPetitionSelector mockPetitionSelector = (IPetitionSelector) mocks.mock(IPetitionSelector.class);
		mocks.startStubbing();
		mocks.when(mockPetitionSelector.sObjectType()).thenReturn(Petition__c.SObjectType);
		mocks.when(mockPetitionSelector.selectByWhereClause(ScheduleRecordsRefresh.wc)).thenReturn(petitionList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockPetitionSelector);

		//Mock Investigation Selector
		IInvestigationSelector mockInvestigationSelector = (IInvestigationSelector) mocks.mock(IInvestigationSelector.class);
		mocks.startStubbing();
		mocks.when(mockInvestigationSelector.sObjectType()).thenReturn(Investigation__c.SObjectType);
		mocks.when(mockInvestigationSelector.selectByWhereClause(ScheduleRecordsRefresh.wc)).thenReturn(investigationList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockInvestigationSelector);

		//Mock ADCVD Order Selector
		ADCVD_IOrderSelector mockADCVD_OrderSelector = (ADCVD_IOrderSelector) mocks.mock(ADCVD_IOrderSelector.class);
		mocks.startStubbing();
		mocks.when(mockADCVD_OrderSelector.sObjectType()).thenReturn(ADCVD_Order__c.SObjectType);
		mocks.when(mockADCVD_OrderSelector.selectById(new Set<Id>{orderList[0].Id})).thenReturn(orderList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockADCVD_OrderSelector);

		//Mock Litigation Selector
		ILitigationSelector mockLitigationSelector = (ILitigationSelector) mocks.mock(ILitigationSelector.class);
		mocks.startStubbing();
		mocks.when(mockLitigationSelector.sObjectType()).thenReturn(Litigation__c.SObjectType);
		mocks.when(mockLitigationSelector.selectByWhereClause(ScheduleRecordsRefresh.wc)).thenReturn(litigationList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockLitigationSelector);

		//Mock Segment Selector
		ISegmentSelector mockSegmentSelector = (ISegmentSelector) mocks.mock(ISegmentSelector.class);
		mocks.startStubbing();
		mocks.when(mockSegmentSelector.sObjectType()).thenReturn(Segment__c.SObjectType);
		mocks.when(mockSegmentSelector.selectByWhereClause(ScheduleRecordsRefresh.wc)).thenReturn(segmentList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockSegmentSelector);
	}
}