src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Recusal__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Recusals</relationshipLabel>
        <relationshipName>Recusals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recusal</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Recusal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recusals</pluralLabel>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <description>Primary recusals with details about the recusal</description>
        <label>Primary</label>
    </recordTypes>
    <recordTypes>
        <fullName>Related</fullName>
        <active>false</active>
        <description>Recusals that link a primary recusal and a record</description>
        <label>Related</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReviewRecusalExtensionTest.cls
@isTest
private class ReviewRecusalExtensionTest {
	static Petition__c p {
		get {
			if (p == null) {
				p = [SELECT Id FROM Petition__c LIMIT 1];
			}
			return p;
		} set;
	}
	static Investigation__c i {
		get {
			if (i == null) {
				i = [SELECT Id FROM Investigation__c LIMIT 1];
			}
			return i;
		} set;
	}
	static ADCVD_Order__c o {
        get {
            if (o == null) {
                o = [SELECT Id FROM ADCVD_Order__c LIMIT 1];
            }
            return o;
        } set;
    }
    static Segment__c s {
        get {
            if (s == null) {
                s = [SELECT Id FROM Segment__c LIMIT 1];
            }
            return s;
        } set;
    }
    static User u{
		get{
			if(u == null){
				u = [SELECT Id, ProfileId, isActive, Alias, LanguageLocaleKey, LastName, FirstName, 
								Email, EmailEncodingKey, TimeZoneSidKey, CommunityNickname, Username 
							FROM User WHERE LastName =: 'LastName1' LIMIT 1];
			}
			return u;
		} set;
	}
	static ReviewRecusalExtension ext;
  	static PageReference pageRef;
  	static ApexPages.StandardController con;

	@isTest static void primaryRecusalTest() {
        Test.startTest();
		primaryRecusalSetup();
		System.assertNotEquals(null, ext.parentFieldNames);
		ext.cancel();

        Test.stopTest();
	}
	@isTest static void relatedRecusalTest() {
        Test.startTest();
		relatedRecusalSetup();
		System.assertNotEquals(null, ext.parentFieldNames);
		ext.cancel();

        Test.stopTest();
	}
    @isTest static void uxContext() {
    	Test.startTest();
    	primaryRecusalSetup();
    	
    	Test.stopTest();
    	System.assertNotEquals(null, ext.isSalesforce1);
    	System.assertNotEquals(null, ext.isLightningExperience);
    	System.assertNotEquals(null, ext.isSalesforceClassic);
    }
	
	@testSetup static void dataSetup() {
        Test.startTest();
        p = TestUtils.createPetition(System.today().addDays(-280), 'AD ME', true);
        i = TestUtils.createInvestigation('AD', p, true);
        o = TestUtils.createOrder(i, true);
        s = TestUtils.createSegment(o, 'Administrative_Review', true);
        u = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
    } 
    private static void primaryRecusalSetup(){
		pageRef = Page.ReviewRecusalPage;
        pageRef.getParameters().put('parentId', p.Id);
        pageRef.getParameters().put('userId', u.Id);
        pageRef.getParameters().put('retURL', 'apex/'+ p.Id);
        test.setCurrentPage(pageRef);
        Recusal__c r = TestUtils.createRecusal(u.Id, System.today(), System.today().addDays(3), true);
        con = new ApexPages.StandardController(r);
    	ext = new ReviewRecusalExtension(con);
	}
	private static void relatedRecusalSetup(){
		pageRef = Page.ReviewRecusalPage;
        pageRef.getParameters().put('parentId', p.Id);
        pageRef.getParameters().put('userId', u.Id);
        pageRef.getParameters().put('retURL', 'apex/'+ p.Id);
        test.setCurrentPage(pageRef);
        Recusal__c primary = TestUtils.createRecusal(u.Id, System.today(), System.today().addDays(3), true);
        Recusal__c related = TestUtils.createRecusal(primary.Id, p.Id, 'Petition__c', true);
        con = new ApexPages.StandardController(related);
    	ext = new ReviewRecusalExtension(con);
	}
}