src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Custom_Instruction__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Custom Instructions</relationshipLabel>
        <relationshipName>Custom_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Custom Instruction</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Custom Instruction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <formula>TEXT(ADCVD_Case__r.ADCVD_Case_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ADCVD Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Harmonized_Tariff_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <formula>TEXT(ADCVD_Case__r.ADCVD_Case_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ADCVD Case Type Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Harmonized Tariff Schedules</relationshipLabel>
        <relationshipName>Harmonized_Tariff_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Deprecated</label>
        <type>Text</type>
    </fields>
    <label>Harmonized Tariff Schedule</label>
    <nameField>
        <label>Harmonized Tariff Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harmonized Tariff Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Litigation__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <label>ADCVD Case Type</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Litigation</relationshipLabel>
        <relationshipName>Litigation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <label>Litigation</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Litigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litigation</pluralLabel>
    <recordTypes>
        <fullName>International_Litigation</fullName>
        <active>true</active>
        <label>International Litigation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <description>Referenced from parent Petition case</description>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <label>ADCVD Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <formula>TEXT(ADCVD_Case__r.ADCVD_Case_Type__c)</formula>
        <label>ADCVD Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staffing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <label>ADCVD Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Staffing Assignment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Staffing Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <formula>TEXT(ADCVD_Case__r.ADCVD_Case_Type__c)</formula>
        <label>ADCVD Case Type Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Colombia</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/classes/ADCVDStandardCaseFieldBatchTest.cls
@isTest
public class ADCVDStandardCaseFieldBatchTest {

    static ADCVD_Case__c adcvdCase{
        get{
            if(adcvdCase == null){
                adcvdCase = [SELECT Id, ADCVD_Case_Type__c, Country__c, Commodity__c, Product__c, Product_Short_Name__c,
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Petitions__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Investigations__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM ADCVD_Orders__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Segments__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Suspension_Agreements__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Litigation__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Federal_Registers__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Harmonized_Tariff_Schedules__r),
                            (SELECT Id,ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Staffing_Assignments__r),
                            (SELECT Id, ADCVD_Case__c, ADCVD_Case_Type_Text__c, Country_Text__c, Commodity_Text__c, Product_Text__c, Product_Short_Name_Text__c FROM Custom_Instructions__r) FROM ADCVD_Case__c];
            }
            return adcvdCase;
        }
        set;
    }

    @isTest static void testInitialRecordSetup(){
        //Records in the dataSetup method were all created with a specific field values
        adcvdCase = null;
        System.debug(adcvdCase);
        System.debug(adcvdCase.Petitions__r);
        //Assert petition standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Petitions__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert investigation standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Investigations__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert adcvd order standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert segment standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Segments__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Segments__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Segments__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Segments__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Segments__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert suspension agreement standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert litigation standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Litigation__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert HTS standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert federal register standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Federal_Registers__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert custom instruction standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Product_Text__c, adcvdCase.Product__c);

    }

    @isTest static void testCaseFieldsChange(){
        adcvdCase = null;
        //Update case fields
        adcvdCase.ADCVD_Case_Type__c = 'AD NME';
        adcvdCase.Commodity__c = 'Minerals';
        adcvdCase.Country__c = 'Colombia';
        adcvdCase.Product__c = 'New Product Name';
        adcvdCase.Product_Short_Name__c = 'NPN';
        update adcvdCase;

        Test.startTest();
        Database.executeBatch(new ADCVDStandardCaseFieldsBatch(new List<ADCVD_Case__c>{adcvdCase}));
        Test.stopTest();

        //Assert changes
        adcvdCase = null;
        //Assert petition standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Petitions__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Petitions__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert investigation standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Investigations__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Investigations__r[0].Product_Text__c, adcvdCase.Product__c);
       
        //Assert adcvd order standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.ADCVD_Orders__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert segment standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Segments__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Segments__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Segments__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Segments__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Segments__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert suspension agreement standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Suspension_Agreements__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert litigation standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Litigation__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Litigation__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert HTS standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Harmonized_Tariff_Schedules__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert federal register standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Federal_Registers__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Federal_Registers__r[0].Product_Text__c, adcvdCase.Product__c);

        //Assert custom instruction standardized case fields match adcvd case fields
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Commodity_Text__c, adcvdCase.Commodity__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Country_Text__c, adcvdCase.Country__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
        System.assertEquals(adcvdCase.Custom_Instructions__r[0].Product_Text__c, adcvdCase.Product__c);


        //Assert staffing assignment standardized case fields match adcvd case fields
        for(Staffing_Assignment__c staffingAssignment: adcvdCase.Staffing_Assignments__r){
            System.assertEquals(staffingAssignment.ADCVD_Case_Type_Text__c, adcvdCase.ADCVD_Case_Type__c);
            System.assertEquals(staffingAssignment.Commodity_Text__c, adcvdCase.Commodity__c);
            System.assertEquals(staffingAssignment.Country_Text__c, adcvdCase.Country__c);
            System.assertEquals(staffingAssignment.Product_Short_Name_Text__c, adcvdCase.Product_Short_Name__c);
            System.assertEquals(staffingAssignment.Product_Text__c, adcvdCase.Product__c);
        }

    }

    @testSetup static void dataSetup(){
        //create test data
       User testUser = TestUtils.createStaffingUser(true, 'myemail@email.com.testita', 1);

        System.runAs(testUser) {
            Master_Automation__c ma = TestUtils.createMasterAutomation(true, true, true);
            AppConfig__c ac = TestUtils.createAppConfig('ADCVDStandardCaseFieldsBatch', true, true);
            //create test data
         Account testAccount = TestUtils.createAccount(true);
       
            ADCVD_Case__c testADCase = TestUtils.createADCVDCase('A-123-123', 'AD ME', testUser,true);

            Petition__c testADPetition = TestUtils.createPetition(testADCase, System.today().addDays(-280), true);
        
        Investigation__c testADinvestigation = TestUtils.createInvestigation(testADPetition, true);
        ADCVD_Order__c testADOrder = TestUtils.createOrder(testADinvestigation, true);
        Suspension_Agreement__c suspensionAgreement = TestUtils.createSuspensionAgreement(testADinvestigation, Date.today(), true);
        Segment__c segment = TestUtils.createSegment(testADOrder, 'Administrative_Review', true);
        Litigation__c litigation = TestUtils.createLitigation(testADPetition.Id, 'Petition__c', Date.today(), 'International_Litigation', true);
        Test.startTest();
        Federal_Register__c federalRegister = TestUtils.createFR(testADOrder.Id, 'ADCVD_Order__c', Date.today(), 'Order', true);
        Related_Organization__c relatedOrganization = TestUtils.createRelatedOrg(testADPetition, false);
        relatedOrganization.ADCVD_Entity_Name__c = 'test entity';
        relatedOrganization.Account__c = testAccount.Id;
        relatedOrganization.ADCVD_Case__c = testADCase.Id;
       // insert relatedOrganization;
        //HTS records are created through the Controller on their parents object page, in order to have all the standardized case fields filled
        //The records in this test class need to be created through the same controller
        ApexPages.StandardController standardController = new ApexPages.StandardController(testADOrder);
        AttachmentWriterController newAttachmentWriterController = new AttachmentWriterController(standardController);
        newAttachmentWriterController.attachmentBody = 'This is the hts number 3425.3525';
        CreateHTSRecordsController htsRecordsController = new CreateHTSRecordsController(newAttachmentWriterController);
        Custom_Instruction__c customInstruction = TestUtils.createCustomInstruction('Investigation__c', testADinvestigation.Id, true);
        Test.stopTest();
        }

    }

}