src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country Text</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Referenced from parent Petition</description>
        <label>Country Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Iran</fullName>
                </value>
                <value>
                    <fullName>Iraq</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Suspension_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suspension Agreement</label>
        <referenceTo>Suspension_Agreement__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suspension_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number_Text__c</fullName>
        <label>ADCVD Case Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c)</formula>
        <label>Country Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Suspension Agreements</relationshipLabel>
        <relationshipName>Suspension_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Suspension Agreement</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Suspension Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/classes/RelatedOrganizationTriggerHandlerTest.cls
@isTest
public class RelatedOrganizationTriggerHandlerTest {
	private static List<ADCVD_Case__c> adcvdCaseList { get; set;}
	private static List<Petition__c> petitionList {get; set;}
	private static List<Investigation__c> investigationList {get; set;}
	private static List<ADCVD_Order__c> orderList {get; set;}
//	private static List<Suspension_Agreement__c> suspAgrmtList {get; set;}
	private static List<Segment__c> segmentList {get; set;}
	private static List<Related_Organization__c> relOrgList {get; set;}
	private static Map<Id,Related_Organization__c> relOrgMap {get; set;}

	@isTest static void testInitialize(){
		dataSetup();
		selectorSetup();
		RelatedOrganizationMapper relOrgMapper = new RelatedOrganizationMapper(new Set<Id> {
				relOrgList[0].Id,
				relOrgList[1].Id,
				relOrgList[2].Id,
				relOrgList[3].Id
		}
		);

		Test.startTest();
		RelatedOrganizationTriggerHandler.initialize(relOrgList, null);
		Test.stopTest();

		//Assert adcvd case records
		System.assertNotEquals(RelatedOrganizationTriggerHandler.caseMapper, null);
		System.assertEquals(relOrgList[0].IO_Parent__c, 'Petition__c');

	}

	@isTest static void testSetCaseValues(){
		dataSetup();
		selectorSetup();
		RelatedOrganizationMapper relOrgMapper = new RelatedOrganizationMapper(new Set<Id> {
				relOrgList[0].Id,
				relOrgList[1].Id,
				relOrgList[2].Id,
				relOrgList[3].Id
		}
		);

		Test.startTest();
		RelatedOrganizationTriggerHandler.mainEntry(relOrgList, null, true, true, false);
		Test.stopTest();

		//Assert adcvd case records
		System.assertEquals(adcvdCaseList[0].Country__c, relOrgList[0].Country_Text__c);
	}

	@isTest static void testAddNewROsToMapper() {
		dataSetup();
		selectorSetup();
		relOrgMap = new Map<Id, Related_Organization__c>();
		for (Related_Organization__c ro : relOrgList) {
			relOrgMap.put(ro.Id, ro);
		}

		Test.startTest();
		RelatedOrganizationTriggerHandler.mainEntry(relOrgList, relOrgMap, true, false, true);
		Test.stopTest();

		//Assert adcvd case records
		for (Related_Organization__c ro : relOrgList) {
			RelatedOrganizationMapper rom = (RelatedOrganizationMapper) ADCVD_CaseMapper.mapperMap.get('Related_Organization__c');
			System.assert(rom.getMap().containsKey(ro.Id));
		}

	}

	@IsTest
	static void exerciseTrigger() {

		ADCVD_Case__c c = TestUtils.createADCVDCase('A-123-123', 'AD ME', true);
		Petition__c p = TestUtils.createPetition(c, System.today(), true);
		Account a = new Account(name = 'Test Co');
		insert a;
		insert new Related_Organization__c(ADCVD_Case_Number_Text__c = '--This is a test--', IO_Parent__c = 'Petition__c', Petition__c = p.Id, Account__c = a.Id, ADCVD_Entity_Name__c = 'TestName');
	}

	private static void dataSetup() {
		// Create ADCVD_Case record
		adcvdCaseList = new List<ADCVD_Case__c>();
		adcvdCaseList.add(
				new ADCVD_Case__c(
						Id = fflib_IdGenerator.generate(ADCVD_Case__c.SObjectType),
						Locked__c = false,
						Country__c = 'Mexico'
				)
		);
		//Create Petition record
		petitionList = new List<Petition__c>();
		petitionList.add(
				new Petition__c(
						Id = fflib_IDGenerator.generate(Petition__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id
				)
		);
		//Create Investigation record
		investigationList = new List<Investigation__c>();
		investigationList.add(
				new Investigation__c(
						Id = fflib_IDGenerator.generate(Investigation__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Petition__c = petitionList[0].Id
				)
		);
		//Create ADCVD Order record
		orderList = new List<ADCVD_Order__c>();
		orderList.add(
				new ADCVD_Order__c(
						Id = fflib_IDGenerator.generate(ADCVD_Order__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Investigation__c = investigationList[0].Id
				)
		);
/*
		//Create Suspension Agreement record
		suspAgrmtList = new List<Suspension_Agreement__c>();
		suspAgrmtList.add(
				new Suspension_Agreement__c(
						Id = fflib_IDGenerator.generate(Suspension_Agreement__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						Investigation__c = investigationList[0].Id
				)
		);
*/
		//Create Segment record
		segmentList = new List<Segment__c>();
		segmentList.add(
				new Segment__c(
						Id = fflib_IDGenerator.generate(Segment__c.SObjectType),
						Locked__c = false,
						ADCVD_Case__c = adcvdCaseList[0].Id,
						ADCVD_Order__c = orderList[0].Id
				)
		);
		//Create Interested Organization records
		relOrgList = new List<Related_Organization__c>();
		relOrgList.add(
				new Related_Organization__c(
						Id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType),
						Locked__c = false,
						Petition__c = petitionList[0].Id
				)
		);
		relOrgList.add(
				new Related_Organization__c(
						Id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType),
						Locked__c = false,
						Investigation__c = investigationList[0].Id
				)
		);
		relOrgList.add(
				new Related_Organization__c(
						Id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType),
						Locked__c = false,
						ADCVD_Order__c = orderList[0].Id
				)
		);
//		relOrgList.add(
//				new Related_Organization__c(
//						Id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType),
//						Locked__c = false,
//						Suspension_Agreement__c = suspAgrmtList[0].Id
//				)
//		);
		relOrgList.add(
				new Related_Organization__c(
						Id = fflib_IDGenerator.generate(Related_Organization__c.SObjectType),
						Locked__c = false,
						Segment__c = segmentList[0].Id
				)
		);

		//Create relationship between ADCVD_Case and Petition
		adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Petition__c.ADCVD_Case__c,
				new List<List<Petition__c>>{petitionList}
		);
		//Create relationship between ADCVD_Case and Investigation
		adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Investigation__c.ADCVD_Case__c,
				new List<List<Investigation__c>>{investigationList}
		);
		//Create relationship between ADCVD_Case and ADCVD Order
		adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				ADCVD_Order__c.ADCVD_Case__c,
				new List<List<ADCVD_Order__c>>{orderList}
		);
/*
		//Create relationship between ADCVD_Case and Suspension Agreement
		adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Suspension_Agreement__c.ADCVD_Case__c,
				new List<List<Suspension_Agreement__c>>{suspAgrmtList}
		);
*/
		//Create relationship between ADCVD_Case and Segment
		adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Segment__c.ADCVD_Case__c,
				new List<List<Segment__c>>{segmentList}
		);
/*
		//Create relationship between ADCVD Case and Interested Organization
		adcvdCaseList = (List<ADCVD_Case__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Case__c>.class,
				adcvdCaseList,
				Related_Organization__c.ADCVD_Case__c,
				new List<List<Related_Organization__c>>{relOrgList}
		);
*/
		//Create relationship between Petition and Investigation
		petitionList = (List<Petition__c>)fflib_ApexMocksUtils.makeRelationship(
				List<Petition__c>.class,
				petitionList,
				Investigation__c.Petition__c,
				new List<List<Investigation__c>>{investigationList}
		);
		//Create relationship between Investigation and ADCVD Order
		investigationList = (List<Investigation__c>)fflib_ApexMocksUtils.makeRelationship(
				List<Investigation__c>.class,
				investigationList,
				ADCVD_Order__c.Investigation__c,
				new List<List<ADCVD_Order__c>>{orderList}
		);
/*
		//Create relationship between Investigation and Suspension Agreement
		investigationList = (List<Investigation__c>)fflib_ApexMocksUtils.makeRelationship(
				List<Investigation__c>.class,
				investigationList,
				Suspension_Agreement__c.Investigation__c,
				new List<List<Suspension_Agreement__c>>{suspAgrmtList}
		);
*/
		//Create relationship between ADCVD Order and Segment
		orderList = (List<ADCVD_Order__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Order__c>.class,
				orderList,
				Segment__c.ADCVD_Order__c,
				new List<List<Segment__c>>{segmentList}
		);
		//Create relationship between Petition and Interested Organization
		petitionList = (List<Petition__c>)fflib_ApexMocksUtils.makeRelationship(
				List<Petition__c>.class,
				petitionList,
				Related_Organization__c.Petition__c,
				new List<List<Related_Organization__c>>{
						new List<Related_Organization__c> {relOrgList[0]}
				}
		);
		//Create relationship between Investigation and Interested Organization
		investigationList = (List<Investigation__c>)fflib_ApexMocksUtils.makeRelationship(
				List<Investigation__c>.class,
				investigationList,
				Related_Organization__c.Investigation__c,
				new List<List<Related_Organization__c>>{
						new List<Related_Organization__c> {relOrgList[1]}
				}
		);
		//Create relationship between ADCVD Order and Interested Organization
		orderList = (List<ADCVD_Order__c>)fflib_ApexMocksUtils.makeRelationship(
				List<ADCVD_Order__c>.class,
				orderList,
				Related_Organization__c.ADCVD_Order__c,
				new List<List<Related_Organization__c>>{
						new List<Related_Organization__c> {relOrgList[2]}
				}
		);
//		//Create relationship between Suspension Agreement and Custom Instructions
//		suspAgrmtList = (List<Suspension_Agreement__c>)fflib_ApexMocksUtils.makeRelationship(
//				List<Suspension_Agreement__c>.class,
//				suspAgrmtList,
//				Related_Organization__c.Suspension_Agreement__c,
//				new List<List<Related_Organization__c>>{
//						new List<Related_Organization__c> {relOrgList[3]}
//				}
//		);
		//Create relationship between Segment and Interested Organization
		segmentList = (List<Segment__c>)fflib_ApexMocksUtils.makeRelationship(
				List<Segment__c>.class,
				segmentList,
				Related_Organization__c.Segment__c,
				new List<List<Related_Organization__c>>{
						new List<Related_Organization__c> {relOrgList[3]}
				}
		);
	}

	private static void selectorSetup() {
		fflib_ApexMocks mocks = new fflib_ApexMocks();
		//Mock ADCVD Case Selector
		ADCVD_ICaseSelector mockADCVD_CaseSelector = (ADCVD_ICaseSelector) mocks.mock(ADCVD_ICaseSelector.class);
		mocks.startStubbing();
		mocks.when(mockADCVD_CaseSelector.sObjectType()).thenReturn(ADCVD_Case__c.SObjectType);
		mocks.when(mockADCVD_CaseSelector.selectByIdWithRelations(new Set<Id> {adcvdCaseList[0].Id})).thenReturn(adcvdCaseList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockADCVD_CaseSelector);
		//Mock Petition Selector
		IPetitionSelector mockPetitionSelector = (IPetitionSelector) mocks.mock(IPetitionSelector.class);
		mocks.startStubbing();
		mocks.when(mockPetitionSelector.sObjectType()).thenReturn(Petition__c.SObjectType);
		mocks.when(mockPetitionSelector.selectById(new Set<Id> {petitionList[0].Id})).thenReturn(petitionList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockPetitionSelector);
		//Mock Investigation Selector
		IInvestigationSelector mockInvestigationSelector = (IInvestigationSelector) mocks.mock(IInvestigationSelector.class);
		mocks.startStubbing();
		mocks.when(mockInvestigationSelector.sObjectType()).thenReturn(Investigation__c.SObjectType);
		mocks.when(mockInvestigationSelector.selectById(new Set<Id> {investigationList[0].Id})).thenReturn(investigationList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockInvestigationSelector);
		//Mock ADCVD Order Selector
		ADCVD_IOrderSelector mockADCVD_OrderSelector = (ADCVD_IOrderSelector) mocks.mock(ADCVD_IOrderSelector.class);
		mocks.startStubbing();
		mocks.when(mockADCVD_OrderSelector.sObjectType()).thenReturn(ADCVD_Order__c.SObjectType);
		mocks.when(mockADCVD_OrderSelector.selectById(new Set<Id> {orderList[0].Id})).thenReturn(orderList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockADCVD_OrderSelector);
/*
		//Mock Suspension Agreement
		ISuspensionAgreementSelector mockSuspensionAgreementSelector = (ISuspensionAgreementSelector) mocks.mock(ISuspensionAgreementSelector.class);
		mocks.startStubbing();
		mocks.when(mockSuspensionAgreementSelector.sObjectType()).thenReturn(Suspension_Agreement__c.SObjectType);
		mocks.when(mockSuspensionAgreementSelector.selectById(new Set<Id> {suspAgrmtList[0].Id})).thenReturn(suspAgrmtList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockSuspensionAgreementSelector);
*/
		//Mock Segment Selector
		ISegmentSelector mockSegmentSelector = (ISegmentSelector) mocks.mock(ISegmentSelector.class);
		mocks.startStubbing();
		mocks.when(mockSegmentSelector.sObjectType()).thenReturn(Segment__c.SObjectType);
		mocks.when(mockSegmentSelector.selectById(new Set<Id> {segmentList[0].Id})).thenReturn(segmentList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockSegmentSelector);
		//Mock Interested Organizationanization Selector
		IRelatedOrganizationSelector mockRelatedOrganizationSelector = (IRelatedOrganizationSelector) mocks.mock(IRelatedOrganizationSelector.class);
		mocks.startStubbing();
		mocks.when(mockRelatedOrganizationSelector.sObjectType()).thenReturn(Related_Organization__c.SObjectType);
		mocks.when(mockRelatedOrganizationSelector.selectById(new Set<Id> {
				relOrgList[0].Id,
				relOrgList[1].Id,
				relOrgList[2].Id,
				relOrgList[3].Id
		})).thenReturn(relOrgList);
		mocks.stopStubbing();
		fflibext_Application.Selector.setMock(mockRelatedOrganizationSelector);
	}
}