src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Initiation_Signature__c</fullName>
        <label>Actual Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Preliminary_Signature__c</fullName>
        <label>Actual Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Sunset_Initiation_Date__c</fullName>
        <label>Next Sunset Initiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment_Status__c</fullName>
        <label>Segment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Litigation Hold</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <recordTypes>
        <fullName>Anti_Circumvention_Review</fullName>
        <active>true</active>
        <label>Anti-Circumvention Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Continuation</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Amended Preliminary</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amended Final</fullName>
                </value>
                <value>
                    <fullName>ITC Preliminary</fullName>
                </value>
                <value>
                    <fullName>ITC Final</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Postponement</fullName>
                </value>
                <value>
                    <fullName>Post Litigation</fullName>
                </value>
                <value>
                    <fullName>Admin Review Opportunity Notice</fullName>
                </value>
                <value>
                    <fullName>Rescission</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Revocation</fullName>
                </value>
                <value>
                    <fullName>Quarterly Scope</fullName>
                </value>
                <value>
                    <fullName>Suspension Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Date_of_Decision_on_HoP__c</fullName>
        <description>Actual date of Decision on How to Proceed</description>
        <inlineHelpText>Actual date of Decision on How to Proceed</inlineHelpText>
        <label>Actual date of Decision - How to Proceed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Final_Signature__c</fullName>
        <description>Actual Final Signature</description>
        <inlineHelpText>Actual Final Signature</inlineHelpText>
        <label>Actual Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Initiation_Signature__c</fullName>
        <label>Actual Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Preliminary_Signature__c</fullName>
        <description>Actual Preliminary Signature</description>
        <inlineHelpText>Actual Preliminary Signature</inlineHelpText>
        <label>Actual Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Revocation_or_Continuation_FR__c</fullName>
        <label>Actual Revocation or Continuation FR</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Adequacy_of_Respondents_Submission__c</fullName>
        <label>Adequacy of Respondents Submission</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inadequate or Non-Substantive</fullName>
                </value>
                <value>
                    <fullName>Adequate or Substantive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_parties_in_agreement_to_the_outcome__c</fullName>
        <description>Are all parties in agreement as to the outcome?</description>
        <inlineHelpText>Are all parties in agreement as to the outcome?</inlineHelpText>
        <label>All parties in agreement to the outcome?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Anniversary_Month__c</fullName>
        <label>Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Months</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Accepted__c</fullName>
        <label>Application Accepted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Revocation_or_Continuation_FR__c</fullName>
        <label>Calculated Revocation or Continuation FR</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments_on_Adequacy_Determination_Filed__c</fullName>
        <label>Comments on Adequacy Determination Filed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deadline_for_Decision_on_How_to_Proceed__c</fullName>
        <description>Deadline for Decision on How to Proceed</description>
        <inlineHelpText>Deadline for Decision on How to Proceed</inlineHelpText>
        <label>Deadline for Decision on How to Proceed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Date_of_Anniversary_Month__c</fullName>
        <description>Final Date of Anniversary Month</description>
        <inlineHelpText>Final Date of Anniversary Month</inlineHelpText>
        <label>Final Date of Anniversary Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_this_review_expedited__c</fullName>
        <description>Is this review expedited?</description>
        <inlineHelpText>Is this review expedited?</inlineHelpText>
        <label>Is this review expedited?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue_Liquidation_Revocation_Instruction__c</fullName>
        <description>Issue Liquidation/Revocation Instructions, if Order is revoked</description>
        <inlineHelpText>Issue Liquidation/Revocation Instructions, if Order is revoked</inlineHelpText>
        <label>Issue Liquidation/Revocation Instruction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prelim_Extension__c</fullName>
        <label>Prelim Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rebuttal_Comments_Due__c</fullName>
        <label>Rebuttal Comments Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Filed__c</fullName>
        <label>Request Filed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>How To Proceed</fullName>
                </value>
                <value>
                    <fullName>Prelim</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Amend Final</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Customs</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Litigation Hold</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Rejected/Deficient/Negative Finding</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Remand/International Litigation</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>With the Court</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Withdrawn/Rescinded</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_ACE_Customs_Module__c</fullName>
        <description>Update ACE (Customs Module) that Order is revoked</description>
        <inlineHelpText>Update ACE (Customs Module) that Order is revoked</inlineHelpText>
        <label>Update ACE (Customs Module)</label>
        <type>Date</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Anti_Circumvention_Review</fullName>
        <active>true</active>
        <label>Anti-Circumvention Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Changed_Circumstances_Review</fullName>
        <active>true</active>
        <label>Changed Circumstances Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Expedited_Review</fullName>
        <active>true</active>
        <label>Expedited Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>New_Shipper_Review</fullName>
        <active>true</active>
        <label>New Shipper Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Scope_Inquiry</fullName>
        <active>true</active>
        <label>Scope Inquiry</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sunset_Review</fullName>
        <active>true</active>
        <label>Sunset Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Months.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>January</fullName>
    </customValue>
    <customValue>
        <fullName>February</fullName>
    </customValue>
    <customValue>
        <fullName>March</fullName>
    </customValue>
    <customValue>
        <fullName>April</fullName>
    </customValue>
    <customValue>
        <fullName>May</fullName>
    </customValue>
    <customValue>
        <fullName>June</fullName>
    </customValue>
    <customValue>
        <fullName>July</fullName>
    </customValue>
    <customValue>
        <fullName>August</fullName>
    </customValue>
    <customValue>
        <fullName>September</fullName>
    </customValue>
    <customValue>
        <fullName>October</fullName>
    </customValue>
    <customValue>
        <fullName>November</fullName>
    </customValue>
    <customValue>
        <fullName>December</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/ADCVDOrderTriggerHandlerTest.cls
@isTest
public class ADCVDOrderTriggerHandlerTest {
	private static Date orderDate = System.today();
	private static Date testActual = System.today();//reusable date variable for each test to add roll forward logic allowing data normalization
	private static Date testCalculated = System.today();//reusable date variable for each test to add roll forward logic allowing data normalization
	private static User u{
		get{
			if(u == null){
				u = [SELECT Id, ProfileId, isActive, Alias, LanguageLocaleKey, LastName, FirstName, 
								Email, EmailEncodingKey, TimeZoneSidKey, CommunityNickname, Username 
							FROM User WHERE LastName =: 'LastName1' LIMIT 1];
			}
			return u;
		}
	}
	private static ADCVD_Order__c o{
		get{
			if (o == null) {
				o = [SELECT Id, Anniversary_Month__c, Office_Assignment__c, Segment_Status__c, Status__c, Next_Sunset_Initiation_Date__c FROM ADCVD_Order__c LIMIT 1];
			}
			return o;
		}
	}
	private static Federal_Register__c orderFR{
		get{
			if (orderFR == null) {
				orderFR = [SELECT Id, ADCVD_Order__c, Type__c, Published_Date__c FROM Federal_Register__c WHERE Type__c =: 'Order' LIMIT 1];
			}
			return orderFR;
		}
	}
	private static Federal_Register__c continuationFR{
		get{
			if (continuationFR == null) {
				continuationFR = [SELECT Id, ADCVD_Order__c, Type__c, Published_Date__c FROM Federal_Register__c WHERE Type__c =: 'Continuation' LIMIT 1];
			}
			return continuationFR;
		}
	}
	private static Federal_Register__c revoFR{
		get{
			if (revoFR == null) {
				revoFR = [SELECT Id, ADCVD_Order__c, Type__c, Published_Date__c FROM Federal_Register__c WHERE Type__c =: 'Revocation' LIMIT 1];
			}
			return revoFR;
		}
	}
	private static Segment__c adminSeg{
		get{
			if (adminSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Administrative_Review');
				adminSeg = [SELECT Id, RecordTypeId, Status__c, Prelim_Extension__c, Final_Date_of_Anniversary_Month__c, Calculated_Preliminary_Signature__c,
									Calculated_Final_Signature__c, Actual_Final_Signature__c 
								FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return adminSeg;
		}
	}
	private static Segment__c nsSeg{
		get{
			if (nsSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('New_Shipper_Review');
				nsSeg = [SELECT Id, RecordTypeId, Status__c, Prelim_Extension__c, Calculated_Preliminary_Signature__c, Calculated_Initiation_Signature__c,
								Actual_Initiation_Signature__c, Calculated_Final_Signature__c, Actual_Preliminary_Signature__c, Actual_Final_Signature__c
							FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return nsSeg;
		}
	}
	private static Segment__c siSeg{
		get{
			if (siSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Scope_Inquiry');
				siSeg = [SELECT Id, Status__c, Deadline_for_Decision_on_How_to_Proceed__c, Initiation_Extension_of_days__c, RecordTypeId, Request_Filed__c, 
								Prelim_Extension__c, Calculated_Preliminary_Signature__c, Actual_Date_of_Decision_on_HoP__c, Calculated_Final_Signature__c 
							FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return siSeg;
		}
	}
	private static Segment__c expedSeg{
		get{
			if (expedSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Expedited_Review');
				expedSeg = [SELECT Id, RecordTypeId, Status__c, Prelim_Extension__c, Calculated_Initiation_Signature__c, Calculated_Preliminary_Signature__c,
									Calculated_Final_Signature__c, Actual_Final_Signature__c, Actual_Preliminary_Signature__c
								FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return expedSeg;
		}
	}
	private static Segment__c acSeg{
		get{
			if (acSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Anti_Circumvention_Review');
				acSeg = [SELECT Id, RecordTypeId, Status__c, Prelim_Extension__c, Initiation_Extension_of_days__c, Calculated_Preliminary_Signature__c,
									Calculated_Final_Signature__c , Actual_Initiation_Signature__c, Calculated_Initiation_Signature__c,
									Application_Accepted__c
								FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return acSeg;
		}
	}
	private static Segment__c ccSeg{
		get{
			if (ccSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Changed_Circumstances_Review');
				ccSeg = [SELECT Id, RecordTypeId, Status__c, Prelim_Extension__c, Calculated_Preliminary_Signature__c, Is_This_Review_Expedited__c,
									Calculated_Final_Signature__c , Actual_Initiation_Signature__c, Calculated_Initiation_Signature__c,
									All_parties_in_agreement_to_the_outcome__c, Request_Filed__c
								FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return ccSeg;
		}
	}
	private static Segment__c ssSeg{
		get{
			if (ssSeg == null) {
				Id recordTypeId = utils.getRecordTypeIdMap('Segment__c').get('Sunset_Review');
				ssSeg = [SELECT Id, Status__c, Calculated_Final_Signature__c, Update_ACE_Customs_Module__c, Adequacy_of_Respondents_Submission__c, 
							Actual_Final_Signature__c, Actual_Revocation_or_Continuation_FR__c, Calculated_Revocation_or_Continuation_FR__c, 
							Issue_Liquidation_Revocation_Instruction__c, Rebuttal_Comments_Due__c, Adequacy_Determination_Letter_120_day__c, 
							Adequacy_Determination_Letter_240_day__c, Comments_on_Adequacy_Determination_Filed__c, Memorandum_on_Adequacy_Determination__c, 
							Notify_ITC_of_No_Domestic_Interest__c, Inadequate_Domestic_Response_note_to_ITC__c, Notice_of_Intent_to_Participate__c, 
							Notify_Cluster_Coordinator_No_Interest__c, Substantive_Response_Due_For_All_Parties__c, Inform_Cluster_Coordinator_if_No_Respons__c, 
							Notice_of_intent_to_participate_Ips__c, Domestic_Party_File_Substan_Response__c, Review_to_address_zeroing_in_Segments__c, 
							Respondent_File_Substantive_Response__c, Prelim_Extension__c, Initiation_Extension_of_days__c, Final_Extension_of_days__c
							FROM Segment__c WHERE RecordTypeId =: recordTypeId LIMIT 1];
			}
			return ssSeg;
		}
	}

	@isTest static void initialize(){
		Test.startTest();
		List<ADCVD_Order__c> aList = new List<ADCVD_Order__c>();
		aList.add(o);
		ADCVDOrderTriggerHandler.initialize(aList, null);

		Test.stopTest();
		System.assertNotEquals(ADCVDOrderTriggerHandler.orderIdToSegmentMap, null);
	}

	@isTest static void setNextSunsetInitiationDate() {
		Test.startTest();
		System.assertEquals(null, o.Next_Sunset_Initiation_Date__c);
		Federal_Register__c orderFR = setFR(o.Id, 'Order', true);
		o = null;
		testCalculated = orderDate.toStartOfMonth().addYears(4).addMonths(11);
		System.assertEquals(testCalculated, o.Next_Sunset_Initiation_Date__c);
		orderDate = orderDate.addMonths(1);
		Federal_Register__c continuationFR = setFR(o.Id, 'Continuation', true);
		o = null;
		testCalculated = orderDate.toStartOfMonth().addYears(4).addMonths(11);
		System.assertEquals(testCalculated, o.Next_Sunset_Initiation_Date__c);
		orderDate = orderDate.addMonths(1);
		Federal_Register__c revoFR = setFR(o.Id, 'Revocation', true);
		o = null;

		Test.stopTest();
		System.assertEquals(null, o.Next_Sunset_Initiation_Date__c);
	}

	@isTest static void setSegmentStatus1() {
		Test.startTest();
		System.assertEquals('Active', o.Segment_Status__c);
		List<Segment__c> deleteList = new List<Segment__c>();
		deleteList.add(adminSeg);
		deleteList.add(acSeg);
		deleteList.add(ccSeg);
		deleteList.add(expedSeg);
		deleteList.add(nsSeg);
		deleteList.add(siSeg);
		deleteList.add(ssSeg);
		delete deleteList;
		o = null;

		Test.stopTest();
		System.assertEquals('Inactive', o.Segment_Status__c);
	}
	@isTest static void setSegmentStatus2() {
		Test.startTest();
		System.assertEquals('Active', o.Segment_Status__c);
		List<Segment__c> deleteList = new List<Segment__c>();
		deleteList.add(acSeg);
		deleteList.add(ccSeg);
		deleteList.add(expedSeg);
		deleteList.add(nsSeg);
		deleteList.add(siSeg);
		deleteList.add(ssSeg);
		delete deleteList;
		adminSeg.Segment_Outcome__c = 'Withdrawn';
		update adminSeg;
		update o;
		o = null;

		Test.stopTest();
		System.assertEquals('Active', o.Segment_Status__c);
	}

	@isTest static void setStatus1() {
		Test.startTest();
		System.assertEquals('Order FR Needed', o.Status__c);//default on Insert
		Federal_Register__c orderFR = setFR(o.Id, 'Order', true);
		o = null;

		Test.stopTest();
		System.assertEquals('Current-Active', o.Status__c);//updated when any Segment is active
	}

	@isTest static void setStatus2() {
		Test.startTest();
		System.assertEquals('Order FR Needed', o.Status__c);//default on Insert
		Federal_Register__c orderFR = setFR(o.Id, 'Order', true);
		o = null;
		System.assertEquals('Current-Active', o.Status__c);//updated when at least one Segment is active
		Federal_Register__c revoFR = setFR(o.Id, 'Revocation', true);
		o = null;
		System.assertEquals('Revoked-Incomplete', o.Status__c);//updated when Revocation FR is inserted
		o.Status__c = 'Revoked-Complete';//manually set to Revoked-Complete
		update o;
		delete revoFR;
		o = null;

		Test.stopTest();
		System.assertEquals('Revoked-Complete', o.Status__c);//does not overwrite when other changes happen
	}

	@isTest static void setAnniversaryMonth() {
		Test.startTest();
		setFR(o.Id, 'Order', true);
		String month = utils.getMonthFromDate(orderDate);
		o = null;
		
		Test.stopTest();
		System.assertEquals(month, o.Anniversary_Month__c);
	}

	@testSetup static void dataSetup() {
		Test.startTest();
		User testUser = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
		ADCVD_Order__c testOrder = TestUtils.createOrder(true);
		List<Segment__c> segsToInsert = new List<Segment__c>();
		System.runAs(testUser) {
			for(String segRecordTypeName : utils.getRecordTypeDeveloperNameMap('Segment__c').values()) {
				Segment__c testSeg = TestUtils.createSegment(testOrder, segRecordTypeName, false);
				segsToInsert.add(testSeg);
			}
			insert segsToInsert;
		}
	}

	private static Federal_Register__c setFR(Id parentId, String frType, Boolean doInsert) {
		Federal_Register__c testFR = TestUtils.createFR(parentId, 'ADCVD_Order__c', orderDate, frType, doInsert);
		return testFR;
	}

	private static void getNewSegs() {
		adminSeg = null;
		nsSeg = null;
		siSeg = null;
		expedSeg = null;
		acSeg = null;
		ccSeg = null;
		ssSeg = null;
	}
}