src/objects/ADCVD_Case__c.object
<CustomObject>
    <description>The ADCVD Case object is the shell or &quot;manilla folder&quot; to tie all ADCVD Case activities together.</description>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>ADCVD Case</label>
    <nameField>
        <label>ADCVD Case</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADCVD Cases</pluralLabel>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADCVD_Order__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Court_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADCVD Order</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>ADCVD Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ADCVD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CVD</fullName>
        <active>true</active>
        <description>A countervailing duties investigation</description>
        <label>CVD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Petitions</relationshipLabel>
        <relationshipName>Petitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Case</label>
        <referenceTo>ADCVD_Case__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADCVD_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ADCVD Order</label>
        <referenceTo>ADCVD_Order__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>Administrative_Review</fullName>
        <active>true</active>
        <label>Administrative Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SegmentMapperTest.cls
/**
* 
*    Created by Eitan Alfiya
*    on 7/13/2018
*    MIL Corporation
* 
**/
@isTest
public class SegmentMapperTest {
	
    @testSetup static void dataSetup(){
        //Segments only needs an ADCVD Case as parent, multiple segments can be linked to the same ADCVD Case
        //Create both locked and unlocked records for testing
        ADCVD_Case__c adcvdCase1 = TestUtils.createADCVDCase('A-111-111', 'AD ME', false);
        ADCVD_Case__c adcvdCase2 = TestUtils.createADCVDCase('C-222-222', 'CVD', false);
        insert new List<ADCVD_Case__c>{adcvdCase1, adcvdCase2};
        Petition__c petition1 = TestUtils.createPetition(adcvdCase1, Date.today(), false);
        Petition__c petition2 = TestUtils.createPetition(adcvdCase2, Date.today(), false);
        insert new List<Petition__c>{petition1, petition2};
        Investigation__c investigation1 = TestUtils.createInvestigation(petition1, false);
        Investigation__c investigation2 = TestUtils.createInvestigation(petition2, false);
        insert new List<Investigation__c>{investigation1, investigation2};
		ADCVD_Order__c order1 = TestUtils.createOrder(investigation1, false);
		ADCVD_Order__c order2 = TestUtils.createOrder(investigation2, false);
        insert new List<ADCVD_Order__c>{order1, order2};
        Segment__c segmentUnlocked = TestUtils.createSegment(order1, 'Administrative_Review', false);
        Segment__c segmentLocked = TestUtils.createSegment(order2, 'Administrative_Review', false);
        insert new List<Segment__c>{segmentUnlocked, segmentLocked};
        segmentLocked.Locked__c = true;
        update segmentLocked;
    }
    
    private static ADCVD_Case__c case1{
        get{
            if(case1 == null){
                case1 = [Select Id From ADCVD_Case__c Where Name = 'A-111-111' Limit 1];
            }
            return case1;
        }
        set;
    }
    
    private static ADCVD_Case__c case2{
        get{
            if(case2 == null){
                case2 = [Select Id From ADCVD_Case__c Where Name = 'C-222-222' Limit 1];
            }
            return case2;
        }
        set;
    }
    
    private static Segment__c unlockedSegment{
        get{
            if(unlockedSegment == null){
                unlockedSegment = [Select Id From Segment__c Where ADCVD_Case__c =: case1.Id Limit 1];
            }
            return unlockedSegment;
        }
        set;
    }
    
    private static Segment__c lockedSegment{
        get{
            if(lockedSegment == null){
                lockedSegment = [Select Id From Segment__c Where ADCVD_Case__c =: case2.Id Limit 1];
            }
            return lockedSegment;
        }
        set;
    }
    
    static testMethod void testSegmentMapper(){
        Test.startTest();
        ADCVD_CaseMapper adcvdCaseMapper = (ADCVD_CaseMapper) ADCVD_CaseMapper.mapperMap.get('ADCVD_Case__c');
        adcvdCaseMapper = adcvdCaseMapper.getInstance(new Set<Id>{case1.Id ,case2.Id});
        //SegmentMapper
        SegmentMapper segmentMapper = (SegmentMapper) adcvdCaseMapper.getMapper('Segment__c').getInstance();
		//Assert that the mapper is accessing the investigations we have inserted 
		Map<Id, Segment__c> idToUnlockedSegments = segmentMapper.getMap(false);
        Map<Id, Segment__c> idToAllSegments = segmentMapper.getMap(true);
        
        Test.stopTest();
        
        System.assertEquals(unlockedSegment.Id, idToUnlockedSegments.get(unlockedSegment.Id).Id);
        System.assertEquals(null, idToUnlockedSegments.get(lockedSegment.Id));
		
        System.assertEquals(unlockedSegment.Id, idToAllSegments.get(unlockedSegment.Id).Id);
        System.assertEquals(lockedSegment.Id, idToAllSegments.get(lockedSegment.Id).Id); 
        
        
        //Extra call for get 100% coverage
        Map<Id, Segment__c> segmentIdMap = segmentMapper.getMap();
    }
    
    static testMethod void nullInstanceCoverage(){
        Test.startTest();
        SegmentMapper.getInstance();
        Test.stopTest();
    }
}