src/objects/AppConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Configuration data for applications that utilize triggers in the org. There should be a &quot;default&quot; config and a &quot;testConfig&quot; AppConfig list in an org. EnableTriggers to be checked for both.</description>
    <fields>
        <fullName>ADCVD_Admin__c</fullName>
        <description>Email address of any Admin within the ADCVD group that wants to receive notification related to schedulable jobs</description>
        <inlineHelpText>Used by ADCVD App</inlineHelpText>
        <label>ADCVD Admin</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ChronExp_LitigationSegement__c</fullName>
        <defaultValue>&quot;0 &quot; + TEXT(MINUTE(TIMEVALUE(NOW() + 30))) + &quot; &quot; +  TEXT(HOUR(TIMEVALUE(NOW() + 30))) + &quot; &quot; + TEXT(Day(TODAY())) + &quot; &quot; + TEXT(MONTH(TODAY())) + &quot;? &quot;</defaultValue>
        <description>Chron Trigger Expression used for ScheduledDispatcher of RefreshLitigationSegmentDates class.</description>
        <inlineHelpText>Used by ADCVD Application Schedulable Classes.</inlineHelpText>
        <label>ChronExpr LitigationSegement</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Admin__c</fullName>
        <description>PrimaryAdmin to be notified by schedulable classes for ADCVD app&apos;s schedulable classes</description>
        <inlineHelpText>Used by schedulable classes in finish methods</inlineHelpText>
        <label>Primary Admin</label>
        <type>Email</type>
    </fields>
    <label>AppConfig</label>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Next_Announcement_Date__c</fullName>
        <label>Next Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Due_to_DAS_Deadline__c</fullName>
        <label>Next Due to DAS Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Office_Deadline__c</fullName>
        <label>Next Office Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by a Schedulable class to cause the Tolling Date Service to recalculate tolling days whenever a calculated announcement date is equal to &quot;yesterday when the associated trigger calculates the next announcement date.</description>
        <inlineHelpText>For system use only.</inlineHelpText>
        <label>Schedule Refresh</label>
        <type>Checkbox</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SchedulePetitionRefresh.cls
/**
 * 
 *    Created by Cal Smith
 *    on 10/26/2017 
 *    MIL Corporation
 * 
 **/
 
public class SchedulePetitionRefresh implements ScheduledDispatcher.IScheduleDispatched, Schedulable {
    
// This class runs a scheduled job at 1AM every morning

	public integer emailAllowed = 0; 	
	public string emailtext1 = '';
	public string emailtext2 = '';
	public AppConfig__c AC = AppConfig__c.getValues('default');	

    
    public void execute(SchedulableContext sc)
    {
		refreshDueDates();
    }
    
    
	public void refreshDueDates(){

		checkLimits();
		
	    list<Petition__c>petitionsToRefresh = new list<Petition__c>();
        list<Investigation__c>investigationsToRefresh = new list<Investigation__c>();

        petitionsToRefresh = [SELECT Id, Schedule_Refresh__c FROM Petition__c WHERE (Next_Announcement_Date__c = 
        	yesterday OR Next_Due_to_DAS_Deadline__c = yesterday OR Next_Office_Deadline__c = yesterday) for update];

        investigationsToRefresh = [SELECT Id, Schedule_Refresh__c FROM Investigation__c WHERE (Next_Announcement_Date__c = 
        	yesterday OR Next_Due_to_DAS_Deadline__c = yesterday OR Next_Office_Deadline__c = yesterday) for update];
       
      	for(Petition__c p:petitionsToRefresh){

       		if(p.Schedule_Refresh__c){
       			p.Schedule_Refresh__c = false;
       		}else{
       			p.Schedule_Refresh__c = true;
       		}		
      	}
      
      	for(Investigation__c i:investigationsToRefresh){

       		if(i.Schedule_Refresh__c){
       			i.Schedule_Refresh__c = false;
       		}else{
       			i.Schedule_Refresh__c = true;
       		}	
      	}

		Database.SaveResult[] srList = Database.update(petitionsToRefresh, false); 
		for (Database.SaveResult sr : srList) {

    		if (sr.isSuccess()) {
        		// Operation was successful, so get the ID of the record that was processed
        		emailtext1 = emailtext1 + 'Successfully updated Petition ID: ' + sr.getId();
    	
    		}else {

        		// Operation failed, so get all errors               
        		for(Database.Error err : sr.getErrors()) {
        			emailtext2 = emailtext2 + 'The following error has occurred: \n';
        			emailtext2 = emailtext2 + err.getStatusCode() + ': ' + err.getMessage() + '\n';                   
        			emailtext2 = emailtext2 + 'Petition fields that affected this error: ' + err.getFields() + '\n';
        		}
    		}
		
   		}   

		Database.SaveResult[] srList1 = Database.update(investigationsToRefresh, false); 
		for (Database.SaveResult sr1 : srList1) {

    		if (sr1.isSuccess()) {
        		// Operation was successful, so get the ID of the record that was processed
        		emailtext2 = emailtext2 + 'Successfully updated Investiagation ID: ' + sr1.getId();
    	
    		}else {

        		// Operation failed, so get all errors               
        		for(Database.Error ierr : sr1.getErrors()) {
        			emailtext2 = emailtext2 + 'The following error has occurred: \n';
        			emailtext2 = emailtext2 + ierr.getStatusCode() + ': ' + ierr.getMessage() + '\n';                   
        			emailtext2 = emailtext2 + 'Investigation fields that affected this error: ' + ierr.getFields() + '\n';
        		}
    		}
		
   		}   		   

		finish();
	}
	
    public void finish() {
    	
    	string emailtext = '';
    	if(string.isEmpty(emailtext1) && string.isEmpty(emailtext2)) emailtext = 'No records were processed for update during this execution.';
    	if(string.isNotEmpty(emailtext1) && string.isEmpty(emailtext2)) emailtext = 'Operation completely successful. No errors reported.';
   	    if(string.isNotEmpty(emailtext1) && string.isNotEmpty(emailtext2)) emailtext = emailtext += emailtext1 + 'Partial Success! The following errors occurred: ' + emailtext2;
    	
    	Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[]{AC.Primary_Admin__c};
        string[] ccAddresses = new string[]{AC.ADCVD_Admin__c}; 
        mail.setToAddresses(toAddresses);
        mail.setCcAddresses(ccAddresses);
        mail.setReplyTo('noreply@trade.gov');
        mail.setSenderDisplayName('ADCVD Scheduled Apex');
        mail.setBccSender(false);
        mail.setUseSignature(false);
        mail.PlainTextBody = emailtext;
        mail.Subject = 'ScheduledPetitionInvestigationRefresh Job Results ' + System.now();
        mail.saveAsActivity = false;    
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    	    	
   		// dispatch followup scheduled class
   		String chronExp = AC.ChronExp_LitigationSegement__c;
		DispatchScheduledFollower dsf = new DispatchScheduledFollower();	
   		String CronTriggerID1 = system.schedule('DispatchFollower', chronExp, dsf);
         
    }	
    
	public void checkLimits(){
		integer emailMax = limits.getLimitEmailInvocations();
		integer emailActual = limits.getEmailInvocations();
		emailAllowed = emailMax - emailActual;
		if(emailAllowed >3) Messaging.reserveSingleEmailCapacity(3);
	}
   

}