src/objects/ApplicationFactory_Service__mdt.object
<CustomObject>
    <description>Correlates a SObject with the related service implementation class.</description>
    <fields>
        <fullName>SObjectType__c</fullName>
        <description>Specifies the service&apos;s related SObject Type.</description>
        <inlineHelpText>Specifies the service&apos;s related SObject Type.</inlineHelpText>
        <label>SObject Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Implementation_Key__c</fullName>
        <description>The field value for a Service Implementation SObject implementation field. This value is used to map to the service implementation (SObjectType__c) interface.</description>
        <inlineHelpText>The field value for a Service Implementation SObject implementation field. This value is used to map to the service implementation (SObjectType__c) interface.</inlineHelpText>
        <label>Service Implementation Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Implementation_SObject__c</fullName>
        <description>Maps Application Factory Service to Service Implementation SObject, which is used to get the implementation field for service implementations.</description>
        <inlineHelpText>Maps Application Factory Service to Service Implementation SObject, which is used to get the implementation field for service implementations.</inlineHelpText>
        <label>Service Implementation SObject</label>
        <referenceTo>Service_Implementation_SObject__mdt</referenceTo>
        <relationshipLabel>Application Factory - Services</relationshipLabel>
        <relationshipName>Application_Factory_Services</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Application Factory - Service</label>
    <pluralLabel>Application Factory - Services</pluralLabel>
</CustomObject>

src/objects/Service_Implementation_SObject__mdt.object
<CustomObject>
    <description>Stores the SObject type and implementation field for service implementations related to Application Factory Services.</description>
    <fields>
        <fullName>Implementation_Field__c</fullName>
        <description>The SObject field used to store values that will be mapped to the Application Factory Services specific for this SObject. Parent relationship fields are not allowed.</description>
        <inlineHelpText>The SObject field used to store values that will be mapped to the Application Factory Services specific for this SObject. Parent relationship fields are not allowed.</inlineHelpText>
        <label>Implementation Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <description>The full Api name (including __c) for the implementation SObject</description>
        <label>SObject Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Implementation SObject</label>
    <pluralLabel>Service Implementation SObjects</pluralLabel>
</CustomObject>

src/classes/AppFactoryServicesMetadataSelector.cls
/**
 * ApplicationFactory_Service__mdt fflib Selector
 *
 * @author Andrew La Russa
 */
public class AppFactoryServicesMetadataSelector
	extends fflibext_SObjectSelector implements IAppFactoryServicesMetadataSelector {

	public static IAppFactoryServicesMetadataSelector newInstance() {
		return (IAppFactoryServicesMetadataSelector)
					fflibext_Application.Selector.newInstance(ApplicationFactory_Service__mdt.SObjectType);
	}

	private Schema.sObjectType getSObjectType() {
		return ApplicationFactory_Service__mdt.SObjectType;
	}

	private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
		return new List<Schema.SObjectField>{
			ApplicationFactory_Service__mdt.SObjectType__c,
			ApplicationFactory_Service__mdt.Service_Implementation_Key__c
		};
	}

	public List<ApplicationFactory_Service__mdt> selectById(Set<Id> idSet) {
		return (List<ApplicationFactory_Service__mdt>) selectSObjectsById(idSet);
	}

	/**
	 * Application Factory Service implementation wrapper selector
	 *
	 * @param developerName Service_Implementation_SObject__r.DeveloperName
	 *
	 * @return ImplementationWrapper for the Service SObject selected
	 */
	public ImplementationWrapper selectByServiceImplementationSObjectDeveloperName(String sObjectApiName) {
		List<ImplementationWrapper> wrapper = new List<ImplementationWrapper>();
		List<ApplicationFactory_Service__mdt> appServices = Database.query(
			newQueryFactory()
				.selectField('Service_Implementation_SObject__r.Implementation_Field__c')
				.selectField('Service_Implementation_SObject__r.SObject_Type__c')
				.setCondition('Service_Implementation_SObject__r.SObject_Type__c = :sObjectApiName')
				.toSOQL()
		);
		return new ImplementationWrapper(
			appServices.isEmpty() ? null : appServices[0].Service_Implementation_SObject__r.Implementation_Field__c,
			appServices
		);
	}

	/**
	 * Wrapper class used for ApplicationFactory Services when selecting a Service Implementation SObject.
	 * Used to build a map for a service implementation
	 */
	public class ImplementationWrapper {

		public String implementationField {get; private set;}
		public List<ApplicationFactory_Service__mdt> appServices {get; private set;}

		public ImplementationWrapper(String implementationField, List<ApplicationFactory_Service__mdt> appServices) {
			this.implementationField = implementationField;
			this.appServices = appServices;
		}
	}
}