src/objects/Artifact__c.object
<CustomObject>
    <description>Artifacts used to support Framework Certifications.</description>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Artifacts</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Non-HR</fullName>
                </value>
                <value>
                    <fullName>HR and Non-HR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Artifact</label>
    <nameField>
        <label>Artifact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Framework__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Framework</label>
        <referenceTo>Framework__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HR Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_HR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-HR Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Covered_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Other Covered Entities</relationshipLabel>
        <relationshipName>Covered_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Covered Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Covered Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Framework__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose an Active Mission.</errorMessage>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Frameworks</relationshipLabel>
        <relationshipName>Frameworks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the Framework is currently active/available.</description>
        <inlineHelpText>Is this Framework currently active?</inlineHelpText>
        <label>Active Framework</label>
        <type>Checkbox</type>
    </fields>
    <label>Framework</label>
    <nameField>
        <label>Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Framework__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Framework</label>
        <referenceTo>Framework__c</referenceTo>
        <relationshipName>Participation_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HR Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_HR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non-HR Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Framework__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Display_Name__c</fullName>
        <label>Public Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the Program is currently available.</description>
        <inlineHelpText>Is this an active/available Program?</inlineHelpText>
        <label>Active Program</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <fields>
        <fullName>HR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HR Recourse Mechanism</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Third_Party_Master_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Third Party Master List</label>
        <referenceTo>Third_Party_Master_List__c</referenceTo>
        <relationshipLabel>Third Parties</relationshipLabel>
        <relationshipName>Third_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Non-HR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Third Party</label>
    <nameField>
        <label>Third Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Third_Party_Master_List__c.object
<CustomObject>
    <fields>
        <fullName>HR_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resolves HR Data Issues</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Dispute Resolution Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U.S. Statutory Body</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification Provider</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Third Party Master List</label>
    <nameField>
        <label>Third Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Master List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/participant_search_controller.cls
public class participant_search_controller {

    public pageReference advancedSearch() {
        this.offset = 0;
        system.debug('Advanced Search');
        this.search();
        return null;
    }


    public String SelectedDataType { get; set; }
    public String tempQuery {get; set;}    //For debugging
    public String tempString {get; set;}   //For debugging

    public string tmpQuery {get; set;}

    public String selectedOffset {get; set;}
    public Integer getSelectedOffsetInteger(){
        if(this.selectedOffset == null){
            return 10;
        }
        return Integer.valueOf(this.selectedOffset);
    }

    public List<SelectOption> getOffsetOptions(){
        List<SelectOption> output = new List<SelectOption>();
        output.add(new SelectOption('10', '10'));
        output.add(new SelectOption('25', '25'));
        output.add(new SelectOption('50', '50'));
        return output;
    }

    public SelectOption[] getAvailablePrograms() {
        SelectOption[] output = new SelectOption[]{};
        output.add(new selectOption('', '-- NO FILTER --'));
        string query = 'SELECT Id, Name FROM Framework__c WHERE isActive__c = true';
        if(ApexPages.currentPage().getParameters().get('program') != null)
            query += ' and name = \''+ApexPages.currentPage().getParameters().get('program')+'\'';
        query += ' ORDER BY Name ASC';
        for(Framework__c f : database.query(query)){
            output.add(new selectOption(f.id, f.name));
        }
        return output;
    }

    private string ActiveParticipantsQuery {get{return 'SELECT id, participant__c, accountid FROM asset WHERE status = \'Active\' AND Framework__r.isActive__c = true and participant__r.program__r.name = \'Privacy Shield\'';}}
    
    public Integer getTotalOrgCount() {
        system.debug(this.ActiveParticipantsQuery );
        asset[] ActiveParticipants =  database.Query(this.ActiveParticipantsQuery );
        return ActiveParticipants.size();
    }

    public String serviceProvider {get; set;}    
    public map<string, string> serviceProviderMap {get;set;}

    public SelectOption[] getServiceProviders(){
        SelectOption[] output = new SelectOption[]{};
        output.add(new SelectOption('', '-- NO FILTER --'));
        for(Third_Party_Master_List__c provider : [select id, name from third_party_master_list__c where type__c = 'Dispute Resolution Provider' order by name asc]){
            output.add(new SelectOption(provider.id, provider.name));
            this.serviceProviderMap.put(provider.id, provider.name);
        }
        return output;
    }

    public String selectedProgram { get; set; }

    public participant_search_controller(){
        this.offset = 0;
        this.serviceProviderMap = new map<string, string>();
        if(ApexPages.currentPage().getParameters().get('status') != null){
            this.status = ApexPages.currentPage().getParameters().get('status');
        }        
        if(ApexPages.currentPage().getParameters().get('search') != null){
            this.searchTerm = ApexPages.currentPage().getParameters().get('search');
        }
        if(ApexPages.currentPage().getParameters().get('provider') != null){
            this.serviceProvider = ApexPages.currentPage().getParameters().get('provider');
        }
        if (ApexPages.currentPage().getParameters().get('program') != null) {
            this.selectedProgram = ApexPages.currentPage().getParameters().get('program');
        }
    }

    public String status {
        get{
            if(this.status == null)
                this.status = 'Active';
            return this.status;
        }
        set; 
    }
    
    //private boolean isActive { get{if (this.status=='Active') {return true;} else { return false;}}}
    
    public string[] getCouldStartWith(){
        return new string[]{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
    } 
    
    public string startsWith {get; set;}

    public String searchTerm {get; set;}

    public string getReferencedProgram(){
    if(ApexPages.currentPage().getParameters().get('program') != null)    
        return ApexPages.currentPage().getParameters().get('program');
    return null;
    }

    public integer offset {get; set;}
    public integer getLimit(){
        return this.getSelectedOffsetInteger();
    }

    public integer totalFilteredParticipants{get; set;}

    public pageReference search() {
        system.debug('Searching...');
        system.debug(ApexPages.currentPage().getParameters().get('searchMethod'));
        this.searchResults = new map<id, participating>();
        if(ApexPages.currentPage().getParameters().get('searchMethod') == 'StartingLetter'){
            this.searchTerm = null;
        }
        if(ApexPages.currentPage().getParameters().get('searchMethod') == 'SearchTerm'){
            this.startsWith = null;
        }    
        if(ApexPages.currentPage().getParameters().get('offsetChange') != null){
            this.offset += Integer.valueOf(ApexPages.currentPage().getParameters().get('offsetChange'));
        }
        if(ApexPages.currentPage().getParameters().get('startsWith') != null){
            this.startsWith = ApexPages.currentPage().getParameters().get('startsWith')+'%';
        }
        if(!String.isBlank(this.searchTerm)) {
            if (this.searchTerm.length() > 1) {
                this.searchTerm = '%' + this.searchTerm.trim()+'%';
            } else {
                this.searchTerm = this.searchTerm.trim()+'%';
            }
        }

        //Status is determined by the Asset, so query for all assets first.
        Set<Id> ParticipationsByAsset = new Set<Id>();
        Set<Id> AssetIds = new Set<Id>();
        
        if(this.selectedProgram == null){
            System.debug('Selected Program is null');
            System.debug('Asset Status: ' + this.status);
            for(asset asset : [select id, participant__c from asset where status = :this.status and participant__r.program__r.name = 'Privacy Shield']){
                ParticipationsByAsset.add(asset.participant__c);
                AssetIds.add(asset.id);
            }
        }else{
            System.debug('Selected Program: ' + this.selectedProgram);
            for(asset asset : [select id, participant__c from asset where status = :this.status and framework__c = :this.selectedProgram and participant__r.program__r.name = 'Privacy Shield']){
                ParticipationsByAsset.add(asset.participant__c);
                AssetIds.add(asset.id);
            }
        }

        System.debug('Participations by Asset: ' + ParticipationsByAsset.size());
        system.debug('DATA TYPE:  '+this.selectedDataType);

        if(!String.IsBlank(this.SelectedDataType)){
            for(Asset asset : [select id, participant__c, hr_data__c, non_hr_data__c from asset where id in :AssetIds]){
                if(this.SelectedDataType == 'HR Data' && asset.hr_data__c == false){
                    ParticipationsByAsset.remove(asset.Participant__c);
                }
                if(this.SelectedDataType == 'Non-HR Data' && asset.non_hr_data__c == false){
                    ParticipationsByAsset.remove(asset.participant__c);
                }
            }
        }

        Set<Id> FilteredParticipations = new Set<Id>();
        Set<Id> ParticipationsBySearchTerm = new Set<Id>();

        if(!String.IsBlank(this.searchTerm)){
            system.debug('Searching CEs using Search Term: \'' + this.searchTerm + '\'');
            List<Covered_Entity__c> CEList = [select id, participant__c from Covered_Entity__c where Name like :this.searchTerm OR participant__r.name like :this.searchTerm OR participant__r.public_display_name__c like :this.searchTerm order by participant__r.public_display_name__c asc limit 1000];
            for(Covered_Entity__c ce : CEList){
                ParticipationsBySearchTerm.add(ce.participant__c);
            }
            for(Participation__c p : [select id from participation__c where id in :ParticipationsByAsset AND (name like :this.searchTerm OR public_display_name__c like :this.searchTerm) order by public_display_name__c asc limit 1000]){
                ParticipationsBySearchTerm.add(p.id);            
            }
        }

        if(!String.IsBlank(this.startsWith)){
            system.debug('Searching Applications using startsWith: \'' + this.startsWith+ '\'');
//            List<Covered_Entity__c> CEList = [select id, participant__c from Covered_Entity__c where Name like :this.startsWith OR participant__r.name like :this.startsWith OR participant__r.public_display_name__c like :this.startsWith order by participant__r.public_display_name__c asc limit 1000];
//            for(Covered_Entity__c ce : CEList){
//                ParticipationsBySearchTerm.add(ce.participant__c);
//            }
            for(Participation__c p : [select id from participation__c where id in :ParticipationsByAsset AND /*(name like :this.startsWith OR */ public_display_name__c like :this.startsWith /*)*/ order by public_display_name__c asc limit 1000]){
                ParticipationsBySearchTerm.add(p.id);            
            }
        }

        //loop through the search results and the assets to make sure that there are matching records
        if(ParticipationsBySearchTerm.size() != 0){
            system.debug('ParticipationsBySearchTerm is not 0.');
            for(Id filterResult : ParticipationsBySearchTerm){
                if(ParticipationsByAsset.contains(filterResult)){
                    FilteredParticipations.add(filterResult);
                }
            }
        }else{  //otherwise if there are no search terms, use the list of participations by status.
        
            system.debug('Term:  '+String.isEmpty(this.searchTerm));
            system.debug('Start:  '+String.isEmpty(this.startsWith));

            if(!String.isEmpty(this.searchTerm) || !String.isEmpty(this.startsWith)){
                system.debug('ParticipationsBySearchTerm is 0 and there should be no results.');            
            }else{
                system.debug('ParticipationsBySearchTerm is 0.');
                FilteredParticipations = ParticipationsByAsset;
            }
        }
        

        if(this.serviceProvider != null && this.serviceProvider != ''){
            system.debug('Service Provider...' + this.serviceProvider);
            Set<Id> ProviderListResults = new Set<Id>();
            for(Third_Party__c tp : [select id, participation__c, third_party_master_list__c from third_party__c where third_party_master_list__c = :this.serviceProvider AND participation__c in :FilteredParticipations]){
                ProviderListResults.add(tp.participation__c);
            }
            FilteredParticipations = ProviderListResults;
        }

        this.totalFilteredParticipants = FilteredParticipations.size();

        this.participants = [select id, public_display_name__c, city__c, state__c, 
            (select id, hr_data__c, non_hr_data__c,  usageenddate, framework__r.name from assets__r WHERE status = :this.Status and Framework__r.isActive__c = true ORDER BY framework__r.name asc),
            (select id, type__c from artifacts__r),
            (select id, name from Covered_Entities__r order by name asc),
            (select id, third_party_master_list__c from third_parties__r where third_party_master_list__r.type__c = 'Dispute Resolution Provider')
            from participation__c where id in :FilteredParticipations order by public_display_name__c asc limit :this.getSelectedOffsetInteger() offset:this.offset ];
        System.debug('Participants size:' + this.participants.size());
        for(Participation__c p : this.participants){
            if(this.searchResults.get(p.id) == null){
                participating part = new participating();
                    part.name = p.Public_Display_Name__c;
                    part.id = p.id;
                    part.city = p.city__c;
                    part.state = p.state__c;
                    part.programs = new string[]{};
                    part.coveredData = new string[]{};
                    part.coveredDataTypes = new set<string>();
                    boolean hasHr = false;
                    boolean hasNonHr = false;
                    set<string> ProgramSet = new set<string>();
                    for(asset a: p.assets__r){
                        if (a.HR_Data__c&& !hasHr){ 
                            part.coveredData.add('HR');
                            part.coveredDataTypes.add('HR');
                            hasHr = true;
                        }
                        if (a.Non_HR_Data__c && !hasNonHr){
                            part.coveredData.add('Non-HR');
                            part.coveredDataTypes.add('Non-HR');
                            hasNonHr = true;
                        }
                        if(!programSet.contains(a.framework__r.name)){
                            part.programs.add(a.framework__r.name);
                            programSet.add(a.framework__r.name);   
                        }
                    }
                    part.coveredEntities = new string[]{};
                    for(Covered_Entity__c ce : p.Covered_Entities__r){
                        part.coveredEntities.add(ce.name);
                    }

                this.searchResults.put(p.id, part);
            }        
        }
        return null;
    }
        
    public string queryString {get; set;}
    public Participation__c[] participants {get; set;}

    public map<id, participating> searchResults {get; set;}
    
    public class participating{
        public string name {get; set;}
        public string id {get; set;}
        public string city {get; set;}
        public string state {get; set;}
        public string[] programs {get; set;}
        public string[] coveredData {get; set;}
        public string[] coveredEntities {get; set;}
        public set<string> coveredDataTypes {get; set;}
        public set<string> resolutionProviders {get; set;}
    }
    
    public boolean getShowResolutionProviders(){
        return ApexPages.currentPage().getParameters().get('showDRP') != null;
    }
}