src/objects/Artifact__c.object
<CustomObject>
    <description>Artifacts used to support Framework Certifications.</description>
    <label>Artifact</label>
    <nameField>
        <label>Artifact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Header__c</fullName>
        <label>Field Header</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Form_Section__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Field</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Section__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Header__c</fullName>
        <description>The header of the section</description>
        <inlineHelpText>The header of the section</inlineHelpText>
        <label>Header</label>
        <length>37</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Section</label>
    <nameField>
        <displayFormat>FS-{000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <label>MicroSite</label>
    <nameField>
        <label>MicroSite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MicroSites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TEST_FieldLightningController.cls
@isTest(seeAllData=false)
public class TEST_FieldLightningController{

    static testmethod void TEST_NoSectionNoForm(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Section__c=mySection.Id, Field_Header__c='header');
        insert myField;
        FieldLightningController controller = new FieldLightningController();
        FieldLightningController.lightningWrapper myLightningWrapper = FieldLightningController.getFieldInfo(null,null);
        System.assertEquals(new Field__c(),myLightningWrapper.myField);
    } 
    
    static testmethod void TEST_NoField(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Section__c=mySection.Id, Field_Header__c='header');
        insert myField;
        FieldLightningController controller = new FieldLightningController();
        FieldLightningController.lightningWrapper myLightningWrapper = FieldLightningController.getFieldInfo(null,mySection.Id);
        System.assertEquals(new Field__c(),myLightningWrapper.myField);
    }
    
    static testmethod void TEST_HasFieldAndSection(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Section__c=mySection.Id, Field_Header__c='header');
        insert myField;
        FieldLightningController controller = new FieldLightningController();
        FieldLightningController.lightningWrapper myLightningWrapper = FieldLightningController.getFieldInfo(myField.Id,mySection.Id);
        System.assertEquals(myField.Id,myLightningWrapper.myField.Id);
    }
    
    static testmethod void TEST_HasFieldAndSectionAPI(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Form__c = myForm.Id,Object_API_Name__c='Artifact__c');
        insert mySection;
        Field__c myField = new Field__c(Section__c=mySection.Id, Field_Header__c='header');
        insert myField;
        FieldLightningController controller = new FieldLightningController();
        FieldLightningController.lightningWrapper myLightningWrapper = FieldLightningController.getFieldInfo(myField.Id,mySection.Id);
        System.assertEquals(myField.Id,myLightningWrapper.myField.Id);
    }
    
    static testmethod void TEST_CreateField(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Field_Header__c='header',Section__c=mySection.Id);
        FieldLightningController.newField(myField);
        Field__c myField2 = [select Id,Field_Header__c from Field__c where Field_Header__c =: 'header'];
        System.assertEquals('header',myField2.Field_Header__c);
    }
    
    static testmethod void TEST_SaveField(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Header__c='header',Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Section__c=mySection.Id, Field_Header__c='header');
        insert myField;
        myField.Field_Header__c = 'header2';
        FieldLightningController.saveField(myField);
        Field__c myField2 = [select Field_Header__c from Field__c where Id =: myField.Id];
        system.assertEquals('header2',myField2.Field_Header__c);
    }
    
    static testmethod void TEST_CreateFieldException(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Field_Header__c='header',Section__c=mySection.Id,Display_Order__c=250);
        FieldLightningController.newField(myField);
        List<Field__c> myField2 = [select Id from Field__c where Field_Header__c =: 'header'];
        System.assertEquals(0,myField2.size());
    }
    
    static testmethod void TEST_SaveFieldException(){
        Form__c myForm = new Form__c();
        insert myForm;
        Form_Section__c mySection = new Form_Section__c(Header__c='header',Form__c = myForm.Id);
        insert mySection;
        Field__c myField = new Field__c(Section__c=mySection.Id, Field_Header__c='header');
        insert myField;
        myField.Field_Header__c = 'header2';
        myField.Display_Order__c = 250;
        FieldLightningController.saveField(myField);
        Field__c myField2 = [select Field_Header__c from Field__c where Id =: myField.Id];
        system.assertNotEquals('header2',myField2.Field_Header__c);
        system.assertEquals('header',myField2.Field_Header__c);
    } 
}