src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Participant on the Order record.</description>
        <formula>Order__r.Participant__r.Name</formula>
        <inlineHelpText>Participant on the Order record.</inlineHelpText>
        <label>Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The tracking Id returned by pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Refunds__c</fullName>
        <description>The total amount of refunds successfully processed for this payment.</description>
        <label>Total Refunds</label>
        <summarizedField>Refund__c.Transaction_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Refund__c.Transaction_Status__c</field>
            <operation>equals</operation>
            <value>Success</value>
        </summaryFilterItems>
        <summaryForeignKey>Refund__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The DateTime of the payment transaction, as returned from pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <description>A detail object for a Payment master object.  The refund of a payment in pay.gov.</description>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The id returned from pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <description>The M/D lookup that ties a refund to a payment.</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The amount of the refund</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The date/time of the refund, as returned by pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The refund status, as returned by pay.gov</description>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>SR{000000000}</displayFormat>
        <label>Refund ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MyOrdersComponentController.cls
/*
Name: MyOrdersComponentController
Author: Dan Kelner
Date Created: 09/23/16
Purpose: Controller for MyOrdersComponent, a VF component designed for use in Privacy Shield
*/

public class MyOrdersComponentController {
    
    public List<Order> orders {get; set;}    //Require the following: EffectiveDate, OrderNumber, Participant__c, AccountID, 
                                         //                       OrderItems subquery (with Pricebookentry.Product2.Name), 
                                         //                       Payments__r subquery (with Transaction_Date__c, Pay_Gov_Tracking_Id__c, 
                                         //                       Transaction_Amount__c, and Total_Refunds__c)
    


    public string getMonth(integer month){
        map<integer, string> months = new map<integer, string>();
            months.put(1, 'January');
            months.put(2, 'February');
            months.put(3, 'March');
            months.put(4, 'April');
            months.put(5, 'May');
            months.put(6, 'June');
            months.put(7, 'July');
            months.put(8, 'August');
            months.put(9, 'September');
            months.put(10, 'October');
            months.put(11, 'November');
            months.put(12, 'December');
        return months.get(month);
    }
    
    public void MyOrdersComponentController(){

    }
    
    public map<id, EcommOrder> getOrderMap(){
        map<id, EcommOrder> output = new map<id, EcommOrder>();        
        List<Id> orderIds = new List<Id>();
        List<Id> productIds = new List<Id>();
        id AccountId = null;
        for(Order order : this.orders){
            orderIds.add(order.id);
            AccountId = order.accountId;
        }
            //@@TODO:  handle the following query errors gracefully.
        Account account = [select id, (select id, UsageEndDate, product2Id from Assets) from Account where id = :AccountId limit 1];
        
        List<Refund__c> refunds = [select id, payment__r.order__c, pay_gov_tracking_id__c, transaction_date__c, transaction_amount__c, transaction_status__c from refund__c where payment__r.order__c = :orderIds];
        for(order order : this.orders){
            EcommOrder tmpOrder = new EcommOrder();
                tmpOrder.orderNumber = order.orderNumber;
                tmpOrder.orderDate = getMonth(order.CreatedDate.Month())+' '+order.CreatedDate.Day()+', '+order.CreatedDate.Year();
                tmpOrder.Products = new map<id, EcommProduct>();
                tmpOrder.Transactions = new map<string, EcommTransaction>();
            for(OrderItem orderItem : order.orderItems){
                EcommProduct tmpProduct = new EcommProduct();
                    tmpProduct.name = orderItem.Pricebookentry.Product2.Name;
                    for(Asset asset : account.assets){
                        if(asset.product2Id == OrderItem.Pricebookentry.product2Id){
                            tmpProduct.NextCertification = asset.UsageEndDate.Month()+'/'+asset.UsageEndDate.Day()+'/'+asset.UsageEndDate.Year();
                        }
                    }
                tmpOrder.Products.put(orderItem.Pricebookentry.product2Id, tmpProduct);
            }
            for(Payment__c payment : order.payments__r){
                if(payment.transaction_date__c != null){
                EcommTransaction tmpTransaction = new EcommTransaction();
                    tmpTransaction.TransactionDate = '' + payment.transaction_date__c.month() + 
                        '/'+payment.transaction_date__c.day() + 
                        '/'+payment.transaction_date__c.year()+
                        ' '+(payment.transaction_date__c.hour() >= 12 ? payment.transaction_date__c.hour() - 12 : payment.transaction_date__c.hour())+
                        ':'+payment.transaction_date__c.minute()+
                        ':'+payment.transaction_date__c.second();
                        if(payment.transaction_date__c.hour() >= 12){
                            tmpTransaction.TransactionDate += 'PM';
                        }else{
                            tmpTransaction.TransactionDate += 'AM';
                        }
                    tmpTransaction.Amount = '$ '+payment.transaction_amount__c+' USD';
                    tmpTransaction.Status = payment.transaction_status__c;
                    tmpTransaction.Type = 'Payment';
                tmpOrder.Transactions.put(payment.pay_gov_tracking_id__c, tmpTransaction);
                }
            }
            for(Refund__c refund : refunds){
                if(refund.payment__r.order__c == order.id){
                    if(refund.transaction_date__c != null){
                    EcommTransaction tmpTransaction = new EcommTransaction();
                        tmpTransaction.TransactionDate = '' + refund.transaction_date__c.month() + 
                            '/'+refund.transaction_date__c.day() + 
                            '/'+refund.transaction_date__c.year()+
                            ' '+(refund.transaction_date__c.hour() >= 12 ? refund.transaction_date__c.hour() - 12 : refund.transaction_date__c.hour())+
                            ':'+refund.transaction_date__c.minute()+
                            ':'+refund.transaction_date__c.second();
                            if(refund.transaction_date__c.hour() >= 12){
                                tmpTransaction.TransactionDate += 'PM';
                            }else{
                                tmpTransaction.TransactionDate += 'AM';
                            }
                        tmpTransaction.Amount = '$ '+refund.transaction_amount__c+' USD';
                        tmpTransaction.Status = refund.transaction_status__c;
                        tmpTransaction.Type = 'Refund';
                    tmpOrder.Transactions.put(refund.pay_gov_tracking_id__c, tmpTransaction);     
                    }           
                }
            }
            if(order.orderItems.size() != 0){
                output.put(order.id, tmpOrder);
            }
        }
        return output;
    }
    
    public class EcommOrder {
        public string orderNumber {get; set;}
        public string orderDate {get; set;}
        public map<id, EcommProduct> Products {get; set;}
        public map<string, EcommTransaction> Transactions {get; set;}
    }

    public class EcommProduct {
        public string Name {get; set;}
        public string NextCertification {get; set;}
    }
    
    public class EcommTransaction{
        public string TransactionDate {get; set;}
        public string Amount {get; set;}
        public string Status {get; set;}
        public string Type {get; set;}
    }
}