src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Organization_Contact__c</fullName>
        <description>The application contact with the role of Organization Contact.</description>
        <inlineHelpText>The application contact with the role of Organization Contact.</inlineHelpText>
        <label>Organization Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization_Corporate_Officer__c</fullName>
        <description>The application contact with the role of Organization Corporate Officer.</description>
        <inlineHelpText>The application contact with the role of Organization Corporate Officer.</inlineHelpText>
        <label>Organization Corporate Officer</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Organization_Contact__c</fullName>
        <description>The application contact with the role Organization Contact.</description>
        <inlineHelpText>The application contact with the role Organization Contact.</inlineHelpText>
        <label>Organization Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization_Corporate_Officer__c</fullName>
        <description>The applicaiton contact with the role of Organization Corporate Officer.</description>
        <inlineHelpText>The applicaiton contact with the role of Organization Corporate Officer.</inlineHelpText>
        <label>Organization Corporate Officer</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Application Contacts</relationshipLabel>
        <relationshipName>Participant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Organization Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Organization Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>International Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Application Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateApplicationContactEmailsBatchable.cls
global class UpdateApplicationContactEmailsBatchable implements 
	Database.Batchable<sObject>, Database.Stateful {

	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator('SELECT ID, Organization_Contact__c, Organization_Corporate_Officer__c, Participant__c FROM Asset');
	}
	global void execute(Database.BatchableContext bc, List<Asset> scope){
		Set<Id> applicationIdList = new Set<Id>();

		Map<Id,String> participantToContactEmail = new Map<Id,String>();
		Map<Id,String> participantToCorporateOfficer = new Map<Id,String>();
		
		for(Asset asset : scope) {
			applicationIdList.add(asset.Participant__c);
		}

		for(Participant_Contact__c applicationContact : [SELECT Name,Id,Role__c,Participant__c,Email__c from Participant_Contact__c where Participant__c IN: applicationIdList ORDER BY LastModifiedDate ASC]) {
			if(applicationContact.Role__c == 'Organization Corporate Officer') {
				participantToCorporateOfficer.put(applicationContact.Participant__c,applicationContact.Email__c);
			} else if(applicationContact.Role__c == 'Organization Contact') {
				participantToContactEmail.put(applicationContact.Participant__c,applicationContact.Email__c);
			}
		}

		List<Asset> assetsToUpdate = new List<Asset>();
		for(Asset asset : scope) {
			if(asset.Organization_Corporate_Officer__c !=  participantToCorporateOfficer.get(asset.Participant__c) ||
				asset.Organization_Contact__c != participantToContactEmail.get(asset.Participant__c)) {
				asset.Organization_Corporate_Officer__c = participantToCorporateOfficer.get(asset.Participant__c);
				asset.Organization_Contact__c = participantToContactEmail.get(asset.Participant__c);
				assetsToUpdate.add(asset);
			}
		}

		update assetsToUpdate;

	}	
	global void finish(Database.BatchableContext bc){
		System.debug('UpdateApplicationContactEmailsBatchable batch finished');
	}	
}