src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Organization_Contact__c</fullName>
        <description>The application contact with the role of Organization Contact.</description>
        <inlineHelpText>The application contact with the role of Organization Contact.</inlineHelpText>
        <label>Organization Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization_Corporate_Officer__c</fullName>
        <description>The application contact with the role of Organization Corporate Officer.</description>
        <inlineHelpText>The application contact with the role of Organization Corporate Officer.</inlineHelpText>
        <label>Organization Corporate Officer</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_Contact__c</fullName>
        <description>The application contact with the role of Organization Contact.</description>
        <inlineHelpText>The application contact with the role of Organization Contact.</inlineHelpText>
        <label>Organization Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization_Corporate_Officer__c</fullName>
        <description>The application contact with the role of Organization Corporate Officer.</description>
        <inlineHelpText>The application contact with the role of Organization Corporate Officer.</inlineHelpText>
        <label>Organization Corporate Officer</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participation_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Organization_Contact__c</fullName>
        <description>The application contact with the role Organization Contact.</description>
        <inlineHelpText>The application contact with the role Organization Contact.</inlineHelpText>
        <label>Organization Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization_Corporate_Officer__c</fullName>
        <description>The applicaiton contact with the role of Organization Corporate Officer.</description>
        <inlineHelpText>The applicaiton contact with the role of Organization Corporate Officer.</inlineHelpText>
        <label>Organization Corporate Officer</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Application Contacts</relationshipLabel>
        <relationshipName>Participant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Organization Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Organization Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>International Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Application Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Participant on the Order record.</description>
        <formula>Order__r.Participant__r.Name</formula>
        <inlineHelpText>Participant on the Order record.</inlineHelpText>
        <label>Participant</label>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <description>A detail object for a Payment master object.  The refund of a payment in pay.gov.</description>
    <fields>
        <fullName>Payment__c</fullName>
        <description>The M/D lookup that ties a refund to a payment.</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>SR{000000000}</displayFormat>
        <label>Refund ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentsTest.cls
/*
	Author: Jeff Weyhrauch
	Date: 3-12-19
	Name: PaymentsTest.cls
	Purpose: Test class for IPayments and Payments.
 */
@IsTest
private class PaymentsTest {

	@IsTest
	static void testNewInstanceOfPaymentsDomain_PassListWithOneNonInsertedObject_ReturnsValidInterface() {
		List<Payment__c> paymentList  = new List<Payment__c>();
		paymentList.add(new Payment__c());
		IPayments iPayment = (IPayments) Payments.newInstance(paymentList);
		System.assertNotEquals(iPayment, null, 'Interface returned as null and should not have');
	}

    @isTest
    static void testRefundContactAndOfficer_Insert() {
        Account myAccount = new Account(Name='MyAccount');
        insert myAccount;

        Participation__c myApplication = new Participation__c(Name='test',Postal_Code__c='22222');
        insert myApplication;

        Participant_Contact__c appContact = new Participant_Contact__c(Role__c='Organization Corporate Officer',Email__c='officer@success.com',Participant__c=myApplication.Id);
        Participant_Contact__c appContact2 = new Participant_Contact__c(Role__c='Organization Contact',Email__c='contact@success.com',Participant__c=myApplication.Id);

        List<Participant_Contact__c> appContacts = new List<Participant_Contact__c>{appContact,appContact2};
        insert appContacts;

        Case myCase = new Case(Participation_Profile__c=myApplication.Id);
        insert myCase;

        Asset asset = new Asset();
        asset.Name ='Name';
        asset.Organization_Contact__c = 'i@i.com';
        asset.Organization_Corporate_Officer__c = 'i@i.com';
        asset.Participant__c = myApplication.Id;
        asset.AccountId = myAccount.Id;
        insert asset;

        Order myOrder = new Order(Participant__c=myApplication.Id,AccountId=myAccount.Id,
                Status='In Progress', Organization_Corporate_Officer__c = 'officer@success.com',
                Organization_Contact__c = 'contact@success.com',EffectiveDate=Date.today());
        insert myOrder;

        Payment__c myPayment = new Payment__c(Order__c=myOrder.Id);
        insert myPayment;

        Refund__c myRefund = new Refund__c(Payment__c=myPayment.Id);
        insert myRefund;

        Participation__c myApplication2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Participation__c WHERE Id =: myApplication.Id];
        Order myOrder2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Order WHERE Id =: myOrder.Id];
        Payment__c myPayment2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Payment__c WHERE Id =: myPayment.Id];
        Refund__c myRefund2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Refund__c WHERE Id =: myRefund.Id];
        Case myCase2 = [SELECT Organization_Contact__c,Organization_Corporate_Officer__c FROM Case WHERE Id =: myCase.Id];

        Test.startTest();
        System.assertEquals('officer@success.com',myApplication2.Organization_Corporate_Officer__c);
        System.assertEquals('contact@success.com',myApplication2.Organization_Contact__c);
        System.assertEquals('officer@success.com',myOrder2.Organization_Corporate_Officer__c);
        System.assertEquals('contact@success.com',myOrder2.Organization_Contact__c);
        System.assertEquals('officer@success.com',myPayment2.Organization_Corporate_Officer__c);
        System.assertEquals('contact@success.com',myPayment2.Organization_Contact__c);
        Test.stopTest();
    }

    @isTest
    static void testRefundContactAndOfficer_Update() {
        Account myAccount = new Account(Name='MyAccount');
        insert myAccount;

        Participation__c myApplication = new Participation__c(Name='test',Postal_Code__c='22222');
        insert myApplication;

        Participant_Contact__c appContact = new Participant_Contact__c(Role__c='Organization Corporate Officer',Email__c='i@i.com',Participant__c=myApplication.Id);
        Participant_Contact__c appContact2 = new Participant_Contact__c(Role__c='Organization Contact',Email__c='i@i.com',Participant__c=myApplication.Id);

        List<Participant_Contact__c> appContacts = new List<Participant_Contact__c>{appContact,appContact2};
        insert appContacts;

        Case myCase = new Case(Participation_Profile__c=myApplication.Id);
        insert myCase;

        Asset asset = new Asset();
        asset.Name ='Name';
        asset.Organization_Contact__c = 'i@i.com';
        asset.Organization_Corporate_Officer__c = 'i@i.com';
        asset.Participant__c = myApplication.Id;
        asset.AccountId = myAccount.Id;
        insert asset;

        Order myOrder = new Order(Participant__c=myApplication.Id,AccountId=myAccount.Id,
                Organization_Corporate_Officer__c = 'officer@success.com', Organization_Contact__c = 'contact@success.com',
                Status='In Progress',EffectiveDate=Date.today());
        insert myOrder;

        Payment__c myPayment = new Payment__c(Order__c=myOrder.Id);
        insert myPayment;

        Refund__c myRefund = new Refund__c(Payment__c=myPayment.Id);
        insert myRefund;

        appContacts[0].Email__c = 'officer@success.com';
        appContacts[1].Email__c = 'contact@success.com';
        update appContacts;

        Test.startTest();

        Participation__c myApplication2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Participation__c WHERE Id =: myApplication.Id];
        Order myOrder2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Order WHERE Id =: myOrder.Id];
        Payment__c myPayment2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Payment__c WHERE Id =: myPayment.Id];
        Refund__c myRefund2 = [SELECT Name,Organization_Contact__c,Organization_Corporate_Officer__c FROM Refund__c WHERE Id =: myRefund.Id];
        Case myCase2 = [SELECT Organization_Contact__c,Organization_Corporate_Officer__c FROM Case WHERE Id =: myCase.Id];

        System.assertEquals('officer@success.com',myApplication2.Organization_Corporate_Officer__c);
        System.assertEquals('contact@success.com',myApplication2.Organization_Contact__c);
        System.assertEquals('officer@success.com',myOrder2.Organization_Corporate_Officer__c);
        System.assertEquals('contact@success.com',myOrder2.Organization_Contact__c);
        System.assertEquals('officer@success.com',myPayment2.Organization_Corporate_Officer__c);
        System.assertEquals('contact@success.com',myPayment2.Organization_Contact__c);
        Test.stopTest();
    }

	@IsTest
	static void testPaymentsTrigger_InsertPaymentRecord_TriggerIsCovered() {
		try { insert new Payment__c(); } catch (Exception e) {}
	}

}