src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Organization_Contact__c</fullName>
        <description>The application contact with the role of Organization Contact.</description>
        <inlineHelpText>The application contact with the role of Organization Contact.</inlineHelpText>
        <label>Organization Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Organization_Corporate_Officer__c</fullName>
        <description>The application contact with the role of Organization Corporate Officer.</description>
        <inlineHelpText>The application contact with the role of Organization Corporate Officer.</inlineHelpText>
        <label>Organization Corporate Officer</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Application Contacts</relationshipLabel>
        <relationshipName>Participant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Organization Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Organization Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>International Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Application Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssetsTest.cls
/*
	Author: Jeff Weyhrauch
	Date: 3-12-19
	Name: AssetsTest.cls
	Purpose: Test class for IAssets and Assets.
 */
@IsTest
private class AssetsTest {

	@IsTest
	static void testNewInstanceOfAssetsDomain_PassListWithOneNonInsertedObject_ReturnsValidInterface() {
		List<Asset> assetList  = new List<Asset>();
		assetList.add(new Asset());
		IAssets iAsset = (IAssets) Assets.newInstance(assetList);
		System.assertNotEquals(iAsset, null, 'Interface returned as null and should not have');
	}

	@isTest
	static void testUpdateContactAndOfficer() {
		Account myAccount = new Account(Name='MyAccount');
		insert myAccount;

		Participation__c myApplication = new Participation__c(Name='test',Postal_Code__c='22222');
		insert myApplication;

		Participant_Contact__c appContact = new Participant_Contact__c(Role__c='Organization Corporate Officer',Email__c='officer@success.com',Participant__c=myApplication.Id);
		Participant_Contact__c appContact2 = new Participant_Contact__c(Role__c='Organization Contact',Email__c='contact@success.com',Participant__c=myApplication.Id);

		List<Participant_Contact__c> appContacts = new List<Participant_Contact__c>{appContact,appContact2};
		insert appContacts;

		Asset asset = new Asset();
		asset.Name ='Name';
		asset.Organization_Contact__c = 'i@i.com';
		asset.Organization_Corporate_Officer__c = 'i@i.com';
		asset.Participant__c = myApplication.Id;
		asset.AccountId = myAccount.Id;
		insert asset;

		Test.startTest();
		System.assertEquals('i@i.com',asset.Organization_Contact__c);
		System.assertEquals('i@i.com',asset.Organization_Corporate_Officer__c);
		update asset;

		Asset asset2 = [select Name,Organization_Contact__c,Organization_Corporate_Officer__c from Asset where Name = 'Name'];
		Test.stopTest();

		System.assertEquals('officer@success.com',asset2.Organization_Corporate_Officer__c);
		System.assertEquals('contact@success.com',asset2.Organization_Contact__c);
	}

	@IsTest
	static void testAssetsTrigger_InsertAssetRecord_TriggerIsCovered() {
		try { insert new Asset(); } catch (Exception e) {}
	}

}