src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Framework__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Framework</label>
        <referenceTo>Framework__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Framework__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What is the Product that this is tied to for Automation?</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Frameworks</relationshipLabel>
        <relationshipName>Frameworks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose an Active Mission.</errorMessage>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Frameworks</relationshipLabel>
        <relationshipName>Frameworks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the Framework is currently active/available.</description>
        <inlineHelpText>Is this Framework currently active?</inlineHelpText>
        <label>Active Framework</label>
        <type>Checkbox</type>
    </fields>
    <label>Framework</label>
    <nameField>
        <label>Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Legacy</fullName>
        <active>true</active>
        <description>Legacy order record type</description>
        <label>Legacy</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Framework__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Framework</label>
        <referenceTo>Framework__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Framework__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Framework</label>
        <referenceTo>Framework__c</referenceTo>
        <relationshipName>Participation_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Framework__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Participant_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Application Contacts</relationshipLabel>
        <relationshipName>Participant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Organization Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Organization Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>International Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Application Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The Application abbreviation.  For a refund, is used to determine the pay.gov TCS_APP_ID.</description>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Privacy Shield</fullName>
                    <default>true</default>
                    <label>Privacy Shield</label>
                </value>
                <value>
                    <fullName>Event or Service</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                    <isActive>false</isActive>
                    <label>PS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Participant on the Order record.</description>
        <formula>Order__r.Participant__r.Name</formula>
        <inlineHelpText>Participant on the Order record.</inlineHelpText>
        <label>Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the Program is currently available.</description>
        <inlineHelpText>Is this an active/available Program?</inlineHelpText>
        <label>Active Program</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <fields>
        <fullName>Third_Party_Master_List__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Third Party Master List</label>
        <referenceTo>Third_Party_Master_List__c</referenceTo>
        <relationshipLabel>Third Parties</relationshipLabel>
        <relationshipName>Third_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>Website as indicated by the User.</description>
        <inlineHelpText>What is the Official Website of this Third Party?</inlineHelpText>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Third Party</label>
    <nameField>
        <label>Third Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Third_Party_Master_List__c.object
<CustomObject>
    <fields>
        <fullName>Website__c</fullName>
        <description>Official website of the Third Party Provider</description>
        <inlineHelpText>What is the Website for this Third Party Provider?</inlineHelpText>
        <label>Website</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Third Party Master List</label>
    <nameField>
        <label>Third Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Master List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Order_Events_ControllerTest.cls
@IsTest
public class Order_Events_ControllerTest {

	static Integer recordsToAdd = 10;
	static Id legacyRecordTypeId = Schema.SObjectType.Order
		.getRecordTypeInfosByDeveloperName().get('Legacy').getRecordTypeId();

	@TestSetup
	static void setup() {
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsToAdd; i++) {
			Account acct = new Account(Name = 'TestAccount' + i, Website = 'www.test' + i + '.com');
			accounts.add(acct);
		}
		insert accounts;
		// Create related contacts
		List<Contact> contacts = new List<Contact>();
		for (Integer j = 0; j < accounts.size(); j++) {
			Contact con = new Contact(
				FirstName = 'Test ' + j,
				LastName = 'Test ' + j,
				AccountId = accounts[j].Id,
				Email = 'test' + j + '@test.org.com'
			);
			contacts.add(con);
		}
		insert contacts;
		// Create applications
		List<Participation__c> applications = new List<Participation__c>();
		for (Account account: accounts) {
			applications.add(
				new Participation__c(
					Organization__c = account.Id,
					Postal_Code__c = '55555'
				)
			);
		}
		insert applications;
		List<Participant_Contact__c> applicationContacts = new List<Participant_Contact__c>();
		for (Integer k = 0; k < applications.size(); k++) {
			applicationContacts.add(
				new Participant_Contact__c(
					Participant__c = applications[k].Id,
					Role__c = 'Primary Contact',
					Contact__c = contacts[k].Id
				)
			);
		}
		insert applicationContacts;
		// Create product, framework, and pricebook
		Product2 product = new Product2(Name = 'Privacy Shield Product', IsActive = true);
		insert product;
		Program__c program = new Program__c(isActive__c = true);
		insert program;
		Framework__c framework = new Framework__c(Product__c = product.Id, Program__c = program.Id, isActive__c = true);
		insert framework;
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry standardPricebookEntry = new PricebookEntry(
			Pricebook2Id = pricebookId,
			Product2Id = product.Id,
			UnitPrice = 1000,
			IsActive = true
		);
		insert standardPricebookEntry;
		Pricebook2 pricebook = TestUtils.createPricebook('Privacy Shield', true, true);
		PricebookEntry pricebookEntry = new PricebookEntry(
			IsActive = true,
			UnitPrice = 1000,
			Pricebook2Id = pricebook.Id,
			Product2Id = product.Id
		);
		insert pricebookEntry;
		// Create orders
		List<Order> orders = new List<Order>();
		for (Participation__c application: applications) {
			orders.add(
				new Order(
					RecordTypeId = legacyRecordTypeId,
					Participant__c = application.Id,
					AccountId = application.Organization__c,
					Status = 'In Progress',
					Description = 'Privacy Shield',
					EffectiveDate = Date.today(),
					Pricebook2Id = pricebook.Id
				)
			);
		}
		insert orders;
		// Create order items
		List<OrderItem> orderItems = new List<OrderItem>();
		for (Order order: orders) {
			orderItems.add(
				new OrderItem(
					OrderId = order.Id,
					Quantity = 1,
					PricebookEntryId = pricebookEntry.Id,
					UnitPrice = pricebookEntry.UnitPrice
				)
			);
		}
		insert orderItems;
		// Create payments
		List<Payment__c> payments = new List<Payment__c>();
		for (Order order: orders) {
			payments.add(new Payment__c(Order__c = order.Id, Application__c = 'Privacy Shield'));
		}
		insert payments;
	}



	@IsTest
	static void testUpdateAssets_updateExistingAssets() {
		createAssets();
		Test.startTest();
		updatePaymentStatusAndType([SELECT Id FROM Payment__c]);
		Test.stopTest();
	}

	@IsTest
	static void testUpdateAssets_insertNewAssets() {
		Test.startTest();
		updatePaymentStatusAndType([SELECT Id FROM Payment__c]);
		Test.stopTest();
	}

	@IsTest
	static void testUpdateThirdParties() {
		createAssets();
		List<Third_Party__c> thirdParties = new List<Third_Party__c>();
		Framework__c framework = [SELECT Id FROM Framework__c LIMIT 1][0];
		Third_Party_Master_List__c thirdPartyMasterList = new Third_Party_Master_List__c(Framework__c = framework.Id);
		for (OrderItem orderItem: [SELECT Id FROM OrderItem]) {
			thirdParties.add(
				new Third_Party__c(
					Order_Product__c = orderItem.Id,
					Third_Party_Master_List__c = thirdPartyMasterList.Id,
					Website__c = 'www.test.org'
				)
			);
		}
		insert thirdParties;
		Test.startTest();
		updatePaymentStatusAndType([SELECT Id FROM Payment__c]);
		Test.stopTest();
	}

	static void createAssets() {
		List<Order> orders = [SELECT Id, AccountId FROM Order];
		List<Contact> contacts = [SELECT Id FROM Contact];
		Product2 product = [SELECT Id FROM Product2 LIMIT 1][0];
		List<Asset> assets = new List<Asset>();
		for (Integer l = 0; l < orders.size(); l++) {
			assets.add(
				new Asset(
					Name = 'Test Asset ' + l,
					AccountId = orders[l].AccountId,
					Product2Id = product.Id,
					ContactId = contacts[l].Id
				)
			);
		}
		insert assets;
	}

	static void updatePaymentStatusAndType(List<Payment__c> payments) {
		for (Integer i = 0; i < payments.size(); i++) {
			if (Math.mod(i, 2) == 0) {
				payments[i].Transaction_Status__c = 'Success';
				payments[i].Payment_Type__c = 'PLASTIC_CARD';
			} else {
				payments[i].Transaction_Status__c = 'Received';
				payments[i].Payment_Type__c = 'ACH';
			}
		}
		update payments;
	}
}