src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Inactive_Status_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inactive Status Reason</label>
        <referenceTo>Inactive_Reason__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The related Application&apos;s Program.</description>
        <formula>Participation_Profile__r.Program__r.Name</formula>
        <inlineHelpText>The related Application&apos;s Program.</inlineHelpText>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Inactive_Reason__c.object
<CustomObject>
    <description>Reasons why the status has changed to inactive.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Inactive Reason</label>
    <nameField>
        <label>Inactive Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inactive Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Inactive_Status_Reason__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Inactive Status Reason</label>
        <referenceTo>Inactive_Reason__c</referenceTo>
        <relationshipName>Participation_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Framework__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Display_Name__c</fullName>
        <label>Public Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>A brief summary of the Mission.</description>
        <inlineHelpText>What are the goals/intents of the Mission.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Application.cls
Global class Application{
    /*
    This class provides over-all support of an Application for a specific user's Organization and the provided Program.
    */

    public Set<String> getStandardFields(){
        Set<String> output = new Set<String>(new String[]{'Organization__c', 'Id', 'Name', 'Public_Display_Name__c', 'City__c', 'Street__c', 'State__c', 'Postal_Code__c'});           
        return output;
    }

    private User getCurrentUser(){
        return [SELECT 
            id, firstname, lastname, email, phone, fax,
            contactid, contact.accountid, contact.account.name, contact.account.billingcity, contact.account.billingstatecode, contact.account.billingstate, 
            contact.account.billingstreet, contact.account.billingpostalcode 
            FROM User WHERE id = :UserInfo.getUserId() LIMIT 1];
    }
    
    public Participation__c getApplicationById(Set<string> fields, ID Application){
        String query = 'SELECT ';
        query += this.getQueryFields(fields);
        query += ' FROM Participation__c WHERE Id = \''+Application+'\' limit 1';
        system.debug(query);
        try{
            return database.query(query);
        }catch(exception e){
            system.debug(e);
        }
        return null;
    }
    
    private String getQueryFields(set<string> fields){
        List<string> fieldList = new list<String>(fields); 
        String output = ''; 
        output += String.join(fieldList, ', ');        
        return output;
    }
    
    public Participation__c getApplication(Set<string> fields, Id Program){
    //The field list needs to be an iterable List, but each field must be unique in the list.
    //To resolve this, the parameter 'fields' must be a set, and then the list.addAll method converts the set to a new list.
        String query = 'SELECT ';
        query += getQueryFields(fields);
        query += ' FROM Participation__c WHERE program__c = \''+Program+'\' AND Organization__c = \''+this.getCurrentUser().Contact.AccountId+'\' limit 1';
        system.debug(query);
        try{
            return database.query(query);
        }catch(exception e){
            system.debug(e);
        }
        return null;
    }
    
    public List<Order> getOrders(Id ApplicationId, List<String> Status){
        //Get a list of Orders and their Order Items for the specified application.
        return [select id, Program__c, Order_Paid__c, Status, (select id, unitprice, product2id from orderItems) from order where participant__c = :ApplicationId AND Status IN :Status];
    }

    public Order createOrder(Id Application, Id Program, Id Pricebook){
        try{
            Order order = new Order(
                Program__c = Program,
                Participant__c = Application,
                Status = 'In Progress',
                effectivedate = Date.today(),
                AccountId = this.getCurrentUser().contact.accountid,
                Pricebook2Id = Pricebook
            );
            insert order;
            return order;
        }catch(Exception e){
            system.debug(e);
        }
        return null;        
    }

    Public Order createOrder(Id Application, Id Program){
        try{
            Order order = new Order(
                Program__c = Program,
                Participant__c = Application,
                Status = 'In Progress',
                effectivedate = Date.today(),
                AccountId = this.getCurrentUser().contact.accountid
            );
            insert order;
            return order;
        }catch(Exception e){
            system.debug(e);
        }
        return null;    
    }

    public List<Order> getOrders(Id ApplicationId, String Status){
        //Get a list of Orders and their Order Items for the specified application.
        return [select id, Program__c, Order_Paid__c, (select id, unitprice, product2id from orderItems) from order where participant__c = :ApplicationId AND Status = :Status];
    }

    public List<Order> getOrders(Id ApplicationId){
        //Get a list of Orders and their Order Items for the specified application.
        return [select id, status, Program__c, Order_Paid__c, (select id, unitprice, product2id from orderItems) from order where participant__c = :ApplicationId];
    }

    public List<Asset> getAssets(Id ApplicationId, String Status){
        return [select id, product2.name, product2Id, Inactive_Status_Reason__c, Inactive_Status_Reason__r.Name, Inactive_Status_Reason__r.Description__c from Asset where Participant__c = :ApplicationId AND Status = :Status];
    }

    public List<Asset> getAssets(Id ApplicationId, List<String> Status){
        return [select id, status, product2.name, product2Id, Inactive_Status_Reason__c, Inactive_Status_Reason__r.Name, Inactive_Status_Reason__r.Description__c from Asset where Participant__c = :ApplicationId AND Status IN :Status];
    }
    
    public List<Asset> getAssets(Id ApplicationId){
        return [select id, Status,  product2.name, product2Id, Inactive_Status_Reason__c, Inactive_Status_Reason__r.Name, Inactive_Status_Reason__r.Description__c from Asset where Participant__c = :ApplicationId];
    }
    
    public Participation__c createApplication(Id Program){
        Participation__c app = new Participation__c(
            name = this.getCurrentUser().contact.account.name,
            public_display_name__c = this.getCurrentUser().contact.account.name,
            organization__c = this.getCurrentUser().contact.accountId,
            program__c = Program,
            city__c = this.getCurrentUser().contact.account.billingcity,
            street__c = this.getCurrentUser().contact.account.billingstreet,            
            state__c = this.getCurrentUser().contact.account.billingstate,
            postal_code__c = this.getCurrentUser().contact.account.billingpostalcode  
        );
        
/*        try{
            insert app;
        }catch(Exception e){
            system.debug(e);
        }*/
        return app;
    }
    
    Public PageReference findFormPage(Id Form, Boolean hasApplication){
        if(hasApplication){
            PageReference destination = Page.Form;
            destination.getParameters().put('id', Form);
            destination.setRedirect(true);
            return destination;
        }else{
            PageReference destination = Page.Form_Start;
            destination.getParameters().put('id', Form);
            destination.setRedirect(true);
            return destination;
        }
        return null;
    }
    
    public pageReference submit(Order order, id application, id account, string subject, string recordtypename, string description, string redirect){
        boolean showError = false;
        if([select id from orderItem where orderid = :order.id limit 10].size() != 0){
            order.order_paid__c = true;
            order.status = 'Paid';
            try{
                update order;
            }Catch(Exception e){
                showError = true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error, ErrorMessaging.clearMessage(e.getMessage())));
            }
        }else if(order.id != null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error, 'You must select at least 1 product/service that you provide.'));
            showError = true;
        }
        if(!showError){
            Id recordType = [select id from recordtype where sobjecttype = 'Case' and DeveloperName = :recordtypename limit 1].id;        
            Case c = new Case(subject = subject, order__c = order.id, participation_profile__c = application, recordtypeid = recordtype, accountid = account, description = description);
            Database.DMLOptions dmo = new Database.DMLOptions();        
                dmo.assignmentRuleHeader.useDefaultRule = true;     
            c.setOptions(dmo);
            try{
                insert c;
            }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.fatal, ErrorMessaging.clearMessage(e.getMessage())));
            showError = true;            
            }
        }

        if(showError){
            return null;
        }

        PageReference pr = new PageReference(redirect);
        pr.setRedirect(true);

        return pr;
    }
    
}