src/objects/Attendee__c.object
<CustomObject>
    <description>Child records of Contacts to match attendance of events.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email address of the attendee.</description>
        <inlineHelpText>The email address of the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting__c.object
<CustomObject>
    <description>Used to track U.S Suppliers and Foreign Buyers meetings at Trade Events.</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The participant of the meeting, like a foreign buyer.</description>
        <inlineHelpText>The participant of the meeting, like a foreign buyer.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The host of the meeting.</description>
        <inlineHelpText>The host of the meeting.</inlineHelpText>
        <label>Host</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Meetings (Host)</relationshipLabel>
        <relationshipName>Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of meeting.</description>
        <inlineHelpText>The type of meeting.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>B2G</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                    <isActive>false</isActive>
                    <label>Demo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MeetingCaseCreator.cls
global with sharing class MeetingCaseCreator implements valence.TransformationFilter {

    public Boolean validFor(valence.LinkContext context) {
        if('business_conference_meetings'.equalsIgnoreCase(context.linkSourceName) && 'Meeting__c'.equalsIgnoreCase(context.linkTargetName)) {
            return true;
        }
        return false;
    }

    public void process(valence.LinkContext context, List<valence.RecordInFlight> records) {
        Set<Id> attendeeIds = new Set<Id>();
        Map<String,String> attendeesToEmails = new Map<String,String>();

        for(valence.RecordInFlight record : records) {
            Map<String, Object> props = record.getProperties();
            if(props.get('Attendee__c') != null) {
                attendeeIds.add((Id)props.get('Attendee__c'));
            }
            if(props.get('Host__c') != null) {
                attendeeIds.add((Id)props.get('Host__c'));
            }
        }

        List<Attendee__c> attendeeList = [SELECT Id,Email__c from Attendee__c];
        for(Attendee__c attendee : attendeeList) {
            attendeesToEmails.put(attendee.Id, attendee.Email__c);
        }

        for(valence.RecordInFlight record : records) {
            Map<String, Object> props = record.getProperties();
            String meetingType = 'B2B';

            if(props.get('Attendee__c') != null) {
                if(attendeesToEmails.get(String.valueOf(props.get('Attendee__c'))).toLowerCase().endsWith('.gov') == true) {
                    meetingType = 'G2B';
                }

            }
            if(props.get('Host__c') != null) {
                if(attendeesToEmails.get(String.valueOf(props.get('Host__c'))).toLowerCase().endsWith('.gov') == true) {
                    meetingType = 'G2B';
                }
            }
            record.getProperties().put('Type__c',meetingType);
        }
    }
}