src/objects/Attendee__c.object
<CustomObject>
    <description>Child records of Contacts to match attendance of events.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact record of this Attendee.</description>
        <inlineHelpText>The Contact record of this Attendee.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email address of the attendee.</description>
        <inlineHelpText>The email address of the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The first name of the attendee.</description>
        <inlineHelpText>The first name of the attendee.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name of the attendee.</description>
        <inlineHelpText>The last name of the attendee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCity__c</fullName>
        <description>Attendee&apos;s city.</description>
        <inlineHelpText>Attendee&apos;s city.</inlineHelpText>
        <label>MailingCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCountry__c</fullName>
        <description>Attendee&apos;s country.</description>
        <inlineHelpText>Attendee&apos;s country.</inlineHelpText>
        <label>MailingCountry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailingPostalCode__c</fullName>
        <description>Attendee&apos;s postal code.</description>
        <inlineHelpText>Attendee&apos;s postal code.</inlineHelpText>
        <label>MailingPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingState__c</fullName>
        <description>Attendee&apos;s resident state.</description>
        <inlineHelpText>Attendee&apos;s resident state.</inlineHelpText>
        <label>MailingState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingStreet__c</fullName>
        <description>Attendee&apos;s street.</description>
        <inlineHelpText>Attendee&apos;s street.</inlineHelpText>
        <label>MailingStreet</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <description>The telephone number of the attendee.</description>
        <inlineHelpText>The telephone number of the attendee.</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Job title of the Attendee.</description>
        <inlineHelpText>Job title of the Attendee.</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/classes/AttendeeContactCreator.cls
/**
 * Helps us to make sure no Attendee__c record ever goes into the database without a matching Contact.
 * If we couldn't find a Contact, create one (and possibly a related Account as well).
 */
global with sharing class AttendeeContactCreator implements valence.TransformationFilter {

  public Boolean validFor(valence.LinkContext context) {

    if('business_conference_participants'.equalsIgnoreCase(context.linkSourceName) && 'Attendee__c'.equalsIgnoreCase(context.linkTargetName)) {
      return true;
    }
    return false;
  }

  public void process(valence.LinkContext context, List<valence.RecordInFlight> records) {

    /*
     * 1. Find records that are missing a Contact
     * 2. Look for existing Accounts
     * 3. Create Accounts that need to be created
     * 4. Create Contacts that need to be created (attaching Accounts)
     * 5. Attach Contact Ids to appropriate RecordInFlight instances
     */

    List<valence.RecordInFlight> recordsMissingContact = new List<valence.RecordInFlight>();
    Set<String> namesOfCompanies = new Set<String>();
    for(valence.RecordInFlight record : records) {
      if(!record.getProperties().containsKey('Contact__c')) {
        recordsMissingContact.add(record);
        namesOfCompanies.add(String.valueOf(record.getOriginalProperties().get('company')));

        // TODO - remove
        record.addWarning('Creating a new Contact (and maybe a new Account)');
      }
    }

    // if all our records are good, bail out
    if(recordsMissingContact.isEmpty()) {
      return;
    }

    // fetch all existing Accounts we can find that would be associated with Contacts we're about to create
    Map<String, Id> companyIdByName = new Map<String, Id>();
    for(Account company : [SELECT Id, Name FROM Account WHERE Name IN :namesOfCompanies]) {
      companyIdByName.put(company.Name, company.Id);
    }

    // create new contact records in memory
    List<Contact> newContacts = new List<Contact>();
    Map<String, List<Contact>> accountsAndRelatedContacts = new Map<String, List<Contact>>();
    for(valence.RecordInFlight record : recordsMissingContact) {
      Contact newContact = contactFromRecord(record);
      String companyName = (String)record.getOriginalProperties().get('company');
      if(companyIdByName.containsKey(companyName)) {
        newContact.AccountId = companyIdByName.get(companyName);
      }
      else {
        if(!accountsAndRelatedContacts.containsKey(companyName)) {
          accountsAndRelatedContacts.put(companyName, new List<Contact>());
        }
        accountsAndRelatedContacts.get(companyName).add(newContact);
      }
      newContacts.add(newContact);
    }

    // if we have to create some accounts, create them now and backfill the related contacts
    if(!accountsAndRelatedContacts.isEmpty()) {
      List<Account> accountsToInsert = new List<Account>();
      for(String companyName : accountsAndRelatedContacts.keySet()) {
        accountsToInsert.add(new Account(Name = companyName));
      }
      insert accountsToInsert;

      for(Account company : accountsToInsert) {
        for(Contact relatedContact : accountsAndRelatedContacts.get(company.Name)) {
          relatedContact.AccountId = company.Id;
        }
      }
    }

    // write these new contacts to the database
    insert newContacts;

    // match inserted contacts back to records
    for(Integer i = 0, j = newContacts.size(); i < j; i++) {
      recordsMissingContact[i].getProperties().put('Contact__c', newContacts[i].Id);
    }
  }

  /**
   * Convert a RecordInFlight to a Contact.
   *
   * @param record
   *
   * @return A Contact with fields from the RecordInFlight
   */
  private Contact contactFromRecord(valence.RecordInFlight record) {

    Map<String, Object> props = record.getProperties();
    return new Contact(
      FirstName = String.valueOf(props.get('FirstName__c')),
      LastName = String.valueOf(props.get('LastName__c')),
      Email = String.valueOf(props.get('Email__c')),
      Phone = String.valueOf(props.get('Telephone__c')),
      Title = String.valueOf(props.get('Title__c')),
      MailingStreet = String.valueOf(props.get('MailingStreet__c')),
      MailingCity = String.valueOf(props.get('MailingCity__c')),
      MailingState = String.valueOf(props.get('MailingState__c')),
      MailingPostalCode = String.valueOf(props.get('MailingPostalCode__c')),
      MailingCountry = String.valueOf(props.get('MailingCountry__c'))
    );
  }
}