src/objects/Attendee__c.object
<CustomObject>
    <description>Child records of Contacts to match attendance of events.</description>
    <fields>
        <fullName>AttendeeID__c</fullName>
        <description>The Evemttia ID of the attendee.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Evemttia ID of the attendee.</inlineHelpText>
        <label>Attendee ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessConference__c</fullName>
        <description>Establishes master- detail relationship between attendee and business conference.</description>
        <inlineHelpText>Establishes master- detail relationship between attendee and business conference.</inlineHelpText>
        <label>Business Conference</label>
        <referenceTo>Business_Conference__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <description>The Company of the attendee.</description>
        <inlineHelpText>The Company of the attendee.</inlineHelpText>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact record of this Attendee.</description>
        <inlineHelpText>The Contact record of this Attendee.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email address of the attendee.</description>
        <inlineHelpText>The email address of the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>The first name of the attendee.</description>
        <inlineHelpText>The first name of the attendee.</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>The last name of the attendee.</description>
        <inlineHelpText>The last name of the attendee.</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <description>The telephone number of the attendee.</description>
        <inlineHelpText>The telephone number of the attendee.</inlineHelpText>
        <label>Telephone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Business_Conference__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Record that shows campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Networking Tracks</relationshipLabel>
        <relationshipName>Networking_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventtiaID__c</fullName>
        <description>The Eventtia meeting ID number.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Eventtia meeting ID number.</inlineHelpText>
        <label>Eventtia ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Networking Track</label>
    <nameField>
        <label>Networking Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Networking Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>EventtiaID__c</fullName>
        <externalId>true</externalId>
        <label>Eventtia ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Meeting__c.object
<CustomObject>
    <description>Used to track U.S Suppliers and Foreign Buyers meetings at Trade Events.</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The participant of the meeting, like a foreign buyer.</description>
        <inlineHelpText>The participant of the meeting, like a foreign buyer.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BusinessConference__c</fullName>
        <description>Establishes master- detail relationship between attendee and business conference.</description>
        <inlineHelpText>Establishes master- detail relationship between attendee and business conference.</inlineHelpText>
        <label>Business Conference</label>
        <referenceTo>Business_Conference__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventtiaID__c</fullName>
        <description>External ID for the Eventtia Meeting ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID for the Eventtia Meeting ID.</inlineHelpText>
        <label>Eventtia ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The host of the meeting.</description>
        <inlineHelpText>The host of the meeting.</inlineHelpText>
        <label>Host</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Meetings (Host)</relationshipLabel>
        <relationshipName>Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the meeting. Whether or not it&apos;s been requested, accepted, or rejected.</description>
        <inlineHelpText>The status of the meeting. Whether or not it&apos;s been requested, accepted, or rejected.</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of meeting.</description>
        <inlineHelpText>The type of meeting.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>B2G</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                    <isActive>false</isActive>
                    <label>Demo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>M-{000}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Task_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    <recordTypes>
        <fullName>Tasks</fullName>
        <active>true</active>
        <description>Renamed for ITA Tasks</description>
        <label>Tasks</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MeetingCaseCreatorTest.cls
/**
 * Created by jeffweyhrauch on 2019-07-17.
 */

@IsTest private class MeetingCaseCreatorTest {

    @IsTest static void testRestriction() {

        valence.LinkContext context = new valence.LinkContext();
        context.linkSourceName = 'business_conference_meetings';
        context.linkTargetName = 'Meeting__c';

        System.assertEquals(true, new MeetingCaseCreator().validFor(context));
    }

    @IsTest static void testRestrictionBadSource() {

        valence.LinkContext context = new valence.LinkContext();
        context.linkSourceName = 'meetings';
        context.linkTargetName = 'Meeting__c';

        System.assertEquals(false, new AttendeeContactCreator().validFor(context));
    }

    @IsTest static void testRestrictionBadTarget() {

        valence.LinkContext context = new valence.LinkContext();
        context.linkSourceName = 'business_conference_meetings';
        context.linkTargetName = 'Meeting';

        System.assertEquals(false, new MeetingCaseCreator().validFor(context));
    }

    @IsTest static void testMeetingFilterBehavior() {
        Campaign myCampaign = new Campaign(Name='Campaign');
        insert myCampaign;

        Business_Conference__c busConf = new Business_Conference__c(Name='ABC Conference',EventtiaID__c='6666',Campaign__c=myCampaign.Id);
        insert busconf;

        Account alpha = new Account(Name = 'Alpha');
        Account beta = new Account(Name = 'Beta');
        insert new List<Account>{alpha, beta};

        Contact susie = new Contact(FirstName = 'Susan', LastName = 'Bean', Email = 'susie@alpha.org', Phone = '555-1111', AccountId = alpha.Id);
        Contact tom = new Contact(FirstName = 'Tom', LastName = 'Fiddle', AccountId = beta.Id);
        insert new List<Contact>{susie, tom};

        List<valence.RecordInFlight> records = new List<valence.RecordInFlight>{
                new valence.RecordInFlight(new Map<String, Object>{ // existing contact
                        'email' => 'susie@alpha.org',
                        'FirstName__c' => 'Susie',
                        'LastName__c' => 'Bean',
                        'company' => 'alpha',
                        'Telephone__c' => '555-1111',
                        'Contact__c' => susie.Id,
                        'AttendeeID__c' => '811111'
                }),
                new valence.RecordInFlight(new Map<String, Object>{ // existing company, new contact
                        'email' => 'sarahsword@beta.gov',
                        'FirstName__c' => 'Sarah',
                        'LastName__c' => 'Sword',
                        'company' => 'Beta',
                        'Telephone__c' => '555-3333',
                        'company' => 'Beta',
                        'AttendeeID__c' => '822222'
                }),
                new valence.RecordInFlight(new Map<String, Object>{ // new company, new contact
                        'email' => 'jim.thomas@charlie.org',
                        'FirstName__c' => 'Jim',
                        'LastName__c' => 'Thomas',
                        'company' => 'Charlie Group',
                        'Telephone__c' => '555-2222',
                        'company' => 'Charlie Group',
                        'AttendeeID__c' => '833333'
                })
        };

        // a little hacky, but we need to move the original properties into properties to mimic Valence mapping behavior
        for(valence.RecordInFlight record : records) {
            Map<String, Object> propRef = record.getProperties();
            for(String key : record.getOriginalProperties().keySet())
                propRef.put(key, record.getOriginalProperties().get(key));
        }

        Test.startTest();
        new AttendeeContactCreator().process(null, records);

        Attendee__c susan = new Attendee__c(Email__c='susie@alpha.org',FirstName__c='Susan',LastName__c='Bean',Company__c='Alpha',AttendeeID__c='811111',BusinessConference__c=busconf.Id,Contact__c=susie.Id);
        insert susan;
        Attendee__c sarah = new Attendee__c(Email__c='sarahsword@beta.gov',FirstName__c='Sarah',LastName__c='Sword',Company__c='Beta',AttendeeID__c='822222',BusinessConference__c=busconf.Id);
        insert sarah;

        List<valence.RecordInFlight> records2 = new List<valence.RecordInFlight>{

                new valence.RecordInFlight(new Map<String, Object>{
                        'Host__c' => sarah.Id,
                        'Attendee__c' => susan.Id,
                        //'Host__c' => hostId,
                        'participant_id' => '822222',
                        'location' => 'Fancy Restaurant',
                        'status' => '2',
                        'Status__c' => '2',
                        'id' => '333333',
                        'business_conference_id' => '6666'
                })

        };

        // a little hacky, but we need to move the original properties into properties to mimic Valence mapping behavior
        for(valence.RecordInFlight record : records2) {
            Map<String, Object> propRef = record.getProperties();
            for(String key : record.getOriginalProperties().keySet())
                propRef.put(key, record.getOriginalProperties().get(key));
        }


        new MeetingCaseCreator().process(null, records2);
        Test.stopTest();

        List<Account> accounts = [SELECT Id,Name FROM Account];
        System.debug(accounts.size());

        List<Contact> contacts = [SELECT Id, AccountId, Account.Name, FirstName, LastName, Email, Phone FROM Contact ORDER BY LastName];
        System.assertEquals(4, contacts.size());

        System.assertEquals('B2G',records2[0].getProperties().get('Type__c'));
        System.assertEquals('Accepted',records2[0].getProperties().get('Status__c'));

        List<Case> cases = [SELECT Id FROM Case];
        System.assertEquals(2,cases.size());

        List<Task> tasks = [SELECT Id FROM Task];
        System.assertEquals(0,tasks.size());
    }
}