src/objects/Automated_Chatter_Post__mdt.object
<CustomObject>
    <label>Automated Chatter Post</label>
    <pluralLabel>Automated Chatter Posts</pluralLabel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Administrative_Review_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Administrative Review Aligned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>New Shipper Review</value>
            </filterItems>
            <filterItems>
                <field>Segment__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Administrative Review</value>
            </filterItems>
            <filterItems>
                <field>$Source.ADCVD_Order__c</field>
                <operation>equals</operation>
                <valueField>Segment__c.ADCVD_Order__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Aligned New Shipper Reviews</relationshipLabel>
        <relationshipName>Aligned_New_Shipper_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Extension_of_days__c</fullName>
        <description>Final Extension (# of days)</description>
        <inlineHelpText>If &quot;Preliminary Extension (# of days)&quot; + &quot;Final Extension (# of days)&quot; &gt; 45 days, it is considered late.</inlineHelpText>
        <label>Final Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Litigation_Resolved__c</fullName>
        <label>Litigation Resolved</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Litigation_YesNo__c</fullName>
        <label>Litigation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prelim_Extension__c</fullName>
        <label>Prelim Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>New_Shipper_Review</fullName>
        <active>true</active>
        <label>New Shipper Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/SegmentChatterPostWriter.cls
/**
 * 
 *    Created by Joshua Moody & Skip Kleckner
 *    on Feb 28 2019
 *    MIL Corporation
 *    
 **/

public class SegmentChatterPostWriter extends ChatterPostWriter {
    
    //empty constructor for base class map
    public SegmentChatterPostWriter(){}
    
    //post templates from custom metadata
    private Map<String, Automated_Chatter_Post__mdt> postsMap = getPostsMap('Segment__c');
    
    //override your order logic for multiple post conditions
    public override void checkConditions(SObject newRecord, SObject oldRecord) {
        initiationExtensionChanged(newRecord, oldRecord);
        prelimExtensionChanged(newRecord, oldRecord);
        finalExtensionChanged(newRecord, oldRecord);
        alignmentChanged(newRecord, oldRecord);
        litigationChanged(newRecord, oldRecord);
    }
    
    //conditionally build post for Initiation Extension changes
    @TestVisible private void initiationExtensionChanged(SObject newRecord, SObject oldRecord) {
        //Variables specific to this condition
        String extensionFieldName = 'Initiation_Extension_of_days__c';
        Map<String, String> calculationFieldNameToLabelMap = new Map<String, String> {'Calculated_Initiation_Signature__c' => 'Calculated Initiation Signature'};
        //check if condition is met
        Map<String,String> newToOldValueMap = fieldChanged(extensionFieldName, newRecord, oldRecord);
        //if condition is not met, return
        if(newToOldValueMap.isEmpty() || newRecord.get('Calculated_Initiation_Signature__c') == null) {
            return;
        }
        //get details from record
        String detailsFromRecord = addExtensionChangeToPost('Initiation', newToOldValueMap);
        detailsFromRecord += addExtensionResultToPost(calculationFieldNameToLabelMap, newRecord);
        //insert case info into post template
        String templateWithCaseInfo = addTemplateWithCaseInfo(newRecord, postsMap.get('Extension'));
        //add the standard details to post and add to post map
        finishPost(templateWithCaseInfo, detailsFromRecord, newRecord, false);
    }
    
    //conditionally build post for Prelim Extension changes
    @TestVisible private void prelimExtensionChanged(SObject newRecord, SObject oldRecord) {
        //Variables specific to this condition
        String extensionFieldName = 'Prelim_Extension__c';
        Map<String, String> calculationFieldNameToLabelMap = new Map<String, String> {'Calculated_Preliminary_Signature__c' => 'Calculated Preliminary Signature'};
        //check if condition is met
        Map<String,String> newToOldValueMap = fieldChanged(extensionFieldName, newRecord, oldRecord);
        //if condition is not met, return
        if(newToOldValueMap.isEmpty() || newRecord.get('Calculated_Preliminary_Signature__c') == null) {
            return;
        }
        //get details from record
        String detailsFromRecord = addExtensionChangeToPost('Preliminary', newToOldValueMap);
        detailsFromRecord += addExtensionResultToPost(calculationFieldNameToLabelMap, newRecord);
        //insert case info into post template
        String templateWithCaseInfo = addTemplateWithCaseInfo(newRecord, postsMap.get('Extension'));
        finishPost(templateWithCaseInfo, detailsFromRecord, newRecord, false);
    }
    
    //conditionally build post for Final Extension changes
    @TestVisible private void finalExtensionChanged(SObject newRecord, SObject oldRecord) {
        //Variables specific to this condition
        String extensionFieldName = 'Final_Extension_of_days__c';
        Map<String, String> calculationFieldNameToLabelMap = new Map<String, String> {'Calculated_Final_Signature__c' => 'Calculated Final Signature'};
        //check if condition is met
        Map<String,String> newToOldValueMap = fieldChanged(extensionFieldName, newRecord, oldRecord);
        //if condition is not met, return
        if(newToOldValueMap.isEmpty() || newRecord.get('Calculated_Final_Signature__c') == null) {
            return;
        }
        //get details from record
        String detailsFromRecord = addExtensionChangeToPost('Final', newToOldValueMap);
        detailsFromRecord += addExtensionResultToPost(calculationFieldNameToLabelMap, newRecord);
        //insert case info into post template
        String templateWithCaseInfo = addTemplateWithCaseInfo(newRecord, postsMap.get('Extension'));
        finishPost(templateWithCaseInfo, detailsFromRecord, newRecord, false);
    }
    
    //conditionally build post for litigation field(s) changes
    @TestVisible private void litigationChanged(SObject newRecord, SObject oldRecord) {
        //get details from record
        String detailsFromRecord = getLitigationStateChange(newRecord, oldRecord);
        //check if condition is met
        if ((fieldChanged('Litigation_YesNo__c', newRecord, oldRecord).isEmpty()
            && fieldChanged('Litigation_Resolved__c', newRecord, oldRecord).isEmpty())
            || (detailsFromRecord == 'No Change')) {
            return;
        }
        //insert case info into post template
        String templateWithCaseInfo = addTemplateWithCaseInfo(newRecord, postsMap.get('Litigation Change'));
        //add the standard details to post and add to post map
        finishPost(templateWithCaseInfo, detailsFromRecord, newRecord, false);
    }
    
    //conditionally build post for alignment changes
    @TestVisible private void alignmentChanged(SObject newRecord, SObject oldRecord) {
        //Variables specific to this condition
        String alignmentLookupFieldName = 'Administrative_Review_Aligned_To__c';
        //check if condition is met
        Map<String, String> newToOldValueMap = fieldChanged(alignmentLookupFieldName, newRecord, oldRecord);
        if(newToOldValueMap.isEmpty()
            || Utils.getRecordTypeDeveloperNameMap(newRecord).get((Id)newRecord.get('RecordTypeId')) != 'New_Shipper_Review') {
            return;
        }
        //insert case info into post template
        String templateWithCaseInfo = addTemplateWithCaseInfo(newRecord, postsMap.get('Alignment'));
        String detailsFromRecord = addAlignmentChangeToPost(newToOldValueMap);

        //add the standard details to post and add to post map
        finishPost(templateWithCaseInfo, detailsFromRecord, newRecord, false);
    }
}