src/objects/Carousel_Item__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>Carousel_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Images that will be displayed on the Carousel</description>
        <inlineHelpText>The Images that will be displayed on the Carousel</inlineHelpText>
        <label>Image</label>
        <referenceTo>Image__c</referenceTo>
        <relationshipName>Carousel_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sliding Image</label>
    <nameField>
        <label>Sliding Image</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sliding Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <description>The Atom Body (Formatting should be done here)</description>
        <inlineHelpText>The Atom Body (Formatting should be done here)</inlineHelpText>
        <label>Atom</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Image</label>
        <referenceTo>Image__c</referenceTo>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Atom</label>
    <nameField>
        <label>Atom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atoms</pluralLabel>
    <recordTypes>
        <fullName>Carousel</fullName>
        <active>true</active>
        <description>Large images, with title and description, which slide across the page; aka Hero Box</description>
        <label>Carousel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Image__c.object
<CustomObject>
    <fields>
        <fullName>Image__c</fullName>
        <formula>IMAGE(&quot;/servlet/servlet.FileDownload?file=&quot;+ Location__c , alt__c, 100, 296)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Location</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>alt__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Navigation_Group__c.object
<CustomObject>
    <fields>
        <fullName>Chatter_Group__c</fullName>
        <description>If this field is populated, the Navigation group will direct the user to the Chatter Group populated</description>
        <inlineHelpText>If this field is populated, the Navigation group will direct the user to the Chatter Group populated</inlineHelpText>
        <label>Chatter Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>If this field is populated, the Navigation group will direct the user to the Page populated (Chatter Group takes priority)</description>
        <inlineHelpText>The Page this Navigation Group will link to if the Navigation Group is clicked.</inlineHelpText>
        <label>Page Link</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Navigation</relationshipLabel>
        <relationshipName>Navigation_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Site that this Navigation Group will appear on</description>
        <inlineHelpText>The Site that this Navigation Group will appear on</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Navigation</relationshipLabel>
        <relationshipName>Navigation_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>If this field is populated, the Navigation group link will be directed to this URL.</description>
        <inlineHelpText>This field allows you to link to an external web site. If populated with a URL, it will override the Page field. Note: http:// is not needed.</inlineHelpText>
        <label>Custom URL</label>
        <type>Url</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Navigation_Link__c.object
<CustomObject>
    <fields>
        <fullName>Navigation_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Navigation Group that this Navigation Link will appear on</description>
        <inlineHelpText>The Navigation Group that this Navigation Link will appear on</inlineHelpText>
        <label>Navigation Group</label>
        <referenceTo>Navigation_Group__c</referenceTo>
        <relationshipLabel>Navigation Links</relationshipLabel>
        <relationshipName>Navigation_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this field is populated, the Navigation link will direct the user to the Page specified</description>
        <inlineHelpText>If this field is populated, the Navigation link will direct the user to the Page specified</inlineHelpText>
        <label>Page Link</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Navigation Links</relationshipLabel>
        <relationshipName>Navigation_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Team Object that this Navigation Link will appear on</description>
        <inlineHelpText>The MicroSite which this Navigation Link will appear.</inlineHelpText>
        <label>MicroSite</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Navigation Links</relationshipLabel>
        <relationshipName>Navigation_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Navigation Link</label>
    <nameField>
        <label>Navigation Link</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Links</pluralLabel>
    <recordTypes>
        <fullName>Link</fullName>
        <active>true</active>
        <description>Navigation Link items that direct a user to a link</description>
        <label>Link</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <description>Groups of Navigation Link items inside a MegaMenu</description>
        <label>Mega Section</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Atom</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You cannot select a Carousel for this content.</errorMessage>
            <filterItems>
                <field>Content__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Carousel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Home_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template_Page__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MicroSite</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page_Content__c.object
<CustomObject>
    <description>Junction object between Content, Pages, and Rows.</description>
    <fields>
        <fullName>Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Atom that will be used in this page Content Container</description>
        <inlineHelpText>The Atom that will be used in this page Content Container</inlineHelpText>
        <label>Atom</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>Page_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>The Page this Atom will be displayed on</description>
        <inlineHelpText>The Page this Atom will be displayed on</inlineHelpText>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Elements</relationshipLabel>
        <relationshipName>Page_Contents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Element</label>
    <nameField>
        <displayFormat>E {0}</displayFormat>
        <label>Element Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <recordTypes>
        <fullName>Carousel</fullName>
        <active>true</active>
        <description>Large images, with title and description, which slide across the page; aka Hero Box</description>
        <label>Carousel</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MicroSite Homepage</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>MicroSites</relationshipLabel>
        <relationshipName>MicroSites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>MicroSite</label>
    <nameField>
        <label>MicroSite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MicroSites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>This represents a Salesforce.com Site or Community, but does not actually control the availability of a Site.</description>
    <fields>
        <fullName>Domain__c</fullName>
        <description>The site URL</description>
        <externalId>true</externalId>
        <inlineHelpText>The site URL</inlineHelpText>
        <label>Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site_CSS__c</fullName>
        <description>The location of the style used by the site</description>
        <externalId>true</externalId>
        <inlineHelpText>The location of the style used by the site</inlineHelpText>
        <label>Site Colors</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Logo__c</fullName>
        <description>The Logo that is displayed on the top left corner of the page</description>
        <externalId>true</externalId>
        <inlineHelpText>The Logo that is displayed on the top left corner of the page</inlineHelpText>
        <label>Site Logo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Name that will be displayed on the browser tab</description>
        <inlineHelpText>Name that will be displayed on the browser tab</inlineHelpText>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseAsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseAsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/URL__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipName>URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>URL</label>
    <nameField>
        <displayFormat>URL-{00000}</displayFormat>
        <label>URL Rewrite Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>URLs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_CMS.cls
@isTest(seealldata = false)
public class TEST_CMS{
    /*
    IMPORTANT!
    This class is only use to test the CMS portion of the application, not the additional tools used with the app.
    The application consists of the Site Template and Page (and page components)
    */
    public static testMethod void SingleSiteDomain(){
        //The Site_Template_Controller used on Page should pull in the Site__c that has the domain associated to the current domain.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        PageReference pageRef = Page.page;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
            system.assertNotEquals(site.id, null);
            system.assertNotEquals(controller.main, null);
    }
    
    public static testMethod void MultipleDomain_CurrentDomain(){
        //The Site_Template_Controller used on Page should pull in the Site__c that has the domain associated to the current domain, even though there is another Site__c with 'UseAsDefault' set.
        Site__c[] sites = new Site__c[]{};
            sites.add(new Site__c(name = 'Export', title__c = 'Export.gov', domain__c = 'test.url', UseAsDefault__c = true, site_css__c = '/css/sample.css', site_logo__c = '/img/sample.png'));
            sites.add(new Site__c(name = 'SUSA', title__c = 'Select USA', domain__c = URL.getSalesforceBaseUrl().getHost(), UseAsDefault__c = false, site_css__c = '/css/sample.css', site_logo__c = '/img/sample.png'));
        insert sites;
        PageReference pageRef = Page.page;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
            system.assertEquals(controller.main.id, sites[1].id);        
    }
    
    public static testMethod void NoCurrentDomain(){
        //The Site_Template_Controller used on Page should pull in the Site__c that has the attribute 'UseAsDefault' set if the current domain does not match any existing record.
        Site__c[] sites = new Site__c[]{};
            sites.add(new Site__c(name = 'Export', title__c = 'Export.gov', domain__c = 'test.url', UseAsDefault__c = true, site_css__c = '/css/sample.css', site_logo__c = '/img/sample.png'));
            sites.add(new Site__c(name = 'SUSA', title__c = 'Select USA', domain__c = 'selectusa.gov', UseAsDefault__c = false, site_css__c = '/css/sample.css', site_logo__c = '/img/sample.png'));
        insert sites;
        PageReference pageRef = Page.page;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
            system.assertEquals(controller.main.id, sites[0].id);        
    }
    
    public static testMethod void SingleGroup_SingleSite_NoLinks(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test'));
        insert groups;
        //this test only uses one navigation group as it is only testing the following:
        //1) that the navigation group is put into the list of fields for the navigation
        //2) that the url for the group link is '#'
        PageReference pageRef = Page.page;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();

        system.assertNotEquals(controller.NavigationGroups, null);
        system.assertEquals(controller.NavigationGroups.size(), 1);
        //system.assertEquals(controller.NavigationGroups[0].url, '#');
    }

    public static testMethod void SingleGroup_SingleSite_NoLinks_ChatterGroupRedirect(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;        
        CollaborationGroup chatter = new CollaborationGroup(name='Chatter Test', collaborationtype = 'Public');
        insert chatter;
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test', chatter_group__c = 'Chatter Test'));
        insert groups;
        //this test only uses one navigation group as it is only testing the following:
        //1) that the navigation group is put into the list of fields for the navigation
        //2) that the url for the group link is '/apex/group?id=[chatter.id]'
        PageReference pageRef = Page.page;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();

        system.assertNotEquals(controller.NavigationGroups, null);
        system.assertEquals(controller.NavigationGroups.size(), 1);
        //system.assertEquals(controller.NavigationGroups[0].url, '/apex/group?id='+chatter.id);
    }

    public static testMethod void SingleGroup_SingleSite_SingleLink_NoContent(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test', url__c = 'salesforce.com'));
        insert groups;
        Page__c pg = new Page__c(name = 'Test Page');
        insert pg;
        Navigation_Link__c link = new Navigation_Link__c(Navigation_Group__c = groups[0].id, Page__c=pg.id);
        insert link;
        //this test only uses one navigation group as it is only testing the following:
        //1) that the navigation group is put into the list of fields for the navigation
        //2) that the url for the group link is '#'
        //3) that the group contains a link
        PageReference pageRef = Page.page;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();

        system.assertNotEquals(controller.NavigationGroups, null);
        system.assertEquals(controller.NavigationGroups.size(), 1);
        system.assertEquals(controller.NavigationGroups[0].url, 'http://salesforce.com');
        system.assertEquals(controller.NavigationGroups[0].links.size(), 1);
        system.assertEquals(controller.NavigationGroups[0].links[0].page__c, pg.id);
    }

    public static testMethod void SingleGroup_SingleSite_SingleLink_SinglePageContent_WithSection(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test'));
        insert groups;
        Page__c home = new Page__c(name = 'Test Home Page');
        insert home;
        Section__c section = new Section__c(name='section 1', page__c = home.id);
        insert section;
        Page__c pg = new Page__c(name = 'Test Page', section__c = section.id);
        insert pg;
        Content__c content = new Content__c(content__c = '<h1>Hello World!</h1>');
        insert content;
        Page_Content__c pc = new Page_Content__c(page__c = pg.id, content__c = content.id);
        insert pc;
        Navigation_Link__c link = new Navigation_Link__c(Navigation_Group__c = groups[0].id, Page__c=pg.id);
        insert link;
        PageReference pageRef = Page.page;
            pageRef.getParameters().put('id', pg.id);
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
        ApexPages.StandardController stdPg = new ApexPages.StandardController(pg);
        Page_Section_Controller PSC = new Page_Section_Controller(stdPg);

        system.assertNotEquals(controller.NavigationGroups, null);
        system.assertEquals(controller.NavigationGroups.size(), 1);
        system.assertEquals(controller.NavigationGroups[0].url, '#');
        system.assertEquals(controller.NavigationGroups[0].links.size(), 1);
        system.assertEquals(controller.NavigationGroups[0].links[0].page__c, pg.id);
        system.assertEquals(PSC.section.id, section.id); 
        system.assertEquals(PSC.page.id, pg.id);              
    }

    public static testMethod void SingleGroup_SingleSite_SingleLink_SinglePageContent_Carousel(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test'));
        insert groups;
        Page__c home = new Page__c(name = 'Test Home Page');
        insert home;
        Section__c section = new Section__c(name='section 1', page__c = home.id);
        insert section;
        Content__c content = new Content__c( name='Carousel Test', RecordTypeId = [select id from RecordType where SObjectType = 'Content__c' and name='Carousel' limit 1].id);
        insert content;
        Image__c img = new Image__c(Name = 'Image 1', alt__c = 'test alt', location__c = '/img/image.jpg');
        insert img;
        Carousel_Item__c item = new Carousel_Item__c(image__c = img.id, content__c = content.id);
        insert item;
        CollaborationGroup chatter = new CollaborationGroup(name='Chatter Test', collaborationtype = 'Public');
        insert chatter;        
        Page__c pg = new Page__c(name = 'Test Page', section__c = section.id, carousel__c = content.id, collaboration_group__c = 'Chatter Test');
        insert pg;
        Navigation_Link__c link = new Navigation_Link__c(Navigation_Group__c = groups[0].id, Page__c=pg.id);
        insert link;
        PageReference pageRef = Page.page;
            pageRef.getParameters().put('id', pg.id);
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
        ApexPages.StandardController stdPg = new ApexPages.StandardController(pg);
        Page_Section_Controller PSC = new Page_Section_Controller(stdPg);

        system.assertNotEquals(controller.NavigationGroups, null);
        system.assertEquals(controller.NavigationGroups.size(), 1);
        system.assertEquals(controller.NavigationGroups[0].url, '#');
        system.assertEquals(controller.NavigationGroups[0].links.size(), 1);
        system.assertEquals(controller.NavigationGroups[0].links[0].page__c, pg.id);
        system.assertEquals(PSC.section.id, section.id); 
        system.assertEquals(PSC.page.id, pg.id);          
    }
    
    public static testMethod void Landing(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test'));
        insert groups;
        Page__c home = new Page__c(name = 'Test Home Page');
        insert home;
        Section__c section = new Section__c(name='section 1', page__c = home.id);
        insert section;
        Page__c pg = new Page__c(name = 'Test Page', section__c = section.id);
        insert pg;
        Content__c content = new Content__c(content__c = '<h1>Hello World!</h1>');
        insert content;
        Page_Content__c pc = new Page_Content__c(page__c = pg.id, content__c = content.id);
        insert pc;
        Navigation_Link__c link = new Navigation_Link__c(Navigation_Group__c = groups[0].id, Page__c=pg.id);
        insert link;
        PageReference pageRef = Page.landing;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
        Landing_Controller landing = new Landing_Controller(); 
        landing.redirect();
    }    

    public static testMethod void Landing_withPage(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Page__c pg = new Page__c(name = 'Test Page');
        insert pg;
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
            site.default_page__c = pg.id;
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test'));
        insert groups;
        Page__c home = new Page__c(name = 'Test Home Page');
        insert home;
        Section__c section = new Section__c(name='section 1', page__c = home.id);
        insert section;
        Content__c content = new Content__c(content__c = '<h1>Hello World!</h1>');
        insert content;
        Page_Content__c pc = new Page_Content__c(page__c = pg.id, content__c = content.id);
        insert pc;
        Navigation_Link__c link = new Navigation_Link__c(Navigation_Group__c = groups[0].id, Page__c=pg.id);
        insert link;
        PageReference pageRef = Page.landing;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
        Landing_Controller landing = new Landing_Controller(); 
        landing.redirect();
    }    

    public static testMethod void Landing_withRedirect(){
        //NOTE:  This test assumes that the previous tests pass, and so uses the setup data that was also used in SingleSiteDomain() test method.
        //The navigation in this test sets up a single page but does not create content as it is only testing the navigation links.
        Page__c pg = new Page__c(name = 'Test Page');
        insert pg;
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
            site.VisualForce_Redirect__c = 'apex/market_intelligence_latest';
        insert site;        
        Navigation_Group__c[] groups = new Navigation_Group__c[]{};
            groups.add(new Navigation_Group__c(Site__c = site.id, name = 'Test'));
        insert groups;
        Page__c home = new Page__c(name = 'Test Home Page');
        insert home;
        Section__c section = new Section__c(name='section 1', page__c = home.id);
        insert section;
        Content__c content = new Content__c(content__c = '<h1>Hello World!</h1>');
        insert content;
        Page_Content__c pc = new Page_Content__c(page__c = pg.id, content__c = content.id);
        insert pc;
        Navigation_Link__c link = new Navigation_Link__c(Navigation_Group__c = groups[0].id, Page__c=pg.id);
        insert link;
        PageReference pageRef = Page.landing;
        Test.setCurrentPage(pageRef);
        Site_Template_Controller controller = new Site_Template_Controller();
        Landing_Controller landing = new Landing_Controller(); 
        landing.redirect();
    }
    
    public static testMethod void ImageManager(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.upload();
    }

    public static testMethod void ImageManager_no_Body(){
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.upload();   
    }

    public static testMethod void CarouselManager_Search(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.upload();

        controller.name = 'Upload 2';
        controller.filename = 'testImage2.jpg';
        controller.description = 'Test Description of the Second Image'; 
        controller.image.body = b;
        controller.upload();   

        Content__c c = new Content__c();
        c.recordtypeid = [select id from recordtype where sobjecttype = 'content__c' and name = 'Carousel' limit 1].id;
        insert c;
        
        ApexPages.StandardController stdPg = new ApexPages.StandardController(c);
        pageRef = page.carouselManager;
        test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.id);
        CarouselController cont = new CarouselController(stdPg);
        
        Image__c[] images = cont.getImages();
        system.assertEquals(images.size(), 0);
        
        cont.search = '2';
        cont.search();
        system.assertEquals(cont.getImages().size(), 0); 
    }
    
    public static testMethod void CarouselManager_AddSlide(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.type = 'Carousel Image';
        controller.upload();

        controller.name = 'Upload 2';
        controller.filename = 'testImage2.jpg';
        controller.description = 'Test Description of the Second Image'; 
        controller.type = 'Carousel Image';
        controller.image.body = b;
        controller.upload();   

        Content__c c = new Content__c();
        c.recordtypeid = [select id from recordtype where sobjecttype = 'content__c' and name = 'Carousel' limit 1].id;
        insert c;
        
        ApexPages.StandardController stdPg = new ApexPages.StandardController(c);
        pageRef = page.carouselManager;
        test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.id);
        CarouselController cont = new CarouselController(stdPg);
        
        Image__c[] images = cont.getImages();
        system.assertEquals(images.size(), 2);
        system.assertEquals(cont.getCItems().size(), 0);
        cont.search = '2';
        cont.search();
        system.assertEquals(cont.getImages().size(), 1); 
        ApexPages.currentPage().getParameters().put('img', cont.getImages()[0].id);
        cont.doNothing();
        cont.saveSlide();
        system.assertEquals(cont.getCItems().size(), 1);
    }

    public static testMethod void CarouselManager_AddSlide_Error(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.upload();

        controller.name = 'Upload 2';
        controller.filename = 'testImage2.jpg';
        controller.description = 'Test Description of the Second Image'; 
        controller.image.body = b;
        controller.upload();   

        Content__c c = new Content__c();
        c.recordtypeid = [select id from recordtype where sobjecttype = 'content__c' and name = 'Carousel' limit 1].id;
        insert c;
        
        ApexPages.StandardController stdPg = new ApexPages.StandardController(c);
        pageRef = page.carouselManager;
        test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.id);
        CarouselController cont = new CarouselController(stdPg);
        
        Image__c[] images = cont.getImages();
        system.assertEquals(images.size(), 0);
        system.assertEquals(cont.getCItems().size(), 0);
        cont.search = '2';
        cont.search();
        system.assertEquals(cont.getImages().size(), 0); 
        cont.saveSlide();
        system.assertEquals(cont.getCItems().size(), 0);
    }

    public static testMethod void CarouselManager_Cancel(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.type = 'Carousel Image';
        controller.upload();

        controller.name = 'Upload 2';
        controller.filename = 'testImage2.jpg';
        controller.description = 'Test Description of the Second Image'; 
        controller.type = 'Carousel Image';
        controller.image.body = b;
        controller.upload();   

        Content__c c = new Content__c();
        c.recordtypeid = [select id from recordtype where sobjecttype = 'content__c' and name = 'Carousel' limit 1].id;
        insert c;
        
        ApexPages.StandardController stdPg = new ApexPages.StandardController(c);
        pageRef = page.carouselManager;
        test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.id);
        CarouselController cont = new CarouselController(stdPg);
        
        Image__c[] images = cont.getImages();
        system.assertEquals(images.size(), 2);
        system.assertEquals(cont.getCItems().size(), 0);
        cont.search = '2';
        cont.search();
        system.assertEquals(cont.getImages().size(), 1); 
        ApexPages.currentPage().getParameters().put('img', cont.getImages()[0].id);
        cont.doNothing();
        cont.Cancel();
        system.assertEquals(cont.getCItems().size(), 0);
    }

    public static testMethod void CarouselManager_DeleteSlide(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.type = 'Carousel Image';
        controller.upload();

        controller.name = 'Upload 2';
        controller.filename = 'testImage2.jpg';
        controller.description = 'Test Description of the Second Image'; 
        controller.image.body = b;
        controller.type = 'Carousel Image';
        controller.upload();   

        Content__c c = new Content__c();
        c.recordtypeid = [select id from recordtype where sobjecttype = 'content__c' and name = 'Carousel' limit 1].id;
        insert c;
        
        ApexPages.StandardController stdPg = new ApexPages.StandardController(c);
        pageRef = page.carouselManager;
        test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.id);
        CarouselController cont = new CarouselController(stdPg);
        
        Image__c[] images = cont.getImages();
        system.assertEquals(images.size(), 2);
        system.assertEquals(cont.getCItems().size(), 0);
        cont.search = '2';
        cont.search();
        system.assertEquals(cont.getImages().size(), 1); 
        ApexPages.currentPage().getParameters().put('img', cont.getImages()[0].id);
        cont.doNothing();
        cont.saveSlide();
        system.assertEquals(cont.getCItems().size(), 1);
        system.assertNotEquals(cont.getCItems()[0].id, null);
        ApexPages.currentPage().getParameters().put('ci', cont.getCItems()[0].id);
        //ApexPages.currentPage().getParameters().put('img', null);
        cont.doNothing();
        system.assertNotEquals(cont.cItem, null);
        system.assertNotEquals(cont.cItem.id, null);
        cont.deleteSlide();
    }

    public static testMethod void CarouselManager_DeleteSlide_Error(){
        Blob b = Blob.valueOf('Test Data');  
        PageReference pageRef = page.imageManager;
        test.setCurrentPage(pageRef);
        imageManager_Controller controller = new imageManager_Controller();
        controller.name = 'Image Upload';
        controller.filename = 'testImage.jpg';
        controller.description = 'Test Description of an Image';
        controller.image.body = b;
        controller.upload();

        controller.name = 'Upload 2';
        controller.filename = 'testImage2.jpg';
        controller.description = 'Test Description of the Second Image'; 
        controller.image.body = b;
        controller.upload();   

        Content__c c = new Content__c();
        c.recordtypeid = [select id from recordtype where sobjecttype = 'content__c' and name = 'Carousel' limit 1].id;
        insert c;
        
        ApexPages.StandardController stdPg = new ApexPages.StandardController(c);
        pageRef = page.carouselManager;
        test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c.id);
        CarouselController cont = new CarouselController(stdPg);
        
        Image__c[] images = cont.getImages();
        system.assertEquals(images.size(), 0);
        system.assertEquals(cont.getCItems().size(), 0);
        cont.search = '2';
        cont.search();
        system.assertEquals(cont.getImages().size(), 0); 

        cont.deleteSlide();
    }
    
    public static testMethod void TestSiteMap(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Site__c site2 = new Site__c();
            site2.name = 'Second Site';
            site2.domain__c = 'google.com';
            site2.title__c = 'Google!';
            site2.Site_CSS__c = '/css/sample.css' ;
            site2.site_logo__c = '/img/sample.png';
            site2.UseAsDefault__c = false;
        insert site2;
        
        Page__c[] pages = new Page__c[]{
            new Page__c(name='page1', site__c = site2.id),
            new Page__c(name='page2', site__c = site.id),
            new Page__c(name='page3', site__c = site2.id),
            new Page__c(name='page4', site__c = site.id)
        };
        insert pages;
        
        PageReference pageRef = Page.SiteMap;
        Test.setCurrentPage(pageRef);
        SiteMap_Controller controller = new SiteMap_Controller();
        system.assertEquals([select id from page__c].size(), 4);
        system.assertEquals(controller.getPages().size(), 2);
        system.assertEquals(controller.getXML(), '<?xml version="1.0" encoding="UTF-8"?>');
    }
}