src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee-Based Services</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Fee-Based Services Used</fullName>
                    <default>true</default>
                    <label>No Fee-Based Services Used</label>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Business Facilitation Service</fullName>
                </value>
                <value>
                    <fullName>Business Service Provider</fullName>
                </value>
                <value>
                    <fullName>BuyUSA.gov Business Service Provider</fullName>
                </value>
                <value>
                    <fullName>Certification Letter</fullName>
                </value>
                <value>
                    <fullName>Certified Trade Mission</fullName>
                </value>
                <value>
                    <fullName>Contact List</fullName>
                </value>
                <value>
                    <fullName>Customized Market Research</fullName>
                </value>
                <value>
                    <fullName>Featured US Exporters (FUSE)</fullName>
                </value>
                <value>
                    <fullName>Foreign Buyer Delegation</fullName>
                </value>
                <value>
                    <fullName>Gold Key Matching Service</fullName>
                </value>
                <value>
                    <fullName>HQ Use Only - Administration</fullName>
                </value>
                <value>
                    <fullName>Initial Market Check</fullName>
                </value>
                <value>
                    <fullName>International Company Profile</fullName>
                </value>
                <value>
                    <fullName>International Company Profile – Full</fullName>
                </value>
                <value>
                    <fullName>International Company Profile – Partial</fullName>
                </value>
                <value>
                    <fullName>International Partner Search</fullName>
                </value>
                <value>
                    <fullName>International Partner Search + Virtual Introductions</fullName>
                </value>
                <value>
                    <fullName>Facilitated Investment Mission</fullName>
                </value>
                <value>
                    <fullName>Platinum Key Service</fullName>
                </value>
                <value>
                    <fullName>Quicktake</fullName>
                </value>
                <value>
                    <fullName>Single Company Promotion</fullName>
                </value>
                <value>
                    <fullName>Tourism Research Programs</fullName>
                </value>
                <value>
                    <fullName>Single Location Promotion</fullName>
                </value>
                <value>
                    <fullName>Trade Event</fullName>
                </value>
                <value>
                    <fullName>Trade Mission</fullName>
                </value>
                <value>
                    <fullName>Trade Show Representation</fullName>
                </value>
                <value>
                    <fullName>Virtual Fair</fullName>
                </value>
                <value>
                    <fullName>Website Globalization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>to select record type with one button publisher</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Commercial Diplomacy</fullName>
                </value>
                <value>
                    <fullName>Export Promotion</fullName>
                </value>
                <value>
                    <fullName>Investment Promotion</fullName>
                </value>
                <value>
                    <fullName>Client Assist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/sendToConnection.cls
public class sendToConnection{
    public static void shareFY16Records(){
        List <Case> casesToShare = [SELECT Id, CaseNumber, Subject FROM CASE 
									WHERE Record_Type__c = 'Export Promotion' 
									AND Fee__c != '' 
									AND Fee__c != 'No Fee-Based Services Used' 
									AND Fee__c != 'HQ Use Only - Administration'
                                    AND Status = 'Successfully Closed'
                                    AND Contact.HasOptedOutOfEmail = false
                                    AND ClosedDate > 2015-09-30T23:01:01+01:00];
        System.debug('# of Cases to Share = ' + casesToShare.size());
        String connName = 'Export-Import Bank of the United States';
        ID networkID = ConnectionHelper.getConnectionId(connName);
        List<PartnerNetworkRecordConnection> caseConnections =  new  List<PartnerNetworkRecordConnection>();
        
        //Ensures that the list has a value
        if (casesToShare.size() > 0 ) {
            for (Case o: casesToShare){
                PartnerNetworkRecordConnection newConnection = 
                      new PartnerNetworkRecordConnection( 
                          ConnectionId = networkId, 
                          LocalRecordId = o.Id, 
                          SendClosedTasks = false, 
                          SendOpenTasks = false, 
                          SendEmails = false 
                         // ParentRecordId = o.AccountId
                         ); 
                          
                 caseConnections.add(newConnection);  
            }
            
            //Ensure that records were added to send to connection
            if (caseConnections.size() > 0){
                database.insert(caseConnections);
            }
        }
    }
	
}