src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Participant_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Application</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Application Contacts</relationshipLabel>
        <relationshipName>Participant_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Organization Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Organization Corporate Officer</fullName>
                </value>
                <value>
                    <fullName>International Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Application Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The Application abbreviation.  For a refund, is used to determine the pay.gov TCS_APP_ID.</description>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Privacy Shield</fullName>
                    <default>true</default>
                    <label>Privacy Shield</label>
                </value>
                <value>
                    <fullName>Event or Service</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                    <isActive>false</isActive>
                    <label>PS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Participant on the Order record.</description>
        <formula>Order__r.Participant__r.Name</formula>
        <inlineHelpText>Participant on the Order record.</inlineHelpText>
        <label>Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>ACH_CREDIT</fullName>
                </value>
                <value>
                    <fullName>AMAZON</fullName>
                </value>
                <value>
                    <fullName>PAYPAL</fullName>
                </value>
                <value>
                    <fullName>DWOLLA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TEST_PaymentTriggerHandler.cls
@isTest(seeAllData=false)
public class TEST_PaymentTriggerHandler{

	public static testmethod void TEST_1(){
		Payment__c payment1 = new Payment__c();
	    insert payment1;
	    Payment__c payment2 = new Payment__c();
	    insert payment2;
	    Payment__c[] newList = new List<Payment__c>();
		newList.add(payment1);
		newList.add(payment2);
		Map<id, Payment__c> newMap = new Map<id, Payment__c>();
		Map<id, Payment__c> oldMap = new Map<id, Payment__c>();
		Test.startTest();    
		PaymentTriggerHandler.createCases(newList, newMap, oldMap);
		system.assertEquals(null, null);  //Nothing is return from createCases so nothing can be compared
		Test.stopTest();
	}
    
    @IsTest
	static void testCreatePrivacyShieldPaymentCases_Update() {
		List<Payment__c> payments = getPrivacyShieldPayments(10);
		Test.startTest();
		updatePaymentStatusAndType(payments);
		Test.stopTest();
		System.assertEquals(10, [SELECT COUNT() FROM Case],
			'Verify Privacy Shield cases were created by future method');
	}

	static List<Payment__c> getPrivacyShieldPayments(Integer recordsToAdd) {
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsToAdd; i++) {
			Account acct = new Account(Name = 'TestAccount' + i, Website = 'www.test' + i + '.com');
			accounts.add(acct);
		}
		insert accounts;
		// Create related contacts
		List<Contact> contacts = new List<Contact>();
		for (Integer j = 0; j < accounts.size(); j++) {
			Contact con = new Contact(
				FirstName = 'Test ' + j,
				LastName = 'Test ' + j,
				AccountId = accounts[j].Id,
				Email = 'test' + j + '@test.org.com'
			);
			contacts.add(con);
		}
		insert contacts;
		// Create applications
		List<Participation__c> applications = new List<Participation__c>();
		for (Account account: accounts) {
			applications.add(
				new Participation__c(
					Organization__c = account.Id,
					Postal_Code__c = '55555'
				)
			);
		}
		insert applications;
		List<Participant_Contact__c> applicationContacts = new List<Participant_Contact__c>();
		for (Integer k = 0; k < applications.size(); k++) {
			applicationContacts.add(
				new Participant_Contact__c(
					Participant__c = applications[k].Id,
					Role__c = 'Primary Contact',
					Contact__c = contacts[k].Id
				)
			);
		}
		insert applicationContacts;
		// Create product and pricebook
		Product2 product = new Product2(Name = 'Privacy Shield Product', IsActive = true);
		insert product;
		Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry standardPricebookEntry = new PricebookEntry(
			Pricebook2Id = pricebookId,
			Product2Id = product.Id,
			UnitPrice = 1000,
			IsActive = true
		);
		insert standardPricebookEntry;
		Pricebook2 pricebook = TestUtils.createPricebook('Privacy Shield', true, true);
		PricebookEntry pricebookEntry = new PricebookEntry(
			IsActive = true,
			UnitPrice = 1000,
			Pricebook2Id = pricebook.Id,
			Product2Id = product.Id
		);
		insert pricebookEntry;
		// Create orders
		List<Order> orders = new List<Order>();
		for (Participation__c application: applications) {
			orders.add(
				new Order(
					Participant__c = application.Id,
					AccountId = application.Organization__c,
					Status = 'In Progress',
					Description = 'Privacy Shield',
					EffectiveDate = Date.today(),
					Pricebook2Id = pricebook.Id
				)
			);
		}
		insert orders;
		// Create order items
		List<OrderItem> orderItems = new List<OrderItem>();
		for (Order order: orders) {
			orderItems.add(
				new OrderItem(
					OrderId = order.Id,
					Quantity = 1,
					PricebookEntryId = pricebookEntry.Id,
					UnitPrice = pricebookEntry.UnitPrice
				)
			);
		}
		insert orderItems;
		// Create payments
		List<Payment__c> payments = new List<Payment__c>();
		for (Order order: orders) {
			payments.add(new Payment__c(Order__c = order.Id, Application__c = 'Privacy Shield'));
		}
		insert payments;
		return payments;
	}
    
    static void updatePaymentStatusAndType(List<Payment__c> payments) {
		for (Integer i = 0; i < payments.size(); i++) {
			if (Math.mod(i, 2) == 0) {
				payments[i].Transaction_Status__c = 'Success';
				payments[i].Payment_Type__c = 'PLASTIC_CARD';
			} else {
				payments[i].Transaction_Status__c = 'Received';
				payments[i].Payment_Type__c = 'ACH';
			}
		}
		update payments;
	}

}