src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Participation</fullName>
        <active>true</active>
        <businessProcess>Trade Support</businessProcess>
        <description>Privacy Shield Web Assistance Case Type - https://www.privacyshield.gov/assistance</description>
        <label>Participation</label>
    </recordTypes>
    <recordTypes>
        <fullName>U_S_Business</fullName>
        <active>true</active>
        <businessProcess>Trade Support</businessProcess>
        <description>Case management RT for Privacy Shield applications using Participation App</description>
        <label>Privacy Shield</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Participation</relationshipLabel>
        <relationshipName>Participation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Participant on the Order record.</description>
        <formula>Order__r.Participant__r.Name</formula>
        <inlineHelpText>Participant on the Order record.</inlineHelpText>
        <label>Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PaymentTriggerHandler.cls
Public without sharing Class PaymentTriggerHandler {
    public static void createCases(Payment__c[] newList, map<id, Payment__c> newMap, map<id, Payment__c> oldMap){
        Set<Id> newListIds = new Set<Id>();
        for(Payment__c payment : newList){
            if(payment != null && payment.order__c !=  null && oldMap.get(payment.id) != null && oldMap.get(payment.id).Transaction_Status__c != payment.Transaction_Status__c && (payment.Transaction_Status__c == 'Received' || payment.Transaction_Status__c == 'Success')){
                newListIds.add(payment.id);
            }
        }
        createCaseFuture(newListIds);
    }
    @Future
    public static void createCaseFuture(Set<Id> newListIds) {
        string subject = 'Application for Review';
        Id recordType = [select id from recordtype where sobjecttype = 'Case' and DeveloperName = 'U_S_Business' limit 1].id;
        List<Case> caseList = new List<Case>();
        Set<Id> participationIds = new Set<Id>();
//        List<User> uList = [SELECT ContactId FROM User WHERE Id =: UserInfo.getUserId()];
  //      Id cId = null;
    //    if(uList.size() > 0) {
      //      cId = uList[0].ContactId;
        //}
        Payment__c[] payments = [select id, order__r.participant__c, order__r.participation__c, order__c, order__r.participant__r.organization__c from payment__c
            where id = :newListIds];
            for(Payment__c payment: payments){ 
            if(payment != null && payment.Order__c != null && payment.order__r.participation__c != null && payment.order__r.participant__r.organization__c != null) {
                participationIds.add(payment.order__r.participation__c);    
                case c = new case();
          //      c.contactId = cId;
                c.subject = subject; 
                c.Order__c = payment.Order__c;
                c.recordtypeid = recordType;
                c.accountid = payment.order__r.participant__r.organization__c;
                c.participation__c = payment.order__r.participation__c;
                c.description = 'Thank you for contacting the Privacy Shield team at the U.S. Department of Commerce’s International Trade Administration (ITA).  We will work diligently to review and respond to your submission in a timely manner.  Please note that the processing time will depend on the nature and completeness of the submission, as well as the volume of submissions received.';
            Database.DMLOptions dmo = new Database.DMLOptions();        
                    dmo.assignmentRuleHeader.useDefaultRule = true;     
                c.setOptions(dmo);
                system.debug(c);
                caseList.add(c);
            }
            }
        if(caseList.size() > 0) {
            system.debug(caseList);
            INSERT CASELIST;
            //SafeDmlHandler.safeInsert(caseList, false);
        }
        
        Participant__c[] participations = [select id, application_stage__c from participant__c where id = :participationIds];
        for(Participant__c participation :participations){
            participation.application_stage__c = 'Pending Review';
        }
        UPDATE PARTICIPATIONS;
        //SafeDmlHandler.safeUpdate(participations, false);
    }
}