src/objects/Chapter__c.object
<CustomObject>
    <fields>
        <fullName>Publication_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication Template</label>
        <referenceTo>Publication_Template__c</referenceTo>
        <relationshipLabel>Chapter</relationshipLabel>
        <relationshipName>Chapter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Chapter</label>
    <nameField>
        <label>Chapter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chapter_Section__c.object
<CustomObject>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chapter</label>
        <referenceTo>Chapter__c</referenceTo>
        <relationshipLabel>Chapter Sections</relationshipLabel>
        <relationshipName>Chapter_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication Template</label>
        <referenceTo>Publication_Template__c</referenceTo>
        <relationshipLabel>Chapter Sections</relationshipLabel>
        <relationshipName>Chapter_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Chapter Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapter Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>The API destination</description>
        <label>Source URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Atom</label>
    <nameField>
        <label>Atom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atoms</pluralLabel>
    <recordTypes>
        <fullName>Video</fullName>
        <active>true</active>
        <description>Video media which is stored on an external system; ex: You Tube or Vimeo</description>
        <label>Video</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Commercial__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Input form to capture individual sections of a Country Commercial Guide</description>
    <fields>
        <fullName>Atom__c</fullName>
        <description>Body of an Article</description>
        <inlineHelpText>This rich-text area is where the body of your content should be placed. The content should not deviate from the overall theme and should stand on its own as a reliable source of information. Otherwise, a new topic should be created.</inlineHelpText>
        <label>Atom</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <description>Related Chapter of a Country Commercial Guide</description>
        <inlineHelpText>Select the applicable chapter from the publication that your content belongs to.</inlineHelpText>
        <label>Level 1</label>
        <picklist>
            <picklistValues>
                <fullName>Doing Business in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Political &amp; Economic Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selling US Products &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leading Sectors for US Exports &amp; Investments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Regulations, Customs, &amp; Standards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Climate Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade &amp; Project Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>References__c</fullName>
        <defaultValue>&quot;Prepared by our U.S. Embassies abroad.  With its network of 108 offices across the United States and in more than 75 countries, the U.S. Commercial Service of the U.S. Department of Commerce utilizes its global presence and international marketing expertise to help U.S. companies sell their products and services worldwide. Locate the U.S. Commercial Service trade specialist in the U.S. nearest you by visiting http://export.gov/usoffices.&quot;</defaultValue>
        <description>Article references</description>
        <inlineHelpText>If there are any references that were used during the writing of the content, they can be highlighted here. The rich text editor allows for formatting and link creation.</inlineHelpText>
        <label>References (Public)</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Creates relationship to Publications</description>
        <inlineHelpText>Type a keyword, such as country name and click the magnifying glass to search available Publications.</inlineHelpText>
        <label>Series</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Series__c.Type__c</field>
                <operation>equals</operation>
                <value>Country Commercial</value>
            </filterItems>
            <infoMessage>Search by Country name to find a Country Commercial Guide</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Series__c</referenceTo>
        <relationshipLabel>Country Commercial Guide Articles</relationshipLabel>
        <relationshipName>Country_Commercial_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Country Commercial</label>
    <pluralLabel>Country Commercials</pluralLabel>
</CustomObject>

src/objects/KnowledgeSearch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Facet of the Search App</description>
        <inlineHelpText>Facet of the Search App</inlineHelpText>
        <label>Search App Facet</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Search</label>
</CustomObject>

src/objects/Level__c.object
<CustomObject>
    <description>Manage the Tables of Contents for the Public Web per Article Type.</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <inlineHelpText>The order the levels will be displayed in the Table of Contents</inlineHelpText>
        <label>Sort Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Level</label>
    <nameField>
        <label>Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market_Intelligence__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Provide current awareness, market research in order to deliver timely information to clients.</description>
    <fields>
        <fullName>Atom__c</fullName>
        <label>Atom</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <label>Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>References__c</fullName>
        <label>Custom Citation</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Series__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Series</label>
        <referenceTo>Series__c</referenceTo>
        <relationshipLabel>Markets Intelligence</relationshipLabel>
        <relationshipName>Markets_Intelligence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Intelligence</label>
    <pluralLabel>Markets Intelligence</pluralLabel>
</CustomObject>

src/objects/Publication_Template__c.object
<CustomObject>
    <fields>
        <fullName>Series_Template_Name__c</fullName>
        <inlineHelpText>Name of the Template should correlate to Article Type.</inlineHelpText>
        <label>Series Template Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Series Template</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Series__c.object
<CustomObject>
    <description>Object to cluster Knowledge Articles by Publication</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Series Type</label>
        <picklist>
            <picklistValues>
                <fullName>Country Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic Guide to Exporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Insight</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>This represents a Salesforce.com Site or Community, but does not actually control the availability of a Site.</description>
    <fields>
        <fullName>Domain__c</fullName>
        <description>The site URL</description>
        <externalId>true</externalId>
        <inlineHelpText>The site URL</inlineHelpText>
        <label>Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site_CSS__c</fullName>
        <description>The location of the style used by the site</description>
        <externalId>true</externalId>
        <inlineHelpText>The location of the style used by the site</inlineHelpText>
        <label>Site Colors</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Logo__c</fullName>
        <description>The Logo that is displayed on the top left corner of the page</description>
        <externalId>true</externalId>
        <inlineHelpText>The Logo that is displayed on the top left corner of the page</inlineHelpText>
        <label>Site Logo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Name that will be displayed on the browser tab</description>
        <inlineHelpText>Name that will be displayed on the browser tab</inlineHelpText>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseAsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseAsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_Knowledge_Management.cls
@isTest(seealldata = false)
public class TEST_Knowledge_Management{
/*
    This class handles all of the unit tests related to knowledge management code.
*/
    public static TestMethod void testCase1(){
        //A link is clicked that navigates the user's browser to /km_atom.
        //This test passes when the following 4 variables are returned to the page from the Knowledge Article Type for the 'id' provided:
        //    Title, Last Published Date, Atom, and Summary
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;

       Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my Reference';
           kav.urlName = 'this-is-my-kav';
           kav.series__c = pub.id;
           kav.language = 'en_US';
           insert kav;
        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        
        article_controller controller = new article_controller();
        system.assertNotEquals(controller.atom, null); //make sure that the atom is not empty
        system.assertEquals(controller.atom, 'This is my KAV Atom'); //make sure that the atom matches what was specified in this test
        system.assertEquals(controller.title, 'This is my KAV Title'); //make sure that the title matches what was specified in the test        
    }

    public static TestMethod void testCase2(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        //A link is somehow clicked to an article that is not published or is no longer available.
        //the data returned should be a generic error message.
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;

       Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           insert kav;
        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
        //removing assert since article_controller is being replaced with article2_controller
        //system.assertEquals(controller.atom, 'We\'re sorry, this page does not exist.');    
    }
    
    public static TestMethod void testCase3(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter1: Blammo';
           kav.level_2__c = 'Doing Business In';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter1: Blammo';
           kav2.level_2__c = 'Doing Business In';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }

    public static TestMethod void testCase4(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.publication_template__c = pt.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.publication_template__c = pt.id;
        insert cs2;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_2__c = 'Doing Business In';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_2__c = 'Doing Business In';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }

    public static TestMethod void testCase5(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }
    
    public static TestMethod void testCase6(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter 1 : Testing Kav';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter 1 : Testing Kav';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }

    public static TestMethod void testCase7(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter 1 : Testing Kav';
           kav.level_2__c = 'Section 1';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter 1 : Testing Kav';
           kav2.level_2__c = 'Section 1';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }

    public static TestMethod void testCase8(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_2__c = 'Section 1';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_2__c = 'Section 1';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }

    public static TestMethod void testCase9(){
        //A link is clicked that navigates the user's browser to /km_atom.
        //This test passes when the following 4 variables are returned to the page from the Knowledge Article Type for the 'id' provided:
        //    Title, Last Published Date, Atom, and Summary
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;

       Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           insert kav;
        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
        system.assertNotEquals(controller.atom, null); //make sure that the atom is not empty
        system.assertEquals(controller.atom, 'This is my KAV Atom'); //make sure that the atom matches what was specified in this test
        system.assertEquals(controller.title, 'This is my KAV Title'); //make sure that the title matches what was specified in the test        
    }

    public static TestMethod void testCase10(){
        //A link is somehow clicked to an article that is not published or is no longer available.
        //the data returned should be a generic error message.
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;

       Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           insert kav;
        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
        system.assertEquals(controller.atom, 'We\'re sorry, this page does not exist.');    
    }
    
    public static TestMethod void testCase11(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial Guide';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter1: Blammo';
           kav.level_2__c = 'Doing Business In';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter1: Blammo';
           kav2.level_2__c = 'Doing Business In';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
    }

    public static TestMethod void testCase12(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial Guide';
        insert pt;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.publication_template__c = pt.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.publication_template__c = pt.id;
        insert cs2;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_2__c = 'Doing Business In';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_2__c = 'Doing Business In';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
    }

    public static TestMethod void testCase13(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
    }
    
    public static TestMethod void testCase14(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter 1 : Testing Kav';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter 1 : Testing Kav';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
    }

    public static TestMethod void testCase15(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter 1 : Testing Kav';
           kav.level_2__c = 'Section 1';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter 1 : Testing Kav';
           kav2.Level_2__c = 'Section 1';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
    }

    public static TestMethod void testCase16(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_2__c = 'Section 1';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_2__c = 'Section 1';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('printarticle');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        print_article_controller controller = new print_article_controller();
    }

    public static TestMethod void testCase17(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        //testing series list controller
        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Series__c pub2 = new Series__c();
        pub2.name = 'Rocket and Groot';
        pub2.type__c = 'Country Commercial';
        insert pub2;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Level 1';
           kav.level_2__c = 'Section 1';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub2.id;
           kav.level_1__c = 'Level 1';
           kav2.level_2__c = 'Section 1';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        
        SeriesType_Controller controller = new SeriesType_Controller();
        controller.type =  'Country Commercial';
        KnowledgeMap__c ccg = new KnowledgeMap__c();
            ccg.name = 'Country Commercial';
            ccg.api__c = 'Country_Commercial__kav';
            insert ccg;
        controller.recordID = null;
        system.assertEquals(controller.getRecordType(), 'Country_Commercial__kav');
        system.assertEquals(controller.getTypes().size(), 2);
    }
    public static TestMethod void testCase18(){
            Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 2';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 1';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_1__c = 'Chapter1: Blammo';
           kav.level_2__c = 'Doing Business In';
           insert kav;
        Country_Commercial__kav kav2 = new Country_Commercial__kav();
           kav2.title = 'This is my KAV Title 2';
           kav2.atom__c = 'This is my KAV Atom 2';
           kav2.summary = 'This is my KAV Summary 2';
           kav2.references__c = 'This is my KAV Reference 2';
           kav2.urlName = 'this-is-my-kav2';
           kav2.language = 'en_US';
           kav2.series__c = pub.id;
           kav2.level_1__c = 'Chapter1: Blammo';
           kav2.level_2__c = 'Doing Business In';
           insert kav2;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }

    public static TestMethod void testCase19(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 2';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 1';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Chapter1: Blammo';
           kav.level_2__c = 'Doing Business In';
           insert kav;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
    }
    
    public static TestMethod void testCase20(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 2';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 4';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Chapter1: Blammo';
           kav.level_2__c = 'Doing Business In';
           kav.level_3__c = 'Test 4';
           insert kav;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('id', 'this-is-my-kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
        controller.isSectionalNav = false;
        controller.isStaticNav = false;
        system.assertEquals(controller.getLoggedIn(), true);
        controller.navigation = new map<string, map<string, map<string, string>>>();
        system.assertNotEquals(controller.navObjects.size(), 0);
        system.assertNotEquals(controller.navObjects[0].empty, null);
    }
    
    public static TestMethod void testCase21(){
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 3';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 4';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Test 2';
           kav.level_2__c = 'Test 3';
           kav.level_3__c = 'Test 4';
           insert kav;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('series', pub.id);
            page.getParameters().put('type', 'Country_Commercial__kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
        controller.isSectionalNav = false;
        controller.isStaticNav = false;
        system.assertEquals(controller.getLoggedIn(), true);
        controller.navigation = new map<string, map<string, map<string, string>>>();
        system.assertNotEquals(controller.navObjects.size(), 0);
        system.assertNotEquals(controller.navObjects[0].empty, null);
    }
    
    public static TestMethod void testCase22(){
        //No N1 links
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        /*Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 3';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 4';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;*/

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           /*kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Test 2';
           kav.level_2__c = 'Test 3';
           kav.level_3__c = 'Test 4';*/
           insert kav;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('series', pub.id);
            page.getParameters().put('type', 'Country_Commercial__kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
        controller.isSectionalNav = false;
        controller.isStaticNav = false;
        system.assertEquals(controller.getLoggedIn(), true);
        controller.navigation = new map<string, map<string, map<string, string>>>();
        system.assertNotEquals(controller.navObjects.size(), 0);
        system.assertNotEquals(controller.navObjects[0].empty, null);
    }
    
    public static TestMethod void testCase23(){
        //No N2 links
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 3';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        /*Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 4';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;*/

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Test 2';
           /*kav.level_2__c = 'Test 3';
           kav.level_3__c = 'Test 4';*/
           insert kav;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('series', pub.id);
            page.getParameters().put('type', 'Country_Commercial__kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
        controller.isSectionalNav = false;
        controller.isStaticNav = false;
        system.assertEquals(controller.getLoggedIn(), true);
        controller.navigation = new map<string, map<string, map<string, string>>>();
        system.assertNotEquals(controller.navObjects.size(), 0);
        system.assertNotEquals(controller.navObjects[0].empty, null);
    }
    
    public static TestMethod void testCase24(){
        //No N3 links
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Country_Commercial__kav';
            pt.Series_Template_Name__c = 'Country Commercial';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 3';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 4';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;

        Series__c pub = new Series__c();
        pub.name = 'Blammo Country Commercial Guide';
        pub.type__c = 'Country Commercial';
        insert pub;
        Country_Commercial__kav kav = new Country_Commercial__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Test 2';
           kav.level_2__c = 'Test 3';
           /*kav.level_3__c = 'Test 4';*/
           insert kav;

        Country_Commercial__kav inserted = [select KnowledgeArticleId from Country_Commercial__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('series', pub.id);
            page.getParameters().put('type', 'Country_Commercial__kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', type__c = 'Country Commercial', endpoint__c = 'http://google.com');
        article_controller controller = new article_controller();
        controller.isSectionalNav = false;
        controller.isStaticNav = false;
        system.assertEquals(controller.getLoggedIn(), true);
        controller.navigation = new map<string, map<string, map<string, string>>>();
        system.assertNotEquals(controller.navObjects.size(), 0);
        system.assertNotEquals(controller.navObjects[0].empty, null);
    }
    
    public static TestMethod void testCase25(){
        //Video
        Site__c site = new Site__c();
            site.name = 'Export';
            site.domain__c = URL.getSalesforceBaseUrl().getHost();
            site.title__c = 'Export.gov';
            site.Site_CSS__c = '/css/sample.css' ;
            site.site_logo__c = '/img/sample.png';
            site.UseAsDefault__c = false;
        insert site;
        Publication_Template__c pt = new Publication_Template__c();
            pt.name = 'Market_Intelligence__kav';
            pt.Series_Template_Name__c = 'Market Intelligence';
        insert pt;
        Chapter__c chap = new chapter__c();
            chap.name = 'Blammo';
            chap.sort_order__c = 1.0;
            chap.publication_template__c = pt.id;
        insert chap;
        Chapter__c chap2 = new chapter__c();
            chap2.name = 'Blammo';
            chap2.sort_order__c = 1.0;
            chap2.publication_template__c = pt.id;
        insert chap2;

        Chapter_Section__c cs = new Chapter_Section__c();
            cs.name = 'Doing Business In';
            cs.sort_order__c = 1.0;
            cs.chapter__c = chap.id;
        insert cs;
        Chapter_Section__c cs2 = new Chapter_Section__c();
            cs2.name = 'Doing Business In';
            cs2.sort_order__c = 1.0;
            cs2.chapter__c = chap.id;
        insert cs2;
        Level__c lvl0 = new Level__c();
            lvl0.name = 'Test 1';
            lvl0.series_template__c = pt.id;
            lvl0.Level_Number__c = 'Level 0';
            lvl0.sort_order__c = 1;
            insert lvl0;
        Level__c lvl1 = new Level__c();
            lvl1.name = 'Test 2';
            lvl1.series_template__c = pt.id;
            lvl1.Level_Number__c = 'Level 1';
            lvl1.parent_level__c = lvl0.id;
            lvl1.sort_order__c = 1;
            insert lvl1;
        Level__c lvl2 = new Level__c();
            lvl2.name = 'Test 3';
            lvl2.series_template__c = pt.id;
            lvl2.Level_Number__c = 'Level 2';
            lvl2.parent_level__c = lvl1.id;
            lvl2.sort_order__c = 1;
            insert lvl2;
        Level__c lvl3 = new Level__c();
            lvl3.name = 'Test 4';
            lvl3.series_template__c = pt.id;
            lvl3.Level_Number__c = 'Level 3';
            lvl3.parent_level__c = lvl2.id;
            lvl3.sort_order__c = 1;
            insert lvl3;

        Series__c pub = new Series__c();
        pub.name = 'Blammo Market Intelligence Guide';
        pub.type__c = 'Market Intelligence';
        insert pub;
        Content__c video = new Content__c();
        video.Endpoint__c = 'Endpoint';
        video.Video_Description__c = 'Video Description';
        video.Video_Download__c = 'www.google.com';
        video.Video_File_Size__c = '5';
        insert video;
        
        Market_Intelligence__kav kav = new Market_Intelligence__kav();
           kav.title = 'This is my KAV Title';
           kav.atom__c = 'This is my KAV Atom';
           kav.summary = 'This is my KAV Summary';
           kav.references__c = 'This is my KAV Reference';
           kav.urlName = 'this-is-my-kav';
           kav.language = 'en_US';
           kav.series__c = pub.id;
           kav.video__c = video.id;
           /*kav.level_0__c = 'Test 1';
           kav.level_1__c = 'Test 2';
           kav.level_2__c = 'Test 3';
           kav.level_3__c = 'Test 4';*/
           insert kav;

        Market_Intelligence__kav inserted = [select KnowledgeArticleId from Market_Intelligence__kav where id = :kav.id];
        KbManagement.PublishingService.publishArticle(inserted.KnowledgeArticleId, true);
        PageReference page = new PageReference('article');
            page.getParameters().put('series', pub.id);
            page.getParameters().put('type', 'Market_Intelligence__kav');
        Test.setCurrentPage(page);
        KnowledgeSearch__c ks = new KnowledgeSearch__c(name='abc', 
                                                       type__c = 'Market Intelligence',
                                                       endpoint__c = 'http://google.com',
                                                      site__c = URL.getSalesforceBaseUrl().getHost(),
                                                      KAV_or_Category__c = 'Market Intelligence');
        insert ks;
        DescribeDataCategoryGroupResult[] results = Schema.describeDataCategoryGroups(
            new String[] { 'KnowledgeArticleVersion'}
        ); 
        Market_Intelligence__DataCategorySelection ds = new Market_Intelligence__DataCategorySelection();
            ds.parentid = inserted.id;
            ds.DataCategoryGroupName = 'Trade_Topics';
            ds.DataCategoryName = 'Advertising';
        insert ds;
        article_controller controller = new article_controller();
        controller.isSectionalNav = false;
        controller.isStaticNav = false;
        system.assertEquals(controller.getLoggedIn(), true);
        controller.navigation = new map<string, map<string, map<string, string>>>();
        system.assertNotEquals(controller.navObjects.size(), 0);
        system.assertNotEquals(controller.navObjects[0].empty, null);
    }
    
    public static TestMethod void testCase26() {
        //Errors
        Site__c site = new Site__c();
        site.name = 'Export';
        site.domain__c = URL.getSalesforceBaseUrl().getHost();
        site.title__c = 'Export.gov';
        site.Site_CSS__c = '/css/sample.css' ;
        site.site_logo__c = '/img/sample.png';
        site.UseAsDefault__c = false;
        insert site;
        
        article_controller controller = new article_controller();
        PageReference pg = controller.error();
        system.assertEquals('/apex/pagenotfound', pg.getUrl());
         
        controller.pageError = false;
        controller.publicViewing = false;
        controller.customerViewing = false; 
        pg = controller.error();
        system.assertEquals(pg.getParameters().get('retURL'), '/article');
         
        controller.publicViewing = true;
        pg = controller.error();
        system.assertEquals(null, pg);
     }    
}