src/objects/Clean_URL__c.object
<CustomObject>
    <description>Relationship between URL__c and Page__c records.</description>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Site that the URL is associated to.</description>
        <inlineHelpText>What Site is this URL associated to?</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>Clean_URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site URL</label>
    <nameField>
        <displayFormat>URL {0}</displayFormat>
        <label>URL Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site URLs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Clean_URL__c</fullName>
        <label>URL Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>This represents a Salesforce.com Site or Community, but does not actually control the availability of a Site.</description>
    <fields>
        <fullName>Default_Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Page the site will default to, when a user logs on to the site Domain</description>
        <inlineHelpText>The Page the site will default to, when a user logs on to the site Domain</inlineHelpText>
        <label>Site Homepage</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>The site URL</description>
        <externalId>true</externalId>
        <inlineHelpText>The site URL</inlineHelpText>
        <label>Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UseAsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseAsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VisualForce_Redirect__c</fullName>
        <description>VisualForce Page to use as the homepage instead of the homepage Page record.</description>
        <label>VisualForce Redirect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Landing_Controller.cls
public class Landing_Controller{
public pagereference redirect(){
    Site__c site = [select default_page__c, default_page__r.clean_url__c, VisualForce_Redirect__c from site__c where domain__c = :URL.getSalesforceBaseUrl().getHost() or UseAsDefault__c = true order by UseAsDefault__c asc limit 1];
    if(site.VisualForce_Redirect__c != null){
        PageReference pg = new PageReference('/'+site.VisualForce_Redirect__c);
        pg.setRedirect(true);
        return pg;    
    }
    if(site.default_page__c != null){
        if(site.default_page__r.clean_url__c != null){
            PageReference pg = new PageReference(site.default_page__r.clean_url__c);
            pg.setRedirect(false);
            return pg;
        }else{
            PageReference pg = Page.page;
            pg.getParameters().put('id', site.default_page__c);
            pg.setRedirect(false);
            return pg;
        }
    }
    return null;
}
}