src/objects/Clean_URL__c.object
<CustomObject>
    <description>Relationship between URL__c and Page__c records.</description>
    <fields>
        <fullName>Non_Page_URL__c</fullName>
        <externalId>true</externalId>
        <label>Actual URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Page that the URL is for.</description>
        <inlineHelpText>Which Page is this for?</inlineHelpText>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipName>Clean_URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Site that the URL is associated to.</description>
        <inlineHelpText>What Site is this URL associated to?</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>Clean_URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL that the Page should be associated with.</description>
        <inlineHelpText>What is the clean URL for this page?</inlineHelpText>
        <label>URL Name</label>
        <referenceTo>URL__c</referenceTo>
        <relationshipLabel>Site URLs</relationshipLabel>
        <relationshipName>Clean_URLs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Site URL</label>
    <nameField>
        <displayFormat>URL {0}</displayFormat>
        <label>URL Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site URLs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template_Page__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>This represents a Salesforce.com Site or Community, but does not actually control the availability of a Site.</description>
    <fields>
        <fullName>Domain__c</fullName>
        <description>The site URL</description>
        <externalId>true</externalId>
        <inlineHelpText>The site URL</inlineHelpText>
        <label>Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UseAsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseAsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/URL__c.object
<CustomObject>
    <fields>
        <fullName>Friendly__c</fullName>
        <description>The Public URL which will display in a web browser instead of the Actual URL.</description>
        <inlineHelpText>The Public URL which will display in a web browser instead of the Actual URL.</inlineHelpText>
        <label>Display URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipName>URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Real__c</fullName>
        <description>This is the actual, static URL which needs to be rewritten.</description>
        <inlineHelpText>This is the actual, static URL which needs to be rewritten.</inlineHelpText>
        <label>Actual URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>URL</label>
    <nameField>
        <displayFormat>URL-{00000}</displayFormat>
        <label>URL Rewrite Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>URLs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/urlRewriter.cls
global class urlRewriter implements Site.UrlRewriter{
    global PageReference mapRequestUrl(PageReference myFriendlyUrl){
        String givenURL = myFriendlyUrl.getUrl();
        system.debug('@@URL:  '+givenURL);
        URL__c[] urls = [select id, friendly__c, real__c, page__c, (select id, page__c, Non_Page_URL__c from clean_urls__r where 
            site__r.domain__c = :URL.getSalesforceBaseUrl().getHost() 
            or site__r.UseAsDefault__c = true 
            order by site__r.UseAsDefault__c asc limit 1) 
        from url__c where friendly__c = :givenURL];
        if(urls.size() != 0){
            system.debug('@@URLs: '+urls[0].real__c);
            if(urls[0].clean_urls__r.size() != 0){
                //check to see if there is a page__c
                if(urls[0].clean_urls__r[0].page__c != null){
                    PageReference pr = Page.page;
                        pr.getParameters().put('id', urls[0].clean_urls__r[0].page__c);
                    return pr;
                }
                //check to see if there is a url
                if(urls[0].clean_urls__r[0].Non_Page_URL__c != null){
                    if(!urls[0].clean_urls__r[0].Non_Page_URL__c.contains('/servlet.FileDownload')){
                        return new PageReference(urls[0].clean_urls__r[0].Non_Page_URL__c);
                    }else{
                        PageReference pg = Page.redirect;
                        pg.getParameters().put('dest', urls[0].clean_urls__r[0].Non_Page_URL__c);
                        return pg;
                    }
                }
            }
            if(urls[0].page__c != null){
                PageReference pr = Page.page;
                    pr.getParameters().put('id', urls[0].page__c);
                return pr;
            }
            if(urls[0].real__c.contains('/servlet.FileDownload')){
                PageReference pg = Page.redirect;
                pg.getParameters().put('dest', urls[0].real__c);
                return pg;            
            }
            return new PageReference(urls[0].real__c);            
        }else if(givenURL.countMatches('/') == 1){
            system.debug('@@ GIVEN:  '+givenURL);
            givenURL = givenURL.replaceAll('/', '');
            if(givenURL.contains('?')){
                system.debug('@@ CONTAINS QUERY');
                String[] URLParts = givenURL.split('\\?');
                system.debug('@@ PARTS:  '+URLParts);
                givenURL = URLParts[0];

            }
            system.debug('@@ STRIPPED SLASH:  '+givenURL);

            if(givenURL == ''){
                givenURL = 'landing';
            }

            if(givenURL != 'login' && [select id, name from apexpage where name = :givenURL].size() == 0){
                PageReference pg = Page.PageNotFound;
                return pg;
            }
        }
        system.debug('@@No friendly url found');
        return null;
    }
    global List<PageReference> generateUrlFor(List<PageReference> mySalesforceUrls){
        system.debug('@@Redirecting');
        return null;
    }
}