src/objects/Clean_URL__c.object
<CustomObject>
    <description>Relationship between URL__c and Page__c records.</description>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Page that the URL is for.</description>
        <inlineHelpText>Which Page is this for?</inlineHelpText>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipName>Clean_URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Site that the URL is associated to.</description>
        <inlineHelpText>What Site is this URL associated to?</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>Clean_URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site URL</label>
    <nameField>
        <displayFormat>URL {0}</displayFormat>
        <label>URL Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site URLs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Clean_URL__c</fullName>
        <label>URL Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template_Page__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Frequency__c</fullName>
        <label>Update Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>monthly</fullName>
                    <default>true</default>
                    <label>monthly</label>
                </value>
                <value>
                    <fullName>always</fullName>
                </value>
                <value>
                    <fullName>hourly</fullName>
                </value>
                <value>
                    <fullName>daily</fullName>
                </value>
                <value>
                    <fullName>weekly</fullName>
                </value>
                <value>
                    <fullName>yearly</fullName>
                </value>
                <value>
                    <fullName>never</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>This represents a Salesforce.com Site or Community, but does not actually control the availability of a Site.</description>
    <fields>
        <fullName>Domain__c</fullName>
        <description>The site URL</description>
        <externalId>true</externalId>
        <inlineHelpText>The site URL</inlineHelpText>
        <label>Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UseAsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseAsDefault</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SiteMap_Controller.cls
public class SiteMap_Controller {

public string getXML(){
    return '<?xml version="1.0" encoding="UTF-8"?>';
}

public string domain {get; set;}
public id site {get; set;}

public SiteMap_Controller(){
    this.domain = URL.getSalesforceBaseUrl().getHost();
    this.site = [select id from site__c where domain__c = :this.domain or UseAsDefault__c = true order by domain__c nulls last limit 1].id;
}

public page__c[] getPages(){
    return [select id, lastmodifieddate, clean_url__c, update_frequency__c from page__c where
            site__c = :this.site
           ];
}

}