src/objects/Clean_URL__c.object
<CustomObject>
    <description>Relationship between URL__c and Page__c records.</description>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Site that the URL is associated to.</description>
        <inlineHelpText>What Site is this URL associated to?</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>Clean_URLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL that the Page should be associated with.</description>
        <inlineHelpText>What is the clean URL for this page?</inlineHelpText>
        <label>URL Name</label>
        <referenceTo>URL__c</referenceTo>
        <relationshipLabel>Site URLs</relationshipLabel>
        <relationshipName>Clean_URLs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Site URL</label>
    <nameField>
        <displayFormat>URL {0}</displayFormat>
        <label>URL Page Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site URLs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <fields>
        <fullName>Alt_Text__c</fullName>
        <formula>Name &amp; &quot; &quot; &amp; &quot;Icon&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Alt Text</label>
        <type>Text</type>
    </fields>
    <label>Atom</label>
    <nameField>
        <label>Atom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/My_Profile_Option__c.object
<CustomObject>
    <fields>
        <fullName>Icon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Icon</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Icon from the existing library.</errorMessage>
            <filterItems>
                <field>Content__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Icon</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>My_Profile_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>My_Profile_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>Custom URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>My Account Navigation</label>
    <nameField>
        <label>My Profile Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Account Navigation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Navigation_Group__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Site that this Navigation Group will appear on</description>
        <inlineHelpText>The Site that this Navigation Group will appear on</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Navigation</relationshipLabel>
        <relationshipName>Navigation_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>If this field is populated, the Navigation group link will be directed to this URL.</description>
        <inlineHelpText>This field allows you to link to an external web site. If populated with a URL, it will override the Page field. Note: http:// is not needed.</inlineHelpText>
        <label>Custom URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>isMegaMenu__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked this Navigation option will be a MegaMenu (Having multiple sections in one dropdown)</description>
        <inlineHelpText>When checked this Navigation option will be a MegaMenu (Having multiple sections in one dropdown)</inlineHelpText>
        <label>Mega Navigation Group</label>
        <type>Checkbox</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Navigation_Link__c.object
<CustomObject>
    <fields>
        <fullName>Navigation_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Navigation Group that this Navigation Link will appear on</description>
        <inlineHelpText>The Navigation Group that this Navigation Link will appear on</inlineHelpText>
        <label>Navigation Group</label>
        <referenceTo>Navigation_Group__c</referenceTo>
        <relationshipLabel>Navigation Links</relationshipLabel>
        <relationshipName>Navigation_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Navigation Link</label>
    <nameField>
        <label>Navigation Link</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Links</pluralLabel>
    <recordTypes>
        <fullName>Link</fullName>
        <active>true</active>
        <description>Navigation Link items that direct a user to a link</description>
        <label>Link</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <description>This represents a Salesforce.com Site or Community, but does not actually control the availability of a Site.</description>
    <fields>
        <fullName>Disable_Login__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Login</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>The site URL</description>
        <externalId>true</externalId>
        <inlineHelpText>The site URL</inlineHelpText>
        <label>Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GA_Account__c</fullName>
        <description>Google Analytics Account #.</description>
        <externalId>true</externalId>
        <inlineHelpText>Google Analytics Account #.</inlineHelpText>
        <label>GA Account #</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GA_Domain__c</fullName>
        <label>GA Domain</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GA_Script__c</fullName>
        <description>Allows user to select the correct GA script for the web domain.</description>
        <inlineHelpText>Legacy script starts with &quot;var _gaq&quot;. Modern script starts with &quot;(function(i,s,o,g,r,a,m)&quot;.</inlineHelpText>
        <label>GA Script</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Modern</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logo_Alt_Text__c</fullName>
        <description>The 508 Compliant text for the Site Logo.</description>
        <inlineHelpText>What is the 508 Compliant text for this Site&apos;s Logo?</inlineHelpText>
        <label>Logo Alt Text</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Footer__c</fullName>
        <label>Required Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Search_URL__c</fullName>
        <description>The Search API endpoint</description>
        <label>Search URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_CSS__c</fullName>
        <description>The location of the style used by the site</description>
        <externalId>true</externalId>
        <inlineHelpText>The location of the style used by the site</inlineHelpText>
        <label>Site Colors</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Logo__c</fullName>
        <description>The Logo that is displayed on the top left corner of the page</description>
        <externalId>true</externalId>
        <inlineHelpText>The Logo that is displayed on the top left corner of the page</inlineHelpText>
        <label>Site Logo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Slogan__c</fullName>
        <description>The &quot;Tagline&quot; that will be displayed beneath the Site Logo</description>
        <inlineHelpText>The &quot;Tagline&quot; that will be displayed beneath the Site Logo</inlineHelpText>
        <label>Tagline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Name that will be displayed on the browser tab</description>
        <inlineHelpText>Name that will be displayed on the browser tab</inlineHelpText>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>favicon__c</fullName>
        <label>Site Favicon</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSearchEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the Search utility turned on for the Site Template for this Site?</description>
        <inlineHelpText>Turn on the Search utility for the Site?</inlineHelpText>
        <label>isSearchEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Social_Icons__c.object
<CustomObject>
    <description>Table to store font-based social icons per Site.</description>
    <fields>
        <fullName>Icon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail relationship with Atom object - Icon Record Type.</description>
        <inlineHelpText>Search for the Icon required for this Social Icon</inlineHelpText>
        <label>Atom</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Content__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Icon</value>
            </filterItems>
            <filterItems>
                <field>Content__c.Icon_Type__c</field>
                <operation>equals</operation>
                <value>Social</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Social Icons</relationshipLabel>
        <relationshipName>Social_Icons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <description>Master-Detail relationship with the Site object.</description>
        <inlineHelpText>Search for the Site associated to this Social Icon</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Social Icons</relationshipLabel>
        <relationshipName>Social_Icons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>URL of the designated social media</description>
        <inlineHelpText>Enter the URL for this Social Icon</inlineHelpText>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Social Icon</label>
    <nameField>
        <label>Social Icon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Icons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Site_Template_Controller.cls
public class Site_Template_Controller {

    public Navigation_Group__c[] navigation {get; set;}
    public Site__c Main {get; set;}
    public NavigationGroup[] NavigationGroups {get; set;}
    public String loggedInUser{get; set;}
    public Social_Icons__c[] si{get; set;}

// Login and Register
    public String username {get; set;}
    public String password {get; set;}
//  public CustomLoginController () {}    
    public PageReference login() {
        return Site.login(username, password, null);
    } 

    public PageReference Registerredirect() {
        PageReference rr = new PageReference('/registration');
        rr.setRedirect(true);
        return rr;
    }
    public String currentBaseUrl {get { //used to return the base url of the current page
        return 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/';
    }}
//

    public class NavigationGroup{
        public Id id {get; set;}
        public string label {get; set;}
        public string url {get; set;}
        public boolean isMegaMenu {get; set;}
        public Navigation_Link__c[] links {get; set;}
    }

    public Site_Template_Controller(){
    
        map<string, string> chatterMap = new map<string, string>();
        String[] groups = new String[]{};
        Site__c[] site = [SELECT id, title__c, Site_CSS__c, site_logo__c,slogan__c,Disable_Login__c,isSearchEnabled__c, Search_URL__c, 
                            Required_Footer__c, Logo_Alt_Text__c,favicon__c,
                            GA_Domain__c, GA_Account__c, GA_Script__c,
                                (SELECT id, name, isMegaMenu__c, Chatter_Group__c, page__c, url__c, page__r.clean_url__c
                                FROM Navigation_Groups__r
                                ORDER BY sort_order__c asc nulls first), 
                                (SELECT URL__c, Name, icon__r.Alt_Text__c, icon__r.class_name__c, icon__r.name
                                  FROM Social_Icons__r
                                  Where Active__c = true
                                  ORDER BY Sort_Order__c asc nulls first LIMIT 6),
                                (SELECT id, name, url__c, icon__r.Class_Name__c from my_profile_options__r
                                  order by sort_order__c)
                            from site__c where 
                                domain__c = :URL.getSalesforceBaseUrl().getHost() 
                                or UseAsDefault__c = true 
                            order by UseAsDefault__c asc limit 1];
        if(site.size() == 1){
            this.main = site[0];
            si = this.main.Social_Icons__r;
            this.navigation = [select id, sort_order__c, name, isMegaMenu__c, chatter_group__c, page__c, page__r.clean_url__c, url__c,
                               (select id, Page__c, Name, redirect__c, page__r.clean_url__c 
                                from navigation_links__r 
                                order by sort_order__c asc nulls first) 
                               from Navigation_Group__c 
                               where site__c = :site[0].id 
                               order by sort_order__c asc nulls first];
            Id[] GroupIds = new Id[]{};
            map<id, NavigationGroup> GroupMap = new map<id, NavigationGroup>();
            for(navigation_group__c grp : this.main.navigation_groups__r){
                groups.add(grp.Chatter_Group__c);
            }
            for(CollaborationGroup chatter : [select name, id from collaborationgroup where name = :groups]){
                chatterMap.put(chatter.name, chatter.id);
            }
            for(Navigation_Group__c grp : this.main.navigation_groups__r){
                GroupIds.add(grp.id);
                NavigationGroup ng = new NavigationGroup();
                    ng.id = grp.id;
                    ng.label = grp.name;
                    ng.url = '#';
                    if(grp.chatter_group__c != null && chatterMap.get(grp.chatter_group__c) != null){
                        ng.url = '/apex/group?id='+chatterMap.get(grp.chatter_group__c);
                    }else if(grp.url__c != null){ 
                        ng.url = 'http://'+grp.url__c;
                    }else if(grp.page__c != null){
                       ng.url = '/apex/page?id='+grp.page__c;
                       if(grp.page__r.clean_url__c != null){
                           ng.url = grp.page__r.clean_url__c;
                       }
                    }else{
                       ng.url = '#'; 
                    }
                    ng.isMegaMenu = grp.isMegaMenu__c;
                    ng.links = new Navigation_Link__c[]{};
                    /*if(grp.chatter_group__c != null && chatterMap.get(grp.chatter_group__c) != null){
                        ng.url = '/apex/group?id='+chatterMap.get(grp.chatter_group__c);
                    }*/
                GroupMap.put(grp.id, ng);
            }
            Navigation_Link__c[] links = [select id, name, Navigation_Group__c, recordtype.name, page__c, redirect__c, page__r.Clean_URL__c, 
                                          (select id, page__c, name, redirect__c, page__r.clean_url__c
                                           from navigation_links__r 
                                           order by sort_order__c asc nulls first) 
                                          from navigation_link__c 
                                          where navigation_group__c = : GroupIds 
                                          order by sort_order__c asc nulls first];
            for(Navigation_Link__c link : links){
                    GroupMap.get(link.Navigation_Group__c).links.add(link);
            }
            this.NavigationGroups = new NavigationGroup[]{};
            for(id record :GroupMap.keySet()){
                this.NavigationGroups.add(GroupMap.get(record));
            }
        }
        
        if(UserInfo.getUserType() != 'Guest'){
                loggedInUser = '1';
            } else {
                loggedInUser = '0';
            }
        
    }
}