src/objects/Constant__mdt.object
<CustomObject>
    <description>This holds constant values used in classes</description>
    <fields>
        <fullName>ADCVD_Objects__c</fullName>
        <label>ADCVD Objects</label>
        <referenceTo>ADCVD_Objects__mdt</referenceTo>
        <relationshipLabel>Constants</relationshipLabel>
        <relationshipName>Constants</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Description__c</fullName>
        <label>Record Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staffing_Assignment_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Staffing Assignment Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Staffing_Role__c</fullName>
        <label>Staffing Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Director</fullName>
                </value>
                <value>
                    <fullName>Accounting PM</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>AS Assistant</fullName>
                </value>
                <value>
                    <fullName>Assistant Secretary</fullName>
                </value>
                <value>
                    <fullName>Associate DAS</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>DAS Assistant</fullName>
                </value>
                <value>
                    <fullName>Office Director</fullName>
                </value>
                <value>
                    <fullName>Program Manager</fullName>
                </value>
                <value>
                    <fullName>Senior Legal</fullName>
                </value>
                <value>
                    <fullName>Senior Policy</fullName>
                </value>
                <value>
                    <fullName>Staff Accountant</fullName>
                </value>
                <value>
                    <fullName>Staff Legal</fullName>
                </value>
                <value>
                    <fullName>Staff Policy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used_with_Field_Named__c</fullName>
        <label>Used with Field Named</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Constant</label>
    <pluralLabel>Constants</pluralLabel>
</CustomObject>

src/classes/ADCVD_ConstantMetadataSelectorTest.cls
@isTest
public with sharing class ADCVD_ConstantMetadataSelectorTest {

    private static Map<Id, Constant__mdt> constants{
        get{
            if(constants == null){
                constants = new Map<Id, Constant__mdt>([Select Id, MasterLabel, DeveloperName,
                        ADCVD_Objects__c,
                        ADCVD_Order_Calculation_Offset__c,
                        Investigation_Calculation_Offset__c,
                        Issue_Calculation_Offset__c,
                        Litigation_Calculation_Offset__c,
                        Number_Value__c,
                        Petition_Calculation_Offset__c,
                        Record_Description__c,
                        Segment_Calculation_Offset__c,
                        Staffing_Assignment_Default__c,
                        Staffing_Role__c,
                        String_Value__c,
                        Suspension_Agreement_Calculation_Offset__c,
                        Used_with_Field_Named__c From Constant__mdt]);
            }
            return constants;
        }
        set;
    }

    @isTest static void testConstantMetadataSelector(){
        Set<Id> selectedRecordIds = new Set<Id>{constants.values().get(0).Id,constants.values().get(1).Id,constants.values().get(2).Id,constants.values().get(3).Id,constants.values().get(4).Id};
        Test.startTest();
        ADCVD_ConstantMetadataSelector constantMetadataSelector = new ADCVD_ConstantMetadataSelector();
        Schema.SObjectType customMDT = constantMetadataSelector.getSObjectType();
        List<Constant__mdt> expectedConstantsList = constantMetadataSelector.selectById(selectedRecordIds);

        //Create new instance for coverage
        ADCVD_IConstantMetadataSelector newinstance = ADCVD_ConstantMetadataSelector.newInstance();
        Test.stopTest();

        System.assertEquals(customMDT, constants.values().get(0).getSObjectType());
        for(Constant__mdt aConstant: expectedConstantsList){
            //Assert that all the fields are retrieved by the selector
            System.assertEquals(aConstant.MasterLabel, constants.get(aConstant.Id).MasterLabel);
            System.assertEquals(aConstant.DeveloperName, constants.get(aConstant.Id).DeveloperName);
            System.assertEquals(aConstant.ADCVD_Objects__c, constants.get(aConstant.Id).ADCVD_Objects__c);
            System.assertEquals(aConstant.ADCVD_Order_Calculation_Offset__c, constants.get(aConstant.Id).ADCVD_Order_Calculation_Offset__c);
            System.assertEquals(aConstant.Investigation_Calculation_Offset__c, constants.get(aConstant.Id).Investigation_Calculation_Offset__c);
            System.assertEquals(aConstant.Issue_Calculation_Offset__c, constants.get(aConstant.Id).Issue_Calculation_Offset__c);
            System.assertEquals(aConstant.Litigation_Calculation_Offset__c, constants.get(aConstant.Id).Litigation_Calculation_Offset__c);
            System.assertEquals(aConstant.Number_Value__c, constants.get(aConstant.Id).Number_Value__c);
            System.assertEquals(aConstant.Petition_Calculation_Offset__c, constants.get(aConstant.Id).Petition_Calculation_Offset__c);
            System.assertEquals(aConstant.Record_Description__c, constants.get(aConstant.Id).Record_Description__c);
            System.assertEquals(aConstant.Segment_Calculation_Offset__c, constants.get(aConstant.Id).Segment_Calculation_Offset__c);
            System.assertEquals(aConstant.Staffing_Assignment_Default__c, constants.get(aConstant.Id).Staffing_Assignment_Default__c);
            System.assertEquals(aConstant.Staffing_Role__c, constants.get(aConstant.Id).Staffing_Role__c);
            System.assertEquals(aConstant.String_Value__c, constants.get(aConstant.Id).String_Value__c);
            System.assertEquals(aConstant.Suspension_Agreement_Calculation_Offset__c, constants.get(aConstant.Id).Suspension_Agreement_Calculation_Offset__c);
            System.assertEquals(aConstant.Used_with_Field_Named__c, constants.get(aConstant.Id).Used_with_Field_Named__c);
        }
    }
}