src/objects/DAS__c.object
<CustomObject>
    <label>DAS</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DAS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department_Taxonomy__c.object
<CustomObject>
    <description>This object contains all the current department taxonomy information</description>
    <fields>
        <fullName>All__c</fullName>
        <description>All (Highest Level)</description>
        <label>User Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country (Level 5)</description>
        <label>User Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DAS__c</fullName>
        <description>DAS (Level 2)</description>
        <label>User DAS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_0__c</fullName>
        <label>User Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Office_Name__c</fullName>
        <description>Old office name mapped to new office</description>
        <label>User Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_1__c</fullName>
        <description>Region 1 (Level 4)</description>
        <label>User Sub-region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_2__c</fullName>
        <description>Region 2 (Level 3)</description>
        <label>User Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department Taxonomy</label>
    <nameField>
        <displayFormat>DT{00000}</displayFormat>
        <label>Department Taxonomy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Taxonomy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ITA_Office__c</fullName>
        <description>temp field for collecting office names until picklist option is defined or master list.</description>
        <label>ITA Office (AD)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCreateHierarchy.cls
@isTest
private class TestCreateHierarchy {
    
    @isTest (seealldata = true)
    static void TestCreateHierarchyTrigger() {
        Department_Taxonomy__c DT = new Department_Taxonomy__c();
        DT.Level_0__c = 'LV0';
        DT.All__c = 'LV0';
        DT.DAS__c = 'LV0';
        DT.Region_2__c = 'LV0';
        DT.Region_1__c = 'LV0';
        DT.Country__c = 'LV0';
        DT.Old_Office_Name__c = 'OLDOFF';
        Insert DT;
        User Usr = new User();
        Usr.Alias = 'asdfas';
        Usr.Email = 'email@test.com';
        Usr.EmailEncodingKey = 'UTF-8';
        Usr.LanguageLocaleKey = 'en_US';
        Usr.LocaleSidKey = 'en_US';
        Usr.ProfileId = [Select id from profile where name = 'Read Only'].id;
        Usr.username = 'Username@esawtds.com';
        Usr.ITA_Office__c = 'OLDOFF';
        Usr.Lastname = 'sadfasdf';
        Usr.TimeZoneSidKey = 'America/New_York';
        insert Usr;
        }
    }