src/objects/Department_Taxonomy__c.object
<CustomObject>
    <description>This object contains all the current department taxonomy information</description>
    <fields>
        <fullName>All__c</fullName>
        <description>All (Highest Level)</description>
        <label>User Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country (Level 5)</description>
        <label>User Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DAS__c</fullName>
        <description>DAS (Level 2)</description>
        <label>User DAS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_0__c</fullName>
        <label>User Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Office (Level 6)</description>
        <label>OLD Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Office_Name__c</fullName>
        <description>Old office name mapped to new office</description>
        <label>User Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_1__c</fullName>
        <description>Region 1 (Level 4)</description>
        <label>User Sub-region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_2__c</fullName>
        <description>Region 2 (Level 3)</description>
        <label>User Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department Taxonomy</label>
    <nameField>
        <displayFormat>DT{00000}</displayFormat>
        <label>Department Taxonomy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Taxonomy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ITA_Office__c</fullName>
        <description>temp field for collecting office names until picklist option is defined or master list.</description>
        <label>ITA Office (AD)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RH_Lev_1_Top_Level__c</fullName>
        <inlineHelpText>Highest level within organization. Add all three areas to pull reports for all ITA.</inlineHelpText>
        <label>User Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GM All</fullName>
                </value>
                <value>
                    <fullName>EC All</fullName>
                </value>
                <value>
                    <fullName>IA All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Lev_2_DAS_Level__c</fullName>
        <inlineHelpText>Level 2</inlineHelpText>
        <label>User DAS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GM Advocacy Everywhere</fullName>
                </value>
                <value>
                    <fullName>EC Policy &amp; Negotiations DAS Office</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-HQ DAS Office</fullName>
                </value>
                <value>
                    <fullName>GM CS-China-HQ DAS Office</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-HQ DAS Office</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-HQ DAS Office</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-HQ DAS Office</fullName>
                </value>
                <value>
                    <fullName>GM SelectUSA Everywhere</fullName>
                </value>
                <value>
                    <fullName>IA MFG DAS Office</fullName>
                </value>
                <value>
                    <fullName>IA NTTO</fullName>
                </value>
                <value>
                    <fullName>IA OACIO</fullName>
                </value>
                <value>
                    <fullName>IA OPCM</fullName>
                </value>
                <value>
                    <fullName>IA SVCS DAS Office</fullName>
                </value>
                <value>
                    <fullName>IA TAS</fullName>
                </value>
                <value>
                    <fullName>IA TCGM DAS Office</fullName>
                </value>
                <value>
                    <fullName>IA TPA DAS Office</fullName>
                </value>
                <value>
                    <fullName>IA TPPSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Lev_3_Region_2__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GM CS-EMEA-Field Europe</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field Great Lakes</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field MidAtlantic</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field MidWest</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field Northeast</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field Pacific North</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field Pacific South</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field Southern</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-Field Southwest</fullName>
                </value>
                <value>
                    <fullName>GM CS-DDG Units</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-HQ</fullName>
                </value>
                <value>
                    <fullName>GM SelectUSA-Field</fullName>
                </value>
                <value>
                    <fullName>GM SelectUSA-HQ</fullName>
                </value>
                <value>
                    <fullName>GM Advocacy-Field</fullName>
                </value>
                <value>
                    <fullName>GM Advocacy-HQ</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-HQ</fullName>
                </value>
                <value>
                    <fullName>GM CS-China-Field</fullName>
                </value>
                <value>
                    <fullName>GM CS-China-HQ</fullName>
                </value>
                <value>
                    <fullName>GM CS-DG</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field MEA</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA HQ</fullName>
                </value>
                <value>
                    <fullName>GM CS-USA-HQ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Lev_4_Region_1__c</fullName>
        <label>User Sub-region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GM Advocacy Field</fullName>
                </value>
                <value>
                    <fullName>GM Advocacy HQ</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ANZ</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Africa</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Balkans</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Benelux</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field EURASIA</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field GEAUS</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Gulf</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Nordics</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field North Africa</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field PoCz</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field SPG</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field UK</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field ANDPAN</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field ARGUR</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field CAFTA</fullName>
                </value>
                <value>
                    <fullName>GM SelectUSA HQ</fullName>
                </value>
                <value>
                    <fullName>GM SelectUSA-Field</fullName>
                </value>
                <value>
                    <fullName>IA MFG OEEI</fullName>
                </value>
                <value>
                    <fullName>IA MFG OHIT</fullName>
                </value>
                <value>
                    <fullName>IA MFG OTM</fullName>
                </value>
                <value>
                    <fullName>IA SVCS ODSI</fullName>
                </value>
                <value>
                    <fullName>IA SVCS OFI</fullName>
                </value>
                <value>
                    <fullName>IA SVCS OSCPBS</fullName>
                </value>
                <value>
                    <fullName>IA TCGM OCG</fullName>
                </value>
                <value>
                    <fullName>IA TCGM OM</fullName>
                </value>
                <value>
                    <fullName>IA TCGM OTEXA</fullName>
                </value>
                <value>
                    <fullName>IA TPA OIPR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Lev_5_Country__c</fullName>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GM CS-Asia-Field ANZ Australia</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ANZ New Zealand</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Bangkok</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Jakarta</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Kaula Lumpur</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Manila</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Rangoon</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Singapore</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field ASEAN Vietnam</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field India</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field Japan</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field Pakistan</fullName>
                </value>
                <value>
                    <fullName>GM CS-Asia-Field Taiwan</fullName>
                </value>
                <value>
                    <fullName>GM CS-China-Field China</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Africa South Africa</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field EURASIA Russia</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field GEAUS Germany</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Gulf UAE</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Iraq</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Israel</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Italy</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Saudi Arabia</fullName>
                </value>
                <value>
                    <fullName>GM CS-EMEA-Field Turkey</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field Brazil</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field Canada</fullName>
                </value>
                <value>
                    <fullName>GM CS-WH-Field Mexico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RH_Lev_7_Individual__c</fullName>
        <label>User Agency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ITA</fullName>
                    <default>true</default>
                    <label>ITA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateTaxonomyOnUserHelper.cls
public class CreateTaxonomyOnUserHelper {

    public Static void createTaxonomy(list<User> Users)
    {
        list<String> offices = new list<String>();
        Map<String, Department_Taxonomy__c> DTMap = new Map<String, Department_Taxonomy__c>();
        list<Department_Taxonomy__c> taxonomy = new list<Department_Taxonomy__c>();
        for(User usr : Users){
            if(usr.ITA_Office__c != null){
                offices.add(usr.ITA_Office__c);
            }
        }
        if(offices.size() > 0){
            taxonomy = [Select Id, Level_0__c, All__c, Country__c, DAS__c, Office__c, Region_1__c, Region_2__c, Old_Office_Name__c from Department_Taxonomy__c where Old_Office_Name__c in : offices];
        }
        if(taxonomy.size() > 0){
            for(Department_Taxonomy__c dt : taxonomy) {
                DTMap.put(dt.Old_Office_Name__c, dt);
            }
        }
        for(User usr : Users){
            if(usr.ITA_Office__c != null){
                if(DTMap.get(usr.ITA_Office__c) != null) {
                    usr.RH_Lev_7_Individual__c = DTMap.get(usr.ITA_Office__c).Level_0__c;
                    usr.RH_Lev_1_Top_Level__c = DTMap.get(Usr.ITA_Office__c).All__c;
                    usr.RH_Lev_2_DAS_Level__c = DTMap.get(Usr.ITA_Office__c).DAS__c;
                    usr.RH_Lev_3_Region_2__c = DTMap.get(Usr.ITA_Office__c).Region_2__c;
                    usr.RH_Lev_4_Region_1__c = DTMap.get(Usr.ITA_Office__c).Region_1__c;
                    usr.RH_Lev_5_Country__c = DTMap.get(Usr.ITA_Office__c).Country__c;
                    usr.RH_Lev_6_Office__c = DTMap.get(Usr.ITA_Office__c).Old_Office_Name__c;
                }
            }
        }
    }
}