src/objects/di_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings used to configure the Force-DI framework operations.</description>
    <fields>
        <fullName>OrgCachePartitionName__c</fullName>
        <description>The partition name to store the binding records to.  If this value is not specified, the bindings will be stored to the main Org Platform Cache.</description>
        <inlineHelpText>The partition name to store the binding records to.  If this value is not specified, the bindings will be stored to the main Org Platform Cache.</inlineHelpText>
        <label>Org Cache Partition Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UsePlatformCacheToStoreBindings__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, and a Platform Cache partition is specified, then Force-DI will store all bindings in the Platform Cache system on Salesforce.</description>
        <inlineHelpText>If checked, and a Platform Cache partition is specified, then Force-DI will store all bindings in the Platform Cache system on Salesforce.</inlineHelpText>
        <label>Use Platform Cache To Store Bindings</label>
        <type>Checkbox</type>
    </fields>
    <label>Force-DI Configurations</label>
</CustomObject>

src/classes/di_PlatformCacheTest.cls
@isTest
public class di_PlatformCacheTest {
	@isTest
    static void exerciseMethods() {
        di_Configurations__c c = new di_Configurations__c();
        c.OrgCachePartitionName__c = 'myPartitionName';
        c.UsePlatformCacheToStoreBindings__c = true;
        insert c;
        di_PlatformCache cache = di_PlatformCache.getInstance();
        di_PlatformCache.getConfig();
        di_PlatformCache.isStoringBindingInPlatformCache();
        cache.retrieveBindings('myString', Account.SObjectType);
    }
}