src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CVD</fullName>
        <active>true</active>
        <description>A countervailing duties investigation</description>
        <label>CVD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvestigationSelectorTest.cls
@isTest
public class InvestigationSelectorTest {

	/************************************************
	InvestigatioSelector IS CURRENTLY A PLACEHOLDER CLASS AND IS NOT USED IN APP.

    * This class performs unit tests on the InvestigationSelector
    * under these condititions.
    * 1. Test to ensure that the class is initialized when creating an investigation
    *************************************************/
	
	private static FINAL Integer COUNT = 1;

	@isTest static void allInvestigations() {
		Test.startTest();
		Test.stopTest();
		System.assertEquals((COUNT*2), InvestigationSelector.allInvestigations.size());
	}

	@testSetup static void dataSetup() {
		Date petitionDate = System.today();
		List<User> uList = new List<User>();
		List<Petition__c> pList = new List<Petition__c>();
		List<Investigation__c> iList = new List<Investigation__c>();
		List<Federal_Register__c> frList = new List<Federal_Register__c>();
		for (Integer i = 0; i < COUNT; i++) {
			User testUser = TestUtils.createAdminUser(false, 'myemail@email.com.testita', i);
			uList.add(testUser);
			Petition__c testADPetition = TestUtils.createPetition(petitionDate.addDays(i), 'AD ME', false);
			pList.add(testADPetition);
			Petition__c testCVDPetition = TestUtils.createPetition(petitionDate.addDays(7+i), 'CVD', false);
			pList.add(testCVDPetition);
		}
		insert uList;
		insert pList;
		for (Petition__c p : pList) {
			Investigation__c testInvestigation = TestUtils.createInvestigation('', p, false);
			iList.add(testInvestigation);
			Federal_Register__c initFR = TestUtils.createFR(p.Id, 'Petition__c', petitionDate.addDays(120), 'Initiation', false);
			frList.add(initFR);
		}
		insert iList;
		for (Investigation__c i : iList) {
			Federal_Register__c prelimFR = TestUtils.createFR(i.Id, 'Investigation__c', petitionDate.addDays(120), 'Preliminary', false);
			frList.add(prelimFR);
			Federal_Register__c finalFR = TestUtils.createFR(i.Id, 'Investigation__c', petitionDate.addDays(120), 'Final', false);
			frList.add(finalFR);
		}
		insert frList;
	}
}