src/objects/Federal_Register__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Federal Registers</relationshipLabel>
        <relationshipName>Federal_Registers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Federal Register</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Federal Register Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Federal Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Calc_Amended_Prelim_Determination_Sig__c</fullName>
        <description>Calculated Amended Preliminary Determination Signature</description>
        <inlineHelpText>Calculated Amended Preliminary Determination Signature</inlineHelpText>
        <label>Calc Amended Prelim Determination Sig</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Amended_Final_Signature__c</fullName>
        <description>Calculated Amended Final Signature</description>
        <inlineHelpText>Calculated Amended Final Signature</inlineHelpText>
        <label>Calculated Amended Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_ITC_Final_FR_Published__c</fullName>
        <description>Calculated ITC Final FR Published</description>
        <inlineHelpText>Calculated ITC Final FR Published</inlineHelpText>
        <label>Calculated ITC Final FR Published</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_ITC_Prelim_Determination__c</fullName>
        <description>Calculated ITC Prelim Determination</description>
        <inlineHelpText>Calculated ITC Prelim Determination</inlineHelpText>
        <label>Calculated ITC Prelim Determination</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Order_FR_Signature__c</fullName>
        <description>Calculated Order FR Signature</description>
        <inlineHelpText>Calculated Order FR Signature</inlineHelpText>
        <label>Calculated Order FR Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Postponement_of_PrelimDeterFR__c</fullName>
        <description>Calculated Postponement of Preliminary Determination Federal Register Signature</description>
        <inlineHelpText>Calculated Postponement of Preliminary Determination Federal Register Signature</inlineHelpText>
        <label>Calculated Postponement of PrelimDeterFR</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Prelim_Extension_Request_File__c</fullName>
        <description>Calculated Prelim Extension Request Filed</description>
        <inlineHelpText>Calculated Prelim Extension Request Filed</inlineHelpText>
        <label>Calculated Prelim Extension Request File</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Est_ITC_Notification_to_DOC_of_Final_Det__c</fullName>
        <description>Estimated ITC Notification to DOC of Final Determination</description>
        <inlineHelpText>Estimated ITC Notification to DOC of Final Determination</inlineHelpText>
        <label>Est ITC Notification to DOC of Final Det</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Order_FR_Published__c</fullName>
        <description>Estimated Order FR Published</description>
        <inlineHelpText>Estimated Order FR Published</inlineHelpText>
        <label>Estimated Order FR Published</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Team_Meeting_Deadline__c</fullName>
        <label>Final Team Meeting Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition_Initiation_Signature__c</fullName>
        <description>This is for either the Actual or Calculated Initiation Signature date from the Petition without any further calculation.  This is used in the lookup filter to align a CVD investigation with an AD investigation.</description>
        <label>Petition Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prelim_Team_Meeting_Deadline__c</fullName>
        <label>Prelim Team Meeting Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_of_Suspension_Gap_Period_Beg__c</fullName>
        <description>Termination of Suspension/Gap Period Begins</description>
        <inlineHelpText>Termination of Suspension/Gap Period Begins</inlineHelpText>
        <label>Termination of Suspension/Gap Period Beg</label>
        <type>Date</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CVD</fullName>
        <active>true</active>
        <description>A countervailing duties investigation</description>
        <label>CVD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DateCalculationServiceTest.cls
@isTest
public class DateCalculationServiceTest {

	/************************************************
    * This class performs unit tests on the DateCalculationService
    * under these condititions.
    * 1. Test to ensure that the class is initialized when creating a petition
    * 2. Test to ensure that the class is initialized when creating an Investigation
    * 3. Test to ensure that the date calculations are queried and held in class
    * 4. Test to ensure that the date calculations are applied to a record
    *************************************************/

	private static FINAL Integer COUNT = 1;

	private static List<Petition__c> petList {
		get {
			if (petList == null) {
				petList = new List<Petition__c>();
				petList = PetitionSelector.allPetitions;
			}
			return petList;
		}
	}

	private static List<Investigation__c> invList {
		get {
			if (invList == null) {
				invList = new List<Investigation__c>();
				invList = InvestigationSelector.allInvestigations;
			}
			return invList;
		}
	}

	@isTest static void setDateCalculations() {
		Test.startTest();
		DateCalculationService dcs = DateCalculationServiceDispatcher.getDateCalculationServiceInstance('Investigation__c');
		dcs.setDateCalculations('Investigation__c', 'AD');
		Test.stopTest();
		System.assertNotEquals(null, dcs.dateCalculations);
	}

	@isTest static void getCalculatedDates() {
		Test.startTest();
		DateCalculationService petDcs = DateCalculationServiceDispatcher.getDateCalculationServiceInstance('Petition__c');
		petDcs.getCalculatedDates(petList, 'Petition__c', '');
		DateCalculationService invDcs = DateCalculationServiceDispatcher.getDateCalculationServiceInstance('Investigation__c');
		invDcs.getCalculatedDates(invList, 'Investigation__c', '');
		Test.stopTest();
		for (Petition__c p : petList) {
			System.assertNotEquals(null, p.Calculated_Initiation_Signature__c);
		}
		for (Investigation__c i : invList) {
			System.debug('*** getCalculatedDates assert Investigation__c record: ' + i);
			System.assertNotEquals(null, i.Calculated_Preliminary_Signature__c);
			System.assertNotEquals(null, i.Preliminary_Announcement_Date__c);
			System.assertEquals(null, i.Calc_Amended_Prelim_Determination_Sig__c);
			System.assertEquals(null, i.Amended_Preliminary_Announcement_Date__c);
			System.assertNotEquals(null, i.Prelim_Team_Meeting_Deadline__c);
			System.assertNotEquals(null, i.Calculated_Final_Signature__c);
			System.assertNotEquals(null, i.Final_Announcement_Date__c);
			System.assertEquals(null, i.Calculated_Amended_Final_Signature__c);
			System.assertEquals(null, i.Amended_Final_Announcement_Date__c);
			System.assertNotEquals(null, i.Final_Team_Meeting_Deadline__c);
			System.assertNotEquals(null, i.Est_ITC_Notification_to_DOC_of_Final_Det__c);
			System.assertNotEquals(null, i.Calculated_Order_FR_Signature__c);
			System.assertNotEquals(null, i.Calculated_ITC_Final_FR_Published__c);
			System.assertNotEquals(null, i.Estimated_Order_FR_Published__c);
			System.assertEquals(null, i.Litigation_Hold_Expiration_Date__c);
			System.assertNotEquals(null, i.Calculated_Prelim_Extension_Request_File__c);
			System.assertNotEquals(null, i.Calculated_Postponement_of_PrelimDeterFR__c);
			System.assertNotEquals(null, i.Calculated_ITC_Prelim_Determination__c);
			System.assertNotEquals(null, i.Termination_of_Suspension_Gap_Period_Beg__c);
			System.assertNotEquals(null, i.Petition_Initiation_Signature__c);
		}

	}

	@testSetup static void dataSetup() {
		Date petitionDate = System.today();
		List<User> uList = new List<User>();
		List<Petition__c> pList = new List<Petition__c>();
		List<Investigation__c> iList = new List<Investigation__c>();
		List<Federal_Register__c> frList = new List<Federal_Register__c>();
		for (Integer i = 0; i < COUNT; i++) {
			User testUser = TestUtils.createAdminUser(false, 'myemail@email.com.testita', i);
			uList.add(testUser);
			Petition__c testADPetition = TestUtils.createPetition(petitionDate.addDays(i), 'AD ME', false);
			pList.add(testADPetition);
			Petition__c testCVDPetition = TestUtils.createPetition(petitionDate.addDays(i), 'CVD', false);
			pList.add(testCVDPetition);
		}
		insert uList;
		insert pList;
		for (Petition__c p : pList) {
			Investigation__c testInvestigation = TestUtils.createInvestigation('', p, false);
			iList.add(testInvestigation);
			Federal_Register__c initFR = TestUtils.createFR(p.Id, 'Petition__c', petitionDate.addDays(120), 'Initiation', false);
			frList.add(initFR);
		}
		insert iList;
		for (Investigation__c i : iList) {
			Federal_Register__c prelimFR = TestUtils.createFR(i.Id, 'Investigation__c', petitionDate.addDays(120), 'Preliminary', false);
			frList.add(prelimFR);
			Federal_Register__c finalFR = TestUtils.createFR(i.Id, 'Investigation__c', petitionDate.addDays(120), 'Final', false);
			frList.add(finalFR);
		}
		insert frList;
	}
}