src/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to check if the question is required</description>
        <inlineHelpText>Is it required?</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <referenceTo>Form_Section__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Validation_Type__c</fullName>
        <label>Validation Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Field</label>
    <nameField>
        <displayFormat>F-{000}</displayFormat>
        <label>Field Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Object_API__c</fullName>
        <defaultValue>&quot;Participation__c&quot;</defaultValue>
        <label>Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Section__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Section</label>
    <nameField>
        <displayFormat>FS-{000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <label>MicroSite</label>
    <nameField>
        <label>MicroSite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MicroSites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FieldController.cls
public with sharing class FieldController {
    public List<LayoutDescriberHelper.LayoutSection> layoutSections { get; set; }
    public List<SelectOption> supportedFieldList {get; set;}

    Form_Section__c form {get; set;}

    public FieldController(ApexPages.StandardController controller) {
        String sObjectType = 'Field__c';
        
        // Create list of fields to add to controller for object 
        List<String> fields = MetadataHelper.getFieldsForSobject(sObjectType);
        // Add fields to controller. This is to avoid the SOQL error in visualforce page
        if(!Test.isRunningTest()){
            controller.addFields(fields);
        }
        sObject obj = controller.getRecord();
        this.control = controller;
        Id sectionId = (Id)obj.get('Section__c');
        String parentObject = '';
        form = [SELECT Id, Object_API_Name__c, Form__r.Object_API__c FROM Form_Section__c WHERE Id =:sectionId];
        if(!String.IsBlank(form.Object_API_Name__c)) {
            parentObject = form.Object_API_Name__c;
        } else {
            parentObject = form.Form__r.Object_API__c;
        }
        supportedFieldList = MetadataHelper.getFieldListForObject(parentObject);
        /************************************************************************/
         //getting the default record type
        //if we want an specific layout we must provide the appropriate record type id
        id theRecordTypeIdToDescribe = LayoutDescriberHelper.getDefaultRecordType(obj);
        //get the layout section items
        layoutSections = LayoutDescriberHelper.describeSectionWithFields(theRecordTypeIdToDescribe, sObjectType);
        /***************************************************************************/
    }

    private final ApexPages.standardController control;
    
    public PageReference SetSystemOptions(){
        sObject obj = control.getRecord();
            Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
            Schema.sObjectType describedObject = globalDescribe.get(form.object_api_name__c != null ? form.object_api_name__c : form.form__r.Object_API__c);

            Schema.DescribeFieldResult field = describedObject.getDescribe().fields.getMap().get((string)obj.get('api__c')).getDescribe();
            if(field.getType() != Schema.DisplayType.BOOLEAN && !field.isNillable() && obj.get('required__c') != true){
                obj.put('required__c', true);
            }
            system.debug(field);
            obj.put('Validation_Type__c', field.getType().name());
            if(field.getType().name() == 'REFERENCE'){
                obj.put('Reference__c', field.getReferenceTo()[0].getDescribe().getName());
            }else{
                obj.put('Reference__c', '');
            }
            system.debug(obj);
        return null;
    }
}