src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Object_API__c</fullName>
        <defaultValue>&quot;Participation__c&quot;</defaultValue>
        <label>Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Form_Section__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section</label>
    <nameField>
        <displayFormat>FS-{000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SectionController.cls
public with sharing class SectionController {
        public List<LayoutDescriberHelper.LayoutSection> layoutSections { get; set; }
        public List<String> supportedObjects {get; set;}
        public List<SelectOption> supportedObjectsList { get {
                List<SelectOption> supportedObjectsList = new List<SelectOption>();
                supportedObjectsList.add(new SelectOption('', '--Default From Parent--'));
                for(String s: supportedObjects) {
                        supportedObjectsList.add(new SelectOption(s, s));
                }
                return supportedObjectsList;
        } set; }
        public SectionController(ApexPages.StandardController controller) {
                String sObjectType = 'Form_Section__c';
                
                // Create list of fields to add to controller for object 
                List<String> fields = MetadataHelper.getFieldsForSobject(sObjectType);
                // Add fields to controller. This is to avoid the SOQL error in visualforce page
                if(!Test.isRunningTest()){
                    controller.addFields(fields);
                }
                sobject obj = controller.getRecord();
                system.debug(obj);
                Id formId = (Id)obj.get('Form__c');

                String parentObject = [SELECT Id, Object_API__c FROM Form__c WHERE Id =:formId].Object_API__c;
                supportedObjects = MetadataHelper.getChildObjects(parentObject);
                /************************************************************************/
                 //getting the default record type
                //if we want an specific layout we must provide the appropriate record type id
                id theRecordTypeIdToDescribe = LayoutDescriberHelper.getDefaultRecordType(obj);
                //get the layout section items
                layoutSections = LayoutDescriberHelper.describeSectionWithFields(theRecordTypeIdToDescribe, sObjectType);
                /***************************************************************************/
        
        }
}