src/objects/Framework__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What is the Product that this is tied to for Automation?</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Frameworks</relationshipLabel>
        <relationshipName>Frameworks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose an Active Mission.</errorMessage>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Frameworks</relationshipLabel>
        <relationshipName>Frameworks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the Framework is currently active/available.</description>
        <inlineHelpText>Is this Framework currently active?</inlineHelpText>
        <label>Active Framework</label>
        <type>Checkbox</type>
    </fields>
    <label>Framework</label>
    <nameField>
        <label>Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Framework__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Framework</label>
        <referenceTo>Framework__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Price Books</relationshipLabel>
        <relationshipName>Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the Program is currently available.</description>
        <inlineHelpText>Is this an active/available Program?</inlineHelpText>
        <label>Active Program</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductSelector_Test.cls
@IsTest
public class ProductSelector_Test{

	/*
	Test class for the ProductSelector class
	*/

	public static testMethod void createOrder() {
		Account acct = TestUtils.createAccount(true);
		Participation__c app = TestUtils.createApplication(acct.Id);
		Program__c p = TestUtils.createProgram('Program Name', true);
		ProductSelector ps = new ProductSelector();
		Order o = ps.createOrder(acct.Id, app.Id, p.Id);
		System.assertNotEquals(o, null);
	}

	public static testMethod void addPriceBookEntryToOrder() {
		Account acct = TestUtils.createAccount(true);
		Participation__c app = TestUtils.createApplication(acct.Id);
		Program__c program = TestUtils.createProgram('Program Name', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Order o = TestUtils.createOrder(acct.Id, app.Id, program.Id, pricebook.Id);

		Product2 productEU = TestUtils.createProduct('EU-US', true);
		Product2 productSW = TestUtils.createProduct('SW-US', true);
		Framework__c frameworkEU = new Framework__c(Name = 'EU-US', Product__c = productEU.Id, Program__c = program.Id, isActive__c = true);
		Framework__c frameworkSW = new Framework__c(Name = 'SW-US', Product__c = productSW.Id, Program__c = program.Id, isActive__c = true);
		insert(new Framework__c[]{frameworkEU, frameworkSW});
		List<Product2> products = new Product2[]{productEU, productSW};
		List<PricebookEntry> priceBookEntries = TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});

		ProductSelector ps = new ProductSelector();
		OrderItem oi = ps.addPriceBookEntryToOrder(o.Id, [SELECT Id FROM PricebookEntry WHERE Pricebook2Id = :pricebook.Id LIMIT 1].Id);
		System.assertNotEquals(oi, null);
	}

	public static testMethod void addProductToOrder() {
		Account acct = TestUtils.createAccount(true);
		Participation__c app = TestUtils.createApplication(acct.Id);
		Program__c program = TestUtils.createProgram('Program Name', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Order o = TestUtils.createOrder(acct.Id, app.Id, program.Id, pricebook.Id);

		Product2 productEU = TestUtils.createProduct('EU-US', true);
		Product2 productSW = TestUtils.createProduct('SW-US', true);
		Framework__c frameworkEU = new Framework__c(Name = 'EU-US', Product__c = productEU.Id, Program__c = program.Id, isActive__c = true);
		Framework__c frameworkSW = new Framework__c(Name = 'SW-US', Product__c = productSW.Id, Program__c = program.Id, isActive__c = true);
		insert(new Framework__c[]{frameworkEU, frameworkSW});
		List<Product2> products = new Product2[]{productEU, productSW};
		List<PricebookEntry> priceBookEntries = TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});

		ProductSelector ps = new ProductSelector();
		OrderItem oi = ps.addProductToOrder(o.Id, productEU.Id, pricebook.Id);
		System.assertNotEquals(oi, null);
		OrderItem oi2 = ps.addProductToOrder(o.Id, productSW.Id, pricebook.Id);
		System.assertNotEquals(oi2, null);
	}

	public static testMethod void deleteProductFromOrder() {
		Account acct = TestUtils.createAccount(true);
		Participation__c app = TestUtils.createApplication(acct.Id);
		Program__c program = TestUtils.createProgram('Program Name', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Order o = TestUtils.createOrder(acct.Id, app.Id, program.Id, pricebook.Id);
		Product2 prod = TestUtils.createProduct(true);
		ProductSelector ps = new ProductSelector();
		Boolean deleted = ps.deleteProductFromOrder(o.Id, prod.Id);
		System.assertEquals(deleted, true);
	}

	public static testMethod void getAllOrderProducts() {
		Account acct = TestUtils.createAccount(true);
		Participation__c app = TestUtils.createApplication(acct.Id);
		Program__c program = TestUtils.createProgram('Program Name', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Order o = TestUtils.createOrder(acct.Id, app.Id, program.Id, pricebook.Id);

		Product2 productEU = TestUtils.createProduct('EU-US', true);
		Product2 productSW = TestUtils.createProduct('SW-US', true);
		Framework__c frameworkEU = new Framework__c(Name = 'EU-US', Product__c = productEU.Id, Program__c = program.Id, isActive__c = true);
		Framework__c frameworkSW = new Framework__c(Name = 'SW-US', Product__c = productSW.Id, Program__c = program.Id, isActive__c = true);
		insert(new Framework__c[]{frameworkEU, frameworkSW});
		List<Product2> products = new Product2[]{productEU, productSW};
		List<PricebookEntry> priceBookEntries = TestUtils.createPricebookEntries(products, new Id[]{Test.getStandardPricebookId(), pricebook.Id});

		ProductSelector ps = new ProductSelector();
		OrderItem oi = ps.addProductToOrder(o.Id, productEU.Id, pricebook.Id);
		OrderItem oi2 = ps.addProductToOrder(o.Id, productSW.Id, pricebook.Id);

		List<Product2> orderProducts = ps.getAllOrderProducts(o.Id);
		System.assertEquals(orderProducts.size() > 0, true);
	}

	public static testMethod void deleteOrder() {
		Account acct = TestUtils.createAccount(true);
		Participation__c app = TestUtils.createApplication(acct.Id);
		Program__c program = TestUtils.createProgram('Program Name', true);
		Pricebook2 pricebook = TestUtils.createPricebook(program.Id);
		Order o = TestUtils.createOrder(acct.Id, app.Id, program.Id, pricebook.Id);
		ProductSelector ps = new ProductSelector();
		Boolean deleted = ps.deleteOrder(o.Id);
		System.assertEquals(deleted, true);
	}

	public static testMethod void coverExceptions() {
		ProductSelector ps = new ProductSelector();
		Account acct = TestUtils.createAccount(true);

		Id fakeId = Test.getStandardPricebookId();  //Any valid ID can be used
		Order o = ps.createOrder(fakeId, fakeId, fakeId);
		System.assertEquals(o, null);
		OrderItem oi = ps.addPriceBookEntryToOrder(fakeId, fakeId);
		System.assertEquals(oi, null);
		oi = ps.addProductToOrder(fakeId, fakeId, fakeId);
		System.assertEquals(oi, null);
		List<Product2> products = ps.getAllOrderProducts(fakeId);
		System.assertEquals(products.size(), 0);
	}

}