src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tolling_Day__c.object
<CustomObject>
    <label>Tolling Day</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Tolling Days</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tolling Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADCVD_TollingDayMapper.cls
public without sharing class ADCVD_TollingDayMapper implements ADCVD_IMapper {
    public static ADCVD_TollingDayMapper instance = null;
    public static Map<Id, Tolling_Day__c> idToAllTollingDayMap = new Map<Id, Tolling_Day__c>();
    public static Map<Id,Tolling_Day__c> standardTollingDayMap = new Map<Id,Tolling_Day__c>();
    // parent record Id (petition, investigation, or segment) > Tolling Id > Tolling record
    public static Map<Id,Map<Id,Tolling_Day__c>> specificTollingDayMap = new Map<Id,Map<Id,Tolling_Day__c>>();

    public ADCVD_TollingDayMapper() {}
    @TestVisible
    private ADCVD_TollingDayMapper(Boolean newQuery) {
        if (standardTollingDayMap.isEmpty()) {
            System.debug('Querying Tolling Days in ADCVD_TollingDayMapper');
            for (Tolling_Day__c td : ADCVD_TollingDaySelector.newInstance().selectAllToLimit()) {
                addTollingDayToMap(td);
            }
        }
    }
    public ADCVD_TollingDayMapper getInstance() {
        if (instance == null) {
            return getNewInstance();
        }
        return instance;
    }
    public static ADCVD_TollingDayMapper getNewInstance() {
        instance = new ADCVD_TollingDayMapper(true);
        return instance;
    }
    public Map<Id,Tolling_Day__c> getMap() {
        return standardTollingDayMap;
    }
    public Map<Id, Tolling_Day__c> getMap(Boolean includeLocked) {
        //Locking not currently implemented on Tolling Day, so all is returned either way
        if (includeLocked) {
            return idToAllTollingDayMap;
        } else {
            return idToAllTollingDayMap;
        }
    }
    public Map<Id, Tolling_Day__c> getMap(Id parentId) {
        return specificTollingDayMap.get(parentId);
    }
    public void addTollingDayToMap(Tolling_Day__c td) {
        System.debug('Adding Tolling to Maps');
        if (Utils.getRecordTypeDeveloperNameMap(td).get(td.RecordTypeId) == 'Toll_By_Specific_Record') {
            //add to specificMap with populated lookup as Id
            String populatedParentLookup = '';
            if(td.Petition__c != null) {
                populatedParentLookup = 'Petition__c';
            } else if (td.Investigation__c != null) {
                populatedParentLookup = 'Investigation__c';
            } else if (td.Segment__c != null) {
                populatedParentLookup = 'Segment__c';
            }
            if (populatedParentLookup != '') {
                System.debug('populated parent lookup: ' + populatedParentLookup);
                Id parentId = (Id)td.get(populatedParentLookup);
                Map<Id, Tolling_Day__c> tempMap = new Map<Id, Tolling_Day__c>();
                if (specificTollingDayMap.get(parentId) != null) {
                    tempMap = specificTollingDayMap.get(parentId);
                }
                tempMap.put(td.Id, td);
                specificTollingDayMap.put(parentId, tempMap);
                System.debug('specificTollingDayMap has been updated to: ' + specificTollingDayMap);
            }
        } else if (Utils.getRecordTypeDeveloperNameMap(td).get(td.RecordTypeId) == 'Standard_Tolling'){
            standardTollingDayMap.put(td.Id, td);
        }
        idToAllTollingDayMap.put(td.Id, td);
    }


}