src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>AD_Investigation_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AD investigation that this CVD investigation is aligned to</description>
        <label>AD Investigation Aligned To</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Investigation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AD</value>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Commodity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Commodity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Initiation_Signature__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Initiation_Signature__c</valueField>
            </filterItems>
            <infoMessage>The Product on both investigations must match as well</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Aligned CVD Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CVD</fullName>
        <active>true</active>
        <description>A countervailing duties investigation</description>
        <label>CVD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>ADCVD Case Number Text Value Deprecated</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <description>Referenced from parent petition</description>
        <label>Commodity Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cement and Ceramics</fullName>
                </value>
                <value>
                    <fullName>Chemicals and Allied Industries</fullName>
                </value>
                <value>
                    <fullName>Foodstuffs</fullName>
                </value>
                <value>
                    <fullName>Machinery and Automotive</fullName>
                </value>
                <value>
                    <fullName>Minerals</fullName>
                </value>
                <value>
                    <fullName>Other Metals and Articles of Metal</fullName>
                </value>
                <value>
                    <fullName>Other Mfg.</fullName>
                </value>
                <value>
                    <fullName>Paper and Paperboard</fullName>
                </value>
                <value>
                    <fullName>Plastics and Rubber</fullName>
                </value>
                <value>
                    <fullName>Steel-Related</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SyncUtilityTest.cls
@isTest
public class SyncUtilityTest {
	private static Date petitionDate = System.today();
	private static String targetObjectName = '';
	private static Set<String> currentSources = new Set<String>();
	private static Map<String,String> currentFieldMappings = new Map<String,String>();	
	private static List<Investigation__c> iList {
		get {
			if(iList == null) {
				iList = [SELECT Id, RecordTypeId, AD_Investigation_Aligned_To__c, Calculated_Final_Signature__c, Petition__c FROM Investigation__c];
			}
			return iList;
		}
	}
	private static List<Petition__c> pList {
		get {
			if(pList == null) {
				pList = [SELECT Id, ADCVD_Case_Number__c, Commodity__c FROM Petition__c];
			}
			return pList;
		}
	}
	private static Investigation__c iAD {
		get {
			Id recordType = utils.getRecordTypeIdMap('Investigation__c').get('AD');
			iAD = [SELECT Id, RecordTypeId, AD_Investigation_Aligned_To__c, Calculated_Final_Signature__c, Petition__c FROM Investigation__c WHERE RecordTypeId =: recordType LIMIT 1];
			return iAD;
		}	
	}
	private static void targetObjectName(List<SObject> soList) {
		targetObjectName = utils.getSObjectName(soList[0]);
	}
	private static Set<String> currentSources(String s) {
		if(s != null) {
			currentSources.removeAll(currentSources);
			currentSources.add(s);
		} else if(targetObjectName == 'Investigation__c') {
			currentSources.removeAll(currentSources);
			currentSources.add('Petition__c');
			currentSources.add('Investigation__c');
		}
		return currentSources;
	}

	@isTest static void initializeInvestigation() {
		Test.startTest();
		targetObjectName(iList);
		SyncUtility.initialize(iList);//initializes, setting targetObjectName and investigationList in utility
		System.assertEquals(targetObjectName, SyncUtility.targetObjectName);
		System.assertEquals(iList, SyncUtility.investigationList);
		Test.stopTest();
	}
	@isTest static void setInvestigationSourceObjectNames() {
		Test.startTest();
		targetObjectName(iList);
		SyncUtility.initialize(iList);//initializes, setting targetObjectName and investigationList in utility
		SyncUtility.setSourceObjectNames(currentSources('Petition__c'), false);
		System.assertEquals(currentSources, SyncUtility.sourceObjectNames);//both have only Petition__c
		SyncUtility.setSourceObjectNames(currentSources, false);
		currentSources.removeAll(currentSources);//reset to size of 0
		System.assertNotEquals(currentSources, SyncUtility.sourceObjectNames);//currentSources size is 0, but that call all sources in utility
		SyncUtility.setSourceObjectNames(currentSources, true);
		System.assertNotEquals(currentSources, SyncUtility.sourceObjectNames);//currentSources still has Petition__c, but the boolean "true" set sourceObjectNames to all sources
		SyncUtility.setSourceObjectNames(currentSources(null), false);
		System.assertEquals(currentSources, SyncUtility.sourceObjectNames);//both have both Petition__c and Investigation__c by passing
		Test.stopTest();
	}
	@isTest static void setInvestigationSyncFieldMap() {
		Test.startTest();
		targetObjectName(iList);
		SyncUtility.initialize(iList);//initializes, setting targetObjectName and investigationList in utility
		SyncUtility.setSourceObjectNames(currentSources, true);//sets sourceObjectNames to all in utility
		SyncUtility.setSyncFieldMap();//grabs CMT for investigation
		System.assertNotEquals(null, SyncUtility.syncFieldMap.get('Petition__c'));//syncFieldMap has Petition values
		currentFieldMappings = SyncUtility.syncFieldMap.get('Petition__c');//map the Petition mappings to current
		System.assertEquals(currentFieldMappings.get('ADCVD_Case_Number__c'), 'ADCVD_Case_Number__c');//confirm a mapping is correct
		currentFieldMappings = SyncUtility.syncFieldMap.get('Investigation__c');//map the Investigation mappings to current
		System.assertEquals(currentFieldMappings.get('Calculated_Final_Signature__c'),'Calculated_Final_Signature__c');//confirm a mapping is correct
		Test.stopTest();
	}
	@isTest static void setInvestigationSourceObjectMap() {
		Test.startTest();
		targetObjectName(iList);
		SyncUtility.initialize(iList);//initializes, setting targetObjectName and investigationList in utility
		SyncUtility.setSourceObjectNames(currentSources(null), true);//sets sourceObjectNames to all in utility
		SyncUtility.setSyncFieldMap();//grabs CMT for investigation
		SyncUtility.setSourceObjectsMap();//map source objects to source map
		System.assertEquals('Foodstuffs', ((Petition__c)SyncUtility.sourceObjectsMap.get(pList[0].Id)).Commodity__c);//confirm source object map queried correctly
		for(Investigation__c i : iList) {
			if(i.RecordTypeId == utils.getRecordTypeIdMap(i).get('AD')){
				System.assertEquals(i.Id, SyncUtility.sourceObjectsMap.get(i.Id).Id);//the AD investigation was queried
			} else {
				System.assertEquals(null, SyncUtility.sourceObjectsMap.get(i.Id));//the CVD investigation was not queried
			}
		}
		Test.stopTest();
	}
	@isTest static void setInvestigationTargetObjectValues() {
		Test.startTest();
		Investigation__c i = TestUtils.createInvestigation('CVD', pList[0], false);
		i.AD_Investigation_Aligned_To__c = iAD.Id;
		iList.add(i);
		targetObjectName(iList);
		SyncUtility.initialize(iList);//initializes, setting targetObjectName and investigationList in utility
		SyncUtility.setSourceObjectNames(currentSources(null), true);//sets sourceObjectNames to all in utility
		SyncUtility.setSyncFieldMap();//grabs CMT for investigation
		SyncUtility.setSourceObjectsMap();//map source objects to source map
		SyncUtility.setTargetObjectValues();//set the source value to the target value
		System.assertEquals(i.Calculated_Final_Signature__c, iAD.Calculated_Final_Signature__c);//the CVD investigation is aligned to the AD
		System.assertEquals(i.Commodity__c, pList[0].Commodity__c);//the Petition synced to Investigation
		Test.stopTest();
	}


	@testSetup static void dataSetup() {
		Test.startTest();
		User testUser = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
		List<Petition__c> petitionsToInsert = new List<Petition__c>();
		Petition__c testAdPetition = TestUtils.createPetition(petitionDate, 'AD ME', false);
		testAdPetition.Commodity__c = 'Foodstuffs';
		petitionsToInsert.add(testAdPetition);
		Petition__c testCvdPetition = TestUtils.createPetition(petitionDate, 'CVD', false);
		testCvdPetition.Commodity__c = 'Foodstuffs';
		petitionsToInsert.add(testCvdPetition);
		insert petitionsToInsert;
		Investigation__c testADinvestigation = TestUtils.createInvestigation('AD', testAdPetition, true);
		Investigation__c testCVDinvestigation = TestUtils.createInvestigation('CVD', testCvdPetition, false);
		testCVDinvestigation.AD_Investigation_Aligned_To__c = testADinvestigation.Id;
		insert testCVDinvestigation;
	}
}