src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>AD_Investigation_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AD investigation that this CVD investigation is aligned to</description>
        <label>AD Investigation Aligned To</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Investigation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AD</value>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Commodity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Commodity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Initiation_Signature__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Initiation_Signature__c</valueField>
            </filterItems>
            <infoMessage>The Product on both investigations must match as well</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Aligned CVD Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prelim_Extension_of_days__c</fullName>
        <description>Prelim Extension (# of days)</description>
        <inlineHelpText>Prelim Extension (# of days)</inlineHelpText>
        <label>Prelim Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <recordTypes>
        <fullName>AD</fullName>
        <active>true</active>
        <description>An anti dumping investigation</description>
        <label>AD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CVD</fullName>
        <active>true</active>
        <description>A countervailing duties investigation</description>
        <label>CVD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Initiation_Signature__c</fullName>
        <description>Actual Initiation Signature</description>
        <inlineHelpText>Actual Initiation Signature</inlineHelpText>
        <label>Actual Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition_Filed__c</fullName>
        <label>Petition Filed</label>
        <type>Date</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvestigationTriggerHandlerTest.cls
@isTest
public class InvestigationTriggerHandlerTest {
	private static Date petitionDate = System.today();
	private static Date testActual = System.today();//reusable date variable for each test to add roll forward logic allowing data normalization
	private static Date testCalculated = System.today();//reusable date variable for each test to add roll forward logic allowing data normalization
	private static User u{
		get{
			if(u == null){
				u = [SELECT Id, ProfileId, isActive, Alias, LanguageLocaleKey, LastName, FirstName, 
								Email, EmailEncodingKey, TimeZoneSidKey, CommunityNickname, Username 
							FROM User WHERE LastName =: 'LastName1' LIMIT 1];
			}
			System.debug('User u: ' + u);
			return u;
		}
	}
	private static Petition__c p{
		get{
			if (p == null) {
				p = [SELECT Id, Petition_Filed__c, Actual_Initiation_Signature__c, Calculated_Initiation_Signature__c FROM Petition__c LIMIT 1];
			}
			System.System.debug('Petition p: ' + p);
			return p;
		}
	}

	@isTest static void initialize(){
		Test.startTest();
		Investigation__c i = TestUtils.createInvestigation('AD', p, true);
		List<Investigation__c> iList = new List<Investigation__c>();
		iList.add(i);
		InvestigationTriggerHandler.initialize(iList, null);
		System.assertEquals(p.Id, InvestigationTriggerHandler.petitionsInScopeMap.get(p.Id).Id);
		System.assertEquals('AD', InvestigationTriggerHandler.recordTypeNameMap.get(i.RecordTypeId));
	}

	//setCalculatedPreliminarySignature
	//Test has 2 parts that test two dates each: AD and CVD
	@isTest static void setCalculatedPreliminarySignature(){
		Test.startTest();
		//AD investigation
		//AD based on calculated
		Investigation__c iAD = TestUtils.createInvestigation('AD', p, true);
		//p.Actual_Initiation_Signature__c is null, so compare Calculated_Initiation_Signature__c
		testCalculated = ADCVD_TollingDayUtility.rollForwardNextBusinessDay(p.Calculated_Initiation_Signature__c.addDays(140));
		System.assertEquals(testCalculated,
			[SELECT Id, Calculated_Preliminary_Signature__c FROM  Investigation__c WHERE Id =: iAD.Id LIMIT 1].Calculated_Preliminary_Signature__c);

		//AD based on Actual
		p.Actual_Initiation_Signature__c = p.Calculated_Initiation_Signature__c.addDays(-14);//set p.Actual_Initiation_Signature__c
		iAD.Prelim_Extension_of_days__c = iAD.Prelim_Extension_of_days__c == null ? 7 : 7;//add Prelim_Extension_of_days__c and avoid NPE in this test
		update p;//update p
		update iAD;//update iAD, adds Prelim_Extension_of_days__c.  Calling update since this is a future call in org
		//p.Actual_Initiation_Signature__c is set, so compare Actual_Initiation_Signature__c + Prelim_Extension_of_days__c
		testActual = ADCVD_TollingDayUtility.rollForwardNextBusinessDay(p.Actual_Initiation_Signature__c.addDays(140).addDays(7));
		System.assertEquals(testActual,
			[SELECT Id, Calculated_Preliminary_Signature__c FROM  Investigation__c WHERE Id =: iAD.Id LIMIT 1].Calculated_Preliminary_Signature__c);

		//CVD investigation
		//CVD based on calculated
		p.Actual_Initiation_Signature__c = null;
		update p;//reset for CVD logic
		Investigation__c iCVD = TestUtils.createInvestigation('CVD', p, true);
		//p.Actual_Initiation_Signature__c is null, so compare Calculated_Initiation_Signature__c
		testCalculated = ADCVD_TollingDayUtility.rollForwardNextBusinessDay(p.Calculated_Initiation_Signature__c.addDays(65));
		System.assertEquals(testCalculated, 
			[SELECT Id, Calculated_Preliminary_Signature__c FROM  Investigation__c WHERE Id =: iCVD.Id LIMIT 1].Calculated_Preliminary_Signature__c);

		//CVD based on actual
		p.Actual_Initiation_Signature__c = p.Calculated_Initiation_Signature__c.addDays(-14);//set p.Actual_Initiation_Signature__c
		iCVD.Prelim_Extension_of_days__c = iCVD.Prelim_Extension_of_days__c == null ? 7 : 7;//add Prelim_Extension_of_days__c and avoid NPE in this test
		update p;//update p
		update iCVD;//update iCVD, adds Prelim_Extension_of_days__c. Calling update since this is a future call in org
		//p.Actual_Initiation_Signature__c is set, so compare Actual_Initiation_Signature__c + Prelim_Extension_of_days__c
		testActual = ADCVD_TollingDayUtility.rollForwardNextBusinessDay(p.Actual_Initiation_Signature__c.addDays(65).addDays(7));
		System.assertEquals(testActual,
			[SELECT Id, Calculated_Preliminary_Signature__c FROM  Investigation__c WHERE Id =: iCVD.Id LIMIT 1].Calculated_Preliminary_Signature__c);
		Test.stopTest();
	}

	//basic framework for tests that also test alignment
	//Test has 2 parts that test 2 dates each and 3rd part that tests alignment
/*	@isTest static void setCalculatedFinalSignature() {
		Test.startTest();
		//AD Investigation
		//AD based on calculated
		


		//CVD Investigation
		//CVD based on actual



		//CVD aligned to AD
		iCVD.AD_Investigation_Aligned_To__c = iAD.Id;
		update iCVD;
		System.assertEquals([SELECT Calculated_Final_Signature__c FROM Investigation__c WHERE Id =: iAD.Id LIMIT 1].Calculated_Final_Signature__c,
							[SELECT Calculated_Final_Signature__c FROM Investigation__c WHERE Id =: iCVD.Id LIMIT 1].Calculated_Final_Signature__c)
	}
*/
	@testSetup static void dataSetup() {
		Test.startTest();
		User testUser = TestUtils.createAdminUser(true, 'myemail@email.com.testita', 1);
		Petition__c testPetition = TestUtils.createPetition(petitionDate, 'AD ME', true);
	}

	private static String attemptInsert(SObject o){
		String error = '';
		try{
			insert o;
			error = 'Success';
		} catch (DmlException e) {
			error = e.getMessage();
		}
		return error;
	}
}