src/objects/Investigation__c.object
<CustomObject>
    <fields>
        <fullName>AD_Investigation_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AD investigation that this CVD investigation is aligned to</description>
        <label>AD Investigation Aligned To</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Investigation__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AD</value>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Commodity__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Commodity__c</valueField>
            </filterItems>
            <filterItems>
                <field>Investigation__c.Petition_Initiation_Signature__c</field>
                <operation>equals</operation>
                <valueField>$Source.Petition_Initiation_Signature__c</valueField>
            </filterItems>
            <infoMessage>The Product on both investigations must match as well</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Aligned CVD Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Extension_of_days__c</fullName>
        <description>Final Extension (# of days)</description>
        <inlineHelpText>Final Extension (# of days)</inlineHelpText>
        <label>Final Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prelim_Extension_of_days__c</fullName>
        <description>Prelim Extension (# of days)</description>
        <inlineHelpText>Prelim Extension (# of days)</inlineHelpText>
        <label>Prelim Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Investigation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>ADCVD Case Number Text Value Deprecated</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Referenced from parent Petition</description>
        <label>Country Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Iran</fullName>
                </value>
                <value>
                    <fullName>Iraq</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <description>Initiation Extension (# of days)</description>
        <inlineHelpText>Initiation Extension (# of days)</inlineHelpText>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Litigation_Resolved__c</fullName>
        <label>Litigation Resolved</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Litigation_YesNo__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>Litigation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Segment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <formula>ADCVD_Case__r.Name</formula>
        <label>ADCVD Case Number Text Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Administrative_Review_Aligned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Administrative Review Aligned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>New Shipper Review</value>
            </filterItems>
            <filterItems>
                <field>Segment__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Administrative Review</value>
            </filterItems>
            <filterItems>
                <field>$Source.ADCVD_Order__c</field>
                <operation>equals</operation>
                <valueField>Segment__c.ADCVD_Order__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Aligned New Shipper Reviews</relationshipLabel>
        <relationshipName>Aligned_New_Shipper_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calculated_Final_Signature__c</fullName>
        <description>Calculated Final Signature</description>
        <inlineHelpText>Calculated Final Signature</inlineHelpText>
        <label>Calculated Final Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Calculated_Preliminary_Signature__c</fullName>
        <description>Calculated Preliminary Signature</description>
        <inlineHelpText>Calculated Preliminary Signature</inlineHelpText>
        <label>Calculated Preliminary Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(ADCVD_Case__r.Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Extension_of_days__c</fullName>
        <description>Final Extension (# of days)</description>
        <inlineHelpText>If &quot;Preliminary Extension (# of days)&quot; + &quot;Final Extension (# of days)&quot; &gt; 45 days, it is considered late.</inlineHelpText>
        <label>Final Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Litigation_YesNo__c</fullName>
        <label>Litigation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prelim_Extension__c</fullName>
        <label>Prelim Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Segment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <recordTypes>
        <fullName>New_Shipper_Review</fullName>
        <active>true</active>
        <label>New Shipper Review</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staffing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <label>ADCVD Case Number</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Staffing Assignments</relationshipLabel>
        <relationshipName>Staffing_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staffing Assignment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Staffing Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffing Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/ChatterPostService.cls
/**
 * 
 *    Created by Joshua Moody
 *    on Jan 11 2018
 *    MIL Corporation
 * 
 **/

public class ChatterPostService {

	/***********************************************************************
	* This class accepts the parent records, performs logic to see if any posts 
	* are needed, gets those posts stored in the org using the CustomMetadataSelector,
	* gets the Staffing Personnel to mention using the StaffingAssignmentSelector,
	* and posts those to Chatter using the ConnectApiHelper.
	***********************************************************************/
	
	public void getChatterPosts(Map<Id,SObject> oldMap, Map<Id,SObject> newMap, String sObjectName) {
		List<Automated_Chatter_Post__mdt> postsList = CustomMetadataSelector.getPostsList(sObjectName);//get all posts for this SObjectType
		StaffingAssignmentsSelector.setParentIdsToStaffLists(newMap.keySet(), sObjectName);//initialized map of all staffing assignments in scope for all parent records
		for(Id i : newMap.keySet()) {
			//initialize strings to be used in post
			String caseNumber = (String)newMap.get(i).get('ADCVD_Case_Number__c') + '--' + (String)newMap.get(i).get('Name') + ' from ' + (String)newMap.get(i).get('Country__c');
			String message = '';
			Map<String,String> conditionToMessageMap = new Map<String,String>();
			//determine if conditions were met for posting
			if (sObjectName == 'Petition__c') {
				Petition__c oldPet = (Petition__c)oldMap.get(i);
				Petition__c newPet = (Petition__c)newMap.get(i);

				if (oldPet.Initiation_Extension_of_days__c != newPet.Initiation_Extension_of_days__c && newPet.Calculated_Initiation_Signature__c != null) {
					message = 'Initiation Extension Number of Days changed from ' + oldPet.Initiation_Extension_of_days__c + ' to ' + newPet.Initiation_Extension_of_days__c;
					message += '<p>The Calculated Initiation Signature date is: <b>' + newPet.Calculated_Initiation_Signature__c.format() + '</b></p>';
					conditionToMessageMap.put('Extension', message);
				}
			} else if (sObjectName == 'Investigation__c') {
				Investigation__c oldInv = (Investigation__c)oldMap.get(i);
				Investigation__c newInv = (Investigation__c)newMap.get(i);

				if (oldInv.AD_Investigation_Aligned_To__c != newInv.AD_Investigation_Aligned_To__c) {
					String changeType = newInv.AD_Investigation_Aligned_To__c == null ? 'removed' : 'added';
					message = 'Alignment has been ' + changeType;
					conditionToMessageMap.put('Alignment', message);
				}
				if (oldInv.Prelim_Extension_of_days__c != newInv.Prelim_Extension_of_days__c && newInv.Calculated_Preliminary_Signature__c != null) {
					message = '<p> Preliminary Extension Number of Days changed from ' + oldInv.Prelim_Extension_of_days__c + ' to ' + newInv.Prelim_Extension_of_days__c + '</p>';
					message += '<p> The Calculated Preliminary Signature date is: <b>' + newInv.Calculated_Preliminary_Signature__c.format() + '</b></p>';
					conditionToMessageMap.put('Extension', message);
				}
				if (oldInv.Final_Extension_of_days__c != newInv.Final_Extension_of_days__c && newInv.Calculated_Final_Signature__c != null) {
					message = conditionToMessageMap.get('Extension') != null ? conditionToMessageMap.get('Extension') : '';
					message += '<p> Final Extension Number of Days changed from ' + oldInv.Final_Extension_of_days__c + ' to ' + newInv.Final_Extension_of_days__c + '</p>';
					message += '<p> The Calculated Final Signature date is: <b>' + newInv.Calculated_Final_Signature__c.format() + '</b></p>';
					conditionToMessageMap.put('Extension', message);

				}
			} else if (sObjectName == 'Segment__c') {
				Segment__c oldSeg = (Segment__c)oldMap.get(i);
				Segment__c newSeg = (Segment__c)newMap.get(i);

				if (Utils.getRecordTypeDeveloperNameMap(newSeg).get(newSeg.RecordTypeId) == 'New_Shipper_Review'
					&& oldSeg.Administrative_Review_Aligned_To__c != newSeg.Administrative_Review_Aligned_To__c) {
					String changeType = newSeg.Administrative_Review_Aligned_To__c == null ? 'removed' : 'added';
					message = 'Alignment has been ' + changeType;
					conditionToMessageMap.put('Alignment', message);
				}
				if (oldSeg.Initiation_Extension_of_days__c != newSeg.Initiation_Extension_of_days__c && newSeg.Calculated_Initiation_Signature__c != null) {
					message = 'Initiation Extension Number of Days changed from ' + oldSeg.Initiation_Extension_of_days__c + ' to ' + newSeg.Initiation_Extension_of_days__c;
					message += '<p>The Calculated Initiation Signature date is: <b>' + newSeg.Calculated_Initiation_Signature__c.format() + '</b></p>';
					conditionToMessageMap.put('Extension', message);
				}
				if (oldSeg.Prelim_Extension__c != newSeg.Prelim_Extension__c && newSeg.Calculated_Preliminary_Signature__c != null) {
					message = conditionToMessageMap.get('Extension') != null ? conditionToMessageMap.get('Extension') : '';
					message += '<p>Preliminary Extension Number of Days changed from ' + oldSeg.Prelim_Extension__c + ' to ' + newSeg.Prelim_Extension__c + '</p>';
					message += '<p>The Calculated Preliminary Signature date is: <b>' + newSeg.Calculated_Preliminary_Signature__c.format() + '</b></p>';
					conditionToMessageMap.put('Extension', message);
				}
				if (oldSeg.Final_Extension_of_days__c != newSeg.Final_Extension_of_days__c && newSeg.Calculated_Final_Signature__c != null) {
					message = conditionToMessageMap.get('Extension') != null ? conditionToMessageMap.get('Extension'): '';
					message += '<p>Final Extension Number of Days changed from ' + oldSeg.Final_Extension_of_days__c + ' to ' + newSeg.Final_Extension_of_days__c + '</p>';
					message += '<p>The Calculated Final Signature date is: <b>' + newSeg.Calculated_Final_Signature__c.format() + '</b></p>';
					conditionToMessageMap.put('Extension', message);
				}
			}
			if (oldMap.get(i).get('Litigation_YesNo__c') != newMap.get(i).get('Litigation_YesNo__c')
				|| oldMap.get(i).get('Litigation_Resolved__c') != newMap.get(i).get('Litigation_Resolved__c')) {
				SObject oldRecord = oldMap.get(i);
				SObject newRecord = newMap.get(i);
				String changeType = '';
				if (newRecord.get('Litigation_YesNo__c') == 'Yes' && newRecord.get('Litigation_Resolved__c') != 'Yes') {
					changeType = 'being litigated.';
				} else if (newRecord.get('Litigation_YesNo__c') == 'No' || newRecord.get('Litigation_Resolved__c') == 'Yes') {
					changeType = 'not being litigated.';
				}
				message = newRecord.get('Litigation_YesNo__c') != null ? 'This record is ' + changeType : 'This record is not being litigated.';
				conditionToMessageMap.put('Litigation Change', message);
			}
			//post to chatter for all conditions met
			for (Automated_Chatter_Post__mdt acp : postsList) {
				if(conditionToMessageMap.containsKey(acp.Posting_Condition__c)) {
					postToChatter(i, caseNumber, conditionToMessageMap.get(acp.Posting_Condition__c), acp);
				}
			}
		}
	}

	private void postToChatter(Id parentId, String caseNumber, String message, Automated_Chatter_Post__mdt post) {
		//initialize variables for post
		String postToParse = post.Feed_Item_Message__c;
		Set<String> staffingRoles = new Set<String>();
		Map<String,List<Id>> roleToUserIdListMap = new Map<String,List<Id>>();
		List<Schema.PicklistEntry> pleList = Schema.Constant__mdt.Staffing_Role__c.getDescribe().getPicklistValues();
		for (Schema.PicklistEntry ple : pleList) {//add all roles from default list to title map
			staffingRoles.add(ple.getValue());
		}
		for (Staffing_Assignment__c sa : StaffingAssignmentsSelector.parentIdsToStaffLists.get(parentId)) {//iterate through the staff lists for each parent record
			List<Id> tempList = new List<Id>();
			if (roleToUserIdListMap.get(sa.Title__c) != null) {
				tempList = roleToUserIdListMap.get(sa.Title__c);
			}
			if (sa.User__c != null) {tempList.add(sa.User__c);}
			roleToUserIdListMap.put(sa.Title__c, tempList);
		}
		for (String role : roleToUserIdListMap.keySet()) {
			//Initialize variables to search for when replacing
			String mentionedRole = '@' + role;
			String mentionedRecord = '@record';
			String replacementUserIds = '';

			if (!postToParse.contains(mentionedRole)) {continue;}//if that role is not present in post from metadata, skip to next role

			for (Id userId : roleToUserIdListMap.get(role)) {
					replacementUserIds = '{' + userId + '}';
			}
			postToParse = postToParse.replace(mentionedRole, replacementUserIds);
			postToParse = postToParse.replace(mentionedRecord, caseNumber);
		}
		postToParse += '<p>' + message + '</p><p>' + 'Link to record: ' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + parentId + '</p>';//add message about changes and link
		ConnectApi.FeedItem fi = (ConnectApi.FeedItem) ConnectApiHelper.postFeedItemWithRichText(Network.getNetworkId(), parentId, postToParse);
	}
}