src/objects/KnowledgeMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of Knowledge Article API names to common names.</description>
    <fields>
        <fullName>API__c</fullName>
        <description>API Name of the Article Type.</description>
        <inlineHelpText>API Name of the Article Type.</inlineHelpText>
        <label>API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Map</label>
</CustomObject>

src/objects/Series__c.object
<CustomObject>
    <description>Object to cluster Knowledge Articles by Publication</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Series Type</label>
        <picklist>
            <picklistValues>
                <fullName>Country Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Markets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic Guide to Exporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Insight</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SeriesType_Controller.cls
public class SeriesType_Controller {
    public string type {get; set;}
    public string recordID {get; set;}
    public string className {get; set;}
    
    public string getRecordType(){
        string output = '';
        output = KnowledgeMap__c.getAll().get(this.type).api__c;
        return output;
    }
    
    public SelectOption[] getTypes(){
        SelectOption[] output = new SelectOption[]{};
        output.add(new selectOption('', ' -- Select a Series -- '));
        Series__c[] seriesList = database.query('select id, name from Series__c where type__c = \''+this.type+'\' order by name asc');
        map<string, integer> counts = new map<string, integer>();
        for(series__c series : seriesList){
            counts.put(series.id, 0);
        }
        SObject[] articles = database.query('select series__c, count(id) from '+this.getRecordType()+' where publishStatus = \'online\' and language=\'en_US\' group by series__c');
        for(sObject article : articles){
            if(counts.get((string) article.get('series__c')) != null){
                string s = (string) article.get('series__c');
                counts.put(s, (integer) article.get('expr0'));
            }
        }
        for(Series__c series : seriesList){
            if(counts.get(series.id) != 0){
                output.add( new SelectOption(series.id, series.name) );
            }
        }
        return output;
    }
}