src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Temporary Campaign ID field</description>
        <label>Web Campaign ID</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Detail__c</fullName>
        <label>Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WebToLead__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CampaignId__c</fullName>
        <label>CampaignId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_URL__c</fullName>
        <label>Return URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WebToLead</label>
</CustomObject>

src/classes/WebToLead.cls
public class WebToLead {

public Lead lead {get; set;}

public String site {get; set;}

public string getSiteName(){
    String strurl = ApexPages.currentPage().getUrl();
    if(strurl.contains('apex/')){
        strurl = strurl.split('apex/')[1];
    }
    return strurl;
}
public WebToLead(){
    this.lead = new Lead(campaign_id__c = WebToLead__c.getAll().get(getSiteName()).CampaignId__c, Source_Detail__c = 'Web To Lead - Launch');
    this.site = getSiteName();
}

public pageReference Submit(){
    PageReference output = new PageReference(WebToLead__c.getAll().get(this.site) != null ? WebToLead__c.getAll().get(this.site).return_url__c : '/welcome');
    try{
        upsert lead;
    }Catch(Exception e){
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, ErrorMessaging.clearMessage(e.getMessage())));
    }
    output.setRedirect(true);
    return output;
}

}