src/objects/Master_CongressionalDistrict__c.object
<CustomObject>
    <fields>
        <fullName>Congressional_Dist__c</fullName>
        <label>Congressional Dist</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County_Name__c</fullName>
        <label>County Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max4__c</fullName>
        <description>In Zip+4 the Maximum 4 digit value will be stored in this field.</description>
        <externalId>true</externalId>
        <label>Max4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max9Zip__c</fullName>
        <formula>zip_Plus4__c + Max4__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max9Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min4__c</fullName>
        <description>In Zip+4 the last 4 Minimum value will be stored in this field.</description>
        <externalId>true</externalId>
        <label>Min4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min9Zip__c</fullName>
        <formula>zip_Plus4__c  +  Min4__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Min9Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zip_Plus4__c</fullName>
        <description>Will have 5 digit zip code.</description>
        <externalId>true</externalId>
        <label>zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Master CongressionalDistrict</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Master CongressionalDistrict Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master CongressionalDistricts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MasterCongressionalDistrictsSelector.cls
/**
 * Master_CongressionalDistrict__c fflib Selector
 *
 * @author Mark Keckeis
 */
public class MasterCongressionalDistrictsSelector extends fflib_SObjectSelector implements IMasterCongressionalDistrictsSelector {

	public static IMasterCongressionalDistrictsSelector newInstance()  {
		return (IMasterCongressionalDistrictsSelector) fflibext_Application.Selector.newInstance(Master_CongressionalDistrict__c.SObjectType);
	}

	public List<Master_CongressionalDistrict__c> selectById(Set<Id> idSet) {
		return (List<Master_CongressionalDistrict__c>) selectSObjectsById(idSet);
	}

	public List<Master_CongressionalDistrict__c> selectByMin4Max4AndZipPlus4(Set<String> zip4, Set<String> zip5) {
		return (List<Master_CongressionalDistrict__c>)
				Database.query(
					newQueryFactory()
						.setCondition('Min4__c <= :zip4 AND Max4__c >= :zip4 AND Zip_Plus4__c = :zip5')
						.toSOQL()
				);
	}

	private List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Master_CongressionalDistrict__c.Id,
			Master_CongressionalDistrict__c.State_Code__c,
			Master_CongressionalDistrict__c.County_Name__c,
			Master_CongressionalDistrict__c.Zip_Plus4__c,
			Master_CongressionalDistrict__c.Max9Zip__c,
			Master_CongressionalDistrict__c.Min9Zip__c,
			Master_CongressionalDistrict__c.Congressional_Dist__c
		};
	}

	private Schema.SObjectType getSObjectType() {
		return Master_CongressionalDistrict__c.SObjectType;
	}
}