src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The successful payment for this order.</description>
        <inlineHelpText>The successful payment for this order.</inlineHelpText>
        <label>Payment 2</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refunded_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>The amount of an order that has been refunded.</description>
        <inlineHelpText>The amount of an order that has been refunded.</inlineHelpText>
        <label>Refunded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Card Refund</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled</fullName>
                    <isActive>false</isActive>
                    <label>NIST-Handled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remote_Tracking_Id__c</fullName>
        <description>The tracking Id returned by the payment processor.</description>
        <externalId>true</externalId>
        <inlineHelpText>The tracking Id returned by the payment processor.</inlineHelpText>
        <label>Remote Tracking Id</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OrdersSelector.cls
public class OrdersSelector extends fflib_SObjectSelector implements IOrdersSelector {

	public static IOrdersSelector newInstance(){
		return (IOrdersSelector) fflibext_Application.Selector.newInstance(Order.SObjectType);
	}

	public List<Order> selectById(Set<Id> idSet) {
		return (List<Order>) selectSObjectsById(idSet);
	}

	public List<Order> selectByPaidNonPaidOnly(Set<Id> idSet, Boolean nonPaidOnly, Boolean paidOnly) {
		fflib_QueryFactory ordersQueryFactory = newQueryFactory();
		ordersQueryFactory.selectFields(new Set<String>{'Payment2__r.Payment_Type__c',
			'Payment2__r.Transaction_Status__c', 'Payment2__r.Name',
			'Payment2__r.Remote_Tracking_Id__c' });
		String condition = 'Id IN :idSet ';
		if (nonPaidOnly) {
			condition += ' AND Order_Paid__c = false AND Payment2__c = null';
		}
		if (paidOnly) {
			condition += ' AND Order_Paid__c = true';
		}
		System.debug(ordersQueryFactory.setCondition(condition).toSOQL());
		return (List<Order>) Database.query(ordersQueryFactory.setCondition(condition).toSOQL());
	}

	public List<Order> selectByContractId(Set<Id> idSet, Boolean onlyCreditCardPayments, Boolean nonPaidOnly, Boolean paidOnly) {
		fflib_QueryFactory ordersQueryFactory = newQueryFactory();
		ordersQueryFactory.selectFields(new Set<String>{'Payment2__r.Payment_Type__c',
		'Payment2__r.Transaction_Status__c', 'Payment2__r.Name', 'Payment2__r.Remote_Tracking_Id__c',
		'Contract.Name', 'Contract.ContractNumber' });
		String condition = 'ContractId IN :idSet  AND TotalAmount > 0';
		if (nonPaidOnly) {
			condition += ' AND Order_Paid__c = false AND Payment2__c = null';
		}
		if (paidOnly) {
			condition += ' AND Order_Paid__c = true';
		}
		if (onlyCreditCardPayments) {
			condition += ' AND Payment2__r.Payment_Type__c = \'PLASTIC_CARD\'';
		}
		return (List<Order>) Database.query(ordersQueryFactory.setCondition(condition).toSOQL());
	}

	public List<Order> selectWithOrderItemDetails(Set<Id> idSet, Boolean primaryItemOnly) {
		if (idSet.isEmpty()) return new List<Order>();  //Avoid unnecessary SOQL
		fflib_QueryFactory ordersQueryFactory = newQueryFactory();
		ordersQueryFactory.selectFields(new Set<String>{'Opportunity.Account.Name',
			'Opportunity.Owner.Name', 'Opportunity.CreatedDate', 'Opportunity.Collection_Post__r.Name',
			'Opportunity.Collection_Post__r.Org_Code__c', 'Opportunity.Fulfillment_Post__r.Name',
			'Opportunity.Fulfillment_Post__r.Org_Code__c', 'Opportunity.Collection_Post__r.Acronym__c', 'Opportunity.Fulfillment_Post__r.Acronym__c'});
		ordersQueryFactory.setCondition('Id IN :idSet');
		fflib_QueryFactory orderItemsQueryFactory = ordersQueryFactory.subselectQuery('OrderItems');
		if (primaryItemOnly) {
			orderItemsQueryFactory.setCondition('IsPrimary__c = true');
		}
		orderItemsQueryFactory.selectFields(new OrderItemsSelector().getSObjectFieldList());
		return Database.query(ordersQueryFactory.toSOQL());
	}

	public List<Order> selectByPaymentId(Set<Id> idSet) {
		if (idSet.isEmpty()) return new List<Order>();  //Avoid unnecessary SOQL
		fflib_QueryFactory ordersQueryFactory = newQueryFactory();
		ordersQueryFactory.selectFields(new Set<String>{'Account.Name'});
		ordersQueryFactory.setCondition('Payment2__c IN :idSet');
		fflib_QueryFactory orderItemsQueryFactory = ordersQueryFactory.subselectQuery('OrderItems');
		orderItemsQueryFactory.selectFields(new OrderItemsSelector().getSObjectFieldList());
		return Database.query(ordersQueryFactory.toSOQL());
	}

	private List<Schema.SObjectField> getSObjectFieldList() {
		//add more fields as appropriate
		return new List<Schema.SObjectField>{
			Order.Id,
			Order.Name,
			Order.TotalAmount,
			Order.Type,
			Order.Status,
			Order.ContractId,
			Order.Payment2__c,
			Order.Order_Paid__c,
			Order.Refunded_Amount__c,
			Order.OrderNumber,
			Order.AccountId
		};
	}

	private Schema.SObjectType getSObjectType() {
		return Order.SObjectType;
	}
}