src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Payment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The successful payment for this order.</description>
        <inlineHelpText>The successful payment for this order.</inlineHelpText>
        <label>Payment 2</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refunded_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>The amount of an order that has been refunded.</description>
        <inlineHelpText>The amount of an order that has been refunded.</inlineHelpText>
        <label>Refunded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>The name of the product family to which this payment applies.</description>
        <inlineHelpText>The name of the product family to which this payment applies.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Services</fullName>
                    <default>true</default>
                    <label>Services</label>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Privacy Shield</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field for refunds related to current payment</description>
        <label>Parent Payment</label>
        <referenceTo>Payment2__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <defaultValue>&apos;PayGov&apos;</defaultValue>
        <description>The name of the entity that processed this payment.</description>
        <inlineHelpText>The name of the entity that processed this payment.</inlineHelpText>
        <label>Payment Processor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Card Refund</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled</fullName>
                    <isActive>false</isActive>
                    <label>NIST-Handled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remote_Tracking_Id__c</fullName>
        <description>The tracking Id returned by the payment processor.</description>
        <externalId>true</externalId>
        <inlineHelpText>The tracking Id returned by the payment processor.</inlineHelpText>
        <label>Remote Tracking Id</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Code__c</fullName>
        <description>The return code given by the payment processor during a refund.</description>
        <inlineHelpText>The return code given by the payment processor during a refund.</inlineHelpText>
        <label>Return Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Detail__c</fullName>
        <description>The return detail  given by the payment processor during a refund.</description>
        <inlineHelpText>The return detail  given by the payment processor during a refund.</inlineHelpText>
        <label>Return Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The DateTime of the payment transaction, as returned from pay.gov for credit card and ACH payments or the date the transaction was recorded for other types of payments.</description>
        <inlineHelpText>The DateTime of the payment transaction, as returned from pay.gov for credit card and ACH payments or the date the transaction was recorded for other types of payments.</inlineHelpText>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Credit_Card_Refund</fullName>
        <active>true</active>
        <description>Record type for credit card refunds.</description>
        <label>Credit Card Refund</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RefundForPayGov.cls
public with sharing class RefundForPayGov implements IRefund {

	public static final String METADATA_SETTINGS_NAME = 'PayGov';

	public Payment2__c issueRefund(Payment2__c payment, List<Order> orders, Decimal refundAmount) {

		String transactionStatus;
		String returnCode;
		String returnDetail;
		String payGovTrackingId;
		Decimal returnedTransactionAmount;
		String transactionDate;
		String status;

		Map<String, Object> paymentSettingsMap = CustomMetadataSelector.getPaymentSettings(METADATA_SETTINGS_NAME);
		String agencyId = (String) paymentSettingsMap.get('Agency_Id__c');

		String remoteAccountName = Payment2.getRemoteAccountName(payment.Account_Type__c);

		//Get the Refund Response from Pay.gov
		PayGovTCSSingleService.PCRefundResponse_element pcRefundResponse = RefundForPayGov.getRefundResponse(payment, refundAmount, agencyId, remoteAccountName);

		if (pcRefundResponse.PCRefund.transaction_status == 'Failed') {
			//Try to cancel the transaction instead of refunding it.  This is needed if the refund is attempted in less than 1 day.

			//Get the cancel response from Pay.gov
			PayGovTCSSingleService.PCCancelResponse_element pcCancelResponse = RefundForPayGov.getCancelResponse(payment, refundAmount, agencyId, remoteAccountName);

			if (pcCancelResponse.PCCancel.transaction_status == 'Canceled') {
				payGovTrackingId = pcCancelResponse.PCCancel.orig_paygov_tracking_id;
				returnedTransactionAmount = Decimal.valueOf(pcCancelResponse.PCCancel.transaction_amount);
				transactionDate = pcCancelResponse.PCCancel.transaction_date;
				transactionStatus = pcCancelResponse.PCCancel.transaction_status;
				returnCode = pcCancelResponse.PCCancel.return_code;
				returnDetail = pcCancelResponse.PCCancel.return_detail;
                if (Test.isRunningTest()) {
                    status = 'Success';  //This is for additional code coverage
                }
			} else {
				//The error from pay.gov is in pcRefundResponse.pcRefund.return_detail.  However, it's not user friendly.
				//The error from pay.gov is: "Force or Refund amount exceeded authorized amount or the Refund amount exceeded remainder amount."
				String errorMessage = 'Partial refunds of transactions that occurred on the same business day are not allowed.  ';
				errorMessage += 'Either wait one business day to process a partial refund or attempt to refund the entire amount of the transaction.';
				AuraHandledException auraHandledException = new AuraHandledException(errorMessage);
				auraHandledException.setMessage(errorMessage);
				throw auraHandledException;
			}
		} else {
			if (pcRefundResponse.PCRefund.transaction_status == 'In Process') {
				//The refund is in process with pay.gov.  No guarantee is made about it's success or failure.
				status = 'Initiated';
			} else {
				status = 'Success';
			}
			payGovTrackingId = pcRefundResponse.PCRefund.paygov_tracking_id;
			returnedTransactionAmount = Decimal.valueOf(pcRefundResponse.PCRefund.transaction_amount);
			transactionDate = pcRefundResponse.PCRefund.transaction_date;
			transactionStatus = pcRefundResponse.PCRefund.transaction_status;
			returnCode = pcRefundResponse.PCRefund.return_code;
			returnDetail = pcRefundResponse.PCRefund.return_detail;
		}

		//Create the Refund record
		Payment2__c refund = RefundForPayGov.createRefundRecord(payment, orders, refundAmount,
			transactionDate, returnCode, returnDetail, payGovTrackingId, status);
		return refund;
	}

	private static PayGovTCSSingleService.PCRefundResponse_element getRefundResponse(Payment2__c payment, Decimal refundAmount, String agencyId, String remoteAccountName) {
		PayGovTCSSingleService.PCRefundRequestType pcRefund = new PayGovTCSSingleService.PCRefundRequestType();
		pcRefund.orig_paygov_tracking_id = payment.Remote_Tracking_Id__c;
		pcRefund.transaction_amount = String.valueOf(refundAmount);
		pcRefund.orig_agency_tracking_id = payment.Name;

		PayGovTCSSingleService.PCRefundResponse_element pcRefundResponse;
		if (Test.isRunningTest()) {
			pcRefundResponse = new PayGovTCSSingleService.PCRefundResponse_element();
			pcRefundResponse.PCRefund = new PayGovTCSSingleService.PCRefundResponseType();
			pcRefundResponse.PCRefund.transaction_status = 'Failed';
		} else {
			PayGovTCSSingleService.TCSSinglePort payGovSingleService = new PayGovTCSSingleService.TCSSinglePort();
			pcRefundResponse = payGovSingleService.processPCRefund(agencyId, remoteAccountName, pcRefund);
		}
		return pcRefundResponse;
	}

	private static PayGovTCSSingleService.PCCancelResponse_element getCancelResponse(Payment2__c payment, Decimal refundAmount, String agencyId, String remoteAccountName) {
		PayGovTCSSingleService.PCCancelRequestType pcCancel = new PayGovTCSSingleService.PCCancelRequestType();
		pcCancel.orig_paygov_tracking_id = payment.Remote_Tracking_Id__c;
		pcCancel.transaction_amount = String.valueOf(refundAmount);
		pcCancel.agency_tracking_id = payment.Name;
		PayGovTCSSingleService.PCCancelResponse_element pcCancelResponse;
		if (Test.isRunningTest()) {
			pcCancelResponse = new PayGovTCSSingleService.PCCancelResponse_element();
			pcCancelResponse.PCCancel = new PayGovTCSSingleService.PCCancelResponseType();
			pcCancelResponse.PCCancel.transaction_status = 'Canceled';
			pcCancelResponse.PCCancel.orig_paygov_tracking_id = '9XVKY2';
			pcCancelResponse.PCCancel.transaction_amount = '9600';
			pcCancelResponse.PCCancel.transaction_date = '2020-03-20T20:16:37';
			pcCancelResponse.PCCancel.return_code = '3C';
			pcCancelResponse.PCCancel.return_detail = 'Successfully canceled';
		} else {
			PayGovTCSSingleService.TCSSinglePort payGovSingleService = new PayGovTCSSingleService.TCSSinglePort();
			pcCancelResponse = payGovSingleService.processPCCancel(agencyId, remoteAccountName, pcCancel);
		}
		return pcCancelResponse;
	}

	private static Payment2__c createRefundRecord(Payment2__c payment, List<Order> orders,
		Decimal refundAmount, String transactionDate, String returnCode, String returnDetail, String payGovTrackingId,
		String status) {
		DateTime transactionDateGMT = null;
		if (!String.isEmpty(transactionDate)) {
			transactionDateGMT = DateTime.Valueof(transactionDate.replace('T', ' '));
			transactionDateGMT = getEST(transactionDateGMT);
		}

		Payment2__c refund = new Payment2__c();
		refund.RecordTypeId = Utils.getRecordTypeIdMap('Payment2__c').get('Credit_Card_Refund');
		refund.Transaction_Amount__c = refundAmount;
		refund.Transaction_Date__c = transactionDateGMT;
		refund.Return_Code__c = returnCode;
		refund.Return_Detail__c = returnDetail;
		refund.Payment_Processor__c = payment.Payment_Processor__c;
		refund.Transaction_Status__c = status;
		refund.Remote_Tracking_Id__c = payGovTrackingId;
		refund.Payment_Type__c = 'Credit Card Refund';
		refund.Payment_2__c = payment.Id;  //The parent payment of this refund
		fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<SObjectType> {Payment2__c.SObjectType, Order.SObjectType});
		uow.registerNew(refund);

		//Only update Orders if the refund was successful
		if (status == 'Success') {
			for (Order eachOrder : orders) {
				eachOrder.Refunded_Amount__c = eachOrder.Refunded_Amount__c + Math.abs(eachOrder.TotalAmount);
				uow.registerDirty(eachOrder, Order.Payment2__c, refund);
			}
		}

		try {
			uow.commitWork();
		} catch (Exception e) {
			String errorMessage = 'Unable to update payment and/or order record.  ';
			errorMessage += e.getMessage();
			AuraHandledException auraHandledException = new AuraHandledException(errorMessage);
			auraHandledException.setMessage(errorMessage);
			throw auraHandledException;
		}

		return refund;
	}

	@TestVisible private static Datetime getEST(Datetime dtTime)
	{
		Date d = dtTime.dateGmt();
		Time t = dtTime.timeGmt();
		Datetime estDateTime = Datetime.newInstanceGmt(d,t);
		return estDateTime;
	}

}