src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicaton</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participation Number</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <description>Status of the Organization&apos;s Participation in a Framework.</description>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participation__c</referenceTo>
        <relationshipName>Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participation__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Participant Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Participant on the Order record.</description>
        <formula>Order__r.Participant__r.Name</formula>
        <inlineHelpText>Participant on the Order record.</inlineHelpText>
        <label>Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The tracking Id returned by pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Refunds__c</fullName>
        <description>The total amount of refunds successfully processed for this payment.</description>
        <label>Total Refunds</label>
        <summarizedField>Refund__c.Transaction_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Refund__c.Transaction_Status__c</field>
            <operation>equals</operation>
            <value>Success</value>
        </summaryFilterItems>
        <summaryForeignKey>Refund__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The DateTime of the payment transaction, as returned from pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MyOrdersPageController.cls
public class MyOrdersPageController {

private User user {get; set;}


public map<id, list<order>> OrderMap {get; set;}
public map<id, participant__c> ParticipantMap {get; set;}
public list<Participant__c> participations {get; set;}
public list<Order> Orders {get; set;}

public MyOrdersPageController(){
    this.ParticipantMap  = new map<id, Participant__c>();
    this.Orders = new list<Order>();

    Id userId = UserInfo.getUserId();
    this.user = [SELECT id, contactid, contact.accountid FROM User WHERE id = :userId LIMIT 1];
    if(this.user.contactId != null){
        this.participations = [select id, name
         from Participant__c where Participant__r.Organization__c = :this.user.contact.accountId]; 
         if(this.participations.size() == 0){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Your organization has not applied to any Frameworks yet.'));
         }else{
             for(Participant__c participant : this.participations){
                 this.ParticipantMap.put(participant.id, participant);
             }
             this.orders = [select 
                            id, ordernumber, TotalAmount, status, effectivedate, participation__c, accountid, createddate,
                            (select id, Pricebookentry.Product2.Name from orderitems),
                            (select Transaction_Date__c, Pay_Gov_Tracking_Id__c, Transaction_Amount__c, Transaction_Status__c, Total_Refunds__c 
                             FROM Payments__r)
                             from order where Participation__c = :this.participantMap.keySet() order by createddate desc];             
         }     
    }else{
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'You must be logged in as a Community User to see MyOrders.'));
    }
}
}