src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Accounting_Code__c</fullName>
        <formula>Product2.Accounting_Code__c</formula>
        <label>Accounting Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPrimary__c</fullName>
        <formula>QuoteLineItem.IsPrimary__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isPrimary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/OrderItemsSelector.cls
public class OrderItemsSelector extends fflib_SObjectSelector implements IOrderItemsSelector {

    public static IOrderItemsSelector newInstance() {
        return (IOrderItemsSelector) fflibext_Application.Selector.newInstance(OrderItem.SObjectType);
    }

    public List<OrderItem> selectById(Set<Id> idSet) {
        return (List<OrderItem>) selectSObjectsById(idSet);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                OrderItem.Id,
                OrderItem.OrderId,
                OrderItem.Product2Id,
                OrderItem.isPrimary__c,
                OrderItem.Accounting_Code__c,
                OrderItem.QuoteLineItemId,
                OrderItem.TotalPrice,
                OrderItem.UnitPrice
        };
    }

    private Schema.SObjectType getSObjectType() {
        return OrderItem.SObjectType;
    }

}