src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template_Page__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MicroSite</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>MicroSite Homepage</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>MicroSites</relationshipLabel>
        <relationshipName>MicroSites</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>MicroSite</label>
    <nameField>
        <label>MicroSite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MicroSites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Template_Page__c.object
<CustomObject>
    <label>Page Template</label>
    <nameField>
        <label>_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/teamController.cls
public with sharing class teamController {
    public recordtype rt{get; set;}
    

    public teamController(){
        
        if(ApexPages.currentPage().getParameters().get('type') != null && ApexPages.currentPage().getParameters().get('type') != ''){
            rt= [SELECT Name
                 FROM recordtype
                 WHERE sobjecttype = 'section__c'
                 AND name = :ApexPages.currentPage().getParameters().get('type')
                 LIMIT 1];
        }else{
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error: No Barrier Parameter has been selected!'));
        }
    }

    public section__c[] getteamList(){
        section__c[] team = new section__c[]{};
        if(ApexPages.currentPage().getParameters().get('type') != null && ApexPages.currentPage().getParameters().get('type') != ''){
            team = [SELECT id, Name, page__r.id
                    FROM section__c
                    WHERE page__r.id != ''
                     AND recordtype.name = :ApexPages.currentPage().getParameters().get('type')
                    ORDER by Name
                    LIMIT 20];    
            return team;
        }else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error: No Records are Available!'));
            return null;
        }
        
   }
}