src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date of the payment, as returned by pay.gov or the current date for manual payments.</description>
        <inlineHelpText>The date of the payment, as returned by pay.gov or the current date for manual payments.</inlineHelpText>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Search_String__c</fullName>
        <description>Text field populated by trigger containing the following values: OrganizationName OrderAmount RefundedAmount. Created to meet global search requirements for NIST.</description>
        <label>System-Search String</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The DateTime of the payment transaction, as returned from pay.gov for credit card and ACH payments or the date the transaction was recorded for other types of payments.</description>
        <inlineHelpText>The DateTime of the payment transaction, as returned from pay.gov for credit card and ACH payments or the date the transaction was recorded for other types of payments.</inlineHelpText>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Payment2TriggerHandler.cls
public class Payment2TriggerHandler{

	/**Update SystemSearchString Field with Transaction Amount,Transaction Date,
	*  and Payment Date.
	*/
	public static void updateSystemSearchString(List<Payment2__c> paymentList){

		for(Payment2__c payment : paymentList){
			String systemSearchString = '$'+payment.Transaction_Amount__c;
			if (payment.Transaction_Date__c != null) {
				Date transactionDate = Date.newInstance(payment.Transaction_Date__c.year(), payment.Transaction_Date__c.month(), payment.Transaction_Date__c.day());
				systemSearchString += ' | ' + transactionDate.format();
			}
			if (payment.Payment_Date__c != null) {
				systemSearchString += ' | ' + payment.Payment_Date__c.format();
			}
			payment.System_Search_String__c = systemSearchString;
		}
	}
}