src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The Application abbreviation.  For a refund, is used to determine the pay.gov TCS_APP_ID.</description>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Privacy Shield</fullName>
                    <default>true</default>
                    <label>Privacy Shield</label>
                </value>
                <value>
                    <fullName>Event or Service</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                    <isActive>false</isActive>
                    <label>PS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The tracking Id returned by pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>ACH_CREDIT</fullName>
                </value>
                <value>
                    <fullName>AMAZON</fullName>
                </value>
                <value>
                    <fullName>PAYPAL</fullName>
                </value>
                <value>
                    <fullName>DWOLLA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The DateTime of the payment transaction, as returned from pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PaymentSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Settings</label>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <description>A detail object for a Payment master object.  The refund of a payment in pay.gov.</description>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The id returned from pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <description>The M/D lookup that ties a refund to a payment.</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Return_Code__c</fullName>
        <description>The return code from pay.gov</description>
        <label>Return Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Detail__c</fullName>
        <description>The return detail from pay.gov</description>
        <label>Return Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>An internal description of the state of the refund.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <default>true</default>
                    <label>Initiated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The amount of the refund</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The date/time of the refund, as returned by pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The refund status, as returned by pay.gov</description>
        <label>Transaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>SR{000000000}</displayFormat>
        <label>Refund ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RefundLightningController.cls
public without sharing class RefundLightningController {

    @TestVisible private static final String PRIVACY_SHIELD_APP_ID = PaymentSettings__c.getAll().get('PRIVACY_SHIELD_APP_ID').value__c;  
    @TestVisible private static final String EVENTS_SERVICES_APP_ID = PaymentSettings__c.getAll().get('EVENTS_SERVICES_APP_ID').value__c;
    @TestVisible private static final String AGENCY_ID = PaymentSettings__c.getAll().get('AGENCY_ID').value__c;
    @TestVisible private static final String PRIVACY_SHIELD_APP_NAME = PaymentSettings__c.getAll().get('PRIVACY_SHIELD_APP_NAME').value__c;
    @TestVisible private static final String EVENTS_SERVICES_APP_NAME = PaymentSettings__c.getAll().get('EVENTS_SERVICES_APP_NAME').value__c;

    @AuraEnabled
    public Refund__c refundObject{get;set;}

    @AuraEnabled
    public String errorMessage{get;set;}

    @AuraEnabled
    public static RefundLightningController issueRefund(Id paymentId) {

        RefundLightningController refundController = new RefundLightningController();

        try {
            Payment__c paymentObject = [SELECT Id, Name, Opportunity__c, Pay_Gov_Tracking_Id__c, Application__c, Transaction_Amount__c, Payment_Type__c FROM PAYMENT__C WHERE Id = :paymentId LIMIT 1];
            if (paymentObject.Payment_Type__c != 'PLASTIC_CARD') {
                refundController.errorMessage = 'Refunds are only allowed for credit card payments.  For ACH payments, contact NIST to perform the refund.';
                return refundController;
            }

            String origAgencyTrackingId = paymentObject.Name;
            String origPayGovTrackingId = paymentObject.Pay_Gov_Tracking_Id__c;
            String transactionAmount = String.valueOf(paymentObject.Transaction_Amount__c);
            String application = paymentObject.Application__c;
            String tcsAppId;
            if (application != null) {
                if (application.equalsIgnoreCase(PRIVACY_SHIELD_APP_NAME)) {
                    tcsAppId = PRIVACY_SHIELD_APP_ID;
                } else if (application.equalsIgnoreCase(EVENTS_SERVICES_APP_NAME)) {
                    tcsAppId = EVENTS_SERVICES_APP_ID;
                }
            }

            if (String.isBlank(tcsAppId)) {
                refundController.errorMessage = 'Unknown TCS Application ID.';
                return refundController;
            }

            PayGovTCSSingleService.PCRefundRequestType pcRefund = new PayGovTCSSingleService.PCRefundRequestType();
            pcRefund.orig_paygov_tracking_id = origPayGovTrackingId;
            pcRefund.transaction_amount = transactionAmount;
            pcRefund.orig_agency_tracking_id = origAgencyTrackingId;

            PayGovTCSSingleService.TCSSinglePort payGovSingleService = new PayGovTCSSingleService.TCSSinglePort();
            PayGovTCSSingleService.PCRefundResponse_element pcRefundResponse = payGovSingleService.processPCRefund(AGENCY_ID, tcsAppId, pcRefund);

            if (pcRefundResponse.pcRefund.transaction_status == 'Failed') {
                refundController.errorMessage = 'Pay.gov refused to accept the refund transaction.  Try to perform the refund on the pay.gov website.  Return code: ' + pcRefundResponse.pcRefund.return_code + '.  Return detail: ' + pcRefundResponse.pcRefund.return_detail;
                return refundController;
            } else if (pcRefundResponse.pcRefund.transaction_status == 'In Process'){
                refundController.errorMessage = 'The refund is in process with pay.gov.  No guarantee is made about it\'s success or failure.  Check it\'s status on the pay.gov website.  Return code: ' + pcRefundResponse.pcRefund.return_code + '.  Return detail: ' + pcRefundResponse.pcRefund.return_detail;
                return refundController;
            }

            String status = 'Completed';
            String payGovTrackingId = String.valueOf(pcRefundResponse.pcRefund.paygov_tracking_id);
            Decimal returnedTransactionAmount = Decimal.valueOf(pcRefundResponse.pcRefund.transaction_amount);
            String transactionDate = String.valueOf(pcRefundResponse.pcRefund.transaction_date);
            DateTime transactionDateGMT = null;
            if (!String.isEmpty(transactionDate)) {
                transactionDateGMT = DateTime.Valueof(transactionDate.replace('T', ' '));
                transactionDateGMT = getEST(transactionDateGMT);
            }
            String transactionStatus = pcRefundResponse.pcRefund.transaction_status;
            String returnCode = pcRefundResponse.pcRefund.return_code;
            String returnDetail = pcRefundResponse.pcRefund.return_detail;

            Refund__c refundObject = new Refund__c(Payment__c = paymentObject.id, Status__c = status, Pay_Gov_Tracking_Id__c = payGovTrackingId,
                Transaction_Amount__c = returnedTransactionAmount, Transaction_Status__c = transactionStatus,
                Return_Code__c = returnCode, Transaction_Date__c = transactionDateGMT,
                Return_Detail__c = returnDetail);

            insert refundObject;

            refundController.refundObject = refundObject;
            return refundController;

        } catch (Exception e) {
            System.debug(e.getMessage());
            refundController.errorMessage = 'Refund Error: ' + e.getMessage();
            return refundController;
        }

    }
    
    @TestVisible private static Datetime getEST(Datetime dtTime)
    {    
        Date d = dtTime.dateGmt();
        Time t = dtTime.timeGmt();
        Datetime estDateTime = Datetime.newInstanceGmt(d,t);
        return estDateTime;
    }
   
    
}