src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The Application abbreviation.  For a refund, is used to determine the pay.gov TCS_APP_ID.</description>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Privacy Shield</fullName>
                    <default>true</default>
                    <label>Privacy Shield</label>
                </value>
                <value>
                    <fullName>Event or Service</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                    <isActive>false</isActive>
                    <label>PS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The tracking Id returned by pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>ACH_CREDIT</fullName>
                </value>
                <value>
                    <fullName>AMAZON</fullName>
                </value>
                <value>
                    <fullName>PAYPAL</fullName>
                </value>
                <value>
                    <fullName>DWOLLA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Record_Log__c.object
<CustomObject>
    <description>A log record that is created from the Record Log Platform Event and is associated with another Salesforce object, such as Payment.</description>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Record_Id__c</fullName>
        <description>The Id of the record that this log entry is related to.</description>
        <inlineHelpText>The Id of the record that this log entry is related to.</inlineHelpText>
        <label>Related Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Record Log</label>
    <nameField>
        <displayFormat>RLOG{0000000000}</displayFormat>
        <label>Record Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecordLogViewerControllerTest.cls
@IsTest
	public class RecordLogViewerControllerTest {

	private static final String PAY_GOV_TRACKING_ID = 'testTrackingId';
	private static final String PRIVACY_SHIELD_APP_NAME = 'Privacy Shield';

	@testSetup static void createData(){
		Account account = new Account(Name='Record Log Viewer Controller Test Account');
		insert account;

		Order order = new Order();
		order.Name = '14TPE000001';
		order.AccountId = account.Id;
		order.EffectiveDate = Date.Today();
		order.Status = 'Draft';
		insert order;

		Payment__c payment = new Payment__c(Order__c = order.id, Pay_Gov_Tracking_Id__c = PAY_GOV_TRACKING_ID, Payment_Type__c = 'PLASTIC_CARD', Application__c = PRIVACY_SHIELD_APP_NAME, Transaction_Amount__c = 5.00);
		insert payment;
	}

	@IsTest
	public static void getRecordLogs_LogExists_True() {

		List<Payment__c> payments = [SELECT Id FROM Payment__c];

		Record_Log__c log = new Record_Log__c();
		log.Data__c = 'Some log data';
		log.Related_Record_Id__c = payments[0].Id;
		insert log;

		List<Record_Log__c> recordLogs = RecordLogViewerController.getRecordLogs(payments[0].Id);
		System.assertEquals(recordLogs.size(), 1);
		System.assertEquals(recordLogs[0].Data__c, 'Some log data');
	}

	@IsTest
	public static void getRecordLogs_LogExists_False() {

		List<Payment__c> payments = [SELECT Id FROM Payment__c];
		List<Record_Log__c> recordLogs = RecordLogViewerController.getRecordLogs(payments[0].Id);
		System.assertEquals(recordLogs.size(), 0);
	}
}