src/objects/Payment2__c.object
<CustomObject>
    <description>Details of payments and refunds.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>The name of the product family to which this payment applies.</description>
        <inlineHelpText>The name of the product family to which this payment applies.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Services</fullName>
                    <default>true</default>
                    <label>Services</label>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Privacy Shield</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Processor__c</fullName>
        <defaultValue>&apos;PayGov&apos;</defaultValue>
        <description>The name of the entity that processed this payment.</description>
        <inlineHelpText>The name of the entity that processed this payment.</inlineHelpText>
        <label>Payment Processor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Payment Type for the transaction</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PLASTIC_CARD</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Card Refund</fullName>
                </value>
                <value>
                    <fullName>NIST-Handled</fullName>
                    <isActive>false</isActive>
                    <label>NIST-Handled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remote_Tracking_Id__c</fullName>
        <description>The tracking Id returned by the payment processor.</description>
        <externalId>true</externalId>
        <inlineHelpText>The tracking Id returned by the payment processor.</inlineHelpText>
        <label>Remote Tracking Id</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <label>Payment 2</label>
    <nameField>
        <displayFormat>DCRM{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Credit_Card_or_ACH_Payment</fullName>
        <active>true</active>
        <description>Record type for credit card and ACH payments.</description>
        <label>Credit Card or ACH Payment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PaymentDetailsLightningController2.cls
public with sharing class PaymentDetailsLightningController2 {

	@AuraEnabled(cacheable=true)
	public static String getPaymentDetails(Id paymentId) {
		try {
			PaymentDetailsLightningController2 PaymentDetailsLightningController2 = new PaymentDetailsLightningController2();
			List<Payment2__c> payments = PaymentsSelector2.newInstance().selectById(new Set<Id>{
				paymentId
			});

			//Get the Record Type Id for Credit Card or ACH Payment
			Map<String, Id> rtMap = Utils.getRecordTypeIdMap('Payment2__c');
			if (payments.size() > 0) {
				if (payments[0].RecordTypeId == rtMap.get('Credit_Card_or_ACH_Payment')) {
					if (payments[0].Payment_Type__c == 'PLASTIC_CARD' || payments[0].Payment_Type__c == 'ACH') {
						String remoteAccountName = Payment2.getRemoteAccountName(payments[0].Account_Type__c);
						String paymentDetailsMetaName = 'PaymentDetailsFor' + payments[0].Payment_Processor__c;
						IPaymentDetails paymentDetails = (IPaymentDetails) di_Injector.Org.getInstance(paymentDetailsMetaName);
						return paymentDetails.getPaymentDetails(payments[0].Name, remoteAccountName, payments[0].Remote_Tracking_Id__c);
					}
				}
			}
			return '';  //return null is not allowed by the lightning component
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

}