src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>ADCVD Case Number Text Value Deprecated</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <description>Referenced from parent Petition case</description>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>ADCVD Case Type Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Actual_Initiation_Concurrence_to_DAS__c</fullName>
        <label>Actual Initiation Concurrence to DAS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Initiation_Issues_to_DAS__c</fullName>
        <label>Actual Initiation Issues to DAS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Initiation_Signature__c</fullName>
        <description>Actual Initiation Signature</description>
        <inlineHelpText>Actual Initiation Signature</inlineHelpText>
        <label>Actual Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CBP_Case_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>CBP Case Number Deprecated</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Referenced from parent Petition case</description>
        <label>Case Number</label>
        <length>28</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Referenced from parent Petition case</description>
        <inlineHelpText>This should be in the following format:
A-###-### for AD 
C-###-### for CVD</inlineHelpText>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <description>Referenced from parent petition</description>
        <label>Commodity Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cement and Ceramics</fullName>
                </value>
                <value>
                    <fullName>Chemicals and Allied Industries</fullName>
                </value>
                <value>
                    <fullName>Foodstuffs</fullName>
                </value>
                <value>
                    <fullName>Machinery and Automotive</fullName>
                </value>
                <value>
                    <fullName>Minerals</fullName>
                </value>
                <value>
                    <fullName>Other Metals and Articles of Metal</fullName>
                </value>
                <value>
                    <fullName>Other Mfg.</fullName>
                </value>
                <value>
                    <fullName>Paper and Paperboard</fullName>
                </value>
                <value>
                    <fullName>Plastics and Rubber</fullName>
                </value>
                <value>
                    <fullName>Steel-Related</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Referenced from parent Petition</description>
        <label>Country Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Iran</fullName>
                </value>
                <value>
                    <fullName>Iraq</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initiation_Announcement_Date__c</fullName>
        <label>Initiation Announcement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Concurrence_Due_to_DAS__c</fullName>
        <label>Initiation Concurrence Due to DAS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_Remaining__c</fullName>
        <description>Extension Number of days remaining for Initiation</description>
        <formula>20 - Initiation_Extension_of_days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initiation Extension Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <description>Initiation Extension (# of days)</description>
        <inlineHelpText>Initiation Extension (# of days)</inlineHelpText>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initiation_Issues_Due_to_DAS__c</fullName>
        <label>Initiation Issues Due to DAS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <formula>HYPERLINK( LEFT($Api.Enterprise_Server_URL_390 , FIND(&apos;/services&apos;, $Api.Enterprise_Server_URL_390)) &amp; Id,  Petition_Name__c , &apos;_self&apos;)</formula>
        <label>Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litigation_Resolved__c</fullName>
        <label>Litigation Resolved</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Litigation_Status__c</fullName>
        <label>Litigation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Litigation_YesNo__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <label>Litigation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>YesNo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent_of_Domestic_Industry__c</fullName>
        <label>% of Domestic Industry</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Filed</fullName>
                    <isActive>false</isActive>
                    <label>Filed</label>
                </value>
                <value>
                    <fullName>Rejected/Deficient/Negative Finding</fullName>
                    <isActive>false</isActive>
                    <label>Rejected/Deficient/Negative Finding</label>
                </value>
                <value>
                    <fullName>Remand/International Litigation</fullName>
                    <isActive>false</isActive>
                    <label>Remand/International Litigation</label>
                </value>
                <value>
                    <fullName>Self Initiating</fullName>
                    <isActive>false</isActive>
                    <label>Self Initiating</label>
                </value>
                <value>
                    <fullName>With the Court</fullName>
                    <isActive>false</isActive>
                    <label>With the Court</label>
                </value>
                <value>
                    <fullName>Withdrawn/Rescinded</fullName>
                    <isActive>false</isActive>
                    <label>Withdrawn/Rescinded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Imports_Domestic_Consumption__c</fullName>
        <label>% of Total Imports/Domestic Consumption%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Organization__c.object
<CustomObject>
    <fields>
        <fullName>ADCVD_Case_Number__c</fullName>
        <label>ADCVD Case Number</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADCVD_Case_Type__c</fullName>
        <label>ADCVD Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD ME</fullName>
                </value>
                <value>
                    <fullName>AD NME</fullName>
                </value>
                <value>
                    <fullName>CVD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CBP_Case_Number__c</fullName>
        <label>CBP Case Number</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <formula>HYPERLINK( LEFT($Api.Enterprise_Server_URL_390 , FIND(&apos;/services&apos;, $Api.Enterprise_Server_URL_390)) &amp; Id,  Related_Organization_Name__c , &apos;_self&apos;)</formula>
        <label>Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Petition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Petition</label>
        <referenceTo>Petition__c</referenceTo>
        <relationshipLabel>Related Organizations</relationshipLabel>
        <relationshipName>Related_Organizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Organization</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Related Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/YesNo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

src/classes/PetitionsSelector.cls
public class PetitionsSelector extends fflib_SObjectSelector{
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Petition__c.Id, 
            Petition__c.Percent_of_Domestic_Industry__c,
            Petition__c.Total_Imports_Domestic_Consumption__c ,
		    Petition__c.Actual_Initiation_Concurrence_to_DAS__c,
	        Petition__c.Actual_Initiation_Issues_to_DAS__c,
            Petition__c.Actual_Initiation_Signature__c,
			Petition__c.ADCVD_Case_Number__c,
		    Petition__c.ADCVD_Case_Type__c,
	        Petition__c.Calculated_Initiation_Signature__c,
//            Petition__c.Case_Number__c,
//			Petition__c.Case_Type__c,
			Petition__c.CBP_Case_Number__c,
		    Petition__c.Commodity__c,
	        Petition__c.Country__c,
            Petition__c.External_Id__c,
			Petition__c.Initiation_Announcement_Date__c,
		    Petition__c.Initiation_Concurrence_Due_to_DAS__c,
	        Petition__c.Initiation_Extension_of_days__c,
            Petition__c.Initiation_Extension_Remaining__c,
			Petition__c.Initiation_Issues_Due_to_DAS__c,
		    Petition__c.Link__c,
	        Petition__c.Litigation_YesNo__c,
            Petition__c.Litigation_Resolved__c,
			Petition__c.Litigation_Status__c,
		    Petition__c.Lotus_Notes_History_Data__c,
	        Petition__c.Lotus_Notes_Litigation_ID__c,
            Petition__c.Next_Announcement_Date__c,
			Petition__c.Next_Due_to_DAS_Deadline__c,
		    Petition__c.Next_Major_Deadline__c,
	        Petition__c.Next_Office_PM_Deadline__c,
            Petition__c.Next_Office_Deadline__c,
			Petition__c.Office__c,
		    Petition__c.Period_for_Trade_Data__c,
	        Petition__c.Petition_Filed__c,
            Petition__c.Petition_Name__c,
			Petition__c.Petition_Outcome__c,
		    Petition__c.Product__c,
	        Petition__c.Product_Short_Name__c,
            Petition__c.Locked__c,
			Petition__c.Schedule_Refresh__c,
		    Petition__c.Status__c,
	        Petition__c.Tolling_Update__c 
		};
	}
    
    public Schema.SObjectType getSObjectType() {
        return Related_Organization__c.sObjectType;
    }
    
    public List<Petition__c> selectById(Set<Id> ids) {
        return (List<Petition__c>) selectSObjectsById(ids);
    }
    
    public List<Petition__c> selectAll() {
        return (List<Petition__c>) 
            Database.query(
                newQueryFactory().toSOQL());        
    }
    
}