src/objects/Petition__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Initiation_Signature__c</fullName>
        <label>Calculated Initiation Signature</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiation_Extension_of_days__c</fullName>
        <description>Initiation Extension (# of days)</description>
        <inlineHelpText>Initiation Extension (# of days)</inlineHelpText>
        <label>Initiation Extension (# of days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Petition_Filed__c</fullName>
        <label>Petition Filed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Petition_Outcome__c</fullName>
        <label>Petition Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deficient Petition/Did Not Initiate</fullName>
                </value>
                <value>
                    <fullName>Initiated from Petition</fullName>
                </value>
                <value>
                    <fullName>Petition Withdrawn/Did Not Initiate</fullName>
                </value>
                <value>
                    <fullName>Self-Initiated</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <isActive>false</isActive>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Petition_Withdrawn_Did_Not_Initiate</fullName>
                    <isActive>false</isActive>
                    <label>Petition_Withdrawn_Did_Not_Initiate</label>
                </value>
                <value>
                    <fullName>Self Initiate in Progress</fullName>
                    <isActive>false</isActive>
                    <label>Self Initiate in Progress</label>
                </value>
                <value>
                    <fullName>Self-Initiate In Progress</fullName>
                    <isActive>false</isActive>
                    <label>Self-Initiate In Progress</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Petition</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Petition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Petitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PetitionTriggerHandler.cls
public with sharing class PetitionTriggerHandler {
    public static boolean preventRecursion = false;
    public static void mainEntry(List<Petition__c> newList, List<Petition__c> oldList, Map<Id, Petition__c> newMap, 
        Map<Id, Petition__c> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete, 
        Boolean isBefore, Boolean isAfter){
        if(preventRecursion) {return;}

        if(isAfter && isInsert) {
            //recalculatePetitionTollingDay(newList);
        }
        if(isAfter && isUpdate) {
            
        }
        if(isBefore && isInsert) {
            calculatePetitionDates(newList);
        }
        if(isBefore && isUpdate) {
        	calculatePetitionDates(newList);
        }
    }
    private static void calculatePetitionDates(List<Petition__c> newList) {
       	for (Petition__c p : newList){
       		if(p.Petition_Outcome__c == 'Initiated' || p.Petition_Outcome__c == 'In Progress') {
        		p.Calculated_Initiation_Signature__c = p.Petition_Filed__c.addDays(20);
	        	if(p.Initiation_Extension_of_days__c != null) {
	        		p.Calculated_Initiation_Signature__c = p.Calculated_Initiation_Signature__c.addDays((integer)p.Initiation_Extension_of_days__c);
	        	}
	        	p.Calculated_Initiation_Signature__c = ADCVD_TollingDayUtility.getCalculatedDate(p.Petition_Filed__c, p.Calculated_Initiation_Signature__c, true);
	        }
       	}
    }
}