src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AD_User_Id__c</fullName>
        <externalId>true</externalId>
        <label>AD User Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ITA_Office__c</fullName>
        <description>temp field for collecting office names until picklist option is defined or master list.</description>
        <label>ITA Office (AD)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Updated_by_Last_AD_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate that the record was last updated by AD</description>
        <label>Updated by Last AD Run</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserTriggerTest.cls
@isTest
public class UserTriggerTest {
    @isTest
    private static void testUserTrigger() {
        User Usr = new User();
        Usr.Alias = 'asdfas';
        Usr.AD_User_Id__c = 'email@test.com';
        Usr.EmailEncodingKey = 'UTF-8';
        Usr.LanguageLocaleKey = 'en_US';
        Usr.LocaleSidKey = 'en_US';
        Usr.ProfileId = [Select id from profile where name = 'ITA User Read Only'].id;
        Usr.username = 'Username@esawtds.com';
        Usr.ITA_Office__c = 'OLDOFF';
        Usr.Lastname = 'sadfasdf';
        Usr.TimeZoneSidKey = 'America/New_York';
        insert Usr;
        Usr.ProfileId = [Select id from profile where name = 'System Administrator'].id;
        usr.Updated_by_Last_AD_Run__c = true;
        usr.isActive = false;
        update Usr;
		Usr.ProfileId = [Select id from profile where name = 'ITA User Read Only'].id;
        update Usr;
        Usr = [Select FederationIdentifier, Email from User where id =: usr.id];
        system.assertEquals(Usr.FederationIdentifier, 'email@test.com');
        system.assertEquals(Usr.Email, 'email@test.com');
    }
}